### ISSUE TITLE
Install sparklyr with initialize_connect error

### ISSUE THREAD

**Issue by AkiraKane** [rstudio/sparklyr#1012]
Hi:
After I run this command:

`library("sparklyr")`
`spark_install(version="1.6.2")`
`sc <- spark_connect(master="local")`

I have encountered the following error, I have no idea how to fix that, please help me.

* Using Spark: 2.2.0
Error in force(code) : 
  Failed during initialize_connection: java.lang.ExceptionInInitializerError
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.security.SecurityUtil.getAuthenticationMethod(SecurityUtil.java:611)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:273)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:261)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:791)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2430)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:295)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
	at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:52)
	... 48 more

    Log: /var/folders/tx/gdr9qlrn6xj59pmdsr6xv7sm0000gn/T//RtmpMg3gBu/file12e9b6870d22b_spark.log

---- Output Log ----
17/09/14 23:31:32 INFO sparklyr: Session (6263) is starting under 127.0.0.1 port 8880
17/09/14 23:31:32 INFO sparklyr: Session (6263) found port 8880 is not available
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is registering session in gateway
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is waiting for registration in gateway
17/09/14 23:31:32 INFO sparklyr: Backend (6263) finished registration in gateway with status 0
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is waiting for sparklyr client to connect to port 54523
17/09/14 23:31:32 INFO sparklyr: Backend (6263) accepted connection
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is waiting for sparklyr client to connect to port 54523
17/09/14 23:31:32 INFO sparklyr: Backend (6263) received command 0
17/09/14 23:31:32 INFO sparklyr: Backend (6263) found requested session matches current session
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is creating backend and allocating system resources
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0$1 (file:/Users/akira/spark/spark-2.2.0-bin-hadoop2.7/jars/netty-all-4.0.43.Final.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17/09/14 23:31:32 INFO sparklyr: Backend (6263) created the backend
17/09/14 23:31:32 INFO sparklyr: Backend (6263) is waiting for r process to end
17/09/14 23:31:33 INFO SparkContext: Running Spark version 2.2.0
17/09/14 23:31:33 ERROR sparklyr: Backend (6263) failed calling getOrCreate on org.apache.spark.SparkContext

**Comment by hlendway** [comment]
I think you should probably try adding master and version attributes to your spark_connect call. Although it looks like it's having an issue authenticating so you may not have kerberos configured correctly or try running a kinit in the console in RStudio.  There's been a lot of suggestions in this thread that may also be relevant: [https://github.com/rstudio/sparklyr/issues/984](url)

**Comment by javierluraschi** [comment]
@AkiraKane looks like you have Java 9 installed which is currently not supported in Spark.

Try instead running:

```
system2("java", "-version")
```

You probably want to [Unsinstall Java in Mac](https://www.java.com/en/download/help/mac_uninstall_java.xml) followed by [reinstalling Java 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and then restarting your r session.

Rerunning the above statement should print something like:

```
system2("java", "-version")
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by AkiraKane** [comment]
@javierluraschi Thanks for the response, I do have Java 9 installed before. I have tried to install sparklyr on my other Mac, which only has Java 8 installed and it works fine. Thanks again :)

**Comment by javierluraschi** [comment]
Great, closing.
