### ISSUE TITLE
Text column with newline causes error in dplyr::copy_to in presence of a date column

### ISSUE THREAD

**Issue by russellpierce** [rstudio/sparklyr#1020]
I'll say at the outset I don't know if this report belongs with dplyr, sparklyr, or Spark.  The error returned appears to be from Spark, so I'm starting here.

```
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 67.0 failed 1 times, most recent failure: Lost task 0.0 in stage 67.0 (TID 57, localhost, executor driver): java.text.ParseException: Unparseable number: "= 530*714""
	at java.text.NumberFormat.parse(NumberFormat.java:385)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$4.apply$mcD$sp(CSVInferSchema.scala:268)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$4.apply(CSVInferSchema.scala:268)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$$anonfun$castTo$4.apply(CSVInferSchema.scala:268)
```

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
Sparklyr:  0.6.2
```

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here

df <- structure(
  list(
    date = structure(17426, class = "Date"),
    action = "par7i\n= 530*714"
  ), 
  .Names = c(
    "date", 
    "action"
  ), 
  row.names = c(NA, -1L), 
  class = c("tbl_df",  "tbl", "data.frame")
)
df_spark <- dplyr::copy_to(sc, df, overwrite = TRUE)
```

Notably, if there is no date column, things are fine.  See also similar, but resolved issue: https://github.com/rstudio/sparklyr/issues/411

**Comment by javierluraschi** [comment]
Thank you @russellpierce, tracking some improvements here instead: https://github.com/rstudio/sparklyr/issues/941, closing this one.
