### ISSUE TITLE
spark_read_table fails when table prefixed with db name

### ISSUE THREAD

**Issue by samurainate** [rstudio/sparklyr#1066]
`spark_read_table(sc,"db_name.table_name") `throws an AnalysisException (below)

`tbl_change_db(sc,"db_name"); spark_read_table(sc,"db_name.table_name")` succeeds.

The table was written with `spark_write_table(sdf,"db_name.tbl_name")` originally.

I would expect spark_read_table to handle db prefixes gracefully as spark_write_table.

# Error
```
Error: org.apache.spark.sql.AnalysisException: It is not allowed to add database prefix `day1_hbo` for the TEMPORARY view name.;
	at org.apache.spark.sql.execution.command.CreateViewCommand.<init>(views.scala:79)
	at org.apache.spark.sql.Dataset$$anonfun$createOrReplaceTempView$1.apply(Dataset.scala:2421)
	at org.apache.spark.sql.Dataset$$anonfun$createOrReplaceTempView$1.apply(Dataset.scala:2415)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2603)
	at org.apache.spark.sql.Dataset.createOrReplaceTempView(Dataset.scala:2415)
	at org.apache.spark.sql.Dataset.registerTempTable(Dataset.scala:2385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
trace:
withr::with_options(list(warning.length = 8000), {
    if (nzchar(msg)) {
        core_handle_known_errors(sc, msg)
        stop(msg, call. = FALSE)
    }
    else {
        msg <- core_read_spark_log_error(sc)
        stop(msg, call. = FALSE)
    }
})
core_invoke_method(sc, static, object, method, ...)
invoke_method.spark_shell_connection(spark_connection(jobj), 
    FALSE, jobj, method, ...)
invoke_method(spark_connection(jobj), FALSE, jobj, method, ...)
invoke.shell_jobj(df, "registerTempTable", name)
invoke(df, "registerTempTable", name)
spark_partition_register_df(sc, df, name, repartition, memory)
spark_read_table(sc, "db_name.table_name")
```

**Comment by cootem** [comment]
This doesn't appear to have a solution. Is the expected workflow to first run `tbl_change_db(sc, "dbname")` ?
