### ISSUE TITLE
Cannot connect to 'kerbenized' Spark cluster with the latest sparklyr

### ISSUE THREAD

**Issue by sean-in-korea** [rstudio/sparklyr#1083]
I am creating this thread again since the previous one was already closed. I am still experiencing the same issue that the latest sparklyr cannot connect to the Spark cluster with 6 nodes.

```r
> system2('klist')
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: oracle/KBINS@KBINSURE.CO.KR

Valid starting     Expires            Service principal
10/24/17 10:03:08  10/25/17 10:03:08  krbtgt/KBINSURE.CO.KR@KBINSURE.CO.KR
	renew until 10/31/17 10:03:08
> 
> library(sparklyr)
> library(DBI)
> library(dplyr)
> 
> #setup enviroment
> Sys.setenv(SPARK_HOME="/opt/cloudera/parcels/SPARK2/lib/spark2")
> Sys.setenv(YARN_CONF_DIR="/etc/hadoop/conf")
> Sys.setenv(HADOOP_CONF_DIR="/etc/hadoop/conf")
> Sys.setenv(SPARK_CONF_DIR="/etc/spark2/conf")
> 
> #Create Spark connection
> config <- spark_config()
> # config$`sparklyr.shell.queue` <- "[queue name]"
> config$`sparklyr.shell.deploy-mode` <- "cluster"
> # config$`sparklyr.shell.proxy-user` <- "[user name]"
> config$`sparklyr.log.console` <- TRUE
> config$`sparklyr.shell.num-executors` <- 2
> config$`sparklyr.shell.driver-cores` <- 1
> config$`sparklyr.shell.driver-memory` <- "1G"
> config$`sparklyr.shell.executor-cores` <- 1
> config$`sparklyr.shell.executor-memory` <- "1G"
> config$`sparklyr.shell.files` <- "/etc/hive/conf/hive-site.xml"
> config$`sparklyr.jars.default` <- c("/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-api-jdo-3.2.6.jar",
+                                     "/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-core-3.2.10.jar",
+                                     "/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-rdbms-3.2.9.jar")
> 
> sc <- spark_connect(master = "yarn-cluster", config = config)
Error in spark_yarn_cluster_get_resource_manager_webapp() : 
  Failed to find online resource manager under High Availability cluster.
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node03.kr.oracle.com:8088/ws/v1/cluster/info with status 401. 
2: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node04.kr.oracle.com:8088/ws/v1/cluster/info with status 401. 
3: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node03.kr.oracle.com:8033/ws/v1/cluster/info with status 404. 
4: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node04.kr.oracle.com:8033/ws/v1/cluster/info with status 404. 
17/10/24 10:03:29 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm16
17/10/24 10:03:29 INFO yarn.Client: Requesting a new application from cluster with 6 NodeManagers
17/10/24 10:03:29 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (35341 MB per container)
17/10/24 10:03:29 INFO yarn.Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
17/10/24 10:03:29 INFO yarn.Client: Setting up container launch context for our AM
17/10/24 10:03:29 INFO yarn.Client: Setting up the launch environment for our AM container
17/10/24 10:03:29 INFO yarn.Client: Preparing resources for our AM container
17/10/24 10:03:29 INFO security.HDFSCredentialProvider: getting token for namenode: hdfs://KBINS-ns/user/oracle
17/10/24 10:03:29 INFO hdfs.DFSClient: Created token for oracle: HDFS_DELEGATION_TOKEN owner=oracle/KBINS@KBINSURE.CO.KR, renewer=yarn, realUser=, issueDate=1508807009454, maxDate=1509411809454, sequenceNumber=839, masterKeyId=53 on ha-hdfs:KBINS-ns
17/10/24 10:03:31 INFO yarn.Client: Uploading resource file:/usr/lib64/R/library/sparklyr/java/sparklyr-2.1-2.11.jar -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/sparklyr-2.1-2.11.jar
17/10/24 10:03:31 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-api-jdo-3.2.6.jar -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/datanucleus-api-jdo-3.2.6.jar
17/10/24 10:03:31 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-core-3.2.10.jar -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/datanucleus-core-3.2.10.jar
17/10/24 10:03:31 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-rdbms-3.2.9.jar -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/datanucleus-rdbms-3.2.9.jar
17/10/24 10:03:32 INFO yarn.Client: Uploading resource file:/etc/hive/conf/hive-site.xml -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/hive-site.xml
17/10/24 10:03:32 INFO yarn.Client: Uploading resource file:/tmp/spark-280c6f21-442d-456d-9dca-8df7b187cb63/__spark_conf__8954525291674326620.zip -> hdfs://KBINS-ns/user/oracle/.sparkStaging/application_1506317550811_0019/__spark_conf__.zip
17/10/24 10:03:32 INFO spark.SecurityManager: Changing view acls to: oracle
17/10/24 10:03:32 INFO spark.SecurityManager: Changing modify acls to: oracle
17/10/24 10:03:32 INFO spark.SecurityManager: Changing view acls groups to: 
17/10/24 10:03:32 INFO spark.SecurityManager: Changing modify acls groups to: 
17/10/24 10:03:32 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(oracle); groups with view permissions: Set(); users  with modify permissions: Set(oracle); groups with modify permissions: Set()
17/10/24 10:03:32 INFO yarn.Client: Submitting application application_1506317550811_0019 to ResourceManager
17/10/24 10:03:33 INFO impl.YarnClientImpl: Submitted application application_1506317550811_0019
17/10/24 10:03:34 INFO yarn.Client: Application report for application_1506317550811_0019 (state: ACCEPTED)
17/10/24 10:03:34 INFO yarn.Client: 
	 client token: Token { kind: YARN_CLIENT_TOKEN, service:  }
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.users.oracle
	 start time: 1508807012336
	 final status: UNDEFINED
	 tracking URL: http://bda1node04.kr.oracle.com:8088/proxy/application_1506317550811_0019/
	 user: oracle
17/10/24 10:03:35 INFO yarn.Client: Application report for application_1506317550811_0019 (state: ACCEPTED)
17/10/24 10:03:36 INFO yarn.Client: Application report for application_1506317550811_0019 (state: ACCEPTED)
.... Abbreviated ....
17/10/24 10:05:49 INFO yarn.Client: Application report for application_1506317550811_0019 (state: ACCEPTED)
17/10/24 10:05:50 INFO yarn.Client: Application report for application_1506317550811_0019 (state: FAILED)
17/10/24 10:05:50 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: Application application_1506317550811_0019 failed 2 times due to AM Container for appattempt_1506317550811_0019_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://bda1node04.kr.oracle.com:8088/proxy/application_1506317550811_0019/Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e12_1506317550811_0019_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:601)
	at org.apache.hadoop.util.Shell.run(Shell.java:504)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:786)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:373)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Shell output: main : command provided 1
main : run as user is oracle
main : requested yarn user is oracle
Writing to tmp file /u07/hadoop/yarn/nm/nmPrivate/application_1506317550811_0019/container_e12_1506317550811_0019_02_000001/container_e12_1506317550811_0019_02_000001.pid.tmp


Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.users.oracle
	 start time: 1508807012336
	 final status: FAILED
	 tracking URL: http://bda1node04.kr.oracle.com:8088/cluster/app/application_1506317550811_0019
	 user: oracle
Exception in thread "main" org.apache.spark.SparkException: Application application_1506317550811_0019 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1172)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1218)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/10/24 10:05:50 INFO util.ShutdownHookManager: Shutdown hook called
17/10/24 10:05:50 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-280c6f21-442d-456d-9dca-8df7b187cb63
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------------
 setting  value                                       
 version  Oracle Distribution of R version 3.3.0  (--)
 system   x86_64, linux-gnu                           
 ui       RStudio (1.0.44)                            
 language (EN)                                        
 collate  en_US.UTF-8                                 
 tz       Asia/Seoul                                  
 date     2017-10-24                                  

Packages ----------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                           
 sparklyr   * 0.7.0-9035 2017-10-18 Github (rstudio/sparklyr@39ba4be)
```

**Comment by javierluraschi** [comment]
@sean-in-korea sorry for the delay, could you retry after running:

```
devtools::install_github("rstudio/sparklyr", "bugfix/yarn-cluster-improvements")
```

and let us know how this goes? Thanks!

**Comment by javierluraschi** [comment]
See https://github.com/rstudio/sparklyr/pull/1105

**Comment by sean-in-korea** [comment]
@javierluraschi 
```r
> library(sparklyr)
> library(DBI)
> library(dplyr)
> 
> #setup enviroment
> Sys.setenv(SPARK_HOME="/opt/cloudera/parcels/SPARK2/lib/spark2")
> Sys.setenv(YARN_CONF_DIR="/etc/hadoop/conf")
> Sys.setenv(HADOOP_CONF_DIR="/etc/hadoop/conf")
> Sys.setenv(SPARK_CONF_DIR="/etc/spark2/conf")
> 
> #Create Spark connection
> config <- spark_config()
> # config$`sparklyr.shell.queue` <- "[queue name]"
> config$`sparklyr.shell.deploy-mode` <- "cluster"
> # config$`sparklyr.shell.proxy-user` <- "[user name]"
> config$`sparklyr.log.console` <- TRUE
> config$`sparklyr.shell.num-executors` <- 2
> config$`sparklyr.shell.driver-cores` <- 1
> config$`sparklyr.shell.driver-memory` <- "1G"
> config$`sparklyr.shell.executor-cores` <- 1
> config$`sparklyr.shell.executor-memory` <- "1G"
> config$`sparklyr.yarn.cluster.accepted.timeout` <- 600
> config$`sparklyr.shell.files` <- "/etc/hive/conf/hive-site.xml"
> config$`sparklyr.jars.default` <- c("/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-api-jdo-3.2.6.jar",
+                                     "/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-core-3.2.10.jar",
+                                     "/opt/cloudera/parcels/SPARK2/lib/spark2/jars/datanucleus-rdbms-3.2.9.jar")
> 
> sc <- spark_connect(master = "yarn-cluster", config = config)
Error in spark_yarn_cluster_get_resource_manager_webapp() : 
  Failed to find online resource manager under High Availability cluster.
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node03.kr.oracle.com:8088/ws/v1/cluster/info with status 401. 
2: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node04.kr.oracle.com:8088/ws/v1/cluster/info with status 401. 
3: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node03.kr.oracle.com:8033/ws/v1/cluster/info with status 404. 
4: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open http://bda1node04.kr.oracle.com:8033/ws/v1/cluster/info with status 404. 
17/11/01 10:08:53 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm16
17/11/01 10:08:53 INFO yarn.Client: Requesting a new application from cluster with 6 NodeManagers
17/11/01 10:08:53 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (35341 MB per container)
17/11/01 10:08:53 INFO yarn.Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
17/11/01 10:08:53 INFO yarn.Client: Setting up container launch context for our AM
17/11/01 10:08:53 INFO yarn.Client: Setting up the launch environment for our AM container
17/11/01 10:08:53 INFO yarn.Client: Preparing resources for our AM container
17/11/01 10:08:53 INFO security.HDFSCredentialProvider: getting token for namenode: hdfs://KBINS-ns/user/hdfs
17/11/01 10:08:53 INFO hdfs.DFSClient: Created token for hdfs: HDFS_DELEGATION_TOKEN owner=hdfs/KBINS@KBINSURE.CO.KR, renewer=yarn, realUser=, issueDate=1509498533438, maxDate=1510103333438, sequenceNumber=853, masterKeyId=61 on ha-hdfs:KBINS-ns
17/11/01 10:08:55 INFO yarn.Client: Uploading resource file:/usr/lib64/R/library/sparklyr/java/sparklyr-2.1-2.11.jar -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/sparklyr-2.1-2.11.jar
17/11/01 10:08:55 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-api-jdo-3.2.6.jar -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/datanucleus-api-jdo-3.2.6.jar
17/11/01 10:08:55 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-core-3.2.10.jar -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/datanucleus-core-3.2.10.jar
17/11/01 10:08:55 INFO yarn.Client: Uploading resource file:/opt/cloudera/parcels/SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904/lib/spark2/jars/datanucleus-rdbms-3.2.9.jar -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/datanucleus-rdbms-3.2.9.jar
17/11/01 10:08:56 INFO yarn.Client: Uploading resource file:/etc/hive/conf/hive-site.xml -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/hive-site.xml
17/11/01 10:08:56 INFO yarn.Client: Uploading resource file:/tmp/spark-17532376-7563-4b07-a022-12230d3d447b/__spark_conf__5818217079457582542.zip -> hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029/__spark_conf__.zip
17/11/01 10:08:56 INFO spark.SecurityManager: Changing view acls to: oracle,hdfs
17/11/01 10:08:56 INFO spark.SecurityManager: Changing modify acls to: oracle,hdfs
17/11/01 10:08:56 INFO spark.SecurityManager: Changing view acls groups to: 
17/11/01 10:08:56 INFO spark.SecurityManager: Changing modify acls groups to: 
17/11/01 10:08:56 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(oracle, hdfs); groups with view permissions: Set(); users  with modify permissions: Set(oracle, hdfs); groups with modify permissions: Set()
17/11/01 10:08:56 INFO yarn.Client: Submitting application application_1506317550811_0029 to ResourceManager
17/11/01 10:08:56 INFO impl.YarnClientImpl: Submitted application application_1506317550811_0029
17/11/01 10:08:57 INFO yarn.Client: Application report for application_1506317550811_0029 (state: ACCEPTED)
17/11/01 10:08:57 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.users.hdfs
	 start time: 1509498536267
	 final status: UNDEFINED
	 tracking URL: http://bda1node04.kr.oracle.com:8088/proxy/application_1506317550811_0029/
	 user: hdfs
17/11/01 10:08:58 INFO yarn.Client: Application report for application_1506317550811_0029 (state: ACCEPTED)
17/11/01 10:08:59 INFO yarn.Client: Application report for application_1506317550811_0029 (state: FAILED)
17/11/01 10:08:59 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: Application application_1506317550811_0029 failed 2 times due to AM Container for appattempt_1506317550811_0029_000002 exited with  exitCode: -1000
For more detailed output, check application tracking page:http://bda1node04.kr.oracle.com:8088/proxy/application_1506317550811_0029/Then, click on links to logs of each attempt.
Diagnostics: Application application_1506317550811_0029 initialization failed (exitCode=255) with output: main : command provided 0
main : run as user is hdfs
main : requested yarn user is hdfs
Requested user hdfs is banned

Failing this attempt. Failing the application.
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.users.hdfs
	 start time: 1509498536267
	 final status: FAILED
	 tracking URL: http://bda1node04.kr.oracle.com:8088/cluster/app/application_1506317550811_0029
	 user: hdfs
17/11/01 10:08:59 INFO yarn.Client: Deleted staging directory hdfs://KBINS-ns/user/hdfs/.sparkStaging/application_1506317550811_0029
Exception in thread "main" org.apache.spark.SparkException: Application application_1506317550811_0029 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1172)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1218)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/11/01 10:08:59 INFO util.ShutdownHookManager: Shutdown hook called
17/11/01 10:08:59 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-17532376-7563-4b07-a022-12230d3d447b

> devtools::session_info()
 sparklyr   * 0.7.0-9101 2017-11-01 Github (rstudio/sparklyr@f9760d7)
```
