### ISSUE TITLE
Automatically rename ambiguous/repeated column names in CSV

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#111]
Dear @javierluraschi, I have noticed that you updated spark_read_csv in sparklyr version 0.2.27 and now it automatically removes special characteres and blank spaces in csv column names. It was a nice improvement. 

Could you update spark_read_csv to fix the following point: if I have two or more repeated column names in CSV spark returns:

Source:   query [?? x 24]
Database: spark connection master=local[*] app=sparklyr local=TRUE

Error: org.apache.spark.sql.AnalysisException: Reference 'variable_estb' is ambiguous, could be: variable_estb#142, variable_estb#143.; line 3 pos 777

It is possible automatically rename them to variable_estab0, variable_estab1 and so on. I think it may fix this exception. 

In the same way, column names including some accentuation such as "á,é,ã,ó,ú,í,õ" could be set as "a,e,a,o,u,i,o" automatically, for instance.

Thanks.

**Comment by javierluraschi** [comment]
@kevinushey seems we would have to also make column names unique as part of `spark_sanitize_names`

**Comment by hiltonmbr** [comment]
Dear @kevinushey, it is returning:

Error in make.unique(names, sep = "_") :
'names' must be a character vector

Also, why don't use gsub to remove accentuation from column names. It's a common case in datasets provided in other languages than english. For instance:
gsub("[áãàä]", "a",tolower(names))
gsub("[éèë]", "e",tolower(names))
gsub("[íì]", "i",tolower(names))
gsub("[óõòö]", "o",tolower(names))
gsub("[úùü]", "u",tolower(names))

Thanks.

**Comment by kevinushey** [comment]
Thanks, I'll take a look.

**Comment by kevinushey** [comment]
We now use `iconv()` to attempt to translate names to ASCII -- by default, this should translate accented characters to their un-accented counterparts when possible. Let me know how it looks for you.

**Comment by hiltonmbr** [comment]
Dear @kevinushey , please take a look at this example:

# CSV simulated 
# Three variables: "Município", "var", "var", where "var" is a repeated name 
csv <- file("test.csv", "w+", encoding = "latin1")
cat("Município;var;var\n1233;1;2", file=csv)
close(csv)

library(sparklyr)
sc <- spark_connect("master"="local[*]")

df <- spark_read_csv(sc,name="test",path="test.csv",header = TRUE,delimiter = ";",
                     charset = "Latin1",memory=FALSE)

The following columns have been renamed:
- 'Município' => 'Município'

It cannot set to un-accented on Mac OSX. Also, it returns the following error:

head(df) 

Error: org.apache.spark.sql.AnalysisException: Reference 'var' is ambiguous, could be: var#166, var#167.;
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolve(LogicalPlan.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveQuoted(LogicalPlan.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:130)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:129)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:94)
	at scala.collection.TraversableLike$class.map

**Comment by kevinushey** [comment]
I'll have to dig in more -- I just pushed some code that should, in theory, handle this, but I'm still seeing some issues.

```
> df <- spark_read_csv(sc, name="test", path="test.csv",header = TRUE,delimiter = ";",
+                      charset = "Latin1",memory=FALSE)
The following columns have been renamed:
- 'Município' => 'Municipio'
- 'var'       => 'var_1'    
> df
Source:   query [?? x 3]
Database: spark connection master=local[*] app=sparklyr local=TRUE

 Show Traceback
 
 Rerun with Debug
 Error: org.apache.spark.sql.AnalysisException: Reference 'var' is ambiguous, could be: var#6, var#7.;
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolve(LogicalPlan.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveQuoted(LogicalPlan.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:130)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolve$1.apply(LogicalPlan.scala:129)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at org.apache.spark.sql.types.StructType.foreach(StructType.scala:94)
```

I'll dig in more next week, but I think you'll need to just manually ensure columns don't have duplicated names for now.

**Comment by hiltonmbr** [comment]
@kevinushey it seems that SPARK SQL use c_0 as inner alias name.  So, if you try rename column names using another alias name which not include numbers, i.e, removing all numbers from column names, you may solve this issue.

**Comment by hiltonmbr** [comment]
Another example including "var 1.0" in the CSV header:

csv <- file("test.csv", "w+", encoding = "latin1")
cat("Município;var;var 1.0\n1233;1;2", file=csv)
close(csv)

library(sparklyr)
sc <- spark_connect("master"="local[*]")

df <- spark_read_csv(sc,name="teste",path="test.csv",header = TRUE,
                     delimiter = ";",charset = "Latin1",memory = FALSE)
head(df)

The following columns have been renamed:
- 'Município' => 'Municipio' (#1)
- 'var 1.0'   => 'var_1_0'   (#3)
> head(df)
Source:   query [?? x 3]
Database: spark connection master=local[*] app=sparklyr local=TRUE

Erro: org.apache.spark.sql.AnalysisException: Unable to resolve var 1.0 given [Município, var, var 1.0];

**Comment by hiltonmbr** [comment]
Dear @kevinushey ,

Could you try use dplyr remane_  with setNames to solve this issue? For instance,

df <- df %>% rename_(.dots=setNames(colnames(.), z))

where z is a character vector of newnames.

**Comment by javierluraschi** [comment]
This is looking good to me, adding test but otherwise closing. Let us know if you spot other issues in this area to take a look.
