### ISSUE TITLE
Passing variables to `dplyr_` functions fail

### ISSUE THREAD

**Issue by raphaelvannson** [rstudio/sparklyr#1111]
I would like to calculate the mean of a column (here `result`).
Since this is in a function, I would like to make the column name a variable.

If I hard-code the column name `result`, the mean calculation works 
```
> df %>% summarize(mean = mean(result)) %>% collect %>% .$mean
[1] 1022.746
```

If I provide a string to `summarize_()` then the execution fails.
The end goal would be to construct string using `paste` to evaluate the column name variable and passing the string to `summarize_()`.
As a first step simply "stringyfing" the original call to `summarize()` should work (should it?).

```
df %>% summarize_("mean = mean(result)") %>% collect %>% .$mean

Error: org.apache.spark.sql.catalyst.parser.ParseException: no viable alternative at input 'SELECT ='(line 1, pos 7) == SQL == SELECT =(NULL, AVG(`result`)) -------^^^ FROM (SELECT `lot_id`, `wafer_id`, `test_txt`, `result`, CASE WHEN ("result" < 1022.25) THEN ((1022.25)) ELSE (CASE WHEN (1023.0 < "result") THEN ((1023.0)) ELSE (("result")) END) END AS `col_name` FROM (SELECT * FROM (SELECT * FROM `cab_tbl` WHERE (`lot_id` = "TM80018.1L" OR `lot_id` = "TM80472.1W")) `otunivbpqs` WHERE (`test_txt` = "ADC_static <> ADC_AN5_Min_4V75")) `gywioztwvx`) `zltfeaucmn`
at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:217
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:114)
at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:68)
at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498) at sparklyr.Invoke$.invoke(invoke.scala:102)
at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
at sparklyr.StreamHandler$.read(stream.scala:62)
at sparklyr.BackendHandler.channelRead0(handler.scala:52)
at sparklyr.BackendHandler.channelRead0(handler.scala:14)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.lang.Thread.run(Thread.java:748)
```

Any help would be appreciated - Thanks!

**Comment by raphaelvannson** [comment]
Hello @kevinykuo,

Many (many :) ) thanks for your quick response!
This did the trick (after a minor modification):

```
df %>% summarize(mean = mean(!!rlang::sym("result"))) %>% collect %>% .$mean
``` 

Or

```
col_name = "result"
df %>% summarize(mean = mean(!!rlang::sym(col_name))) %>% collect %>% .$mean
```

Cheers!

**Comment by raphaelvannson** [comment]
Hello @kevinykuo,

Similar question for `mutate()`: the answer provided above for `summarize()` works to evaluate the variable name in the `mutate()` condition but not to set the name of the output column.

Example:

I am trying to do this (this works. `df` already contains a column called `result`):
```
lq = 1
hq = 2
df %>% mutate(result = if(result < lq){lq}else if(uq < result){uq} else{result})
```


The solution proposed above if the name of the output column (`result`) is hard coded:
```
lq = 1
hq = 2
col_name = "result"
df %>% %>% mutate(result = if(!!rlang::sym(col_name) < lq){lq}else if(uq < !!rlang::sym(col_name)){uq} else{!!rlang::sym(col_name)})
```

The solution proposed above does not work when we try to "variablize" the name of the output column with `!!rlang::sym(col_name)`:
```
lq = 1
hq = 2
col_name = "result"
df %>% %>% mutate(!!rlang::sym(col_name) = if(!!rlang::sym(col_name) < lq){lq}else if(uq < !!rlang::sym(col_name)){uq} else{!!rlang::sym(col_name)})
Error: unexpected '=' in "  df %>% mutate((!rlang::sym(col_name) ="

#Same results with:
df %>% %>% mutate( (!!rlang::sym(col_name)) = if(!!rlang::sym(col_name) < lq){lq}else if(uq < !!rlang::sym(col_name)){uq} else{!!rlang::sym(col_name)})
```

Any ideas on how the name of the column where the output of the transformation will be written could be passed as a variable?

Thanks!
