### ISSUE TITLE
 Error: Unexpected state in sparklyr backend, terminating connection: failed to invoke spark command

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#1184]
Hello,

Using the latest master `sparklyr`, and I came across this strange bug. 
Consider this simple code: 

```
df_new <- spark_read_parquet(sc, "parquet_2014*",
                             overwrite = TRUE,
                             name = "df_new",
                             memory = FALSE)


mysample <- df_new %>% filter(!is.na(u),u %rlike% 'stackoverflow.com') %>%
  mutate(unix_t = from_utc_timestamp(timestamp(t) ,'UTC'),
         day = to_date(unix_t)) %>%
  filter(day >= to_date('2014-09-01')) %>%
   count()
# Source:   lazy query [?? x 1]
# Database: spark_connection
        n
    <dbl>
1 6841170

```
but now using `collect()` and everything falls apart

```
 mysample <- df_new %>% filter(!is.na(u),u %rlike% 'stackoverflow.com') %>%
+   mutate(unix_t = from_utc_timestamp(timestamp(t) ,'UTC'),
+          day = to_date(unix_t)) %>%
+   filter(day >= to_date('2014-09-01')) %>%
+   collect()

 Error: Unexpected state in sparklyr backend, terminating connection: failed to invoke spark command
	at java.lang.StringCoding.encode(StringCoding.java:350)
	at java.lang.String.getBytes(String.java:939)
	at sparklyr.Serializer$.writeString(serializer.scala:372)
	at sparklyr.Serializer$.writeObject(serializer.scala:241)
	at sparklyr.Serializer$$anonfun$writeObject$6.apply(serializer.scala:312)
	at sparklyr.Serializer$$anonfun$writeObject$6.apply(serializer.scala:312)
```

What is wrong here? How can I get my data back?
Thanks!!

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo does this have to do with the fact that I am using dates?
I also tried

```
mysample <- df_new %>% filter(!is.na(u),u %rlike% 'stackoverflow.com') %>%
  mutate(unix_t = from_utc_timestamp(timestamp(t) ,'UTC'),
         myday = to_date(unix_t),
         mymonth = month(myday)) %>%
  filter(mymonth >= 9) %>%
  collect()
```
and it fails the same way... what can be done??

Thanks!

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo could it be the size of the data being too big? but I dont understand the serialization thing in the error message

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo could it be the size of the data being too big? but I dont understand the serialization thing in the error message

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo sorry guys to ask again, but that seems to be a pretty basic command here. Any ideas what is wrong? Thanks again for your time!

**Comment by kevinykuo** [comment]
May be a date de/serialization issue. Could you try to collect just one row? If that fails could you provide a small sample file?

**Comment by randomgambit** [comment]
Thanks @kevinykuo 

May be as date de/serialization issue indeed. Pulling a smaller set of data works:


```
mysample <- df_new %>% filter(!is.na(u),u %rlike% 'stackoverflow.com') %>%
  mutate(unix_t = from_utc_timestamp(timestamp(t) ,'UTC'),
         myday = to_date(unix_t),
         mymonth = month(myday)) %>%
  filter(mymonth == 10) %>%
  collect()

```

What do you think? Is there an easy fix? What is the problem with serialization here?

Thanks!

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo any new information on this? how can I be of any help here? this is a very annoying bug!!! thanks!!

**Comment by randomgambit** [comment]
I dont think this is related to the date format. I am working on a large dataset that ONLY contains doubles and characters (4 column total). running `sdf_nrows` returns about 8 million rows.

Trying to `collect()` that data to R generates the same issue. Please let me know if you have some ideas... Thanks!!!

**Comment by javierluraschi** [comment]
Moving to next milestone since investigation shows this would implementing more effective serialization or batch downloads that are non trivial.

**Comment by raphaelvannson** [comment]
Hello,

I am experiencing a similar issue when collecting a large number of rows from Spark into R.
Not sure this is exactly the same issue but they could be related since the error message is somewhat similar so I am posting here in the hopes it will help resolve this issue.

Context:
I am using spark to connect to hive, run a SQL query and collect the data into R. 
The query randomly samples a dataset which is potentially very large, I am looking to limit the number of rows collected into R. I was hoping to get to 20M or to hit some sort of limit introduced by R itself, not sparklyr.
(Note: I have also tried a direct ODBC connection from R to Hive which works but performance was 2-3x times slower).


`spark_connect()` config:

```yaml
spark_connect_args:
    master: "yarn-client"
    spark_home: "/opt/cloudera/parcels/SPARK2/lib/spark2"
    config:
        sparklyr.shell.driver-memory: "64G"
        sparklyr.shell.driver-cores: 4
        sparklyr.shell.executor-cores: 1
        sparklyr.shell.executor-memory: "4G"
```



Code snipet:

```r
#max_rows_retrieved = 15500000    # works - takes 2-3 mins
max_rows_retrieved = 16000000      # fails

query = paste0("select foo FROM bar.baz  where year = 2018 and month = 1 and day = 1 distribute by rand() sort by rand() limit ", format(max_rows_retrieved, scientific = FALSE))

collected_df_sparklyr = sc %>%
  spark_session() %>%
  invoke("sql", query) %>%
  sdf_register() %>%
  collect()
```

Error message:

```
Error: Unexpected state in sparklyr backend, terminating connection: failed to invoke spark command 18/05/22 18:17:47 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-140bb42c-3406-4573-bf2a-a92370107f96 18/05/22 18:17:47 INFO ui.SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.84.120.17:4040 18/05/22 18:17:47 INFO spark.SparkContext: Added JAR file:/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar at spark://10.84.120.17:34450/jars/sparklyr-2.2-2.11.jar with timestamp 1527031067990 18/05/22 18:18:43 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr. 18/05/22 18:18:44 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr. at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.sql.hive.client.Shim_v0_13.getPartitionsByFilter(HiveShim.scala:641) at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitionsByFilter$1.apply(HiveClientImpl.scala:580) at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$getPartitionsByFilter$1.apply(HiveClientImpl.scala:578) at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:275) at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:216) at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:215) at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:258) at org.apache.spark.sql.hive.client.HiveClientImpl.getPartitionsByFilter(HiveClientImpl.scala:578) at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$listPartitionsByFilter$1.apply(HiveExternalCatalog.scala:1127) at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$listPartitionsByFilter$1.apply(HiveExternalCatalog.scala:1120) at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:99) at org.apache.spark.sql.hive.HiveExternalCatalog.listPartitionsByFilter(HiveExternalCatalog.scala:1120) at org.apache.spark.sql.catalyst.catalog.SessionCatalog.listPartitionsByFilter(SessionCatalog.scala:942) at org.apache.spark.sql.execution.datasources.CatalogFileIndex.filterPartitions(CatalogFileIndex.scala:73) at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$$anonfun$apply$1.applyOrElse(PruneFileSourcePartitions.scala:60) at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$$anonfun$apply$1.applyOrElse(PruneFileSourcePartitions.scala:27) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$2.apply(TreeNode.scala:267) at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:266) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:272) at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:272) at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$.apply(PruneFileSourcePartitions.scala:27) at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$.apply(PruneFileSourcePartitions.scala:26) at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85) at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82) at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57) at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66) at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35) at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82) at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74) at scala.collection.immutable.List.foreach(List.scala:381) at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74) at org.apache.spark.sql.execution.QueryExecution.optimizedPl
27.
	
stop("Unexpected state in sparklyr backend, terminating connection: ", msg, call. = FALSE)
26.
	
force(code)
25.
	
withr::with_options(list(warning.length = 8000), { stop("Unexpected state in sparklyr backend, terminating connection: ", msg, call. = FALSE) })
24.
	
core_invoke_method(sc, static, object, method, ...)
23.
	
invoke_method.spark_shell_connection(sc, TRUE, class, method, ...)
22.
	
invoke_method(sc, TRUE, class, method, ...)
21.
	
invoke_static.spark_shell_connection(sc, "sparklyr.Utils", "collect", sdf, separator$regexp)
20.
	
invoke_static(sc, "sparklyr.Utils", "collect", sdf, separator$regexp)
19.
	
sdf_collect(sdf)
18.
	
df_from_sdf(res@conn, res@sdf, end)
17.
	
.local(res, n, ...)
16.
	
dbFetch(res, n = n)
15.
	
dbFetch(res, n = n)
14.
	
tryCatchList(expr, classes, parentenv, handlers)
13.
	
tryCatch({ out <- dbFetch(res, n = n) if (warn_incomplete) { res_warn_incomplete(res, "n = Inf") ...
12.
	
db_collect.DBIConnection(x$src$con, sql, n = n, warn_incomplete = warn_incomplete)
11.
	
db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete)
10.
	
collect.tbl_sql(.)
9.
	
collect(.)
8.
	
function_list[[k]](value)
7.
	
withVisible(function_list[[k]](value))
6.
	
freduce(value, `_function_list`)
5.
	
`_fseq`(`_lhs`)
4.
	
eval(quote(`_fseq`(`_lhs`)), env, env)
3.
	
eval(quote(`_fseq`(`_lhs`)), env, env)
2.
	
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1.
	
sc %>% spark_session() %>% invoke("sql", query) %>% sdf_register() %>% collect()
```

I was also running a loop to monitor the Virtual and Resident size of the Spark driver process from creation to failure. It always fails when the resident size hits about 22-25GB.
The process remains relatively small (around 1GB) while the executors are working and getting the data from Hive, then the driver grows significantly during the collect (which makes sense) and then fails there.

```bash
$ while [ 1 == 1 ]; do ps aux | egrep 'COMAND|myuser' | egrep 'COMMAND|sparklyr' | grep -v bash | grep -v grep | awk '{print $1 " " $2 " " $3 " " $4 " " $5  /1024/1024" " $6 / 1024/1024}'; sleep 1; done
USER       PID %CPU %MEM    VSZ   RSS
myuser 24824 28.7 0.6 34.619 0.827202
myuser 24824 28.3 0.6 34.619 0.827202
myuser 24824 27.9 0.6 34.619 0.827229
myuser 24824 27.1 0.6 34.619 0.827229
myuser 24824 26.7 0.6 34.619 0.827515
myuser 24824 26.3 0.6 34.619 0.827515
myuser 24824 26.0 0.6 34.619 0.827671
myuser 24824 25.6 0.6 34.619 0.827972
myuser 24824 25.3 0.6 34.619 0.827972
myuser 24824 25.0 0.6 34.619 0.827972
myuser 24824 24.9 0.6 34.6825 0.830425
myuser 24824 25.9 0.6 34.6884 0.861153
myuser 24824 31.0 0.7 34.6942 0.973869
myuser 24824 31.7 0.7 34.6962 0.983318
myuser 24824 32.0 0.7 34.6962 0.984936
myuser 24824 31.6 0.7 34.6962 0.985199
myuser 24824 31.2 0.7 34.6962 0.985199
myuser 24824 30.8 0.7 34.6962 0.985363
myuser 24824 30.5 0.7 34.6962 0.985363
myuser 24824 30.1 0.7 34.6962 0.985363
myuser 24824 29.8 0.7 34.6962 0.985432
myuser 24824 29.5 0.7 34.6962 0.985432
myuser 24824 29.1 0.7 34.6962 0.98563
myuser 24824 28.5 0.7 34.6962 0.985806
myuser 24824 28.2 0.7 34.6962 0.985806
myuser 24824 27.9 0.7 34.6962 0.985806
myuser 24824 29.5 0.8 34.704 1.06568
myuser 24824 30.1 0.8 34.706 1.12215
myuser 24824 29.7 0.8 34.706 1.12228
myuser 24824 29.4 0.8 34.706 1.12228
myuser 24824 29.2 0.8 34.706 1.12228
myuser 24824 28.9 0.8 34.706 1.12228
myuser 24824 28.6 0.8 34.706 1.12228
myuser 24824 28.3 0.8 34.706 1.12228
myuser 24824 28.0 0.8 34.706 1.12228
myuser 24824 27.8 0.8 34.706 1.12229
myuser 24824 27.5 0.8 34.706 1.12229
myuser 24824 27.2 0.8 34.706 1.12229
myuser 24824 27.0 0.8 34.706 1.12229
myuser 24824 26.7 0.8 34.706 1.12229
myuser 24824 26.5 0.8 34.706 1.12231
myuser 24824 26.2 0.8 34.706 1.12231
myuser 24824 26.3 0.9 34.9609 1.19289
myuser 24824 26.0 0.9 34.9609 1.19313
myuser 24824 25.6 0.9 34.9609 1.19328
myuser 24824 25.3 0.9 34.9609 1.19328
myuser 24824 25.1 0.9 34.9609 1.19328
myuser 24824 24.9 0.9 34.9609 1.19328
myuser 24824 24.7 0.9 34.9609 1.19328
myuser 24824 24.5 0.9 34.9609 1.1933
myuser 24824 24.3 0.9 34.9609 1.1933
myuser 24824 24.1 0.9 34.9609 1.1933
myuser 24824 23.9 0.9 34.9609 1.19579
myuser 24824 23.7 0.9 34.9609 1.19579
myuser 24824 23.5 0.9 34.9609 1.19579
myuser 24824 23.3 0.9 34.9609 1.19579
myuser 24824 23.1 0.9 34.9609 1.19581
myuser 24824 22.9 0.9 34.9609 1.19581
myuser 24824 23.1 1.0 35.0713 1.2653
myuser 24824 24.4 1.1 35.1504 1.50014
myuser 24824 24.3 1.1 35.1504 1.50014
myuser 24824 24.2 1.1 35.2139 1.50161
myuser 24824 24.0 1.1 35.2139 1.50161
myuser 24824 23.8 1.1 35.2139 1.50161
myuser 24824 23.4 1.1 35.2139 1.50173
myuser 24824 23.3 1.1 35.2139 1.5022
myuser 24824 23.2 1.1 35.2139 1.50222
myuser 24824 23.0 1.1 35.2139 1.50222
myuser 24824 22.8 1.1 35.2139 1.50241
myuser 24824 22.7 1.1 35.2139 1.50248
myuser 24824 22.5 1.1 35.2139 1.50248
myuser 24824 22.4 1.1 35.2139 1.50264
myuser 24824 22.2 1.1 35.2773 1.50267
myuser 24824 22.1 1.1 35.2773 1.50276
myuser 24824 22.0 1.1 35.2773 1.50288
myuser 24824 21.8 1.1 35.2773 1.50296
myuser 24824 21.7 1.1 35.2773 1.50314
myuser 24824 21.6 1.1 35.3408 1.50396
myuser 24824 21.5 1.1 35.3408 1.50425
myuser 24824 21.4 1.1 35.4678 1.50465
myuser 24824 21.3 1.1 35.4678 1.50518
myuser 24824 21.1 1.1 35.4678 1.50544
myuser 24824 21.0 1.1 35.4678 1.50561
myuser 24824 20.9 1.1 35.4678 1.50569
myuser 24824 20.8 1.1 35.4678 1.50571
myuser 24824 20.5 1.1 35.4678 1.50571
myuser 24824 20.4 1.1 35.4678 1.50571
myuser 24824 20.3 1.1 35.4678 1.50583
myuser 24824 20.1 1.1 35.4678 1.50583
myuser 24824 20.4 1.2 35.4678 1.51405
myuser 24824 20.6 1.2 35.4834 1.52537
myuser 24824 21.2 1.2 35.4834 1.54043
myuser 24824 21.3 1.2 35.4834 1.54713
myuser 24824 21.5 1.2 35.4834 1.56768
myuser 24824 21.7 1.2 35.4834 1.61912
myuser 24824 22.8 1.6 35.7403 2.06625
myuser 24824 22.8 1.6 35.7403 2.06656
myuser 24824 22.8 1.6 35.7403 2.06675
myuser 24824 23.2 1.6 35.7403 2.06696
myuser 24824 26.0 2.2 35.9307 2.84557
myuser 24824 26.2 2.2 36.1846 2.88465
myuser 24824 28.8 2.4 36.3751 3.09992
myuser 24824 28.8 2.4 36.3751 3.10026
myuser 24824 28.7 2.4 36.3751 3.10162
myuser 24824 31.3 3.1 36.3751 3.95106
myuser 24824 31.0 3.1 36.3751 3.95117
myuser 24824 31.0 3.1 36.3751 3.95409
myuser 24824 31.0 3.1 36.3751 3.96491
myuser 24824 31.0 3.1 36.3751 3.96519
myuser 24824 30.9 3.1 36.3751 3.96579
myuser 24824 30.8 3.1 36.3751 3.96605
myuser 24824 30.8 3.1 36.3751 3.96685
myuser 24824 33.0 3.4 36.3751 4.39899
myuser 24824 32.9 3.4 36.3751 4.3995
myuser 24824 32.8 3.4 36.3751 4.39956
myuser 24824 32.8 3.4 36.3751 4.39974
myuser 24824 32.7 3.5 36.3751 4.40034
myuser 24824 32.6 3.5 36.3751 4.40038
myuser 24824 32.6 3.5 36.3751 4.40046
myuser 24824 34.3 4.1 36.3751 5.15541
myuser 24824 46.6 4.2 36.3751 5.3494
myuser 24824 58.9 4.2 36.3751 5.36928
myuser 24824 63.2 4.3 36.3751 5.40835
myuser 24824 63.3 4.3 36.3751 5.42794
myuser 24824 63.2 4.3 36.3751 5.42794
myuser 24824 65.0 4.6 36.3751 5.80697
myuser 24824 70.0 5.0 36.3751 6.30299
myuser 24824 70.1 5.0 36.3751 6.30299
myuser 24824 78.6 7.1 36.3751 8.93554
myuser 24824 90.1 7.1 36.3751 8.95506
myuser 24824 101 7.1 36.3751 8.97404
myuser 24824 112 7.1 36.3751 8.99562
myuser 24824 123 7.1 36.3751 9.01568
myuser 24824 134 7.3 36.3751 9.29205
myuser 24824 140 7.3 36.3751 9.29296
myuser 24824 140 7.3 36.3751 9.29296
myuser 24824 140 7.4 36.3751 9.3238
myuser 24824 140 7.4 36.3751 9.3238
myuser 24824 140 7.4 36.3751 9.32383
myuser 24824 140 7.4 36.3751 9.32488
myuser 24824 144 7.7 36.3751 9.78453
myuser 24824 149 8.5 36.3751 10.7942
myuser 24824 150 8.5 36.3751 10.7947
myuser 24824 161 10.1 36.3751 12.8168
myuser 24824 171 10.2 36.3751 12.8297
myuser 24824 181 10.2 36.3751 12.8415
myuser 24824 191 10.2 36.3751 12.8547
myuser 24824 201 10.2 36.3751 12.8887
myuser 24824 211 10.2 36.3751 12.8914
myuser 24824 217 10.2 36.3751 12.897
myuser 24824 217 10.2 36.3751 12.9364
myuser 24824 216 10.2 36.3751 12.9365
myuser 24824 220 10.2 36.3751 12.9419
myuser 24824 230 10.3 36.3751 12.9538
myuser 24824 240 10.3 36.3751 12.9538
myuser 24824 244 10.3 36.3751 12.953
myuser 24824 246 10.3 36.3751 12.9591
myuser 24824 255 10.3 36.3751 12.9794
myuser 24824 264 10.3 36.3751 12.9864
myuser 24824 273 10.3 36.3751 13.0195
myuser 24824 282 10.6 36.3751 13.4376
myuser 24824 292 10.9 36.3751 13.8079
myuser 24824 293 11.0 36.4385 13.8798
myuser 24824 292 11.0 36.4385 13.8799
myuser 24824 291 11.0 36.4385 13.8799
myuser 24824 290 11.0 36.4385 13.8799
myuser 24824 290 11.0 36.4385 13.8799
myuser 24824 289 11.0 36.4385 13.8799
myuser 24824 288 11.0 36.4385 13.8799
myuser 24824 287 11.0 36.4385 13.88
myuser 24824 287 11.0 36.4385 13.88
myuser 24824 291 11.0 36.4385 13.8868
myuser 24824 299 11.3 36.4385 14.2871
myuser 24824 308 11.3 36.4385 14.2906
myuser 24824 317 11.4 36.4385 14.4045
myuser 24824 324 11.6 36.4385 14.6116
myuser 24824 333 11.7 36.4385 14.8264
myuser 24824 341 11.9 36.4385 15.0319
myuser 24824 350 12.1 36.4385 15.2325
myuser 24824 358 12.2 36.4385 15.436
myuser 24824 366 12.4 36.4385 15.6426
myuser 24824 375 12.6 36.4385 15.8527
myuser 24824 383 12.7 36.4385 16.0605
myuser 24824 391 12.8 36.4385 16.1224
myuser 24824 398 12.8 36.4385 16.1224
myuser 24824 406 12.8 36.4385 16.1307
myuser 24824 414 12.8 36.4385 16.1307
myuser 24824 421 12.8 36.4385 16.1331
myuser 24824 428 12.8 36.4385 16.1423
myuser 24824 436 12.8 36.4385 16.1553
myuser 24824 443 12.8 36.4385 16.1669
myuser 24824 451 12.8 36.4385 16.1784
myuser 24824 458 12.8 36.4385 16.1877
myuser 24824 465 12.8 36.4385 16.195
myuser 24824 472 12.8 36.4385 16.2044
myuser 24824 477 12.8 36.4385 16.2065
myuser 24824 476 12.8 36.4385 16.2065
myuser 24824 475 12.8 36.4385 16.2065
myuser 24824 474 12.9 36.4385 16.2265
myuser 24824 472 12.9 36.4385 16.2266
myuser 24824 471 12.9 36.4385 16.2266
myuser 24824 470 12.9 36.4385 16.2266
myuser 24824 467 12.9 36.4385 16.2266
myuser 24824 465 12.9 36.4385 16.2267
myuser 24824 464 12.9 36.4385 16.2267
myuser 24824 466 12.9 36.4385 16.2267
myuser 24824 464 12.9 36.4385 16.2267
myuser 24824 463 12.9 36.4385 16.2419
myuser 24824 462 12.9 36.4385 16.2419
myuser 24824 461 12.9 36.4385 16.2419
myuser 24824 459 13.8 36.4385 17.4136
myuser 24824 458 15.0 36.4385 18.9508
myuser 24824 457 16.6 36.4385 20.9403
myuser 24824 460 17.4 36.4385 21.9497
myuser 24824 466 17.4 36.4385 21.9497
myuser 24824 473 17.4 36.4385 21.9497
myuser 24824 479 17.4 36.4385 21.9497
myuser 24824 486 17.4 36.4385 21.9497
myuser 24824 492 17.4 36.4385 21.9497
myuser 24824 499 17.4 36.4385 21.9497
myuser 24824 503 17.4 36.4385 21.9497
myuser 24824 510 17.4 36.4385 21.9497
myuser 24824 516 17.4 36.4385 21.9497
myuser 24824 522 17.4 36.4385 21.9497
myuser 24824 528 17.4 36.4385 21.9497
myuser 24824 535 17.4 36.4385 21.9497
myuser 24824 541 17.4 36.4385 21.9497
myuser 24824 547 17.4 36.4385 21.9497
myuser 24824 550 16.6 36.4385 20.9455
myuser 24824 548 16.6 36.4385 20.9406
myuser 24824 547 16.6 36.4385 20.9406
myuser 24824 546 16.6 36.4385 20.9406
myuser 24824 544 16.6 36.4385 20.9406
myuser 24824 543 16.6 36.4385 20.9406
myuser 24824 541 16.6 36.4385 20.9406
myuser 24824 540 16.6 36.4385 20.9406
myuser 24824 539 16.6 36.4385 20.9406
myuser 24824 535 16.6 36.4385 20.9406
myuser 24824 534 16.6 36.4385 20.9406
myuser 24824 533 16.6 36.4385 20.9406
myuser 24824 533 16.7 36.4385 21.0036
myuser 24824 531 16.7 36.7559 21.0037
myuser 24824 530 16.7 36.7559 21.0037
myuser 24824 528 16.7 36.7559 21.0036
myuser 24824 527 16.7 36.7559 21.0036
myuser 24824 525 16.7 36.7559 21.0036
myuser 24824 523 16.7 36.7559 21.0036
myuser 24824 522 16.7 36.7559 21.0036
```


I hope this helps.
Thanks!

**Comment by alitrack** [comment]
@randomgambit 
have a try in this way,

df_new <- spark_read_parquet(sc, "parquet_2014*",
                             overwrite = TRUE,
                             name = "df_new",
                             memory = FALSE)
```
library(DBI)
rs<-dbSendQuery(sc,"create or replace view df_new as select * from  parquet.`parquet_2014*`")
dbClearResult(rs)
df_new=  tbl(sc,"df_new")
```
no matter your parquet files in local or hdfs
