### ISSUE TITLE
yarn-client spark_disconnect(sc) not working in sparklyr > 0.6.2

### ISSUE THREAD

**Issue by bernhardschaefer** [rstudio/sparklyr#1213]
In sparklyr v0.6.3 & v0.6.4 in `yarn-client` mode, `spark_disconnect(sc)` does not shutdown the actual Spark job.
The Spark job is still listed as "RUNNING" in the resourcemanager. Even when killing this yarn application, the Spark driver Java process keeps running on the node where the sparklyr session has been created.

In sparklyr v0.6.2, the whole Spark job gracefully shuts down when `spark_disconnect` is used.

This whole issue can be reproduced using a very basic example:

```r
library(sparklyr)
sc <- spark_connect(master = "yarn-client")
spark_disconnect(sc)
```

The `spark_disconnect` does not show any error.
Also, if I use `spark_disconnect_all`, on the first call it returns `1`, all subsequent calls return `0`.

Output of `utils::sessionInfo()`:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.3 (Maipo)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.6.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     dbplyr_1.1.0     pillar_1.0.1     plyr_1.8.4       bindr_0.1        base64enc_0.1-3  tools_3.3.2     
 [8] digest_0.6.14    memoise_1.1.0    jsonlite_1.5     tibble_1.4.1     nlme_3.1-128     lattice_0.20-35  pkgconfig_2.0.1 
[15] rlang_0.1.6      psych_1.7.8      shiny_1.0.5      DBI_0.7          rstudioapi_0.7   yaml_2.1.16      parallel_3.3.2  
[22] bindrcpp_0.2     withr_2.1.1      dplyr_0.7.2      httr_1.3.1       stringr_1.2.0    devtools_1.13.4  rprojroot_1.3-2 
[29] grid_3.3.2       glue_1.2.0       R6_2.2.2         foreign_0.8-67   tidyr_0.7.0      purrr_0.2.4      reshape2_1.4.2  
[36] magrittr_1.5     backports_1.1.2  htmltools_0.3.6  assertthat_0.2.0 mnormt_1.5-5     mime_0.5         xtable_1.8-2    
[43] httpuv_1.3.5     config_0.2       stringi_1.1.2    openssl_0.9.9    lazyeval_0.2.1   broom_0.4.3   
```

**Comment by javierluraschi** [comment]
@bernhardschaefer we haven't been able to reproduce this issue, which Spark distribution you are using? Standalone? Cloudera? EMR? Hortonworks?

**Comment by bernhardschaefer** [comment]
Hortonworks HDP-2.6.1.0 with Spark 2.1.1.
For a full list of component versions see: https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.1/bk_release-notes/content/comp_versions.html.

**Comment by bernhardschaefer** [comment]
I tried to further debug this issue.
It seems to me like sparklyr has issues finding the matching Spark job.
E.g. spark_web(sc) opens the Spark UI of the wrong Spark application from another user.

The following shows the console output of everything I ran:

```
> library(sparklyr)
> sc <- spark_connect(master = "yarn-client")
Warning messages:
1: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
2: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
3: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
> library(dplyr)

Attaching package: \u2018dplyr\u2019

The following objects are masked from \u2018package:stats\u2019:

    filter, lag

The following objects are masked from \u2018package:base\u2019:

    intersect, setdiff, setequal, union

> src_tbls(sc) # this works as expected
 [1] "tbl1"                              "tbl2"                 "tbl3"                                       
                        
> spark_log(sc, n = 10) # works as expected, the stacktrace is only due to Spark trying a different port than 4040
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
18/01/17 10:40:43 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
18/01/17 10:41:05 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 10:41:05 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 10:41:09 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
18/01/17 10:41:09 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
Warning messages:
1: In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
2: In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
> spark_web(sc) # this shows the wrong Spark application of another user
Warning message:
In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
> spark_disconnect(sc)
> spark_log(sc, n = 10)
18/01/17 10:40:43 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
18/01/17 10:41:05 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 10:41:05 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 10:41:09 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
18/01/17 10:41:09 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
18/01/17 10:46:02 INFO sparklyr: Backend (49649) is unregistering session in gateway
18/01/17 10:46:02 INFO sparklyr: Backend (49649) is unregistering session in gateway
18/01/17 10:46:02 INFO sparklyr: Backend (49649) is waiting for unregistration in gateway
18/01/17 10:46:02 INFO sparklyr: Backend (49649) is waiting for unregistration in gateway

src_tbls(sc)
Error in writeBin(con, backend) : invalid connection
```

**Comment by bernhardschaefer** [comment]
So I redid everything from the last comment with sparklyr 0.6.2.
The issue with `spark_web()` pointing to the wrong Spark application remains.
However, `spark_disconnect(sc)` now works.

```R
> library(sparklyr)

Restarting R session...

> library(sparklyr)
> library(dplyr)

Attaching package: \u2018dplyr\u2019

The following objects are masked from \u2018package:stats\u2019:

    filter, lag

The following objects are masked from \u2018package:base\u2019:

    intersect, setdiff, setequal, union

> sc <- spark_connect(master = "yarn-client")
Warning messages:
1: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
2: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
3: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
> src_tbls(sc)
 [1] "addresses_sort"                              "bakeoff_at_predictions_rank"                 "cars"                                       
 [4] "daily_bakeoff"                               "hcatsmokeidc90a1cd9_date151516"              "hcatsmokeidc90a1cd9_date301616"             
 [7] "hcatsmokeidc90a1cd9_date360516"              "myars"                                       "pv_descriptive_results"                     
[10] "pv_descriptive_timeday_daily_test"           "pv_descriptive_timeday_weekly_smoothed_test" "pv_factor_wday_artur"                       
[13] "pv_factor_wday_nan_artur"                    "pv_factor_wday_nan_stable"                   "pv_factor_wday_stable"                      
[16] "saurabh_src"                                 "src"                                         "temp_scrm_cat"                              
[19] "test"                                        "test2"                                      

Restarting R session...

> library(sparklyr)
> library(dplyr)

Attaching package: \u2018dplyr\u2019

The following objects are masked from \u2018package:stats\u2019:

    filter, lag

The following objects are masked from \u2018package:base\u2019:

    intersect, setdiff, setequal, union

> 
> sc <- spark_connect(master = "yarn-client")
Warning messages:
1: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
2: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
3: In yaml.load(readLines(con), error.label = error.label, ...) :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
> 
> src_tbls(sc)
 [1] "test"                                        "test2"                                      
> spark_log(sc, n = 10)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
18/01/17 11:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
18/01/17 11:07:54 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 11:07:55 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 11:07:59 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
18/01/17 11:07:59 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
> spark_web(sc)
Warning messages:
1: In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
2: In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
3: In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
> spark_disconnect(sc)
> spark_log(sc, n = 10)
18/01/17 11:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
18/01/17 11:07:54 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 11:07:55 WARN Connection: BoneCP specified but not present in CLASSPATH (or one of dependencies)
18/01/17 11:07:59 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
18/01/17 11:07:59 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
18/01/17 11:09:48 INFO sparklyr: Backend (3081) is unregistering session in gateway
18/01/17 11:09:48 INFO sparklyr: Backend (3081) is waiting for unregistration in gateway
18/01/17 11:09:48 INFO sparklyr: Backend (3081) is terminating backend
18/01/17 11:09:49 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerExecutorMetricsUpdate(1,WrappedArray())
```

**Comment by javierluraschi** [comment]
Sounds good, will push a fix for `spark_web()` then. There is a new API in Spark 2.x that makes this much more reliable.

**Comment by bernhardschaefer** [comment]
Hi @javierluraschi, thanks for the fast fix.
I can confirm that `spark_web(sc)` works with this fix. 
However, the problem with `spark_disconnect(sc)` not working still remains.
