### ISSUE TITLE
Can't pull result back from Spark

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#1289]
A large RStudio Server Pro client is having trouble pulling results back from the Spark cluster.  I think the underlying issue is the remote table is "wide" (has over 500 columns).  I was able to build a trivial example that shows the problem.  Notice the data is not large and we are only trying to pull back one number.  

``` r
library("sparklyr")
conf <- sparklyr::spark_config()
conf$sparklyr.log.console <- FALSE
conf$spark.executor.memory <- "4G"
conf$spark.yarn.am.memory <- "4G" 
conf$spark.driver.maxResultSize <- "4G" 
db <- sparklyr::spark_connect(version='2.2.0', 
                              master = "local",
                              config = conf)
df <- as.data.frame(matrix(nrow = 1, 
                           ncol = 10000,
                           data = 0.0))
DBI::dbWriteTable(db, "df", df, temporary = TRUE)
df1 <- DBI::dbGetQuery(db, "SELECT V1 FROM df")
#> Error in value[[3L]](cond): Failed to fetch data: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.OutOfMemoryError: Java heap space
#>  at java.util.Arrays.copyOf(Arrays.java:3332)
#>  at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
#>  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
#>  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
#>  at java.lang.StringBuffer.append(StringBuffer.java:272)
#>  at org.apache.log4j.helpers.PatternParser$LiteralPatternConverter.format(PatternParser.java:419)
#>  at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
#>  at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
#>  at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:369)
#>  at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
#>  at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
#>  at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
#>  at org.apache.log4j.Category.callAppenders(Category.java:206)
#>  at org.apache.log4j.Category.forcedLog(Category.java:391)
#>  at org.apache.log4j.Category.log(Category.java:856)
#>  at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:576)
#>  at org.apache.spark.internal.Logging$class.logError(Logging.scala:91)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.logError(CodeGenerator.scala:901)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.org$apache$spark$sql$catalyst$expressions$codegen$CodeGenerator$$doCompile(CodeGenerator.scala:965)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1027)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1024)
#>  at org.spark_project.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
#>  at org.spark_project.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
#>  at org.spark_project.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
#>  at org.spark_project.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
#>  at org.spark_project.guava.cache.LocalCache.get(LocalCache.java:4000)
#>  at org.spark_project.guava.cache.LocalCache.getOrLoad(LocalCache.java:4004)
#>  at org.spark_project.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.compile(CodeGenerator.scala:906)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:412)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:366)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection$.create(GenerateUnsafeProjection.scala:32)
#> 
#> Driver stacktrace:
#>  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
#>  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
#>  at scala.Option.foreach(Option.scala:257)
#>  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
#>  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
#>  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
#>  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
#>  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2087)
#>  at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
#>  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
#>  at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
#>  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:278)
#>  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:2853)
#>  at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2390)
#>  at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2390)
#>  at org.apache.spark.sql.Dataset$$anonfun$55.apply(Dataset.scala:2837)
#>  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
#>  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:2836)
#>  at org.apache.spark.sql.Dataset.collect(Dataset.scala:2390)
#>  at sparklyr.Utils$.collect(utils.scala:211)
#>  at sparklyr.Utils.collect(utils.scala)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:102)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
#>  at sparklyr.StreamHandler$.read(stream.scala:62)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:52)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.p

sparklyr::spark_disconnect(db)
```

**Comment by JohnMount** [comment]
Also I was trying to research a work-around found the query itself fails.  Am I missing a config that will allocate enough memory to prevent this failure?

``` r
library("sparklyr")
conf <- sparklyr::spark_config()
conf$sparklyr.log.console <- FALSE
conf$spark.executor.memory <- "4G"
conf$spark.yarn.am.memory <- "4G" 
conf$spark.driver.maxResultSize <- "4G" 
db <- sparklyr::spark_connect(version='2.2.0', 
                              master = "local",
                              config = conf)
df <- as.data.frame(matrix(nrow = 1, 
                           ncol = 10000,
                           data = 0.0))
DBI::dbWriteTable(db, "df", df, temporary = TRUE)

# fails, see:
# https://github.com/rstudio/sparklyr/issues/1289
# df1 <- DBI::dbGetQuery(db, "SELECT V1 FROM df")

# attempted work around, also fails
DBI::dbExecute(db, "CREATE TABLE df2 as SELECT V1 from df")
#> Error: org.apache.spark.SparkException: Job aborted.
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:215)
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
#>  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:173)
#>  at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.run(InsertIntoHiveTable.scala:317)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
#>  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
#>  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
#>  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
#>  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
#>  at org.apache.spark.sql.hive.execution.CreateHiveTableAsSelectCommand.run(CreateHiveTableAsSelectCommand.scala:81)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:67)
#>  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:182)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:67)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:102)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
#>  at sparklyr.StreamHandler$.read(stream.scala:62)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:52)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:745)
#> Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.spark.SparkException: Task failed while writing rows
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:272)
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:191)
#>  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:190)
#>  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
#>  at org.apache.spark.scheduler.Task.run(Task.scala:108)
#>  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
#>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
#>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
#>  at java.lang.Thread.run(Thread.java:745)
#> Caused by: java.lang.OutOfMemoryError: Java heap space
#>  at java.util.Arrays.copyOf(Arrays.java:3332)
#>  at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
#>  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
#>  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
#>  at java.lang.StringBuffer.append(StringBuffer.java:272)
#>  at org.apache.log4j.helpers.PatternParser$LiteralPatternConverter.format(PatternParser.java:419)
#>  at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
#>  at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
#>  at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:369)
#>  at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
#>  at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
#>  at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
#>  at org.apache.log4j.Category.callAppenders(Category.java:206)
#>  at org.apache.log4j.Category.forcedLog(Category.java:391)
#>  at org.apache.log4j.Category.log(Category.java:856)
#>  at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:576)
#>  at org.apache.spark.internal.Logging$class.logError(Logging.scala:91)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.logError(CodeGenerator.scala:901)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$.org$apache$spark$sql$catalyst$expressions$codegen$CodeGenerator$$doCompile(CodeGenerator.scala:965)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1027)
#>  at org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$$anon$1.load(CodeGenerator.scala:1024)
#>  at org.s
df2 <- DBI::dbGetQuery(db, "SELECT * FROM df2")
#> Error: org.apache.spark.sql.AnalysisException: Table or view not found: df2; line 1 pos 14
#>  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupTableFromCatalog(Analyzer.scala:643)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.resolveRelation(Analyzer.scala:595)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:625)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:618)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:62)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:62)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:61)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:59)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:59)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
#>  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:59)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:618)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:564)
#>  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
#>  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
#>  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
#>  at scala.collection.immutable.List.foldLeft(List.scala:84)
#>  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
#>  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
#>  at scala.collection.immutable.List.foreach(List.scala:381)
#>  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:69)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:67)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:50)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:66)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:102)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
#>  at sparklyr.StreamHandler$.read(stream.scala:62)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:52)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:745)

sparklyr::spark_disconnect(db)
```

**Comment by javierluraschi** [comment]
We've seen a couple issues with wide tables in Spark, is it feasible to reduce columns in your example? We'll take a look at this one on the next patch.

**Comment by JohnMount** [comment]
The actual production example is probably around 700 columns.  It sometimes works, and sometimes does not work (which is hard to teach against).  My second comment is in fact me trying to narrow the table by a query (which fails).  The original application tried to narrow the data with `dplyr::select()`, but that also failed.  Would a `compute()` or checkpoint help?  The idea I am pursuing is: can we build a temporary thinner remote table and then try to collect from that.

**Comment by javierluraschi** [comment]
Sounds like a Spark limitation, but let me see what I can do in the next couple days, ping me here again if I don't report back with progress.

**Comment by JohnMount** [comment]
I tried some more variations (from https://github.com/rstudio/sparklyr/issues/287 ) which I think got me closer.  

``` r
library("sparklyr")
conf <- spark_config()
conf$sparklyr.log.console <- FALSE
conf$spark.executor.memory <- "8G"
conf$spark.yarn.am.memory <- "8G" 
conf$`sparklyr.shell.driver-memory` <- "4G"
conf$`sparklyr.shell.executor-memory` <- "4G"
conf$`spark.yarn.executor.memoryOverhead` <- "4G"
db <- sparklyr::spark_connect(version='2.2.0', 
                              master = "local",
                              config = conf)
df <- as.data.frame(matrix(nrow = 1, 
                           ncol = 10000,
                           data = 0.0))
DBI::dbWriteTable(db, "df", df, temporary = TRUE)
df1 <- DBI::dbGetQuery(db, "SELECT V1 FROM df")
#> Error in value[[3L]](cond): Failed to fetch data: C stack usage  154826172 is too close to the limit
df1 <- dplyr::as.tbl(df1)
#> Error in dplyr::as.tbl(df1): object 'df1' not found
spark_disconnect(db)
```

**Comment by javierluraschi** [comment]
Moving to next milestone since investigation shows this would require some Spark workarounds that are non-trivial

**Comment by JohnMount** [comment]
Neat idea, looking forward to it.
