### ISSUE TITLE
Spark_apply fails on permissions error

### ISSUE THREAD

**Issue by nviets** [rstudio/sparklyr#1320]
Hello,

I tried to call spark_apply on a table where I have read-only permissions, but the job fails on a permissions error.  Using basic sparklyr syntax, I'm able to query the table normally.  Spark_apply works on tables I manually push from R to spark memory.

Thanks for investigating.

Best,
Nathan

# example that fails
> myTable %>%
+   select(myCol) %>%
+   select(myCol) %>%
+   spark_apply(function(data) {
+     data[1] + rgamma(1,2)
+   })
Error in force(code) : 
  sparklyr worker rscript failure, check worker logs for details
    Log: /opt/revr/tmp/RtmpIMI0YS/file769622f08add_spark.log

---- Output Log ----
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to alter table. java.security.AccessControlException: User myUserID (user id 10031828) does not have access to maprfs:///core/myTable
	at org.apache.hadoop.hive.ql.metadata.Hive.alterTable(Hive.java:557)
	at org.apache.hadoop.hive.ql.metadata.Hive.alterTable(Hive.java:543)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$alterTable$1.apply$mcV$sp(HiveClientImpl.scala:440)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$alterTable$1.apply(HiveClientImpl.scala:436)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$alterTable$1.apply(HiveClientImpl.scala:436)
	at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:283)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:230)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:229)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:272)
	at org.apache.spark.sql.hive.client.HiveClientImpl.alterTable(HiveClientImpl.scala:436)
	at org.apache.spark.sql.hive.client.HiveClient$class.alterTable(HiveClient.scala:89)
	at org.apache.spark.sql.hive.client.HiveClientImpl.alterTable(HiveClientImpl.scala:78)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$alterTableSchema$1.apply$mcV$sp(HiveExternalCatalog.scala:615)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$alterTableSchema$1.apply(HiveExternalCatalog.scala:600)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$alterTableSchema$1.apply(HiveExternalCatalog.scala:600)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
	... 84 more
Caused by: MetaException(message:java.security.AccessControlException: User myUserID(user id 10031828) does not have access to maprfs:///core/myTable)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_cascade_result$alter_table_with_cascade_resultStandardScheme.read(ThriftHiveMetastore.java:48810)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_cascade_result$alter_table_with_cascade_resultStandardScheme.read(ThriftHiveMetastore.java:48787)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_cascade_result.read(ThriftHiveMetastore.java:48729)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_table_with_cascade(ThriftHiveMetastore.java:1382)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.alter_table_with_cascade(ThriftHiveMetastore.java:1366)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.alter_table(HiveMetaStoreClient.java:349)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.alter_table(SessionHiveMetaStoreClient.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:164)
	at $Proxy14.alter_table(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:1997)
	at $Proxy14.alter_table(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.alterTable(Hive.java:555)
	... 99 more
18/02/23 09:32:26 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/02/23 09:32:26 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/02/23 09:32:41 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/02/23 09:32:41 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/02/23 09:33:08 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/02/23 09:33:09 INFO sparklyr: Worker (7173) is tracking worker context under 48
18/02/23 09:33:09 INFO sparklyr: Worker (7173) initializing backend
18/02/23 09:33:09 INFO sparklyr: Session (7173) is starting under 127.0.0.1 port 8880
18/02/23 09:33:09 INFO sparklyr: Worker (7173) starting backend
18/02/23 09:33:09 INFO sparklyr: Session (7173) is waiting for sparklyr client to connect to port 16291
18/02/23 09:33:09 INFO sparklyr: Worker (7173) is waiting using lock for RScript to complete
18/02/23 09:33:09 INFO sparklyr: Worker (7173) is starting rscript
18/02/23 09:33:09 INFO sparklyr: Worker (7173) using source file /opt/mapr/tmp/spark/sparkworker/7f5c060d-5eed-4376-b0ad-985b183a372e/sparkworker.R
18/02/23 09:33:09 INFO sparklyr: Worker (7173) launching command Rscript --vanilla /opt/mapr/tmp/spark/sparkworker/7f5c060d-5eed-4376-b0ad-985b183a372e/sparkworker.R 7173 16291 FALSE;8880;localhost
18/02/23 09:33:09 INFO sparklyr: Worker (7173) is starting R process
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is starting 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is connecting to backend using port 16291 
18/02/23 09:33:10 INFO sparklyr: Session (7173) accepted connection
18/02/23 09:33:10 INFO sparklyr: Session (7173) is waiting for sparklyr client to connect to port 16291
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is querying ports from backend using port 16291 
18/02/23 09:33:10 INFO sparklyr: Session (7173) received command 0
18/02/23 09:33:10 INFO sparklyr: Session (7173) found requested session matches current session
18/02/23 09:33:10 INFO sparklyr: Session (7173) is creating backend and allocating system resources
18/02/23 09:33:10 INFO sparklyr: Session (7173) created the backend
18/02/23 09:33:10 INFO sparklyr: Session (7173) is waiting for r process to end
18/02/23 09:33:10 INFO sparklyr: RScript (7173) found redirect gateway port 16291 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is connected to backend 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is connecting to backend session 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is connected to backend session 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) created connection 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) is connected 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) retrieved worker context id 48 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) retrieved worker context 
18/02/23 09:33:10 INFO sparklyr: RScript (7173) found 1679449 rows 
18/02/23 09:34:10 INFO sparklyr: RScript (7173) retrieved 1679449 rows 
18/02/23 09:34:46 INFO sparklyr: RScript (7173) computing closure 
18/02/23 09:34:48 INFO sparklyr: RScript (7173) computed closure 
18/02/23 09:34:48 INFO sparklyr: RScript (7173) updating 1679449 rows 
18/02/23 09:39:26 ERROR sparklyr: Session (7173) failed calling setResultArraySeq on 48
18/02/23 09:39:26 ERROR sparklyr: RScript (7173) terminated unexpectedly: there is no package called ‘withr’ 
18/02/23 09:39:26 ERROR sparklyr: Worker (7173) failed to complete R process
(18/02/23 09:39:26 ERROR sparklyr: Worker (7173) failed to run rscript: ,java.lang.Exception: sparklyr worker rscript failure with status 255, check wo

# example that works
> iris_tbl %>%
+   spark_apply(function(data) {
+     data[1] + rgamma(1,2)
+   })
# Source:   table<sparklyr_tmp_76967654f0e5> [?? x 1]
# Database: spark_connection
   Sepal_Length
          <dbl>
 1         7.92
 2         7.72
 3         7.52
 4         7.42
 5         7.82
 6         8.22
 7         7.42
 8         7.82
 9         7.22
10         7.72
# ... with more rows
>

**Comment by yitao-li** [comment]
The actual error is "terminated unexpectedly: there is no package called ‘withr’" which tells me you did not install withr on your Spark workers. The default spark_apply() behavior is to copy R packages from your current R env to Spark worker nodes, so maybe check if withr is installed in your current R env?
