### ISSUE TITLE
Cannot pass data as a Scala List object

### ISSUE THREAD

**Issue by nathaneastwood** [rstudio/sparklyr#1324]
There doesn't appear to be any documentation around this so I assume this is an issue. According to [this link](https://campus.datacamp.com/courses/introduction-to-spark-in-r-using-sparklyr/going-native-use-the-native-interface-to-manipulate-spark-dataframes?ex=10), passing an R `list` to an `invoke` function will pass a Spark `ArrayType`. How exactly do I pass a list? I am trying to call [this function](https://github.com/SteveBall/SML/blob/master/src/main/scala/com/ons/sml/businessMethods/methods/Lag.scala) from R but when giving it a list, it obviously doesn't work because the data types don't match up. So how exactly do we pass lists? I feel like there should be an `ensure_scala_list` function. The code that I am running can be found below.

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

# Read in the data
lag_data <- data.frame("id" = c(1, 1, 1, 2, 2), "t" = c(1, 2, 3, 1, 2), "v" = c(11, 12, 13, 21, 22)) %>% 
  sdf_copy_to(sc, ., name = "lag_data") %>% 
  spark_dataframe()

# Invoke the lagFunc method
invoke_static(
  sc,
  class = "com.ons.sml.businessMethods.methods.Lag",
  method = "lag",
  df = lag_data
) %>% invoke(
  "lagFunc", 
  df = lag_data, 
  partitionCol = as.list(ensure_scalar_character("id")), 
  orderCol = as.list(ensure_scalar_character("t")), 
  targetCol = ensure_scalar_character("v"), 
  lagNum = ensure_scalar_integer(2L)
)
```

My session info is as follows:

```r
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.419)           
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               
 date     2018-02-26                  

Packages -----------------------------------------------------------------------------------------------------------
 package    * version    date       source        
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)
 backports    1.1.2      2017-12-13 CRAN (R 3.4.3)
 base       * 3.4.3      2017-12-07 local         
 base64enc    0.1-3      2015-07-28 CRAN (R 3.4.0)
 bindr        0.1        2016-11-13 CRAN (R 3.4.0)
 bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)
 broom        0.4.3      2017-11-20 CRAN (R 3.4.3)
 cli          1.0.0      2017-11-05 CRAN (R 3.4.2)
 compiler     3.4.3      2017-12-07 local         
 config       0.2        2016-08-02 CRAN (R 3.4.0)
 crayon       1.3.4      2017-09-16 CRAN (R 3.4.1)
 datasets   * 3.4.3      2017-12-07 local         
 DBI          0.7        2017-06-18 CRAN (R 3.4.0)
 dbplyr       1.2.1      2018-02-19 CRAN (R 3.4.3)
 devtools     1.13.5     2018-02-18 CRAN (R 3.4.3)
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)
 dplyr        0.7.4      2017-09-28 CRAN (R 3.4.2)
 foreign      0.8-69     2017-06-22 CRAN (R 3.4.3)
 glue         1.2.0      2017-10-29 CRAN (R 3.4.2)
 graphics   * 3.4.3      2017-12-07 local         
 grDevices  * 3.4.3      2017-12-07 local         
 grid         3.4.3      2017-12-07 local         
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)
 httpuv       1.3.5      2017-07-04 CRAN (R 3.4.1)
 httr         1.3.1      2017-08-20 CRAN (R 3.4.1)
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.0)
 lattice      0.20-35    2017-03-25 CRAN (R 3.4.3)
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.2)
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)
 methods    * 3.4.3      2017-12-07 local         
 mime         0.5        2016-07-07 CRAN (R 3.4.0)
 mnormt       1.5-5      2016-10-15 CRAN (R 3.4.0)
 nlme         3.1-131    2017-02-06 CRAN (R 3.4.3)
 openssl      1.0        2018-02-02 CRAN (R 3.4.3)
 parallel     3.4.3      2017-12-07 local         
 pillar       1.1.0      2018-01-14 CRAN (R 3.4.3)
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)
 psych        1.7.8      2017-09-09 CRAN (R 3.4.3)
 purrr        0.2.4      2017-10-18 CRAN (R 3.4.2)
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)
 rappdirs     0.3.1      2016-03-28 CRAN (R 3.4.0)
 Rcpp         0.12.15    2018-01-20 CRAN (R 3.4.3)
 reshape2     1.4.3      2017-12-11 CRAN (R 3.4.3)
 rlang        0.1.6      2017-12-21 CRAN (R 3.4.3)
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.4.3)
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.1)
 shiny        1.0.5      2017-08-23 CRAN (R 3.4.1)
 sparklyr   * 0.7.0      2018-01-23 CRAN (R 3.4.3)
 sparkts    * 0.0.0.9000 2018-02-26 local         
 stats      * 3.4.3      2017-12-07 local         
 stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)
 stringr      1.3.0      2018-02-19 CRAN (R 3.4.3)
 tibble       1.4.2      2018-01-22 CRAN (R 3.4.3)
 tidyr        0.8.0      2018-01-29 CRAN (R 3.4.3)
 tools        3.4.3      2017-12-07 local         
 utf8         1.1.3      2018-01-03 CRAN (R 3.4.3)
 utils      * 3.4.3      2017-12-07 local         
 withr        2.1.1      2017-12-19 CRAN (R 3.4.3)
 xtable       1.8-2      2016-02-05 CRAN (R 3.4.0)
 yaml         2.1.16     2017-12-12 CRAN (R 3.4.3)
```

**Comment by schlichtanders** [comment]
use ``Seq`` instead of ``List`` as your type
luckily ``Array`` has also the ``Seq`` trait in Scala, so everything works out-of-the-box

if you really need ``List``, Seq has also a ``toList`` method which you can use for conversion

**Comment by nathaneastwood** [comment]
Yes that's a possibility but we have a large code base we don't want to start making changes to. We could use overloading, which [has issues](https://stackoverflow.com/questions/2510108/why-avoid-method-overloading), or we could define a new method that is called from R, which effectively invokes the `toList` function on the sequence and then calls the existing method, but ideally we would like a way to sort this on the R side.

**Comment by kevinykuo** [comment]
I wonder if it'd make sense to have a low-level API in sparklyr to facilitate some of these conversions. @javierluraschi thoughts?

**Comment by mattpollock** [comment]
Not terribly elegant, but this can be accomplished in R

```r
# map some R vector `x` to a java ArrayList
new_array_list <- invoke_new(sc, "java.util.ArrayList")
lapply(x, FUN = function(y){invoke(new_array_list, "add", y)})

 # convert from list to seq if that's what you want
sbuf <- invoke_static(sc, "scala.collection.JavaConversions", "asScalaBuffer", lst)
new_seq ,- invoke(sbuf, "toSeq")
```

**Comment by nathaneastwood** [comment]
@mattpollock I don't think this works:

```
create_scala_list <- function(sc, x) {
  tmp <- invoke_new(sc, "java.util.ArrayList")
  tmp <- lapply(
    x,
    FUN = function(y) {
      invoke(new_array_list, "add", y)
    }
  )
  print(tmp)
}
create_scala_list(sc, x = "id")
# [[1]]
# [1] TRUE
```

**Comment by nathaneastwood** [comment]
@mattpollock I don't think this will work in my case still. Let's say I update my example in my original post such that I include a functionalised version of your code.

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

# Read in the data
lag_data <- data.frame(
  "id" = c(1, 1, 1, 2, 2), 
  "t" = c(1, 2, 3, 1, 2), 
  "v" = c(11, 12, 13, 21, 22)
) %>% 
  sdf_copy_to(sc, ., name = "lag_data") %>% 
  spark_dataframe()

# Create the scala lists
create_scala_list <- function(sc, x) {
  array_list <- invoke_new(sc, "java.util.ArrayList")
  lapply(
    x,
    FUN = function(y) {
      invoke(array_list, "add", y)
    }
  )
  array_list
}

pc <- create_scala_list(sc, "id")
oc <- create_scala_list(sc, "t")

# Invoke the lagFunc method
invoke_static(
  sc,
  class = "com.ons.sml.businessMethods.methods.Lag",
  method = "lag",
  df = lag_data
) %>% invoke(
  "lagFunc", 
  df = lag_data, 
  partitionCol = pc, 
  orderCol = oc, 
  targetCol = "v", 
  lagNum = 2L
)
```

I still get the same error as before:

```
# Error: java.lang.Exception: No matched method found for class com.ons.sml.businessMethods.methods.Lag.lagFunc
```

I think this is possibly because they are Java lists? Inspecting `pc`, for example, shows

```r
pc
# <jobj[308]>
#   java.util.ArrayList
#   [id]
```

So I have an `ArrayList` and not a `List` object. My Java/Scala knowledge is very limited to understand whether this is important.

**Comment by mattpollock** [comment]
Seems like you're nearly there. Now convert your java list to a scala list. Disclaimer here is that I'm not a scala guy - there may be better ways of doing this. But this does at least seem functional.

```r
> pc <- create_scala_list(sc, "id")
> oc <- create_scala_list(sc, "t")
pc
# <jobj[61]>
#   java.util.ArrayList
#   [id]
s_scala_list <- invoke_static(sc, "scala.collection.JavaConversions", "asScalaBuffer", pc) %>%
 invoke("toSeq") %>%
 invoke("toList")
ps_scala_list
# <jobj[76]>
#   scala.collection.immutable.$colon$colon
#   List(id)
```

**Comment by nathaneastwood** [comment]
Amazing! Thanks so much @mattpollock!

@kevinykuo Would you like me to submit a PR with this code in? I feel this is something that should be callable from R rather than having to go through all of this. I suspect that there will also be other types too, however, and so maybe some instructions in a vignette would be better placed than having functions for every data type?

**Comment by schlichtanders** [comment]
I would have thought that 
```
invoke_static(sc, "scala.collection.immutable.List", "apply", list(1,2))
```
works too, but I get a ``NullPointerException``
```
Error: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```
does someone know why this happens?

this would be the most straightforward way I think
