### ISSUE TITLE
Unable to Install Package Requiring to Load sparklyr ML Model

### ISSUE THREAD

**Issue by chrisvwn** [rstudio/sparklyr#1345]
Hi,

I am trying to install an R package for use with OpenCPU on Centos 7.1 with R 3.4.3. The package uses `spark` via the `sparklyr` package and needs to read in a spark model that is saved in the `inst/extdata` folder in the package. However, the error obtained seems to indicate that R is looking for the package/extdata on hdfs rather than on the disk?

The relevant parts of the package:

`api.R` the only R script in the package connects to spark and loads the saved spark models. It also has 3 API prediction functions, one for each model:

```{r}
if(!require(sparklyr))
{
  install.packages("sparklyr")
  library(sparklyr)
  spark_install()
}

if(!require(jsonlite))
{
  install.packages("rjsonlite")
  library(rjsonlite)
}

if(!require(dplyr))
{
  install.packages("dplyr")
  library(dplyr)
}

config <- sparklyr::spark_config()
sc <- sparklyr::spark_connect(master = "spark://x.x.x.x:7077", config = config)

if(!spark_connection_is_open(sc))
  stop("Startup: Unable to connect to Spark")

strTrainingData21DT <- readRDS(system.file('extdata', 'strTrainingData21DT.RDS', package = 'vdaiocpuspark'))
mdlGBT <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdlgbt.mdl', package = 'vdaiocpuspark'))
mdlRF <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdlrf.mdl', package = 'vdaiocpuspark'))
mdlDT <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdldt.mdl', package = 'vdaiocpuspark'

function1 <- function(Inputs)
{
  ...
}

.
.
.
```
The error I get:

```
[root@vdai ~]# Rscript -e 'install.packages("vdaiocpuspark_0.1.0-1.tar.gz", repos=NULL, type="source")'
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘vdaiocpuspark’ ...
** R
** inst
** preparing package for lazy loading
**Error : org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://localhost:9000/usr/lib64/R/library/vdaiocpuspark/extdata/sparkmdlgbt.mdl/metadata/part-00000;**
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:360)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:333)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

Error : unable to load R code in package ‘vdaiocpuspark’
ERROR: lazy loading failed for package ‘vdaiocpuspark’
* removing ‘/usr/lib64/R/library/vdaiocpuspark’
* restoring previous ‘/usr/lib64/R/library/vdaiocpuspark’
Warning message:
In install.packages("vdaiocpuspark_0.1.0-1.tar.gz",  :
  installation of package ‘vdaiocpuspark_0.1.0-1.tar.gz’ had non-zero exit status
```

my sessioninfo:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.3  R6_2.2.2        tools_3.4.3    
 [5] withr_2.1.1     curl_3.1        memoise_1.1.0   knitr_1.18     
 [9] git2r_0.20.0    digest_0.6.13   devtools_1.13.5
```
This seems related to #1088 and maybe #1260 with the difference being the model I am trying to load is contained in the package and the path seems to get misinterpreted by ml_load? I have tried using the dev rstudio/sparklyr version with the same result.

**Comment by kevinykuo** [comment]
Could you try passing the complete path to `ml_load()`, with the `file:///` prefix?

**Comment by chrisvwn** [comment]
That works! Install is successful. However, now when I try to load the package it fails with the following error:

```
> library(vdaiocpuspark)
Error: package or namespace load failed for ‘vdaiocpuspark’:
 .onLoad failed in loadNamespace() for 'vdaiocpuspark', details:
  call: force(code)
  error: Failed while connecting to sparklyr to port (8880) for sessionid (33818): ignoring SIGPIPE signal
    Path: /opt/spark-2.2.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 33818
    Log: /tmp/RtmpPzMxVx/fileb30b21cd9db6_spark.log


---- Output Log ----
18/03/16 17:11:40 INFO sparklyr: Session (33818) is starting under 127.0.0.1 port 8880
18/03/16 17:11:40 INFO sparklyr: Session (33818) found port 8880 is available
18/03/16 17:11:40 INFO sparklyr: Gateway (33818) is waiting for sparklyr client to connect to port 8880

---- Error Log ----

```
The mentioned log file has pretty much the same as above:

```
18/03/16 17:11:40 INFO sparklyr: Session (33818) is starting under 127.0.0.1 port 8880
18/03/16 17:11:40 INFO sparklyr: Session (33818) found port 8880 is available
18/03/16 17:11:40 INFO sparklyr: Gateway (33818) is waiting for sparklyr client to connect to port 8880
18/03/16 17:12:40 INFO sparklyr: Gateway (33818) is terminating backend since no client has connected after 60 seconds
```

**Comment by kevinykuo** [comment]
Could you describe your use case here? Are you trying to serve spark models for real-time predictions?

**Comment by chrisvwn** [comment]
Yes. I am trying to serve spark models for real-time predictions.
