### ISSUE TITLE
Add ALS ML model similar to SparkR

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#139]
could you add ALS Model similar to this:

https://github.com/apache/spark/pull/14384

**Comment by kevinushey** [comment]
For reference, the Scala class: http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.ml.recommendation.ALS

**Comment by kevinushey** [comment]
I've added a quick dummy implementation of this; can you give it a shot and see if it behaves how you expect?

**Comment by ElianoMarques** [comment]
Sure. I will come back to you tomorrow morning on this. I just saw the code, thanks for adding.

**Comment by ElianoMarques** [comment]
@kevinushey, the model seems to be working but the predictions fail. Perhaps a good thing to bring some of the evaluator to the package. Code below:

```
ratings <- tbl(sc, "ratings")
partitions <- sdf_partition(ratings,training = 0.8, test = 0.2)
als <- ml_als_factorization(partitions$training, rating.column = "Rating",
                            user.column = "UserID", item.column = "MovieID", rank = 10, max.iter = 5)
predictions = sdf_predict(als,partitions$test)
spark_dataframe(partitions$test) %>% invoke("transform",als)

reg_evaluator_path <- "org.apache.spark.ml.evaluation.RegressionEvaluator"
reg_evaluator <- invoke_new(sc, reg_evaluator_path)
reg_evaluator  %>%
  invoke("setMetricName", "rmse") %>%
  invoke("setLabelCol","Rating") %>%
  invoke("setPredictionCol","prediction") %>% invoke("evaluate", predictions)
```

Errors:
```
predictions = sdf_predict(als,partitions$test)
Error: java.lang.NullPointerException
	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:47)
	at scala.collection.immutable.StringOps.length(StringOps.scala:47)
	at scala.collection.IndexedSeqOptimized$class.isEmpty(IndexedSeqOptimized.scala:27)
	at scala.collection.immutable.StringOps.isEmpty(StringOps.scala:29)
	at scala.collection.TraversableOnce$class.nonEmpty(TraversableOnce.scala:111)
	at scala.collection.immutable.StringOps.nonEmpty(StringOps.scala:29)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:42)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:65)
	at org.apache.spark.ml.feature.VectorAssembler.transform(VectorAssembler.scala:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.
spark_dataframe(partitions$test) %>% invoke("transform",als)
Error in writeType(con, serdeType) : 
  Unsupported type for serialization ml_model_als_factorization
```
Any hints on the why is not predicting?

**Comment by kevinushey** [comment]
Are there any missing / null values in your data set? If so, you might need to remove those.

Also, in this:

```
spark_dataframe(partitions$test) %>% invoke("transform",als)
```

You likely want to invoke the `transform` method of `als` on the test dataset, not the other way around. Ie, I think you want:

```
als$.model %>% invoke("transform", spark_dataframe(partitions$test))
```

**Comment by ElianoMarques** [comment]
This works.

```
predictions = als$.model %>% invoke("transform", spark_dataframe(partitions$test))

reg_evaluator_path <- "org.apache.spark.ml.evaluation.RegressionEvaluator"
reg_evaluator <- invoke_new(sc, reg_evaluator_path)
rmse = reg_evaluator  %>%
  invoke("setMetricName", "rmse") %>%
  invoke("setLabelCol","Rating") %>%
  invoke("setPredictionCol","prediction") %>% invoke("evaluate", predictions)
```
However the rmse returns nan probably because of missing/ null values. Need to check that. Note that the standard sdf_predict doesn't probably because of the same reason. 

Eliano

**Comment by ElianoMarques** [comment]
just tried: 
```
test = na.omit(partitions$test, columns = "Rating")
predictions = sdf_predict(als,test)
Error: java.lang.NullPointerException
	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:47)
	at scala.collection.immutable.StringOps.length(StringOps.scala:47)
	at scala.collection.IndexedSeqOptimized$class.isEmpty(IndexedSeqOptimized.scala:27)
	at scala.collection.immutable.StringOps.isEmpty(StringOps.scala:29)
	at scala.collection.TraversableOnce$class.nonEmpty(TraversableOnce.scala:111)
	at scala.collection.immutable.StringOps.nonEmpty(StringOps.scala:29)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:42)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:65)
	at org.apache.spark.ml.feature.VectorAssembler.transform(VectorAssembler.scala:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.
```
Still gets the same but this works fine 
```
predictions = als$.model %>% invoke("transform", spark_dataframe(partitions$test))
```

**Comment by kevinushey** [comment]
I haven't seen much about the `RegressionEvaluator` class -- is it supposed to be a kind of interface to accessing summary statistics for a model fit?

**Comment by ElianoMarques** [comment]
yap, it is. I just confirmed in python the prediction had some null and na. 

I made it to work like this:
```
predictions = als$.model %>% invoke("transform", spark_dataframe(test)) %>% 
spark_dataframe() %>%  invoke("na") %>% invoke("drop")
```
ie. the na.omit was not working, i've tried 
```
predictions = als$.model %>% invoke("transform", spark_dataframe(test)) %>% na.omit() 
```
while it does the job the evaluator returns nan which means predictions didn't drop.  I then wrote the na.drop by hand and worked fine. 

Thanks
