### ISSUE TITLE
Cannot write spark table due to wrong FS

### ISSUE THREAD

**Issue by shabbybanks** [rstudio/sparklyr#1421]
I am unable to write a temporary data frame, sourced from a CSV in hdfs, into a database table due to a `Wrong FS` error. The 'expected' database, `hdfs://groupprod` is not something in my configuration, but I assume it is somehow in the default Hive configurations. Searching around on the internet for [this error](https://opensourceconnections.com/blog/2013/03/24/hdfs-debugging-wrong-fs-expected-file-exception/) suggests that somehow there is a Java error due to passing a `String` instead of a `Path`, which I am afraid is beyond my understanding of what is going on under the hood.
```
indata <- spark_read_csv(sc=sc,
                         path='hdfs://nameservice1/usrwrk/foo/bar/myfile.csv',
                         name='zko_test_import',
                         infer_schema=TRUE,
                         header=TRUE)

spark_write_table(indata, 'zk_test_written', mode='overwrite')

Error: java.lang.IllegalArgumentException: Wrong FS: hdfs://nameservice1/usrwrk/foo/schemas/database_name_1.db/zk_test_written,
expected: hdfs://groupprod
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:657)
        at org.apache.hadoop.fs.FileSystem.makeQualified(FileSystem.java:477)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$doCreateTable$1.apply$mcV$sp(HiveExternalCatalog.scala:246)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$doCreateTable$1.apply(HiveExternalCatalog.scala:217)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$doCreateTable$1.apply(HiveExternalCatalog.scala:217)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:99)
        at org.apache.spark.sql.hive.HiveExternalCatalog.doCreateTable(HiveExternalCatalog.scala:217)
        at org.apache.spark.sql.catalyst.catalog.ExternalCatalog.createTable(ExternalCatalog.scala:110)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.createTable(SessionCatalog.scala:316)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:166)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        ...

 1: spark_write_table(indata, "zk_test_written", mode = "overwrite")
 2: spark_write_table.tbl_spark(indata, "zk_test_written", mode = "overwrite")
 3: spark_data_write_generic(sqlResult, name, fileMethod, mode, options, partit
 4: invoke(options, fileMethod, path)
 5: invoke.shell_jobj(options, fileMethod, path)
 6: invoke_method(spark_connection(jobj), FALSE, jobj, method, ...)
 7: invoke_method.spark_shell_connection(spark_connection(jobj), FALSE, jobj, m
 8: core_invoke_method(sc, static, object, method, ...)
 9: withr::with_options(list(warning.length = 8000), {
    if (nzchar(msg)) {

10: force(code)
```

**Comment by shabbybanks** [comment]
(I have tried to scrub some of the path names here, because my company prefers obscurity.)

**Comment by shabbybanks** [comment]
[Another google hit](http://techidiocy.com/java-lang-illegalargumentexception-wrong-fs-expected-file/) has more Java bits that hint either a configuration hiccough or an incorrect type somewhere in the scala code.
