### ISSUE TITLE
copy_to error & saveAsTable option

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#143]
I have the public movies dataset and this is returning an error with the function copy_to.

code used:

```
movies <- readLines(paste(getwd(),path,"movies.dat",sep = ""))
movies = gsub("::","\t", movies)
movies <- fread(paste(movies, collapse="\n"), sep="\t")
setnames(movies, c("movie_id", "title", "genres"))
str(movies)
movies_tbl = copy_to(sc, movies, "movies_temp")
```

Here is two lines of the data:
movie_id, title, genres
1,Toy Story (1995),Animation|Children's|Comedy

Not sure if scala/java likes the "|" , here is the error:

```
    at sparklyr.Utils$$anonfun$4$$anonfun$5.apply(utils.scala:56)
    at sparklyr.Utils$$anonfun$4$$anonfun$5.apply(utils.scala:55)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:234)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.mutable.ArrayOps$ofInt.map(ArrayOps.scala:234)
    at sparklyr.Utils$$anonfun$4.apply(utils.scala:55)
    at sparklyr.Utils$$anonfun$4.apply(utils.scala:53)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scal
```

Currently only sdf_register is available. Perhaps you could add sdf_saveAsTable, see below:

```
sdf_register(movies_tbl)
spark_dataframe(movies_tbl) %>% invoke("write") %>% invoke("saveAsTable",as.character("movies"))
```

From a discovery perspective, sometimes its easier to persist a table to hive to enable others to use without the hassle of copy into etc. Also enable append which might be useful. 

Thanks

**Comment by kevinushey** [comment]
Where does this movies data set come from (`movies.dat`)?

**Comment by ElianoMarques** [comment]
[http://grouplens.org/datasets/movielens/](http://grouplens.org/datasets/movielens/) 

I'm using the 1m row dataset.

**Comment by kevinushey** [comment]
This code works fine for me:

```R
library(sparklyr)
library(dplyr)
library(data.table)

sc <- spark_connect(master = "local", version = "2.0.0")

setwd(tempdir())
zipfile <- "ml-1m.zip"
download.file("http://files.grouplens.org/datasets/movielens/ml-1m.zip", destfile = zipfile)
unzip(zipfile)

contents <- readLines("ml-1m/movies.dat")
replaced <- gsub("::", "\t", contents)
movies <- fread(paste(replaced, collapse = "\n"), sep = "\t")
setnames(movies, c("movie_id", "title", "genres"))
str(movies)
movies_tbl <- copy_to(sc, movies, "movies_temp")
```

What version of Spark are you using?

**Comment by ElianoMarques** [comment]
we are using the same code. the difference is that you are using master = local and I'm using yarn-client.

**Comment by kevinushey** [comment]
I see. Based on your stack trace, it would be our `utils` jar that is failing. It indeed interprets `|` as a separator -- see: https://github.com/rstudio/sparklyr/blob/51b55890f99004888b2baeeeb1531ae6a4d655e5/inst/scala/utils.scala#L47-L71

Copying the code for posterity:

```scala
    var data = rows.map(o => {
      val r = o.split('|')
      var typed = (Array.range(0, r.length)).map(idx => {
        val column = columns(idx)
        val value = r(idx)

        column match {
          case "integer"  => if (Try(value.toInt).isSuccess) value.toInt else null.asInstanceOf[Int]
          case "double"  => if (Try(value.toDouble).isSuccess) value.toDouble else null.asInstanceOf[Double]
          case "logical" => if (Try(value.toBoolean).isSuccess) value.toBoolean else null.asInstanceOf[Boolean]
          case _ => value
        }
      })

      org.apache.spark.sql.Row.fromSeq(typed)
    })
```

cc: @javierluraschi, is there a different / 'safer' separator we could be using here?

**Comment by kevinushey** [comment]
To get you unblocked in the interim, I think you need to rename any pipe characters (`|`) to some other separator.

**Comment by ElianoMarques** [comment]
ok.

**Comment by javierluraschi** [comment]
Fixed with https://github.com/rstudio/sparklyr/commit/321d56ddfe47aa8f56ce3bcc8c3f57298f38dcb5
