### ISSUE TITLE
Connecting to Spark using cluster mode Hive connectivity failed.

### ISSUE THREAD

**Issue by Purna17** [rstudio/sparklyr#1430]
# Reporting an Issue with sparklyr

While connecting to spark using cluster mode not able to establish Hive connection it fails with below exception. It is able to establish connection spark in cluster only exception I got from Hive connectivity.

It is succeeded with client mode, i can see hive tables, but not with cluster mode.

Even I supplied hive-site.xml file explicitly but still failed with below exception.

ENV:
-----
Target Spark version:  2.1.1 (HDP Stack) 

$master
[1] "yarn-cluster"

$method
[1] "shell"

$app_name
[1] "SparklyR-New"

$config
$config$sparklyr.sanitize.column.names
[1] "true"

$config$`sparklyr.shell.executor-memory`
[1] "2G"

$config$`sparklyr.shell.executor-cores`
[1] "2"

$config$`sparklyr.shell.driver-memory`
[1] "2G"

$config$`sparklyr.shell.driver-cores`
[1] "2"

$config$sparklyr.shell.files
[1] "/etc/hive/conf/hive-site.xml"

$config$sparklyr.yarn.cluster.start.timeout
[1] 50

$config$spark.rpc.askTimeout
[1] "300s"

$config$spark.yarn.max.executor.failures
[1] "300"

$config$spark.sql.hive.convertMetastoreOrc
[1] "false"

$config$spark.shuffle.service.enabled
[1] "true"

$config$spark.dynamicAllocation.enabled
[1] "true"

$config$sparklyr.gateway.address
[1] "datanode.prod.net"

$spark_home
[1] "/usr/hdp/2.6.1.0-129/spark2"

$backend
A connection with                                                            
description "->datanode.prod.net:35661"
class       "sockconn"                                      
mode        "wb"                                            
text        "binary"                                        
opened      "opened"                                        
can read    "yes"                                           
can write   "yes"                                           

$monitor
A connection with                                                           
description "->datanode.prod.net:8880"
class       "sockconn"                                     
mode        "rb"                                           
text        "binary"                                       
opened      "opened"                                       
can read    "yes"                                          
can write   "yes"                                          

$output_file
[1] "/tmp/RtmpNsylIv/file4588577e3e8e_spark.log"

$spark_context
<jobj[8]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@47617748

$java_context
<jobj[9]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@7a8f660a

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection" 

Can someone look into this issue, please let me know if need further details.

Cluster Mode Code below:
-----------------------------
 # point this to your preferred hive-site.xml or use the default
my.hive.site.xml <- "/etc/hive/conf/hive-site.xml"

# name for this application in YARN
my.app.name <- "SparklyR-New"      

# how big are each of your executors
my.app.executor.cores <- "2" 
my.app.executor.memory <- "2G"

# how big is your driver
my.app.driver.cores <- "2G"   
my.app.driver.memory <- "2G"   

### Startup

# set necessary environment and library paths
Sys.setenv(JAVA_HOME="/usr/java/jdk1.7.0_15/jre") 
dy.load('/usr/local/lib/libjvm.dylib')
Sys.setenv(SPARK_HOME="/usr/hdp/current/spark2-client")
Sys.setenv(HADOOP_CONF_DIR="/usr/hdp/current/hadoop-client/conf")
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"),"R","lib"), .libPaths()))

config = list(
        "sparklyr.sanitize.column.names"="true",
        "sparklyr.shell.executor-memory"=my.app.executor.memory, 
        "sparklyr.shell.executor-cores"=my.app.executor.cores, 
        "sparklyr.shell.driver-memory"=my.app.driver.memory, 
        "sparklyr.shell.driver-cores"=my.app.driver.cores, 
        
        "sparklyr.yarn.cluster.start.timeout"=50,
        "spark.rpc.askTimeout"="300s",
        "spark.yarn.max.executor.failures"="300",
        "spark.sql.hive.convertMetastoreOrc"="false",
        "spark.shuffle.service.enabled"="true",
        "spark.dynamicAllocation.enabled"="true"
    )

# start spark cluster on YARN
sc <- sparklyr::spark_connect(
    app_name = my.app.name, 
    version="2.0.0", 
    hadoop_version="2.7", 
    master="yarn-cluster",
    spark_home="/usr/hdp/current/spark2-client",
    config=config
)

Exception:
-----------
Error: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionState':
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:983)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:110)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:109)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:878)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:980)

**Comment by Purna17** [comment]
Updated exception:

Caused by: java.lang.ClassNotFoundException: java.lang.NoClassDefFoundError: org/apache/tez/dag/api/SessionNotRunning when creating Hive client using classpath: file:/hdfs/d01/yarn/local/usercache/pmahesh/appcache/application_1523937182533_63961/container_e216_1523937182533_63961_01_000001/__app__.jar, file:/hdfs/d01/yarn/local/usercache/pmahesh/appcache/application_1523937182533_63961/container_e216_1523937182533_63961_01_000001/datanucleus-api-jdo-3.2.6.jar, file:/hdfs/d01/yarn/local/usercache/pmahesh/appcache/application_1523937182533_63961/container_e216_1523937182533_63961_01_000001/datanucleus-core-3.2.10.jar, file:/hdfs/d01/yarn/local/usercache/pmahesh/appcache/application_1523937182533_63961/container_e216_1523937182533_63961_01_000001/datanucleus-rdbms-3.2.9.jar, file:/hdfs/d01/yarn/local/usercache/pmahesh/appcache/application_1523937182533_63961/container_e216_1523937182533_63961_01_000001/, file:/hdfs/d01/yarn/local/usercache/pmahesh/filecache/48/__spark_conf__.zip/, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/htrace-core-3.1.0-incubating.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/xz-1.0.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/osgi-resource-locator-1.0.1.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/metrics-json-3.1.2.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/zookeeper-3.4.6.2.6.1.0-129.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/jsp-api-2.1.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/hadoop-annotations-2.7.3.2.6.1.0-129.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/aopalliance-repackaged-2.4.0-b34.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/arpack_combined_all-0.1.jar, file:/hdfs/d01/yarn/local/filecache/1860/spark2-hdp-yarn-archive.tar.gz/metrics-jvm-3.1.2.jar, file:/hdfs/d01/yarn/local/filecache/1860/s


Can someone help here?

What changes has to do get ride of this issue?

**Comment by Purna17** [comment]
In cluster mode hive connectivity issue, We should point to hive-site.xml located in spark2 conf. like "config$sparklyr.shell.files <- "/etc/spark/conf/hive-site.xml"

Please dont copy hive-site.xml from hive conf to hdfs conf location especially for distribution platforms (Hortonworks, Cloudera, Standalone, EMR, HDInsights.)
