### ISSUE TITLE
spark_write_table: save the result to hdfs?

### ISSUE THREAD

**Issue by yuying273** [rstudio/sparklyr#1491]
Hi,
I have a large csv file (size from 256GB to TB) on hdfs. I want to group the data by a variable and save the groupby data to hdfs. The spark_connect is from master "yarn-client" and my spark version is 2.2.0. I had error when I call 'spark_write_table'. My another question is where the data is saved after I call spark_write_table? I want to save it to hdfs, not locally. Thank you very much!

```r
library(sparklyr)
library(dplyr)
config$spark.executor.instances <- 2 
config$spark.executor.cores <- 5
config <- spark_config() 
spark_version <- "2.2.0"
sc <- spark_connect(master = "yarn-client", version = "2.2.0",config=config) 

# your reproducible example here
data_tbl = spark_read_csv(sc, "data", "/wsc/song273/pf10n/sparklyr/data/n20v4m10.csv", header = TRUE)
data_tbl
# Source:   table<data> [?? x 17]
# Database: spark_connection
#      v0     v1     v2     v3      v4     v5      v6     v7     v8      v9
#   <dbl>  <dbl>  <dbl>  <dbl>   <dbl>  <dbl>   <dbl>  <dbl>  <dbl>   <dbl>
# 1  1.76   0.400  0.979  2.24   1.87   -0.977  0.950  -0.151 -0.103  0.411 
# 2  0.334  1.49  -0.205  0.313 -0.854  -2.55   0.654   0.864 -0.742  2.27  
# 3  0.155  0.378 -0.888 -1.98  -0.348   0.156  1.23    1.20  -0.387 -0.302 
# 4 -0.438 -1.25   0.777 -1.61  -0.213  -0.895  0.387  -0.511 -1.18  -0.0282
# 5 -0.672 -0.360 -0.813 -1.73   0.177  -0.402 -1.63    0.463 -0.907  0.0519
# 6 -0.685 -0.871 -0.579 -0.312  0.0562 -1.17   0.901   0.466 -1.54   1.49  
# 7 -0.403  1.22   0.208  0.977  0.356   0.707  0.0105  1.79   0.127  0.402 
# 8  1.94  -0.414 -0.747  1.92   1.48    1.87   0.906  -0.861  1.91  -0.268 
# 9  0.376 -1.10   0.298  1.33  -0.695  -0.150 -0.435   1.85   0.672  0.407 
#10  0.676  0.577 -0.208  0.396 -1.09   -1.49   0.439   0.167  0.635  2.38  
# ... with more rows, and 7 more variables: v10 <dbl>, v11 <dbl>, v12 <dbl>,
#   v13 <dbl>, v14 <dbl>, y <dbl>, g <dbl>

## save the groupy result to file
groupdata = data_tbl %>% group_by(g)
spark_write_table(groupdata,"groupdata",mode="overwrite")
```
I have errors when I call 'spark_write_table'. My part error message is:
##################################################################################
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 14.0 failed 4 times, most recent failure: Lost task 3.3 in stage 14.0 (TID 147, wsc-b009.rcac.purdue.edu, executor 1): org.apache.spark.SparkException: Task failed while writing rows
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:272)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:191)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:190)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Mkdirs failed to create file:/home/song273/spark-warehouse/groupdata/_temporary/0/_temporary/attempt_20180514001145_0014_m_000003_3 (exists=false, cwd=file:/hadoop/datanode/d/yarn/local/usercache/song273/appcache/application_1522944155325_0266/container_1522944155325_0266_01_000002)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:455)
        at org.apach
####################################################################################

Yuying

**Comment by yuying273** [comment]
I attach my full error message:
Error: org.apache.spark.SparkException: Job aborted.
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:215)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:173)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:145)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.datasources.DataSource.writeInFileFormat(DataSource.scala:438)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.datasources.DataSource.writeInFileFormat(DataSource.scala:438)
        at org.apache.spark.sql.execution.datasources.DataSource.writeAndRead(DataSource.scala:454)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.saveDataIntoTable(createDataSourceTables.scala:198)
        at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:158)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
        at org.apache.spark.sql.DataFrameWriter.createTable(DataFrameWriter.scala:420)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:399)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:354)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sparklyr.Invoke.invoke(invoke.scala:137)
        at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
        at sparklyr.StreamHandler.read(stream.scala:66)
        at sparklyr.BackendHandler.channelRead0(handler.scala:51)
        at sparklyr.BackendHandler.channelRead0(handler.scala:4)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 14.0 failed 4 times, most recent failure: Lost task 3.3 in stage 14.0 (TID 147, wsc-b009.rcac.purdue.edu, executor 1): org.apache.spark.SparkException: Task failed while writing rows
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:272)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:191)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:190)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Mkdirs failed to create file:/home/song273/spark-warehouse/groupdata/_temporary/0/_temporary/attempt_20180514001145_0014_m_000003_3 (exists=false, cwd=file:/hadoop/datanode/d/yarn/local/usercache/song273/appcache/application_1522944155325_0266/container_1522944155325_0266_01_000002)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:455)
        at org.apach

**Comment by yuying273** [comment]
```{r}
> utils::sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /apps/wsc/openblas/0.2.19_gcc-4.8.5/lib/libopenblas_haswellp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4    sparklyr_0.8.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     dbplyr_1.2.1     pillar_1.2.2     compiler_3.4.3  
 [5] later_0.7.2      plyr_1.8.4       bindr_0.1.1      base64enc_0.1-3 
 [9] tools_3.4.3      digest_0.6.15    jsonlite_1.5     tibble_1.4.2    
[13] nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.2.0     
[17] psych_1.8.4      cli_1.0.0        shiny_1.0.5      DBI_1.0.0       
[21] rstudioapi_0.7   yaml_2.1.19      parallel_3.4.3   bindrcpp_0.2.2  
[25] withr_2.1.1      stringr_1.3.0    httr_1.3.1       rprojroot_1.3-2 
[29] grid_3.4.3       glue_1.2.0       R6_2.2.2         foreign_0.8-69  
[33] tidyr_0.8.0      purrr_0.2.4      reshape2_1.4.3   magrittr_1.5    
[37] backports_1.1.2  promises_1.0.1   htmltools_0.3.6  assertthat_0.2.0
[41] mnormt_1.5-5     mime_0.5         xtable_1.8-2     httpuv_1.4.2    
[45] config_0.3       utf8_1.1.3       stringi_1.2.2    openssl_1.0.1   
[49] lazyeval_0.2.1   broom_0.4.4      crayon_1.3.4    

```

**Comment by yuying273** [comment]
The hadoop version is:
#############################################################################
Hadoop 2.7.4
Subversion Unknown -r Unknown
Compiled by jyepesri on 2017-10-25T20:39Z
Compiled with protoc 2.5.0
From source with checksum 50b0468318b4ce9bd24dc467b7ce1148
This command was run using /usr/lib/hadoop/share/hadoop/common/hadoop-common-2.7.4.jar
#############################################################################

**Comment by kevinykuo** [comment]
Could you try writing just a few rows of the data instead of all of it?

**Comment by harryprince** [comment]
@yuying273  why save data after `group by`? it is a little bit wired. Maybe you need to save csv file into different `partition`, and don't use `group by ` function.

**Comment by javierluraschi** [comment]
This looks like a write permission or configuration issue in general. Grouping and saving works just fine, but does not have the effect you intend, as mentioned, you probably want to use `partition` to split data more explicitly. 

The issue you are hitting is more likely to be a Spark configuration issue, see for instance https://stackoverflow.com/questions/35778653/spark-saveastextfile-results-in-mkdirs-failed-to-create-for-half-of-the-direct

You might want to consider using `hdfs://` in your path, as in:

```
spark_read_csv(sc, "data", "hdfs://wsc/song273/pf10n/sparklyr/data/n20v4m10.csv", header = TRUE)
```

Going to close this one but feel free to reopen a new one if you are still experiencing issues.
