### ISSUE TITLE
Trouble with spark_read_csv() on YARN 

### ISSUE THREAD

**Issue by corridordigital** [rstudio/sparklyr#1497]
Hello everyone, 

  First of all, great job with sparklyr, it feels good using Spark in a familiar context :+1: 

I am having trouble with using sparklyr from RStudio Server in distributed mode (YARN).
Connecting to the Spark cluster works, but I can't read a CSV file from local or HDFS storage using spark_read_csv(). I don't have this problem when in local mode. Also, the problem does not occur when creating a Spark DataFrame from an existing R Object through copy_to().   

Here's a reproducible example : 

```R
write.csv2(iris, "iris.csv", row.names = FALSE)
spark_read_csv(sc
                     ,path ="file://./iris.csv"
                     ,name = "irs"
                     ,infer_schema = TRUE
                     ,header = TRUE
                     ,delimiter = ';')
```

Returns this Scala (?) error : 

```Scala
Error: java.lang.IllegalArgumentException: invalid method csv for object 176/org.apache.spark.sql.DataFrameReader fields 1 selected 0
	at sparklyr.Invoke.invoke(invoke.scala:163)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

I am using Spark 2.1.0, and here's the sessionInfo : 

```R
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4    sparklyr_0.8.3 rlang_0.2.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     dbplyr_1.2.1     pillar_1.2.2     later_0.7.2      plyr_1.8.4       bindr_0.1.1      base64enc_0.1-3  tools_3.3.3      digest_0.6.15    jsonlite_1.5    
[11] tibble_1.4.2     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  psych_1.8.4      shiny_1.0.5      DBI_1.0.0        rstudioapi_0.7   curl_3.1         yaml_2.1.19     
[21] parallel_3.3.3   bindrcpp_0.2.2   withr_2.1.2      httr_1.3.1       stringr_1.2.0    rappdirs_0.3.1   hms_0.4.2        rprojroot_1.3-2  grid_3.3.3       glue_1.2.0      
[31] R6_2.2.2         foreign_0.8-70   readr_1.1.1      tidyr_0.8.0      purrr_0.2.4      reshape2_1.4.3   magrittr_1.5     backports_1.1.2  promises_1.0.1   htmltools_0.3.6 
[41] assertthat_0.2.0 mnormt_1.5-5     mime_0.5         xtable_1.8-2     httpuv_1.4.3     config_0.3       stringi_1.1.5    openssl_1.0.1    lazyeval_0.2.1   broom_0.4.4  
 ```
I cannot understand the underlying issus from the error log, and I couldn't find help online or in the package documentation. Do you have any idea how I can solve this ?

Thanks a lot !

**Comment by harryprince** [comment]
read from csv somethings bugy, I always load from Hive.

**Comment by corridordigital** [comment]
Hello Harry, 
  There seems to be an issue indeed, but I suspect it may be just about YARN or Livy configuration. spark_read_csv() works fine in local mode.

**Comment by harryprince** [comment]
@corridordigital if spark launched by yarn-cluster, the spark node will read the csv file at remote worker machine instead of your driver local machine.

So, to make sure everything goes well, I suggest you pass the file to hdfs without these annoying things.

**Comment by corridordigital** [comment]
Hi @harryprince. I get the exact same problem with that file on HDFS. 
Any idea ?
Thanks

**Comment by javierluraschi** [comment]
@corridordigital you sure you are using Spark 2.X? What is the value from `spark_version(sc)`? The error seems to point out that `csv` is not a member of `dataframe` which got added in Spark 2.X. My guess is that there might be a SPARK_HOME version mismatch so I would double check this SPARK_HOME points to the correct path.

**Comment by revaldozen** [comment]
I also have the same problem, the file is already in HDFS.. 
```
sc <- spark_connect(master = "yarn-client", version="2.2.0", spark_home = '/usr/hdp/current/spark-client/')

spark_read_csv(sc=sc
               ,path ="hdfs:///user/mdmbigdata1/mobilewalla_100K.csv"
               ,name ="FinStatement"
               ,infer_schema = TRUE
               ,header = FALSE
)
```

reproduce this error
rror: java.lang.IllegalArgumentException: invalid method csv for object 25/org.apache.spark.sql.DataFrameReader fields 1 selected 0
	at sparklyr.Invoke.invoke(invoke.scala:163)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
