### ISSUE TITLE
Feature: be able to overwrite parquet file

### ISSUE THREAD

**Issue by koaning** [rstudio/sparklyr#152]
When I am saving over an old parquet file I get an error.

```
Error: org.apache.spark.sql.AnalysisException: path file:/Users/code/Development/warcraft-avatar-history/wowah_data.parquet already exists.;
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation.run(InsertIntoHadoopFsRelation.scala:76)
    at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
    at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
    at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
    at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
    at org.apache.spark.sql.execution.QueryExecuti
```

The error is a good thing! One should not accidentally overwrite a parquet file. But the scala and pyspark versions of spark do allow for a setting to `overwrite` the original file where the user consciously needs to set a flag that it is alright to overwrite a file. Would this be an appropriate feature?

**Comment by kevinykuo** [comment]
@koaning this should be supported now via `mode = "overwrite"` in `spark_write_parquet()`.
