### ISSUE TITLE
Cache a table: need a name registered

### ISSUE THREAD

**Issue by koaning** [rstudio/sparklyr#154]
If I want to cache a table in memory, the `sparklyr` functionality is a bit different than in SparkR. It seems like we need to first name a table before we can cache it. The function call `tbl_cache(sc, name, force = TRUE)` requires a name so I'll first assign one via `sdf_register`. 

So I try the following code : 

```
ddf_iris <- copy_to(sc, iris) %>% sdf_register("foofoo")
tbl_cache(sc, "foofoo")

```

And this fails, giving me this error: 

```
Error: org.apache.spark.sql.catalyst.analysis.NoSuchTableException
	at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
	at org.apache.spark.sql.hive.client.ClientInterface$$anonfun$getTable$1.apply(ClientInterface.scala:122)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.sql.hive.client.ClientInterface$class.getTable(ClientInterface.scala:122)
	at org.apache.spark.sql.hive.client.ClientWrapper.getTable(ClientWrapper.scala:61)
	at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:391)
	at org.apache.spark.sql.hive.HiveContext$$anon$2.org$apache$spark$sql$catalyst$analysis$OverrideCatalog$$super$lookupRelation(HiveContext.scala:457)
	at org.apache.spark.sql.catalyst.analysis.OverrideCatalog$class.lookupRelation(Catalog.scala:161)
	at org.apache.spark.sql.hive.HiveContext$$anon$2.lookupRelation(HiveContext.scala:457)
	at org.apache.spark.sql.SQLContext.table(SQLContext.scala:83
```

Any idea why the table name is not being registered? I am running this in local mode.

**Comment by koaning** [comment]
This error went away when I went for an upgrade of `sparklyr`.
