### ISSUE TITLE
AGAIN: Failed to launch Spark shell. Ports file does not exist.

### ISSUE THREAD

**Issue by SebastianFinkel** [rstudio/sparklyr#155]
I know similar issues have been posted before, however, none of the solutions applied to my system configuration. I use RStudio, latest Preview Release (Version 0.99.1259) and have installed the latest sparklyr package (Version 0.3.1). I installed Spark 2.0.0 with Hadoop 2.7.  (System: Mac OS 10.11.6)
```
sc <- spark_connect(master = "local")
Fehler in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
  Failed to launch Spark shell. Ports file does not exist.
    Path: /Users/sfinkel/Library/Caches/spark/spark-2.0.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --packages, 'com.databricks:spark-csv_2.11:1.3.0','com.amazonaws:aws-java-sdk-pom:1.10.34', '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0.0.jar', /var/folders/vx/bqgwvbzd5j7clnp823h6k4g80000gn/T//RtmplQ5CZL/file7d174d46b4b1.out
    
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at
```
Would be very grateful for any help. Thanks!

**Comment by SebastianFinkel** [comment]
Seemed to be a version problem with JAVA or something.
