### ISSUE TITLE
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 107.0 failed 1 times, most recent failure: Lost task 0.0 in stage 107.0 (TID 2294, localhost, executor driver): java.lang.OutOfMemoryError: Unable to acquire 16384 bytes of memory, got 0

### ISSUE THREAD

**Issue by yogi-srcc-iimb** [rstudio/sparklyr#1567]
# Reporting an Issue with sparklyr

Hi Team , 

I am need of your inputs as I am struggling with this issues for 2-3 weeks now , and did not get anything on internet to resolve my issue that I am getting in sparklyr. I just I get solution this time .

I have executed code given below, it is throwing error. I couldn't figure out the reason

> config <- spark_config()
> config$'spark.dynamicAllocation.enabled'<- "true"
> spark_cluster<-spark_connect(master = 'local', config = config,version = "2.1.0")
>mydata<-spark_read_csv(spark_cluster,name = "rd_1",columns = columns,path = "MAF_MAY2017_APR2018.csv",header = F,delimiter = ",")

#some codes for K-means cluster n data manipulations etc

> data4<-data3%>%
+   group_by(customer,location_id)%>%
+   mutate(Delta_Visits_Pct= ((Visits-lag(Visits))/Visits)*100,
+          Delta_Avg_Duration_Pct=round(((Avg_Duration-lag(Avg_Duration))/Avg_Duration)*100,2),
+          Delta_Visits=Visits-lag(Visits),
+          Delta_Avg_Duration=round(Avg_Duration-lag(Avg_Duration),2),
+          total_visits=sum(Visits,na.rm = T),total_avg_duration=sum(Avg_Duration,na.rm = T),
+          Delta_Visits_Total_Pct=round((Visits/total_visits)*100,2),
+          Delta_Avg_Duration_Total_Pct=round((Avg_Duration/total_avg_duration)*100,2))%>%
+   select(-c(total_visits,total_avg_duration))

> data4<-select(data4,location_id,local_date,Visits,Delta_Visits,Delta_Visits_Pct,Delta_Visits_Total_Pct,Avg_Duration,Delta_Avg_Duration,Delta_Avg_Duration_Pct,Delta_Visits_Total_Pct)
> data4<-distinct(data4)
> data4

This is the error that i got

Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 107.0 failed 1 times, most recent failure: Lost task 0.0 in stage 107.0 (TID 2294, localhost, executor driver): java.lang.OutOfMemoryError: Unable to acquire 16384 bytes of memory, got 0
	at org.apache.spark.memory.MemoryConsumer.allocateArray(MemoryConsumer.java:100)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeInMemorySorter.<init>(UnsafeInMemorySorter.java:124)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.<init>(UnsafeExternalSorter.java:154)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.create(UnsafeExternalSorter.java:121)
	at org.apache.spark.sql.execution.window.WindowExec$$anonfun$14$$anon$1.fetchNextPartition(WindowExec.scala:340)
	at org.apache.spark.sql.execution.window.WindowExec$$anonfun$14$$anon$1.next(WindowExec.scala:391)
	at org.apache.spark.sql.execution.window.WindowExec$$anonfun$14$$anon$1.next(WindowExec.scala:290)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys1$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:333)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2778)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2351)
	at sparklyr.Utils$.collect(utils.scala:196)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke.invoke(invoke.scala:137)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Unable to acquire 16384 bytes of memory, got 0
	at org.apache.spark.memory.MemoryConsumer.allocateArray(MemoryConsume

utils::sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252 LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2    sparklyr_0.8.4    ggpubr_0.1.6      data.table_1.11.2 magrittr_1.5      qcc_2.7           forcats_0.3.0     stringr_1.3.1     dplyr_0.7.5      
[10] purrr_0.2.4       readr_1.1.1       tidyr_0.8.1       tibble_1.4.2      tidyverse_1.2.1   factoextra_1.0.5  ggplot2_2.2.1     cluster_2.0.7-1   lubridate_1.7.4  

loaded via a namespace (and not attached):
 [1] ggrepel_0.8.0    Rcpp_0.12.17     lattice_0.20-35  utf8_1.1.4       assertthat_0.2.0 rprojroot_1.3-2  digest_0.6.15    psych_1.8.4      mime_0.5        
[10] R6_2.2.2         cellranger_1.1.0 plyr_1.8.4       backports_1.1.2  httr_1.3.1       pillar_1.2.3     rlang_0.2.0      lazyeval_0.2.1   readxl_1.1.0    
[19] rstudioapi_0.7   config_0.3       foreign_0.8-70   munsell_0.4.3    shiny_1.1.0      broom_0.4.4      compiler_3.5.0   httpuv_1.4.3     modelr_0.1.2    
[28] pkgconfig_2.0.1  base64enc_0.1-3  mnormt_1.5-5     htmltools_0.3.6  openssl_1.0.1    tidyselect_0.2.4 withr_2.1.2      crayon_1.3.4     dbplyr_1.2.1    
[37] later_0.7.2      rappdirs_0.3.1   MASS_7.3-49      grid_3.5.0       nlme_3.1-137     jsonlite_1.5     xtable_1.8-2     gtable_0.2.0     DBI_1.0.0       
[46] scales_0.5.0     cli_1.0.0        stringi_1.1.7    reshape2_1.4.3   promises_1.0.1   xml2_1.2.0       tools_3.5.0      glue_1.2.0       hms_0.4.2       
[55] parallel_3.5.0   yaml_2.1.19      colorspace_1.3-2 rvest_0.3.2      bindr_0.1.1      haven_1.1.1

**Comment by javierluraschi** [comment]
After,

```
#some codes for K-means cluster n data manipulations etc
```

I would try caching `data3` into memory with something like `data <- data3 %>% compute()`.

You might also need more memory to perform this operation, how big is `data3`? How much memory is available in your cluster?

**Comment by yogi-srcc-iimb** [comment]
data3 is 100 GB .....  I am using below settings in EC2 with 30 GB RAM...... Could you suggest changes w.r.t to memory allocation etc ?

# Set driver and executor memory allocations
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-XX:MaxPermSize=30G"
config$spark.executor.cores	<- 3
config$spark.memory.fraction <- 0.9
config$'sparklyr.shell.driver-memory' <- "20G"
config$'sparklyr.shell.executor-memory'<- "8G"
config$'spark.yarn.executor.memoryOverhead' <- "2g"
config$spark.dynamicAllocation.enabled <- "false"

#Spark Connection
sc<-spark_connect(master = "local" , config=config)

This is the error I am getting 

“sparkContext was shut down” 

Any suggestions as to how to handle big data(200 GB+ files) with 30 GB RAM ec2 AWS ?
