### ISSUE TITLE
Error sparklyr when using copy_to() function

### ISSUE THREAD

**Issue by lobowadai** [rstudio/sparklyr#1586]
# Reporting an Issue with sparklyr - copy_to() or spark_read_csv failed on my system
Dear all,

I just have installed sparklyr on my local machine by running devtools::install_github("rstudio/sparklyr").
After, I ran spark_install() to have a cluster on my local machine.
I'm struggling reading a csv data or copying an R dataframe.
My code to copy a table is as follows:

```r
## Liabraries ##
library(dplyr)
library(sparklyr)
## Connect to spark cluster
sc <- spark_connect("local")
### Load data ###
train <- read.csv("C:/Users/samba/Documents/Work/Kaggle/santander-value-prediction-challenge/Data/train.csv")

train_tbl <- copy_to(sc,"train")

src_tbls(sc)
```

I'am getting the following error:

```r
Error: java.lang.IllegalArgumentException: Invaid type null
	at sparklyr.SQLUtils$.getSQLDataType(sqlutils.scala:61)
	at sparklyr.SQLUtils$.createStructField(sqlutils.scala:66)
	at sparklyr.SQLUtils.createStructField(sqlutils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Unknown Source)
In addition: Warning message:
In as.data.frame.vector(x, ..., nm = nm) :
  'row.names' is not a character vector of length 1 -- omitting it. Will be an error!
```

My spark_config is at follows:

```r
> spark_config()
$`spark.env.SPARK_LOCAL_IP.local`
[1] "127.0.0.1"

$sparklyr.csv.embedded
[1] "^1.*"

$sparklyr.cores.local
[1] 8

$spark.sql.shuffle.partitions.local
[1] 8

attr(,"config")
[1] "default"
attr(,"file")
[1] "C:\\Users\\samba\\Documents\\R\\win-library\\3.5\\sparklyr\\conf\\config-template.yml"
```
utils::sessionInfo() is giving:

```r
R version 3.5.1 (2018-07-02)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.6         sparklyr_0.8.4.9004

loaded via a namespace (and not attached):
 [1] DBI_1.0.0        withr_2.1.2      git2r_0.21.0     promises_1.0.1   devtools_1.13.6 
 [6] tidyselect_0.2.4 rprojroot_1.3-2  lattice_0.20-35  foreign_0.8-70   config_0.3      
[11] pkgconfig_2.0.1  compiler_3.5.1   stringr_1.3.1    parallel_3.5.1   xtable_1.8-2    
[16] Rcpp_0.12.17     shiny_1.1.0      plyr_1.8.4       httr_1.3.1       tools_3.5.1     
[21] openssl_1.0.1    memoise_1.1.0    nlme_3.1-137     broom_0.4.4      R6_2.2.2        
[26] bindrcpp_0.2.2   dbplyr_1.2.1     bindr_0.1.1      purrr_0.2.5      assertthat_0.2.0
[31] curl_3.2         digest_0.6.15    mime_0.5         stringi_1.1.7    rstudioapi_0.7  
[36] reshape2_1.4.3   backports_1.1.2  htmltools_0.3.6  grid_3.5.1       glue_1.2.0      
[41] httpuv_1.4.4.1   rlang_0.2.1      psych_1.8.4      magrittr_1.5     rappdirs_0.3.1  
[46] lazyeval_0.2.1   yaml_2.1.19      later_0.7.3      tidyr_0.8.1      pillar_1.2.3    
[51] base64enc_0.1-3  mnormt_1.5-5     jsonlite_1.5     tibble_1.4.2 
```
Finally, I'm using Windows 7 in 32 bits.

Thank you for your help.

Wadai

**Comment by ciasom** [comment]
train_tbl <- copy_to(sc, train)
No quotes,  or
train_tbl <- copy_to(sc, df=train, name="train")

**Comment by lobowadai** [comment]
Yes!! IT works! Newbie mistake!!

Thanks Ciasom!!
