### ISSUE TITLE
Livy Proxy

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1595]

**Comment by javierluraschi** [comment]
Note: Reported through support that when TLS is enforced, `sparklyr` fails to connect with TLS enabled.

```
sparklyr: Session (####) is starting under #### port #### Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef; at sparklyr.Utils$.portIsAvailable(utils.scala:435) at sparklyr.Backend.init(backend.scala:158)
```

Related: https://mapr.com/docs/52/Spark/ConfigureSparkOnYarn_Encryption.html
