### ISSUE TITLE
handle model predictions with categorical variables

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#161]
E.g.

```
> library(sparklyr)
> library(dplyr)
> sc <- spark_connect(master = "local")
> train <- iris
> valid <- iris[-c(1:50), ]
> iris_train <- copy_to(sc, train, overwrite = T)
> iris_valid <- copy_to(sc, valid, overwrite = T)
> ml1 <- ml_linear_regression(iris_train, Sepal_Length ~ Species)
> sdf_predict(ml1, iris_valid)
Error: java.lang.IllegalArgumentException: Field "Speciesversicolor" does not exist.
	at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:212)
	at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:212)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at org.apache.spark.sql.types.StructType.apply(StructType.scala:211)
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$2.apply(VectorAssembler.scala:55)
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$2.apply(VectorAssembler.scala:54)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.Traversable
```

The problem here is that, because `versicolor` is not detected as a level in the prediction data set, a dummy variable is not created for it on the fly and prediction fails. We should save the detected levels from the original dataset and use that when constructing dummy variables.

**Comment by kevinushey** [comment]
This should be resolved now; the levels from the trained dataset are used when constructing dummy variables for the test dataset.
