### ISSUE TITLE
Using a new spark dataframe in spark_apply

### ISSUE THREAD

**Issue by songpaper** [rstudio/sparklyr#1613]
I am calculating using two spark data frames 'df_join_sdf' and 'dqbew_sub_sdf'.

and, 
I want to select the value in the first row of  'dqbew_sub_sdf'  
after selecting the filter that matches the elements of each row in 'df_join_sdf'

I want to know if 'dqbew_sub_sdf' can not be used in the spakr_apply function, or if the usage is wrong.

Below is the actual execution code, sessioninfo, and error log.

thank you.

---------------------------------------------------------------------------
```r
df_join_sdf<-copy_to(sc, df_join_temp, name = spark_table_name(substitute(df_join_temp)), overwrite = T)
dqbew_sub_sdf<-copy_to(sc, dqbew_sub, name = spark_table_name(substitute(dqbew_sub)), overwrite = T)

  price<-df_join_sdf %>% 
              select(SBDKZ, IDNRK, PSPID_A, WERKS) %>%
              spark_apply(function(data){
              
              apply(data, 1, function(x){
                if(is.na(x[1])) x[1]<-"0"
                if(as.numeric(x[1])==1){
                  t1<-dqbew_sub_sdf %>%
                    filter(BWKEY==as.character(x[4])) %>%  
                    filter(SOBKZ=="Q") %>%   
                    filter(PSPNR==as.character(x[3])) %>%  
                    filter(MATNR==as.character(x[2])) %>%  
                    select(VERPR, PEINH) %>%
                    head(1) 
                }else if(as.numeric(x[1])==2){
                  t1<-dmbew_sub %>%
                    filter(BWKEY==as.character(x[4])) %>%
                    filter(MATNR==as.character(x[2])) %>%
                    select(VERPR, PEINH) %>%
                    head(1)
                }else{
                  t1<-data.frame("VERPR"=0, "PEINH"=0)
                }
                  t1
              })  
                  
            })
```
---------------------------------------------------------------------------

sessionInfo()
R version 3.4.1 (--)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.8.4    bindrcpp_0.2      data.table_1.11.4 dplyr_0.7.4      
[5] Rook_1.1-1        RJSONIO_1.3-0     Cairo_1.5-6      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     dbplyr_1.2.1     pillar_1.2.3     compiler_3.4.1  
 [5] later_0.7.3      plyr_1.8.4       bindr_0.1        base64enc_0.1-3 
 [9] tools_3.4.1      digest_0.6.12    jsonlite_1.5     tibble_1.4.2    
[13] nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.2.1     
[17] psych_1.8.4      cli_1.0.0        shiny_1.1.0      DBI_1.0.0       
[21] rstudioapi_0.7   yaml_2.1.15      parallel_3.4.1   withr_2.1.0     
[25] stringr_1.2.0    httr_1.3.1       tidyselect_0.2.4 rprojroot_1.3-2 
[29] grid_3.4.1       glue_1.2.0       R6_2.2.2         foreign_0.8-69  
[33] reshape2_1.4.2   tidyr_0.8.1      purrr_0.2.4      magrittr_1.5    
[37] backports_1.1.2  codetools_0.2-15 promises_1.0.1   htmltools_0.3.6 
[41] mnormt_1.5-5     assertthat_0.2.0 mime_0.5         xtable_1.8-2    
[45] httpuv_1.4.3     config_0.3       brew_1.0-6       utf8_1.1.4      
[49] stringi_1.1.6    openssl_0.9.9    lazyeval_0.2.1   broom_0.4.4     
[53] crayon_1.3.4    

---------------------------------------------------------------------------

Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 31.0 failed 4 times, most recent failure: Lost task 0.3 in stage 31.0 (TID 62, dn05.hhi.co.kr, executor 1): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:123)
	at sparklyr.WorkerRDD$$anon$2.run(workerrdd.scala:97)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1587)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1586)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1586)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1820)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2048)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2067)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1358)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:137)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:123)
	at sparklyr.WorkerRDD$$anon$2.run(workerrdd.scala:97)

**Comment by javierluraschi** [comment]
No, `dqbew_sub_sdf` can't be used inside `spark_apply()` since `spark_apply()` only performs operations with the function context, no external context is passed. So mostly, `spark_apply()` transform a data frame (`df_join_sdf %>% select(SBDKZ, IDNRK, PSPID_A, WERKS)` for your code snippet) and cannot access other data frames.

If the Spark data frame you want to use inside `spark_apply()` is small enough, a few MBs in size, you should be able to pass it in the `spark_apply()` `context` parameter by collecting it first from Spark. Alternatively, you can crate a joined data frame from the two you need and then perform an operation over the joined data frame inside `spark_apply()`.
