### ISSUE TITLE
ml_survival_regression fit generates java lang error

### ISSUE THREAD

**Issue by zsharpm** [rstudio/sparklyr#1627]
The ml_survival_regression function generates a java lang error.  I've included the expected output from the survival `survreg` function.

See also: https://spark.apache.org/docs/latest/ml-classification-regression.html#survival-regression

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sparklyr)
library(survival)

spark_version <- "2.1.0"

sc <- spark_connect(master = "local", version = spark_version)

ov <- copy_to(sc, ovarian, "ovarian", overwrite = TRUE)

ov
#> # Source:   table<ovarian> [?? x 6]
#> # Database: spark_connection
#>    futime fustat   age resid_ds    rx ecog_ps
#>     <dbl>  <dbl> <dbl>    <dbl> <dbl>   <dbl>
#>  1     59      1  72.3        2     1       1
#>  2    115      1  74.5        2     1       1
#>  3    156      1  66.5        2     1       2
#>  4    421      0  53.4        2     2       1
#>  5    431      1  50.3        2     1       1
#>  6    448      0  56.4        1     1       2
#>  7    464      1  56.9        2     2       2
#>  8    475      1  59.9        2     2       2
#>  9    477      0  64.2        2     1       1
#> 10    563      1  55.2        1     2       2
#> # ... with more rows

# expected output
survreg(Surv(futime, fustat) ~ ecog.ps + rx, data = ovarian)
#> Call:
#> survreg(formula = Surv(futime, fustat) ~ ecog.ps + rx, data = ovarian)
#> 
#> Coefficients:
#> (Intercept)     ecog.ps          rx 
#>   6.8966931  -0.3850425   0.5286455 
#> 
#> Scale= 0.8838731 
#> 
#> Loglik(model)= -97.1   Loglik(intercept only)= -98
#>  Chisq= 1.74 on 2 degrees of freedom, p= 0.419 
#> n= 26

# error
ml_survival_regression(ov, Surv(futime, fustat) ~ ecog_ps + rx)
#> Error: java.lang.IllegalArgumentException: Field "censor" does not exist.
#>  at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:264)
#>  at org.apache.spark.sql.types.StructType$$anonfun$apply$1.apply(StructType.scala:264)
#>  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
#>  at scala.collection.AbstractMap.getOrElse(Map.scala:59)
#>  at org.apache.spark.sql.types.StructType.apply(StructType.scala:263)
#>  at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:40)
#>  at org.apache.spark.ml.regression.AFTSurvivalRegressionParams$class.validateAndTransformSchema(AFTSurvivalRegression.scala:109)
#>  at org.apache.spark.ml.regression.AFTSurvivalRegression.validateAndTransformSchema(AFTSurvivalRegression.scala:128)
#>  at org.apache.spark.ml.regression.AFTSurvivalRegression.transformSchema(AFTSurvivalRegression.scala:285)
#>  at org.apache.spark.ml.Pipeline$$anonfun$transformSchema$4.apply(Pipeline.scala:184)
#>  at org.apache.spark.ml.Pipeline$$anonfun$transformSchema$4.apply(Pipeline.scala:184)
#>  at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
#>  at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
#>  at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
#>  at org.apache.spark.ml.Pipeline.transformSchema(Pipeline.scala:184)
#>  at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
#>  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:136)
#>  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:96)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#>  at java.lang.reflect.Method.invoke(Unknown Source)
#>  at sparklyr.Invoke.invoke(invoke.scala:137)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Unknown Source)

# error
ml_survival_regression(ov, Surv(futime, fustat) ~ ecog_ps + rx, censor_col = "fustat")
#> Error: java.lang.IllegalArgumentException: Could not parse formula: Surv(futime, fustat) ~ ecog_ps + rx
#>  at org.apache.spark.ml.feature.RFormulaParser$.parse(RFormulaParser.scala:200)
#>  at org.apache.spark.ml.feature.RFormula.fit(RFormula.scala:138)
#>  at org.apache.spark.ml.feature.RFormula.fit(RFormula.scala:74)
#>  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
#>  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
#>  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
#>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
#>  at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
#>  at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
#>  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
#>  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:96)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#>  at java.lang.reflect.Method.invoke(Unknown Source)
#>  at sparklyr.Invoke.invoke(invoke.scala:137)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
#>  at sparklyr.StreamHandler.read(stream.scala:66)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:51)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:4)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Unknown Source)

devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/Chicago             
#>  date     2018-08-02
#> Packages -----------------------------------------------------------------
#>  package    * version date       source        
#>  assertthat   0.2.0   2017-04-11 CRAN (R 3.5.1)
#>  backports    1.1.2   2017-12-13 CRAN (R 3.5.0)
#>  base       * 3.5.1   2018-07-02 local         
#>  base64enc    0.1-3   2015-07-28 CRAN (R 3.5.0)
#>  bindr        0.1.1   2018-03-13 CRAN (R 3.5.1)
#>  bindrcpp     0.2.2   2018-03-29 CRAN (R 3.5.1)
#>  broom        0.5.0   2018-07-17 CRAN (R 3.5.1)
#>  cli          1.0.0   2017-11-05 CRAN (R 3.5.1)
#>  compiler     3.5.1   2018-07-02 local         
#>  config       0.3     2018-03-27 CRAN (R 3.5.1)
#>  crayon       1.3.4   2017-09-16 CRAN (R 3.5.1)
#>  datasets   * 3.5.1   2018-07-02 local         
#>  DBI          1.0.0   2018-05-02 CRAN (R 3.5.1)
#>  dbplyr       1.2.2   2018-07-25 CRAN (R 3.5.1)
#>  devtools     1.13.6  2018-06-27 CRAN (R 3.5.1)
#>  digest       0.6.15  2018-01-28 CRAN (R 3.5.1)
#>  dplyr      * 0.7.6   2018-06-29 CRAN (R 3.5.1)
#>  evaluate     0.11    2018-07-17 CRAN (R 3.5.1)
#>  fansi        0.2.3   2018-05-06 CRAN (R 3.5.1)
#>  glue         1.3.0   2018-07-17 CRAN (R 3.5.1)
#>  graphics   * 3.5.1   2018-07-02 local         
#>  grDevices  * 3.5.1   2018-07-02 local         
#>  grid         3.5.1   2018-07-02 local         
#>  htmltools    0.3.6   2017-04-28 CRAN (R 3.5.1)
#>  httpuv       1.4.5   2018-07-19 CRAN (R 3.5.1)
#>  httr         1.3.1   2017-08-20 CRAN (R 3.5.1)
#>  jsonlite     1.5     2017-06-01 CRAN (R 3.5.1)
#>  knitr        1.20    2018-02-20 CRAN (R 3.5.1)
#>  later        0.7.3   2018-06-08 CRAN (R 3.5.1)
#>  lattice      0.20-35 2017-03-25 CRAN (R 3.5.1)
#>  lazyeval     0.2.1   2017-10-29 CRAN (R 3.5.1)
#>  magrittr     1.5     2014-11-22 CRAN (R 3.5.1)
#>  Matrix       1.2-14  2018-04-13 CRAN (R 3.5.1)
#>  memoise      1.1.0   2017-04-21 CRAN (R 3.5.1)
#>  methods    * 3.5.1   2018-07-02 local         
#>  mime         0.5     2016-07-07 CRAN (R 3.5.0)
#>  nlme         3.1-137 2018-04-07 CRAN (R 3.5.1)
#>  openssl      1.0.2   2018-07-30 CRAN (R 3.5.1)
#>  parallel     3.5.1   2018-07-02 local         
#>  pillar       1.3.0   2018-07-14 CRAN (R 3.5.1)
#>  pkgconfig    2.0.1   2017-03-21 CRAN (R 3.5.1)
#>  promises     1.0.1   2018-04-13 CRAN (R 3.5.1)
#>  purrr        0.2.5   2018-05-29 CRAN (R 3.5.1)
#>  R6           2.2.2   2017-06-17 CRAN (R 3.5.1)
#>  rappdirs     0.3.1   2016-03-28 CRAN (R 3.5.1)
#>  Rcpp         0.12.18 2018-07-23 CRAN (R 3.5.1)
#>  rlang        0.2.1   2018-05-30 CRAN (R 3.5.1)
#>  rmarkdown    1.10    2018-06-11 CRAN (R 3.5.1)
#>  rprojroot    1.3-2   2018-01-03 CRAN (R 3.5.1)
#>  rstudioapi   0.7     2017-09-07 CRAN (R 3.5.1)
#>  shiny        1.1.0   2018-05-17 CRAN (R 3.5.1)
#>  sparklyr   * 0.8.4   2018-05-25 CRAN (R 3.5.1)
#>  splines      3.5.1   2018-07-02 local         
#>  stats      * 3.5.1   2018-07-02 local         
#>  stringi      1.1.7   2018-03-12 CRAN (R 3.5.0)
#>  stringr      1.3.1   2018-05-10 CRAN (R 3.5.1)
#>  survival   * 2.42-3  2018-04-16 CRAN (R 3.5.1)
#>  tibble       1.4.2   2018-01-22 CRAN (R 3.5.1)
#>  tidyr        0.8.1   2018-05-18 CRAN (R 3.5.1)
#>  tidyselect   0.2.4   2018-02-26 CRAN (R 3.5.1)
#>  tools        3.5.1   2018-07-02 local         
#>  utf8         1.1.4   2018-05-24 CRAN (R 3.5.1)
#>  utils      * 3.5.1   2018-07-02 local         
#>  withr        2.1.2   2018-03-15 CRAN (R 3.5.1)
#>  xtable       1.8-2   2016-02-05 CRAN (R 3.5.1)
#>  yaml         2.2.0   2018-07-25 CRAN (R 3.5.1)
```

Created on 2018-08-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by kmezhoud** [comment]
Hi,
Did you see the example [here](https://rdrr.io/cran/sparklyr/man/ml_aft_survival_regression.html)?
Karim

**Comment by zsharpm** [comment]
The updated example in the documentation now functions as expected.  The problem was related to specifying a Surv object like this:

`ml_survival_regression(ov, Surv(futime, fustat) ~ ecog_ps + rx, censor_col = "fustat")`

Instead of:

`ml_aft_survival_regression(ov, futime ~ ecog_ps + rx, censor_col = "fustat")`
