### ISSUE TITLE
implement compute in dplyr

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#165]
implement `compute()` in dplyr using `saveAsTable`. See for instance: http://stackoverflow.com/questions/37050828/save-spark-rdd-to-hive-table

**Comment by ElianoMarques** [comment]
Friends @javierluraschi , @jjallaire do you have any plans on this one? Currently for certain ML procedures we have to use pure R in partitions and/ or node and we have to jump to SparkR for that, then ensemble the model. I didn't look at the sparkR code so i'm not sure how hard is to port it over, not sure if you have an opinion on that? I think this feature would be great!

**Comment by javierluraschi** [comment]
@ElianoMarques `compute()` has a very specific meaning in dplyr: "compute forces computation of lazy tbls, leaving data in the remote source". For the most part, `compute()` already works like this (closing this issue):

```{r}
iris_tbl <- copy_to(sc, iris)
iris_tbl %>% filter(Petal_Length == 1.4) %>% compute("length-1-4")

# print cached table:
tbl(sc, "length-1-4")
```

However, I believe you are referring to parallel computation as in https://github.com/rstudio/sparklyr/issues/81, correct? In which case, we don't have plans to actively start development here yet. Could we move this discussion to https://github.com/rstudio/sparklyr/issues/81 and get some examples on the kind of R partitions that you are blocked from computing?

**Comment by ElianoMarques** [comment]
@javierluraschi I was. I added an example there.

**Comment by yarrick19** [comment]
@javierluraschi 

I'm running into an issue with a script I'm writing where it looks like `compute()` isn't forcing computation of a table.  After executing the `compute` method, when filtering on the subsequent table I'm running into errors that appear to be referencing some lazy evaluation of a join that was done prior to running `compute`.  From the documentation, it doesn't seem like this should happen (unless I'm misinterpreting something).  

I was able to recreate it with a generic script which is below so you can see the behavior.

```
library(sparklyr)
library(dplyr)
library(titanic)


# ----------------------------
# Connect to Spark
# ----------------------------
Sys.setenv(SPARK_HOME = "/usr/lib/spark")

sc <- spark_connect(master = "yarn-client", version = '2.0.1')
# spark_disconnect(sc)


# ----------------------------
# Import Data
# ----------------------------
titanic_tbl <- copy_to(sc, df = titanic_train, name = "titanic", overwrite = TRUE)

passenger_exclude <- data.frame(passenger_excl = c(1, 5, 7))
passenger_exclude_tbl <- copy_to(sc, df = passenger_exclude, name ="pass_exc", overwrite = TRUE)


# ----------------------------
# Prepare dataset and train model
# ----------------------------
titanic_final_tbl <- titanic_tbl %>%
    mutate(Age = ifelse(is.na(Age), mean(Age), Age)) %>%
    select(PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare)

model_frmla <- formula(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare)

# Train model
model <- ml_logistic_regression(titanic_final_tbl, model_frmla)


# ----------------------------
# Eliminate some records that are not needed
# ----------------------------
titanic_test_clean_tbl <- left_join(titanic_final_tbl, passenger_exclude_tbl,  by = c("PassengerId" = "passenger_excl")) %>%
    sdf_register("titanic_test_join")

titanic_test_final_tbl <- titanic_test_clean_tbl %>%
    filter(is.na(passenger_excl)) %>%  #exclude any record that was present in passenger_exclude_tbl
    sdf_register("titanic_test_final")


# ----------------------------
# Score Test file
# ----------------------------
score_tbl <- sdf_predict(model, titanic_test_final_tbl) %>%
    select(PassengerId, prediction, probability) %>%
    sdf_register("score_output")


# Check Score Numbers
score_tbl %>%
    filter(prediction == 1) %>%
    group_by(prediction) %>%
    summarise(count = n())


# ----------------------------
# Results in error which mentions join... assume this has to do with lazy evaluation.
# Lets try using compute() first
# ----------------------------

compute(titanic_test_final_tbl, "compute_test")
compute_tbl <- tbl(sc, "compute_test")


# Score Test file

score_tbl <- sdf_predict(model, compute_tbl) %>%
    select(PassengerId, prediction, probability) %>%
    sdf_register("score_output")


# Check Score Numbers
score_tbl %>%
    filter(prediction == 1) %>%
    group_by(prediction) %>%
    summarise(count = n())


# ----------------------------
# Still get the error... it looks like compute() is not really forcing the lazy eval to calc
# Lets try caching the table
# ----------------------------

tbl_cache(sc, name = "titanic_test_final")

# Score Test file

score_tbl <- sdf_predict(model, titanic_test_final_tbl) %>%
    select(PassengerId, prediction, probability) %>%
    sdf_register("score_output")


# Check Score Numbers
score_tbl %>%
    filter(prediction == 1) %>%
    group_by(prediction) %>%
    summarise(count = n())


# ----------------------------
# Caching seems to force the table to calculate.  
# Based on documentation, it looks like compute() should be doing this as well but its not
# ----------------------------
```

Error message generated when running the "Check Score Numbers" section"

```
Error: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$4: (vector) => double)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1072)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.eval(Expression.scala:408)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$.org$apache$spark$sql$catalyst$optimizer$EliminateOuterJoin$$canFilterOutNull(joins.scala:109)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$$anonfun$7.apply(joins.scala:118)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$$anonfun$7.apply(joins.scala:118)
	at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:93)
	at scala.collection.immutable.List.exists(List.scala:84)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$.org$apache$spark$sql$catalyst$optimizer$EliminateOuterJoin$$buildNewJoinType(joins.scala:118)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$$anonfun$apply$2.applyOrElse(joins.scala:133)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$$anonfun$apply$2.applyOrElse(joins.scala:131)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:321)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:319)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:284)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:268)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$.apply(joins.scala:131)
	at org.apache.spark.sql.catalyst.optimizer.EliminateOuterJoin$.apply(joins.scala:98)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:76)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:83)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2555)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Handler.handleMethodCall(handler.scala:124)
	at sparklyr.Handler.channelRead0(handler.scala:69)
	at sparklyr.Handler.channelRead0(handler.scala:15)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$1: (vector) => vector)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1072)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:90)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:88)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1069)
	... 76 more
Caused by: org.apache.spark.SparkException: Failed to execute user defined function($anonfun$3: (struct<Pclass_double_vecAssembler_b24c727be0db:double,col2:double,col3:double,SibSp_double_vecAssembler_b24c727be0db:double,Parch_double_vecAssembler_b24c727be0db:double,col6:double>) => vector)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1072)
	at org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$2.apply(ScalaUDF.scala:90)
	at org.apache.spark.sql.catalyst.exp
```

Using sparklyr version 0.4.30 on AWS EMR.
