### ISSUE TITLE
ML Pipeline Error: org.apache.spark.SparkException: Exception thrown in awaitResult: 

### ISSUE THREAD

**Issue by ashishrjha** [rstudio/sparklyr#1658]
# Problem description below

I have a spark set up in AWS EMR. Spark version is 2.3.1. I have one master node and two worker nodes.
I am using sparklyr to run xgboost model for a classification problem. My job ran for over six hours and then threw the error report that I have given after the code below.  Error was thrown at the line where I am attempting model fit cv_model <- ml_fit(cv, trainData_tbl). Everything else before this ran just fine. 

This is the first time I am attempting a spark job. I will be grateful for your help. It might even be a simple syntax issue in the way i am defining elements of the pipeline like the grid etc. 

Regards -
Ashish
# my code 
# Start creating own pipeline below 

df <- trainData_tbl %>%
  select(Flag,
         PRED_TOTALSHIPMENTS_clean,
         Observation_Compliance_clean,
         PREDPOSTSHIP_DISCONTINUED_clean,
         OBSERVATION_COMPLIANCEGRP_catB,
         PREDICTOR_TRX_clean,
         PREDICTOR_Days_With_Supply_clean,
         PRED_LAST8WKSHIPMENT_clean,
         PREDPOSTSHIP_DENIED_FORMULARY_clean,
         PRED_LAST4WKSHIPMENT_clean,
         PREDICTOR_VRTXPARENTPBMKEY_catB,
         timeSinceLastShip_clean,
         PRED_LAST13WKDISCONTINUED_clean,
         Last6Wks_UNQ_MasterPayers_clean,
         PREDICTOR_DOT_clean,
         Predictor_UNQ_Pharmacy_clean,
         PREDICTOR_DISCON_OTHER_clean,
         PREDLAST2SHIP_DISCON_PTREQ_clean,
         OPCRatio1_clean,
         meanCompliance_clean,
         PRED_LAST4WKDENIED_STEPEDIT_clean) 

# Define the pipeline
pipeline <- ml_pipeline(sc) %>%
  ft_dplyr_transformer(
    tbl = df
  ) %>%
  ft_r_formula(Flag ~ .) %>%
  ml_gbt_classifier(type = "classification", loss_type = "logistic")

# Specify hyperparameter grid
grid <- list(
  gbt = list(
    step_size = c(0.01, 0.03),
    max_depth = c(10, 15),
    max_iter = c(750),
    min_instances_per_node = c(10),
    subsampling_rate = c(0.95)
  )
)

# Create the cross validator object
cv <- ml_cross_validator(
  sc, estimator = pipeline, estimator_param_maps = grid,
  evaluator = ml_binary_classification_evaluator(sc),
  num_folds = 2, parallelism = 2
)

# Train the models
start_time <- Sys.time()
cv_model <- ml_fit(cv, trainData_tbl) **# this is the line throwing error ---------------**
end_time <- Sys.time()
end_time - start_time
ml_validation_metrics(cv_model)

# spark error output below

Error: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:205)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4$$anonfun$6.apply(CrossValidator.scala:164)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:164)
	at org.apache.spark.ml.tuning.CrossValidator$$anonfun$4.apply(CrossValidator.scala:144)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.tuning.CrossValidator.fit(CrossValidator.scala:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:137)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11536.0 failed 1 times, most recent failure: Lost task 0.0 in stage 11536.0 (TID 348215, localhost, executor driver): java.lang.StackOverflowError
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1604)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2068)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2286)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2210)

# R Console output below 
Time difference of 6.577518 hours
Error: Unexpected state in sparklyr backend, terminating connection: failed to invoke spark command
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/36/temp_shuffle_772bd4b2-04a3-46d8-ae86-bf02946bac08
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/36/temp_shuffle_772bd4b2-04a3-46d8-ae86-bf02946bac08
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/28/temp_shuffle_f812a0bf-8cfe-430a-a203-b6c2e0026a0d
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/28/temp_shuffle_f812a0bf-8cfe-430a-a203-b6c2e0026a0d
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/0e/temp_shuffle_0b69a66d-7eb8-457c-a7b3-0f8281fe0a4b
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/0e/temp_shuffle_0b69a66d-7eb8-457c-a7b3-0f8281fe0a4b
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/29/temp_shuffle_a991df56-04fa-44d7-b552-ad874655fded
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/29/temp_shuffle_a991df56-04fa-44d7-b552-ad874655fded
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/0f/temp_shuffle_2f8885d9-5f67-4d67-949f-4c06709900b5
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/0f/temp_shuffle_2f8885d9-5f67-4d67-949f-4c06709900b5
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/27/temp_shuffle_6edac86a-1577-4228-8cc5-75b83bdd2743
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/27/temp_shuffle_6edac86a-1577-4228-8cc5-75b83bdd2743
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/3f/temp_shuffle_45770d99-5dcb-469b-9799-fb521ef036bd
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/3f/temp_shuffle_45770d99-5dcb-469b-9799-fb521ef036bd
18/08/31 16:17:27 ERROR DiskBlockObjectWriter: Uncaught exception while reverting partial writes to file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/39/temp_shuffle_91a45137-8f46-42c4-843e-0ff8c66fdef4
18/08/31 16:17:27 ERROR BypassMergeSortShuffleWriter: Error while deleting file /mnt/tmp/blockmgr-5da57dc0-adac-4c9b-a05a-d448b5136d28/39/temp_shuffle_91a45137-8f46-42c4-843e-0ff8c66fdef4
18/08/31 16:17:27 ERROR Executor: Exception in task 13.0 in stage 11537.0 (TID 348219)
18/08/31 16:17:27 INFO Executor: Not reporting error to driver during JVM shutdown.
18/08/31 16:17:27 INFO MemoryStore: MemoryStore cleared
18/08/31 16:17:27 INFO BlockManager: BlockManager stopped
18/08/31 16:17:27 INFO BlockManagerMaster: BlockManagerMaster stopped
18/08/31 16:17:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
18/08/31 16:17:27 INFO SparkContext: Successfully stopped SparkContext
18/08/31 16:17:27 INFO ShutdownHookManager: Shutdown hook called
18/08/31 16:17:27 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-7fcd4d34-feb6-48b8-a59e-da950c382b75
18/08/31 16:17:27 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-41f2f771-994c-4db5-bee8-f90a8baa8a54

# sessioInfo output below 
 sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.6    sparklyr_0.8.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     compiler_3.4.1   pillar_1.3.0     later_0.7.3      dbplyr_1.2.2     bindr_0.1.1      base64enc_0.1-3 
 [8] tools_3.4.1      digest_0.6.16    jsonlite_1.5     tibble_1.4.2     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.2 
[15] rlang_0.2.2      cli_1.0.0        shiny_1.1.0      DBI_1.0.0        rstudioapi_0.7   parallel_3.4.1   yaml_2.2.0      
[22] bindrcpp_0.2.2   withr_2.1.2      httr_1.3.1       rprojroot_1.3-2  grid_3.4.1       tidyselect_0.2.4 glue_1.3.0      
[29] R6_2.2.2         fansi_0.3.0      purrr_0.2.5      tidyr_0.8.1      magrittr_1.5     backports_1.1.2  promises_1.0.1  
[36] htmltools_0.3.6  assertthat_0.2.0 mime_0.5         xtable_1.8-2     httpuv_1.4.5     config_0.3       utf8_1.1.4      
[43] openssl_1.0.2    lazyeval_0.2.1   broom_0.5.0      crayon_1.3.4

**Comment by realviacauchy** [comment]
Did you figure out where the problem was originating from?

**Comment by kevinykuo** [comment]
@ashishrjha could you try with a smaller grid and data first? E.g.

```
grid <- list(
  gbt = list(
    step_size = c(0.01, 0.03),
    max_depth = c(1, 5)
  )
)
```

and say 10k rows of data.

**Comment by efh0888** [comment]
@kevinykuo realize this is over a year old, but I'm running into the same exact problem described above. I'll do as you suggested and see what happens.

**Comment by efh0888** [comment]
Also, as a quick aside, what's the difference between just feeding in the data into ml_fit() already having selected the desired columns vs. putting the select in the pipeline with ft_dplyr_transformer()?

**Comment by ashishjwr** [comment]
I am also facing the same issue

**Comment by yitao-li** [comment]
@ashishjwr I think the actual useful error message is the following line _below_ the first stack trace:
`Caused by: org.apache.spark.SparkException: Job aborted due to stage failure:...`

In the original post the cause was `java.lang.StackOverflowError`. Are you sure you have the exact same cause?

Also, trying a smaller subset of the input data with the same pipeline sounds like a good first step for debugging.
