### ISSUE TITLE
Error with dplyr::sample_n function

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#167]
This code:

```
library(sparklyr)
library(dplyr)
system.time(sc <- spark_connect("local", version = "2.0.0"))
iris_tbl <- copy_to(sc, iris)
sample_data <- iris_tbl %>% sample_n(10) %>% collect
```

causes this error:
```
Error in countTotal/op$args$size : 
  non-numeric argument to binary operator
```

**Comment by kevinushey** [comment]
Resolves this particular error, but there's still something else going on with Spark 2.0.0:

```
> sample_data <- iris_tbl %>% sample_n(10) %>% collect
Error: org.apache.spark.sql.AnalysisException: Window function rownumber() requires window to be ordered, please add ORDER BY clause. For example SELECT rownumber()(value_expr) OVER (PARTITION BY window_partition ORDER BY window_ordering) from table;
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:40)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:58)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveWindowOrder$$anonfun$apply$30$$anonfun$applyOrElse$11.applyOrElse(Analyzer.scala:1804)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveWindowOrder$$anonfun$apply$30$$anonfun$applyOrElse$11.applyOrElse(Analyzer.scala:1802)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache. 
```

**Comment by MarcinKosinski** [comment]
Having the same error. With `sample_n` and `sample_frac`

**Comment by kevinushey** [comment]
FWIW you should be able to use `sdf_sample` as an alternative to `sample_frac` for the time being.
