### ISSUE TITLE
Parse exception on certain mutate Date call

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#168]
Not sure if this should work:

```
sc <- spark_connect("local", version = "1.6.1")
year <- c("2001", "2002")
df = data.frame(year) 
df_tbl <- copy_to(sc, df)
mutated <- df_tbl %>%
  mutate(year = as.Date(paste(year, '01-01', sep = '-'))) %>%
  collect
```

We get this error: 

```
Error: org.apache.spark.sql.AnalysisException: mismatched input 'AS' expecting ) near ''-'' in function specification; line 1 pos 43
    at org.apache.spark.sql.hive.HiveQl$.createPlan(HiveQl.scala:318)
    at org.apache.spark.sql.hive.ExtendedHiveQlParser$$anonfun$hiveQl$1.apply(ExtendedHiveQlParser.scala:41)
    at org.apache.spark.sql.hive.ExtendedHiveQlParser$$anonfun$hiveQl$1.apply(ExtendedHiveQlParser.scala:40)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$app
```

**Comment by javierluraschi** [comment]
No repro anymore, either fixed in Spark 2.X or in `sparklyr` itself:

```
df_tbl %>%
+     mutate(year = as.Date(paste(year, '01-01', sep = '-'))) %>%
+     collect()
# A tibble: 2 x 1
        year
       <chr>
1 2001-01-01
2 2002-01-01
```
