### ISSUE TITLE
sparklyr does not work with spark 2.3.1?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#1715]
Hello there!

I am testing the new `sparklyr 0.9.1` and it seems still not compatible with `spark 2.3.1`.

Indeed, trying to run

```
Sys.setenv(SPARK_HOME="/spark/spark-2.3.1-bin-hadoop2.6")
# connect to master
sc <- spark_connect(master = "spark://mynode", config = config)
```
 
gives:
```

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (xxxx): Gateway in localhost:8880 did not respond.
    Path: /spark/spark-2.3.1-bin-hadoop2.6/bin/spark-submit
    Parameters: --driver-memory, 100G, --executor-memory, 100G, --num-executors, 90, --class, sparklyr.Shell, '/myhomeR/x86_64-ubuntu14-linux-gnu-library/3.5/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 67557
    Log: /tmp/RtmpEbncHW/_spark.log


---- Output Log ----
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

the same setup worked without issues with `spark 2.2.1`. What do you think?
Thanks!

**Comment by javierluraschi** [comment]
@randomgambit looks related to https://community.cloudera.com/t5/Advanced-Analytics-Apache-Spark/Spark2-Error-deploying-and-status-ok/td-p/61657, has JAVA_HOME changed in the cluster and is it correctly set? What's the output of `java -version`?

**Comment by randomgambit** [comment]
@javierluraschi yes, `JAVA_HOME` is now pointing to java 8+ in the `spark-envs.sh` .. SHould I specify the `JAVA_HOME` from my R code as well?

**Comment by randomgambit** [comment]
was some `JAVA_HOME` issue...
