### ISSUE TITLE
spark_connect fails when h2o package is loaded

### ISSUE THREAD

**Issue by fzenoni** [rstudio/sparklyr#1717]
I am trying to reproduce the example exposed [here](https://github.com/rstudio/sparklyr#using-h2o).

Connecting to a local spark instance works. That is, the following correctly works:
```r
library(sparklyr)
spark_install(version = '2.1.0')
sc <- spark_connect(master = "local", version = '2.1.0')
```

This on the other hand, fails
```r
library(rsparkling)
library(sparklyr)
library(h2o)

sc <- spark_connect(master = "local", version = "2.1.0")
```
This is the output:
```
Spark version 2.1 detected. Will call latest Sparkling Water version 2.1.40
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (73190): Gateway in localhost:8880 did not respond.
    Path: /home/fzenoni/spark/spark-2.1.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.1.40','ai.h2o:sparkling-water-ml_2.11:2.1.40','ai.h2o:sparkling-water-repl_2.11:2.1.40','no.priv.garshol.duke:duke:1.2', '/home/fzenoni/R/x86_64-pc-linux-gnu-library/3.4/sparklyr/java/sparklyr-2.1-2.11.jar', 8880, 73190
    Log: /tmp/RtmpL39wCO/file6fda55800316_spark.log


---- Output Log ----
	org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v201005082020 from central in [default]
	org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 from central in [default]
	org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 from central in [default]
	org.fusesource.leveldbjni#leveldbjni-all;1.8 from central in [default]
	org.hamcrest#hamcrest-core;1.3 from central in [default]
	org.javassist#javassist;3.18.2-GA from central in [default]
	org.joda#joda-convert;1.7 from central in [default]
	org.kohsuke#libpam4j;1.8 from central in [default]
	org.mapdb#mapdb;0.9.9 from central in [default]
	org.mortbay.jetty#jetty;6.1.26 from central in [default]
	org.mortbay.jetty#jetty-sslengine;6.1.26 from central in [default]
	org.mortbay.jetty#jetty-util;6.1.26 from central in [default]
	org.mortbay.jetty#servlet-api;2.5-20081211 from central in [default]
	org.slf4j#slf4j-api;1.7.10 from central in [default]
	org.slf4j#slf4j-log4j12;1.7.10 from central in [default]
	org.tukaani#xz;1.0 from central in [default]
	org.xerial.snappy#snappy-java;1.0.4.1 from central in [default]
	xerces#xercesImpl;2.9.1 from central in [default]
	xml-apis#xml-apis;1.3.04 from central in [default]
	xmlenc#xmlenc;0.52 from central in [default]
	:: evicted modules:
	joda-time#joda-time;2.9.9 by [joda-time#joda-time;2.10] in [default]
	com.github.fommil.netlib#core;1.1 by [com.github.fommil.netlib#core;1.1.2] in [default]
	commons-logging#commons-logging;1.1.1 by [commons-logging#commons-logging;1.2] in [default]
	org.apache.httpcomponents#httpclient;4.1.2 by [org.apache.httpcomponents#httpclient;4.2.5] in [default]
	org.apache.httpcomponents#httpcore;4.1.2 by [org.apache.httpcomponents#httpcore;4.2.5] in [default]
	com.google.guava#guava;11.0.2 by [com.google.guava#guava;16.0.1] in [default]
	commons-logging#commons-logging;1.1.3 by [commons-logging#commons-logging;1.2] in [default]
	org.apache.commons#commons-math3;3.1.1 by [org.apache.commons#commons-math3;3.3] in [default]
	javax.xml.bind#jaxb-api;2.2.2 by [javax.xml.bind#jaxb-api;2.3.0] in [default]
	javax.xml.stream#stax-api;1.0-2 transitively in [default]
	javax.activation#activation;1.1 transitively in [default]
	com.google.code.gson#gson;2.2.4 by [com.google.code.gson#gson;2.6.2] in [default]
	org.apache.httpcomponents#httpclient;4.2.5 by [org.apache.httpcomponents#httpclient;4.3.6] in [default]
	org.apache.httpcomponents#httpcore;4.2.5 by [org.apache.httpcomponents#httpcore;4.3.3] in [default]
	org.apache.httpcomponents#httpcore;4.2.4 by [org.apache.httpcomponents#httpcore;4.1.2] in [default]
	commons-codec#commons-codec;1.6 by [commons-codec#commons-codec;1.4] in [default]
	joda-time#joda-time;2.8.1 by [joda-time#joda-time;2.10] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |  165  |   1   |   0   |   17  ||  147  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: ai.h2o#mojo2-runtime-api;0.13.2

	==== local-m2-cache: tried

	  file:/home/fzenoni/.m2/repository/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  file:/home/fzenoni/.m2/repository/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

	==== local-ivy-cache: tried

	  /home/fzenoni/.ivy2/local/ai.h2o/mojo2-runtime-api/0.13.2/ivys/ivy.xml

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  /home/fzenoni/.ivy2/local/ai.h2o/mojo2-runtime-api/0.13.2/jars/mojo2-runtime-api.jar

	==== central: tried

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.pom

	  -- artifact ai.h2o#mojo2-runtime-api;0.13.2!mojo2-runtime-api.jar:

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime-api/0.13.2/mojo2-runtime-api-0.13.2.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: ai.h2o#mojo2-runtime-api;0.13.2: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: ai.h2o#mojo2-runtime-api;0.13.2: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1078)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:296)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:160)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

The same occurs for other Spark versions, but I am unable to install 2.3.2 from `spark_install`.

```r
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.453)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       Europe/Brussels             
 date     2018-10-16                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version    date       source                                
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.4)                        
 backports     1.1.2      2017-12-13 CRAN (R 3.4.4)                        
 base        * 3.4.4      2018-04-21 local                                 
 base64enc     0.1-3      2015-07-28 CRAN (R 3.4.4)                        
 bindr         0.1.1      2018-03-13 CRAN (R 3.4.4)                        
 bindrcpp      0.2.2      2018-03-29 CRAN (R 3.4.4)                        
 bitops        1.0-6      2013-08-17 CRAN (R 3.4.4)                        
 broom         0.5.0      2018-07-17 CRAN (R 3.4.4)                        
 compiler      3.4.4      2018-04-21 local                                 
 config        0.3        2018-03-27 CRAN (R 3.4.4)                        
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.4)                        
 datasets    * 3.4.4      2018-04-21 local                                 
 DBI           1.0.0      2018-05-02 CRAN (R 3.4.4)                        
 dbplyr        1.2.2      2018-07-25 CRAN (R 3.4.4)                        
 devtools      1.13.6     2018-06-27 CRAN (R 3.4.4)                        
 digest        0.6.18     2018-10-10 CRAN (R 3.4.4)                        
 dplyr         0.7.6      2018-06-29 CRAN (R 3.4.4)                        
 forge         0.1.0      2018-08-31 CRAN (R 3.4.4)                        
 glue          1.3.0      2018-07-17 CRAN (R 3.4.4)                        
 graphics    * 3.4.4      2018-04-21 local                                 
 grDevices   * 3.4.4      2018-04-21 local                                 
 grid          3.4.4      2018-04-21 local                                 
 h2o         * 3.20.0.9   2018-10-16 local                                 
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.4)                        
 htmlwidgets   1.3        2018-09-30 CRAN (R 3.4.4)                        
 httpuv        1.4.5      2018-07-19 CRAN (R 3.4.4)                        
 httr          1.3.1      2017-08-20 CRAN (R 3.4.4)                        
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.4)                        
 later         0.7.5      2018-09-18 CRAN (R 3.4.4)                        
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.2)                        
 lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.4)                        
 magrittr      1.5        2014-11-22 CRAN (R 3.4.4)                        
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.4)                        
 methods     * 3.4.4      2018-04-21 local                                 
 mime          0.6        2018-10-05 CRAN (R 3.4.4)                        
 nlme          3.1-131    2017-02-06 CRAN (R 3.4.2)                        
 openssl       1.0.2      2018-07-30 CRAN (R 3.4.4)                        
 parallel      3.4.4      2018-04-21 local                                 
 pillar        1.3.0      2018-07-14 CRAN (R 3.4.4)                        
 pkgconfig     2.0.2      2018-08-16 CRAN (R 3.4.4)                        
 promises      1.0.1      2018-04-13 CRAN (R 3.4.4)                        
 purrr         0.2.5      2018-05-29 CRAN (R 3.4.4)                        
 r2d3          0.2.2      2018-05-30 CRAN (R 3.4.4)                        
 R6            2.3.0      2018-10-04 CRAN (R 3.4.4)                        
 rappdirs      0.3.1      2016-03-28 CRAN (R 3.4.4)                        
 Rcpp          0.12.19    2018-10-01 CRAN (R 3.4.4)                        
 RCurl         1.95-4.11  2018-07-15 CRAN (R 3.4.4)                        
 rlang         0.2.2      2018-08-16 CRAN (R 3.4.4)                        
 rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.4)                        
 rsparkling  * 0.2.10     2018-10-16 Github (h2oai/sparkling-water@77adad7)
 rstudioapi    0.8        2018-10-02 CRAN (R 3.4.4)                        
 shiny         1.1.0      2018-05-17 CRAN (R 3.4.4)                        
 sparklyr    * 0.9.1.9000 2018-10-16 Github (rstudio/sparklyr@5febe9a)     
 stats       * 3.4.4      2018-04-21 local                                 
 tibble        1.4.2      2018-01-22 CRAN (R 3.4.4)                        
 tidyr         0.8.1      2018-05-18 CRAN (R 3.4.4)                        
 tidyselect    0.2.5      2018-10-11 CRAN (R 3.4.4)                        
 tools         3.4.4      2018-04-21 local                                 
 utils       * 3.4.4      2018-04-21 local                                 
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                        
 xtable        1.8-3      2018-08-29 CRAN (R 3.4.4)                        
 yaml          2.2.0      2018-07-25 CRAN (R 3.4.4)
```

**Comment by fzenoni** [comment]
I duplicated this issue in a more relevant place: https://github.com/h2oai/sparkling-water/issues/960
