### ISSUE TITLE
dplyr::copy_to spark reactive Table using Shiny 

### ISSUE THREAD

**Issue by kmezhoud** [rstudio/sparklyr#1800]
Dear All,
I am not sure if My question will be solved by Shiny or sparlyr experts.
I would like to save table in spark local server using shiny App.
1- I can connect with action button
2- Disconnect when shiny windows is closed

3- But I can't save the displayed table to spark using dplyr::copy_to
Here a running example. UNCOMMENT the line 
```r
#Studies_tbl <- dplyr::copy_to(global_var$sc, Studies, overwrite = TRUE)
```
 to see the error message. 
Thanks
Karim

```r
library(shiny)
library(cgdsr)
library(dplyr)
library(sparklyr)
library(DT)
library(shinyjs)
jscode <- "shinyjs.closeWindow = function() { window.close(); }"

ui <- function(){
  sidebarLayout(
  sidebarPanel(

    # used to stop shiny when windows is closed
    useShinyjs(),
    extendShinyjs(text = jscode, functions = c("closeWindow")),

    actionButton("close", "Close window & disconnect"),
    actionButton("connect", "Connect to spark"),

    checkboxInput('buttonID', label = "save stable to spark"),
    verbatimTextOutput("Saved")
  ),
  mainPanel(
  DT::dataTableOutput(outputId = "StudiesTable")
  )
  )
}
server <- function(input, output, session){
  global_var <- reactiveValues()

  ## connect to cgdsr server
  cgds <- cgdsr::CGDS("http://www.cbioportal.org/public-portal/")
  ## get Studies
  shiny::withProgress(message = 'Loading Studies from cgdsr server...', value = 1, {
  Studies<- cgdsr::getCancerStudies(cgds)
  })


  # render table of Studies
  output$StudiesTable <- DT::renderDataTable({
    table <- DT::datatable(Studies, filter = list(position = "top", clear = FALSE, plain = TRUE),
                           rownames = FALSE, style = "bootstrap", escape = FALSE,
                          class = "compact",
                           options = list(
                            #ajax = list(url = action),
                             search = list(search = "",regex = TRUE),
                             columnDefs = list(list(className = 'dt-center', targets = "_all")),
                             autoWidth = FALSE,
                             processing = FALSE,
                             pageLength = 10,
                             lengthMenu = list(c(10, 25, 50, -1), c('10','25','50','All'))
                           )
    )
    return(table)
  })

  ##  Reactive checkBox to save Studies table to spark local server
  output$Saved <- renderText({ 
    if(input$buttonID && !is.null(global_var$sc)){
    #Studies_tbl <- dplyr::copy_to(global_var$sc, Studies, overwrite = TRUE)
    }
    ## print value of checkBox
    input$buttonID
    })

  ## connect to spark  
  observeEvent(input$connect, {
    shiny::withProgress(message = 'Connecting to Spark local server...', value = 1, {
      sc <- spark_connect(master = "local")
      ## get sc as global variable to use it when we want to disconnect
      global_var[["sc"]] <- sc
    })
  })


  ## disconnect spark if shiny is closed  
  observeEvent(input$close, {
    js$closeWindow()
    stopApp()
    ## disconnect spark is already connected
    if(!is.null(global_var$sc)){
    spark_disconnect(global_var$sc)
    }
  })


}
shinyApp(ui, server)
```

**Comment by kmezhoud** [comment]
```
Error : java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toIndexedSeq(TraversableOnce.scala:300)
	at scala.collection.AbstractIterator.toIndexedSeq(Iterator.scala:1336)
	at sparklyr.Utils$.createDataFrameFromCsv(utils.scala:362)
	at sparklyr.Utils.createDataFrameFromCsv(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by kmezhoud** [comment]
The App works normally with other DataFrames. 
The Studies DataFrame has text with hypertext, like this

[The Cancer Genome Atlas](https://cancergenome.nih.gov/) (TCGA) Colorectal Cancer project. 
[Nature 2012. Raw data via the TCGA Data Portal](https://tcga-data.nci.nih.gov/docs/publications/coadread_2012/).
