### ISSUE TITLE
stream_render.Rd examples do not run.

### ISSUE THREAD

**Issue by lgongmsft** [rstudio/sparklyr#1805]
The following repro is from example(topic='stream_render', package='sparklyr').
It seems that write.csv() writes to local file system but stream_read_csv() by default reads from HDFS.

> library(sparklyr)
> sc <- spark_connect(master = "local")
> spark_version(sc)

[1] '2.3.1'

> dir.create("iris-in")
> write.csv(iris, "iris-in/iris.csv", row.names = FALSE)
>
> stream <- stream_read_csv(sc, "iris-in/") %>% stream_write_csv("iris-out/")

Error: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://mssql-master-pool-0.service-master-pool:9000/root/iris-in;
        at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:715)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:388)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:596)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:473)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sparklyr.Invoke.invoke(invoke.scala:139)
        at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
        at sparklyr.StreamHandler.read(stream.scala:66)
        at sparklyr.BackendHandler.channelRead0(handler.scala:51)
        at sparklyr.BackendHandler.channelRead0(handler.scala:4)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

>
> #stream_render(stream)
>
> #stream_stop(stream)
>
> utils::sessionInfo()

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /opt/mssql/mlservices/runtime/R/lib/libRblas.so
LAPACK: /opt/mssql/mlservices/runtime/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] survival_2.41-3      bindrcpp_0.2.2       sparklyr_0.9.3
 [4] SparkR_2.3.1         RevoUtilsMath_10.0.1 RevoUtils_10.0.9
 [7] RevoMods_11.0.0      RevoScaleR_9.4.6     lattice_0.20-35
[10] rpart_4.1-13

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0             dbplyr_1.2.2           compiler_3.4.4
 [4] pillar_1.3.0           later_0.7.5            bindr_0.1.1
 [7] r2d3_0.2.2             base64enc_0.1-3        iterators_1.0.9
[10] tools_3.4.4            digest_0.6.18          nlme_3.1-131.1
[13] jsonlite_1.5           mrupdate_1.0.1         tibble_1.4.2
[16] pkgconfig_2.0.2        rlang_0.3.0.1          Matrix_1.2-12
[19] foreach_1.4.5          cli_1.0.1              shiny_1.2.0
[22] DBI_1.0.0              CompatibilityAPI_1.1.0 rstudioapi_0.8
[25] parallel_3.4.4         yaml_2.2.0             withr_2.1.2
[28] httr_1.3.1             dplyr_0.7.8            rappdirs_0.3.1
[31] htmlwidgets_1.3        tidyselect_0.2.5       rprojroot_1.3-2
[34] grid_3.4.4             glue_1.3.0             forge_0.1.0
[37] R6_2.2.2               fansi_0.4.0            tidyr_0.8.2
[40] purrr_0.2.5            magrittr_1.5           splines_3.4.4
[43] backports_1.1.2        codetools_0.2-15       promises_1.0.1
[46] htmltools_0.3.6        assertthat_0.2.0       mime_0.6
[49] xtable_1.8-3           httpuv_1.4.5           config_0.3
[52] utf8_1.1.4             openssl_1.1            lazyeval_0.2.1
[55] broom_0.5.0            crayon_1.3.4
>

**Comment by lgongmsft** [comment]
It seems that the following Rd examples also have the same issue:
    example(topic='stream_view', package='sparklyr')
    example(topic='stream_write_json', package='sparklyr')
    example(topic='stream_write_memory', package='sparklyr')
    example(topic='stream_write_text', package='sparklyr')
