### ISSUE TITLE
Paste/Paste0 doesn't work 

### ISSUE THREAD

**Issue by cantaldenosregions** [rstudio/sparklyr#1819]
I have the following spark dataframe (sdf):

id_op  (type = chr) "id1", "id1", "id1","id2", "id2", ...
word  (type = chr)  "w1", "w2", "w3", "w1", "w2", "w3", ...

Which i obtained by "exploding / splitting" a String column.

I would like to obtain the following sdf:  
  id_op      word
1   id1  w1 w2 w3
2   id2  w1 w2 w3

I am able to do it using dplyr with a local df, with the following codes:

1st option:
------------
df <- df %>%
  group_by(id_op,  word)%>%
  arrange(id_op) %>%
  summarise(clean = paste0(word, collapse=" "))

2nd option:
-------------
words.sdf <- words.sdf %>%
  aggregate(id_op ~ word, paste, collapse = " ")

But when i try it on a sparkdf, it yields this : 

Error: org.apache.spark.sql.catalyst.parser.ParseException: 
extraneous input 'AS' expecting {')', ',', '.', '[', 'OR', 'AND', 'IN', NOT, 'BETWEEN', 'LIKE', RLIKE, 'IS', EQ, '<=>', '<>', '!=', '<', LTE, '>', GTE, '+', '-', '*', '/', '%', 'DIV', '&', '|', '^', STRING}(line 1, pos 63)

== SQL ==
SELECT `id_op`, `word`, CONCAT_WS(" ", `word`, ", " AS "collapse") AS `clean`
---------------------------------------------------------------^^^
FROM (SELECT *
FROM (SELECT `word` AS `word`, `id_op` AS `id_op`
FROM (SELECT *
FROM (SELECT `word`, `id_op`, sum(1.0) OVER (PARTITION BY `id_op`, `word` ROWS UNBOUNDED PRECEDING) AS `index`
FROM (SELECT  `word` AS `word`, `id_op` AS `id_op`
FROM (SELECT *
FROM (SELECT  `id_op`, `lib_ope`,, EXPLODE(SPLIT(`lib_ope`, " ")) AS `word`
FROM `sparklyr_tmp_12fd627911f22`) `zsbvyxooje`
WHERE (`word` != "")) `mvlzopltjk`) `tutpdiuxoe`) `fykysrcram`
WHERE (`index` = 1.0)) `lpouhsurdu`) `lolphnbaqd`
ORDER BY `id_op) `jsnmrghsuz`
GROUP BY `id_op`, `word`
LIMIT 25

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:217)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:114)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:68)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:637)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Then i tried to bypass the issue using ft_sql_transformer:

df <- df %>%
  arrange(id_op)%>%
  ft_sql_transformer(sql="SELECT id_op,concat_ws(' ', word) as clean 
                                        FROM __THIS__ GROUP BY  id_op, clean")

But it yields the exact same error. I've struggled with this for hours but i can't seem to find the answer. 

Thank you in advance for your answer.

**Comment by cantaldenosregions** [comment]
Answer here : https://github.com/rstudio/sparklyr/issues/736
