### ISSUE TITLE
Can't reading parquet in sparklyr.java9 (`spark_read_parquet()`)

### ISSUE THREAD

**Issue by uribo** [rstudio/sparklyr#1833]
Hi everyone,
An error occurred when an attempt to read the parquet file.
Is it only possible to lower the version of Java? I using `java 9.0.1`.

```r
library(sparklyr)
spark_version <- "2.3.2"
sc <- spark_connect(master = "local", version = spark_version)
#> Error in validate_java_version_line(master, version) : 
#>  Java 9 is currently unsupported in Spark distributions unless you manually install Hadoop 2.8 and manually configure Spark. Please consider uninstalling Java 9 and reinstalling Java 8. To override this failure set 'options(sparklyr.java9 = TRUE)'.
```

So, not connecting yet.
Next, I tried a set `options(sparklyr.java9 = TRUE)`.

```r
options(sparklyr.java9 = TRUE)
library(sparklyr)
spark_version <- "2.3.2"
sc <- spark_connect(master = "local", version = spark_version)
d <- 
  spark_read_parquet(
  sc, 
  name = "example", 
  path = "example.parquet")
```

<details>

```
Error: java.lang.IllegalArgumentException
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
	at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2073)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at sparklyr.Utils$.collectColumnString(utils.scala:44)
	at sparklyr.Utils$.collectColumn(utils.scala:58)
	at sparklyr.Utils.collectColumn(utils.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

</details>

```r
spark_config()
#> $sparklyr.java9
#> [1] TRUE
#> 
#> $spark.env.SPARK_LOCAL_IP.local
#> [1] "127.0.0.1"
#> 
#> $sparklyr.connect.csv.embedded
#> [1] "^1.*"
#> 
#> $spark.sql.catalogImplementation
#> [1] "hive"
#> 
#> $sparklyr.connect.cores.local
#> [1] 8
#> 
#> $spark.sql.shuffle.partitions.local
#> [1] 8

devtools::session_info()
```

<details>

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────
setting  value                       
version  R version 3.5.1 (2018-07-02)
os       macOS  10.14.2              
system   x86_64, darwin15.6.0        
ui       RStudio                     
language En                          
collate  ja_JP.UTF-8                 
ctype    ja_JP.UTF-8                 
tz       Asia/Tokyo                  
date     2019-01-08                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
package     * version    date       lib source                        
assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                
backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)                
base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                
bindr         0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                
bindrcpp      0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                
broom         0.5.1      2018-12-05 [1] CRAN (R 3.5.0)                
callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)                
cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                
config        0.3        2018-03-27 [1] CRAN (R 3.5.0)                
crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                
DBI           1.0.0      2018-05-02 [1] CRAN (R 3.5.0)                
dbplyr        1.2.2      2018-07-25 [1] CRAN (R 3.5.0)                
desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                
devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                
digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                
dplyr         0.7.8      2018-11-10 [1] CRAN (R 3.5.1)                
forge         0.1.0      2018-08-31 [1] CRAN (R 3.5.0)                
fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                
generics      0.0.2      2018-11-29 [1] CRAN (R 3.5.0)                
glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                
htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                
htmlwidgets   1.3        2018-09-30 [1] CRAN (R 3.5.0)                
httpuv        1.4.5.1    2018-12-18 [1] CRAN (R 3.5.0)                
httr          1.4.0      2018-12-11 [1] CRAN (R 3.5.1)                
jsonlite      1.6        2018-12-07 [1] CRAN (R 3.5.0)                
knitr       * 1.21       2018-12-10 [1] CRAN (R 3.5.1)                
later         0.7.5      2018-09-18 [1] CRAN (R 3.5.1)                
lattice       0.20-38    2018-11-04 [1] CRAN (R 3.5.0)                
lazyeval      0.2.1      2017-10-29 [1] CRAN (R 3.5.0)                
magrittr    * 1.5        2014-11-22 [1] CRAN (R 3.5.0)                
memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                
mime          0.6        2018-10-05 [1] CRAN (R 3.5.1)                
nlme          3.1-137    2018-04-07 [1] CRAN (R 3.5.1)                
openssl       1.1        2018-11-15 [1] CRAN (R 3.5.0)                
packrat       0.5.0      2018-11-14 [1] CRAN (R 3.5.1)                
pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.1)                
pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.0)                
pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.0)                
pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                
prettycode  * 1.0.2      2018-09-11 [1] CRAN (R 3.5.1)                
prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                
processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)                
promises      1.0.1      2018-04-13 [1] CRAN (R 3.5.0)                
ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)                
purrr         0.2.5      2018-05-29 [1] CRAN (R 3.5.0)                
r2d3          0.2.3      2018-12-18 [1] CRAN (R 3.5.0)                
R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                
rappdirs      0.3.1      2016-03-28 [1] CRAN (R 3.5.0)                
Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.0)                
remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.0)                
rlang         0.3.0.1    2018-10-25 [1] CRAN (R 3.5.1)                
rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                
rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.0)                
sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                
shiny         1.2.0      2018-11-02 [1] CRAN (R 3.5.0)                
sparklyr    * 0.9.3      2018-11-29 [1] CRAN (R 3.5.0)                
testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.0)                
tibble        2.0.0      2019-01-04 [1] CRAN (R 3.5.2)                
tidyr         0.8.2      2018-10-28 [1] CRAN (R 3.5.0)                
tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.0)                
usethis       1.4.0.9000 2018-09-29 [1] Github (r-lib/usethis@1e3c6a6)
withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                
xfun          0.4        2018-10-23 [1] CRAN (R 3.5.0)                
xtable        1.8-3      2018-08-29 [1] CRAN (R 3.5.0)                
yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.0)                

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

`example.parquet`'s reprex is here.

```python
# https://arrow.apache.org/docs/python/parquet.html
import pandas as pd
import numpy as np
import pyarrow as pa

df = pd.DataFrame({'one': [-1, np.nan, 2.5],
                   'two': ['foo', 'bar', 'baz'],
                   'three': [True, False, True]},
                   index=list('abc'))
table = pa.Table.from_pandas(df)

import pyarrow.parquet as pq
pq.write_table(table, 'example.parquet')
```

**Comment by javierluraschi** [comment]
Right, so currently Apache Spark does not support Java 9, since Scala did not supported either Java 9. Work is in progress and some partial attempts have been successful; however, the current recommendation is to downgrade to Java 8 when using Spark.

**Comment by uribo** [comment]
I see, thanks for the clear explanation :)
