### ISSUE TITLE
sqlContext error on Databricks

### ISSUE THREAD

**Issue by The-Dub** [rstudio/sparklyr#1870]
Hello,

We recently gave a shot at Databricks, and we are encountering a "weird" error. Sometimes (we still don't know what is triggering this, but it seems quite random), sparklyr returns the following error when dealing with data (everything worked fine before), and then the only solution is to kill the cluster and restart it (same error comes again, different notebook or user):

```
Error: java.lang.IllegalArgumentException: invalid method catalog for object 2/org.apache.spark.sql.hive.HiveContext fields 0 selected 0
	at sparklyr.Invoke.invoke(invoke.scala:165)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

In the Spark error logs, we can see the following:

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Fri Feb  1 08:23:54 2019 py4j imported
Fri Feb  1 08:23:54 2019 Python shell started with PID  21937  and guid  49dcd6c1240e4b0874aad9444f8aeff9
Fri Feb  1 08:23:54 2019 Python shell executor start
19/02/01 09:29:09 ERROR sparklyr: Gateway (65529) failed calling sql on 2
19/02/01 09:29:09 ERROR sparklyr: Gateway (65529) failed calling fit on 308
19/02/01 09:31:16 ERROR sparklyr: Gateway (65529) failed calling json on 228
19/02/01 09:31:16 ERROR sparklyr: Gateway (65529) failed calling collect on sparklyr.Utils
19/02/01 09:52:46 ERROR sparklyr: Gateway (65529) failed calling catalog on 2
19/02/01 09:52:47 ERROR sparklyr: Gateway (65529) failed calling fit on 656
19/02/01 09:55:51 ERROR sparklyr: Gateway (65529) failed calling sqlContext on 2
19/02/01 09:58:57 ERROR sparklyr: Gateway (65529) failed calling sqlContext on 2
19/02/01 09:58:57 ERROR sparklyr: Gateway (65529) failed calling collect on sparklyr.Utils
19/02/01 10:01:34 ERROR sparklyr: Gateway (65529) failed calling sqlContext on 2
19/02/01 10:15:40 ERROR sparklyr: Gateway (65529) failed calling sqlContext on 2
```

And the R session
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.9.4  DBI_1.0.0       lubridate_1.7.4 dplyr_0.7.8    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       dbplyr_1.3.0     plyr_1.8.4       pillar_1.2.1    
 [5] compiler_3.4.4   later_0.7.5      bindr_0.1.1      r2d3_0.2.3      
 [9] base64enc_0.1-3  tools_3.4.4      digest_0.6.15    lattice_0.20-35 
[13] jsonlite_1.5     tibble_1.4.2     nlme_3.1-137     pkgconfig_2.0.1 
[17] rlang_0.3.1      psych_1.8.3.3    shiny_1.2.0      rstudioapi_0.7  
[21] parallel_3.4.4   bindrcpp_0.2.2   httr_1.3.1       stringr_1.3.0   
[25] htmlwidgets_1.3  grid_3.4.4       rprojroot_1.3-2  tidyselect_0.2.4
[29] glue_1.2.0       forge_0.1.0      R6_2.2.2         foreign_0.8-70  
[33] reshape2_1.4.3   purrr_0.3.0      tidyr_0.8.0      SparkR_2.3.1    
[37] magrittr_1.5     backports_1.1.2  promises_1.0.1   htmltools_0.3.6 
[41] mnormt_1.5-5     assertthat_0.2.0 mime_0.5         Rserve_1.7-3    
[45] xtable_1.8-3     httpuv_1.4.5.1   stringi_1.1.7    lazyeval_0.2.1  
[49] broom_0.4.4     
```

We are working with Spark 2.3.1, scala 2.11, databricks runtime version 4.3, and r4.8xlarge as workers and master

Could that be a bug? Or is there something we are not doing properly?

Thank you for your help

Cheers,
Richard

**Comment by javierluraschi** [comment]
Which version of `sparklyr` are you using? Could you try with the latest version of `sparklyr`? A fix was put in place for Databricks that might be the same issue you experience. You can install this fix with:

```
rstudio::install_github("rstudio/sparklyr")
```

**Comment by The-Dub** [comment]
@javierluraschi I was using `sparklyr_0.9.4`, I have updated sparklyr to `sparklyr_0.9.9002`, but I'm still facing same issues:
* When reading a parquet with `spark_read_parquet`, i get the following error `java.lang.IllegalArgumentException: invalid method sqlContext for object 1/org.apache.spark.sql.hive.HiveContext fields 0 selected 0`
* When trying to load a spark model using `ml_load`, i get the following error `Error: java.lang.IllegalArgumentException: invalid method catalog for object 1/org.apache.spark.sql.hive.HiveContext fields 0 selected 0`

Plus I got the following error when building a pipeline `Error in ml_map_param_list_names(.): cannot open file '/databricks/spark/R/lib/sparklyr/R/sysdata.rdb': No such file or directory`

**Comment by falaki** [comment]
@The-Dub  We recently fixed a similar issue.  https://github.com/rstudio/sparklyr/pull/1797

Would you please verify that you install pre-release version (0.9.5). On Databricks, if you re-install an R package, you need to detach and re-attach the notebook. To double check run `sessionInfo()`
```
remotes::install_github("rstudio/sparklyr", "feature/sparklyr-0.9.5")
```

Please let us know if you still get the error.

**Comment by The-Dub** [comment]
Hi Falaki,

I'll give it a shot, but I already tried the development version (after the fix), and the issue was still present, see my previous post.

@falaki I see that you work for databricks, and look into sparkly problems with databricks. Would you be the right person to talk to about issues on Databricks?

**Comment by falaki** [comment]
Yes, if you are a paying Databricks customer you can file support tickets and our support and engineering teams will handle them.

**Comment by The-Dub** [comment]
Indeed, we are paying DB customer. 

We are still experiencing the above problems, alongside with the following error when writing parquet to s3:

```Error in handleErrors(returnStatus, conn) : 
  No status is returned. Java SparkR backend might have failed.
Calls: <Anonymous> ... <Anonymous> -> callJStatic -> invokeJava -> handleErrors```

Should we go through them, or do you need more info to work where this might be coming from?

Thank you!

**Comment by falaki** [comment]
@The-Dub yes please file a ticket directly to Databricks.

**Comment by The-Dub** [comment]
Opened a ticket with Databricks
