### ISSUE TITLE
"yarn-cluster" mode failed with "Shutdown hook called before final status was reported."

### ISSUE THREAD

**Issue by lgongmsft** [rstudio/sparklyr#1903]
The following code seems to be running fine without any error message in the R console but the state and the final status of associated app are marked as FAILED in the Yarn UI and also in the logs.  Any idea?

```r
library(sparklyr)
sc <- spark_connect(master = "yarn-cluster")
mtcars_tbl <- sdf_copy_to(sc, mtcars, overwrite = TRUE)
spark_disconnect(sc)
```
Here is the logs:

---

19/02/14 19:03:34 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/14 19:03:35 INFO client.RMProxy: Connecting to ResourceManager at mssql-master-pool-0.service-master-pool/10.244.0.143:8032
19/02/14 19:03:36 INFO yarn.Client: Requesting a new application from cluster with 2 NodeManagers
19/02/14 19:03:36 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (18432 MB per container)
19/02/14 19:03:36 INFO yarn.Client: Will allocate AM container, with 2432 MB memory including 384 MB overhead
19/02/14 19:03:36 INFO yarn.Client: Setting up container launch context for our AM
19/02/14 19:03:36 INFO yarn.Client: Setting up the launch environment for our AM container
19/02/14 19:03:36 INFO yarn.Client: Preparing resources for our AM container
19/02/14 19:03:38 INFO yarn.Client: Source and destination file systems are the same. Not copying hdfs:/spark/spark_libs.zip
19/02/14 19:03:38 INFO yarn.Client: Uploading resource file:/opt/mssql/mlservices/libraries/RServer/sparklyr/java/sparklyr-2.3-2.11.jar -> hdfs://mssql-master-pool-0.service-master-pool:9000/user/root/.sparkStaging/application_1549923079997_0130/sparklyr-2.3-2.11.jar
19/02/14 19:03:39 INFO yarn.Client: Uploading resource file:/tmp/spark-a9d3e145-79a3-4ab9-92e0-3f0686842d70/__spark_conf__3671605653590990962.zip -> hdfs://mssql-master-pool-0.service-master-pool:9000/user/root/.sparkStaging/application_1549923079997_0130/__spark_conf__.zip
19/02/14 19:03:40 INFO spark.SecurityManager: Changing view acls to: root
19/02/14 19:03:40 INFO spark.SecurityManager: Changing modify acls to: root
19/02/14 19:03:40 INFO spark.SecurityManager: Changing view acls groups to:
19/02/14 19:03:40 INFO spark.SecurityManager: Changing modify acls groups to:
19/02/14 19:03:40 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/02/14 19:03:40 INFO yarn.Client: Submitting application application_1549923079997_0130 to ResourceManager
19/02/14 19:03:40 INFO impl.YarnClientImpl: Submitted application application_1549923079997_0130
19/02/14 19:03:41 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
19/02/14 19:03:41 INFO yarn.Client:
         client token: N/A
         diagnostics: AM container is launched, waiting for AM container to Register with RM
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: default
         start time: 1550171020365
         final status: UNDEFINED
         tracking URL: http://mssql-master-pool-0.service-master-pool:8088/proxy/application_1549923079997_0130/
         user: root
19/02/14 19:03:42 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
...
19/02/14 19:03:50 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
19/02/14 19:03:51 INFO yarn.Client: Application report for application_1549923079997_0130 (state: RUNNING)
19/02/14 19:03:51 INFO yarn.Client:
         client token: N/A
         diagnostics: N/A
         ApplicationMaster host: 10.244.0.149
         ApplicationMaster RPC port: 0
         queue: default
         start time: 1550171020365
         final status: UNDEFINED
         tracking URL: http://mssql-master-pool-0.service-master-pool:8088/proxy/application_1549923079997_0130/
         user: root
19/02/14 19:03:52 INFO yarn.Client: Application report for application_1549923079997_0130 (state: RUNNING)
...
19/02/14 19:16:22 INFO yarn.Client: Application report for application_1549923079997_0130 (state: RUNNING)
19/02/14 19:16:23 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
19/02/14 19:16:23 INFO yarn.Client:
         client token: N/A
         diagnostics: [Thu Feb 14 19:16:22 +0000 2019] Application is Activated, waiting for resources to be assigned for AM.  Details : AM Partition = <DEFAULT_PARTITION> ; Partition Resource = <memory:36864, vCores:12> ; Queue's Absolute capacity = 100.0 % ; Queue's Absolute used capacity = 0.0 % ; Queue's Absolute max capacity = 100.0 % ;
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: default
         start time: 1550171020365
         final status: UNDEFINED
         tracking URL: http://mssql-master-pool-0.service-master-pool:8088/proxy/application_1549923079997_0130/
         user: root
19/02/14 19:16:24 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
...
19/02/14 19:17:27 INFO yarn.Client: Application report for application_1549923079997_0130 (state: ACCEPTED)
19/02/14 19:17:28 INFO yarn.Client: Application report for application_1549923079997_0130 (state: FAILED)
19/02/14 19:17:28 INFO yarn.Client:
         client token: N/A
         diagnostics: Application application_1549923079997_0130 failed 2 times due to AM Container for appattempt_1549923079997_0130_000002 exited with  exitCode: 1
Failing this attempt.Diagnostics: [2019-02-14 19:17:27.856]Exception from container-launch.
Container id: container_1549923079997_0130_02_000001
Exit code: 1

[2019-02-14 19:17:27.859]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for TERM
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for HUP
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for INT
19/02/14 19:16:25 INFO spark.SecurityManager: Changing view acls to: root
19/02/14 19:16:25 INFO spark.SecurityManager: Changing modify acls to: root
19/02/14 19:16:25 INFO spark.SecurityManager: Changing view acls groups to:
19/02/14 19:16:25 INFO spark.SecurityManager: Changing modify acls groups to:
19/02/14 19:16:25 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/02/14 19:16:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/14 19:16:25 INFO yarn.ApplicationMaster: Preparing Local resources
19/02/14 19:16:27 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1549923079997_0130_000002
19/02/14 19:16:27 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
19/02/14 19:16:27 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
### 19/02/14 19:17:27 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Shutdown hook called before final status was reported.)
19/02/14 19:17:27 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://mssql-master-pool-0.service-master-pool:9000/user/root/.sparkStaging/application_1549923079997_0130
19/02/14 19:17:27 INFO util.ShutdownHookManager: Shutdown hook called

[2019-02-14 19:17:27.860]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for TERM
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for HUP
19/02/14 19:16:25 INFO util.SignalUtils: Registered signal handler for INT
19/02/14 19:16:25 INFO spark.SecurityManager: Changing view acls to: root
19/02/14 19:16:25 INFO spark.SecurityManager: Changing modify acls to: root
19/02/14 19:16:25 INFO spark.SecurityManager: Changing view acls groups to:
19/02/14 19:16:25 INFO spark.SecurityManager: Changing modify acls groups to:
19/02/14 19:16:25 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/02/14 19:16:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/14 19:16:25 INFO yarn.ApplicationMaster: Preparing Local resources
19/02/14 19:16:27 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1549923079997_0130_000002
19/02/14 19:16:27 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
19/02/14 19:16:27 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
### 19/02/14 19:17:27 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Shutdown hook called before final status was reported.)
19/02/14 19:17:27 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://mssql-master-pool-0.service-master-pool:9000/user/root/.sparkStaging/application_1549923079997_0130
19/02/14 19:17:27 INFO util.ShutdownHookManager: Shutdown hook called

For more detailed output, check the application tracking page: http://mssql-master-pool-0.service-master-pool:8088/cluster/app/application_1549923079997_0130 Then click on links to logs of each attempt.
. Failing the application.
         ApplicationMaster host: N/A
         ApplicationMaster RPC port: -1
         queue: default
         start time: 1550171020365
         final status: FAILED
         tracking URL: http://mssql-master-pool-0.service-master-pool:8088/cluster/app/application_1549923079997_0130
         user: root
Exception in thread "main" org.apache.spark.SparkException: Application application_1549923079997_0130 finished with failed status
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:1165)
        at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1520)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/02/14 19:17:28 INFO util.ShutdownHookManager: Shutdown hook called
19/02/14 19:17:28 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-33521f09-2486-4d94-a1ef-43b462f2b397
19/02/14 19:17:28 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-a9d3e145-79a3-4ab9-92e0-3f0686842d70

---

Here is my sessionInfo:
```
> utils::sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /opt/mssql/mlservices/runtime/R/lib/libRblas.so
LAPACK: /opt/mssql/mlservices/runtime/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sparklyr_0.9.9006    RevoUtilsMath_10.0.1 RevoUtils_10.0.9
[4] RevoMods_11.0.0      MicrosoftML_9.4.6    RevoScaleR_9.4.6
[7] lattice_0.20-35      rpart_4.1-13

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0             compiler_3.4.4         pillar_1.3.1
 [4] later_0.7.5            dbplyr_1.3.0           bindr_0.1.1
 [7] r2d3_0.2.3             base64enc_0.1-3        iterators_1.0.9
[10] tools_3.4.4            digest_0.6.18          memoise_1.1.0
[13] jsonlite_1.6           mrupdate_1.0.1         tibble_2.0.1
[16] pkgconfig_2.0.2        rlang_0.3.1            foreach_1.4.5
[19] shiny_1.2.0            DBI_1.0.0              CompatibilityAPI_1.1.0
[22] rstudioapi_0.9.0       bindrcpp_0.2.2         withr_2.1.2
[25] httr_1.4.0             dplyr_0.7.8            devtools_1.13.5
[28] generics_0.0.2         htmlwidgets_1.3        tidyselect_0.2.5
[31] rprojroot_1.3-2        grid_3.4.4             glue_1.3.0
[34] forge_0.1.0            R6_2.3.0               purrr_0.3.0
[37] magrittr_1.5           backports_1.1.2        codetools_0.2-15
[40] promises_1.0.1         htmltools_0.3.6        assertthat_0.2.0
[43] mime_0.6               xtable_1.8-3           httpuv_1.4.5
[46] lazyeval_0.2.1         crayon_1.3.4
>
```

**Comment by benmwhite** [comment]
Does the same thing happen if you run it in "yarn-client" mode?

**Comment by lgongmsft** [comment]
No, "yarn-client" is fine.  The error message seems to be from [here](https://github.com/apache/spark/blob/a829234df35c87c169425f2c79fd1963b5420888/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala#L238) so the error might be due to terminating the application with System.exit(0).

**Comment by m-semnani** [comment]
I have the same problem, any update here?

**Comment by alexsanjoseph** [comment]
Same problem here

**Comment by orlovw** [comment]
Facing the same problem, guys
I am submitting my code via livy, if am setting livy.spark.deployMode=client everything is working like needed, but using "cluster" mode i am getting the same error like mentioned below. Also using spark-submit both client and cluster mode are working.

Very weird bug/behavior, if everyone faced the same problem please post here any researchs
Regards

**Comment by fritzratna** [comment]
> Facing the same problem, guys
> I am submitting my code via livy, if am setting livy.spark.deployMode=client everything is working like needed, but using "cluster" mode i am getting the same error like mentioned below. Also using spark-submit both client and cluster mode are working.
> 
> Very weird bug/behavior, if everyone faced the same problem please post here any researchs
> Regards

Am having the same error, did you find out how to solve it? I tried reaching out to @javierluraschi  (the maintainer of the sparklyr package) but never heard back from him

**Comment by orlovw** [comment]
> > Facing the same problem, guys
> > I am submitting my code via livy, if am setting livy.spark.deployMode=client everything is working like needed, but using "cluster" mode i am getting the same error like mentioned below. Also using spark-submit both client and cluster mode are working.
> > Very weird bug/behavior, if everyone faced the same problem please post here any researchs
> > Regards
> 
> Am having the same error, did you find out how to solve it? I tried reaching out to @javierluraschi (the maintainer of the sparklyr package) but never heard back from him

Actually it was a long time ago, right now we are submiting jobs in cluster mode using Livy without any problems, first of all check nodes logs and also livy logs. Livy didn't do any magic under the hood, it's just invoking spark-submit - you can check source code. Also check if you have set deploy mode to "cluster"(https://docs.datafabric.hpe.com/62/Livy/Configure_Livy_Spark_Modes.html)

**Comment by fritzratna** [comment]
> No, "yarn-client" is fine. The error message seems to be from [here](https://github.com/apache/spark/blob/a829234df35c87c169425f2c79fd1963b5420888/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/ApplicationMaster.scala#L238) so the error might be due to terminating the application with System.exit(0).

am having the same error, did you find out how to solve it? it is working in client mode, in cluster mode, i have to submit the job with Rscript , spark-submit returns the error you mentioned earlier. I am not using livy nor databricks nor AWS,  so any help will be appreciated @m-semnani @alexsanjoseph @lgongmsft @benmwhite
