### ISSUE TITLE
Logical filters and summaries with "%in%" fail after group_by()

### ISSUE THREAD

**Issue by benmwhite** [rstudio/sparklyr#1950]
Creating logical filters, mutated columns, or summaries with an "%in%" statement works on ungrouped Spark tables but fails for attempts with `group_by()` (EDIT: using latest CRAN versions of both `sparklyr` and `dplyr`).

Reprex setup:
```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
```

The following two examples produce the same results locally and as a Spark table:
```{r}
mtcars %>%
  filter(cyl %in% c(4, 6))

mtcars %>%
  sdf_import(sc) %>%
  filter(cyl %in% c(4, 6))
```

 `mutate()` and `transmute()` calls involving "%in%" also work.

However, grouped operations involving "%in%" fail with Spark tables.

local data frame:
```{r}
mtcars %>%
  group_by(cyl) %>%
  summarise(has_1 = 1 %in% vs)
```

output:
```
# A tibble: 3 x 2
    cyl has_1
  <dbl> <lgl>
1     4 TRUE 
2     6 TRUE 
3     8 FALSE
```
Spark table:
```
mtcars %>%
  sdf_import(sc) %>%
  group_by(cyl) %>%
  summarise(has_1 = 1 %in% vs)
```

error message:
```
Error: org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input '`vs`' expecting <EOF>(line 1, pos 21)

== SQL ==
SELECT `cyl`, 1.0 IN `vs` AS `has_1`
---------------------^^^
FROM `sparklyr_tmp_68ef6a302e24`
GROUP BY `cyl`

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:241)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:117)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:69)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

Are there any possible workarounds that don't involve filtering and joining back to the original table? The actual data set for my application isn't going to be cached in Spark's memory so want to minimize the number of times I need to pass through the whole thing.

Session info:
```
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS  10.14.3              
 system   x86_64, darwin17.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2019-03-18                  

─ Packages ───────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.0)
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.1)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
 callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.1)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)
 config        0.3     2018-03-27 [1] CRAN (R 3.5.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.0)
 curl          3.3     2019-01-10 [1] CRAN (R 3.5.1)
 DBI           1.0.0   2018-05-02 [1] CRAN (R 3.5.0)
 dbplyr        1.3.0   2019-01-09 [1] CRAN (R 3.5.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.0)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
 dplyr       * 0.8.0.1 2019-02-15 [1] CRAN (R 3.5.1)
 ellipsis      0.1.0   2019-02-19 [1] CRAN (R 3.5.1)
 fansi         0.4.0   2018-10-05 [1] CRAN (R 3.5.1)
 forge         0.2.0   2019-02-26 [1] CRAN (R 3.5.1)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)
 generics      0.0.2   2018-11-29 [1] CRAN (R 3.5.1)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
 htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.0)
 htmlwidgets   1.3     2018-09-30 [1] CRAN (R 3.5.1)
 httr          1.4.0   2018-12-11 [1] CRAN (R 3.5.1)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.5.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.0)
 openssl       1.1     2018-11-15 [1] CRAN (R 3.5.1)
 pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.1)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.1)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.0)
 processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.1)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.1)
 purrr         0.2.5   2018-05-29 [1] CRAN (R 3.5.0)
 r2d3          0.2.3   2018-12-18 [1] CRAN (R 3.5.1)
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.1)
 rappdirs      0.3.1   2016-03-28 [1] CRAN (R 3.5.1)
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.1)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
 rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.1)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.0)
 rstudioapi    0.9.0   2019-01-09 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
 sparklyr    * 1.0.0   2019-02-25 [1] CRAN (R 3.5.1)
 testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.1)
 tibble        2.0.1   2019-01-12 [1] CRAN (R 3.5.1)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.1)
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
 utf8          1.1.4   2018-05-24 [1] CRAN (R 3.5.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.0)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
```

**Comment by harryprince** [comment]
your local code is not executing a standard SQL
```
mtcars %>%
  group_by(cyl) %>%
  summarise(has_1 = 1 %in% vs)
```

this is the standard SQL
```
mtcars %>%
  group_by(cyl) %>%
  filter(has_1 = 1 %in% vs)
```

**Comment by benmwhite** [comment]
@harryprince that doesn't give the same output though.

```
mtcars %>%
  group_by(cyl) %>%
  mutate(has_1 = 1 %in% vs) %>%
  select(cyl,has_1) %>%
  ungroup()
```

```
# A tibble: 32 x 2
     cyl has_1
   <dbl> <lgl>
 1     6 TRUE 
 2     6 TRUE 
 3     4 TRUE 
 4     6 TRUE 
 5     8 FALSE
 6     6 TRUE 
 7     8 FALSE
 8     4 TRUE 
 9     4 TRUE 
10     6 TRUE
```

I'm trying to get a single row for each unique element in `cyl` letting me know if that group has any observations where `vs` = 1.

```
# A tibble: 3 x 2
    cyl has_1
  <dbl> <lgl>
1     4 TRUE 
2     6 TRUE 
3     8 FALSE
```

**Comment by harryprince** [comment]
it's pretty simple,
```
 group_by(cyl) %>%
mutate( tmp = sum(has_1))%>%
filter(tmp >= 1) %>%
ungroup() %>%
select(cyl,has_1)
```

**Comment by benmwhite** [comment]
Got it running without using "%in%", I was definitely overthinking things earlier. 

```
mtcars %>%
  sdf_import(sc) %>% 
  group_by(cyl) %>%
  summarise(tmp = sum(as.integer(vs == 1))) %>% 
  transmute(cyl, has_1 = tmp > 0)
```
```
# Source: spark<?> [?? x 2]
    cyl has_1
  <dbl> <lgl>
1     8 FALSE
2     4 TRUE 
3     6 TRUE 
```

I'm going to close this for now since it seems like it may be more of a dplyr-to-SQL best practice issue rather than any sort of parsing bug.
