### ISSUE TITLE
Scala 2.12 for spark 2.4.2

### ISSUE THREAD

**Issue by saianger** [rstudio/sparklyr#1993]
Hi,

I have a standalone spark cluster with version 2.4.2 built on AWS, when I try to make a connection to the cluster, I got error msg below:

------------------------------------------------------------------------------
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (15821): Gateway in localhost:8880 did not respond.
    Path: /opt/spark-2.4.2-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/ebs/home/ruser/R/x86_64-redhat-linux-gnu-library/3.4/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 15821
    Log: /tmp/Rtmp5pz8tg/file2d0b17613d58_spark.log

---- Output Log ----
19/04/29 23:57:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at sparklyr.Shell$.main(shell.scala:29)
	at sparklyr.Shell.main(shell.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

---- Error Log ----

After a few googling i think the cause of the problem is that in version 2.4.2 of spark, scala is upgraded to 2.12. 

Here is the code to make a connection to spark from sparklyr:
sc <- spark_connect(master = "spark://eni.dev1-19.rstudio.dept.syd.non.c1.example.com:7077")

Here is my session information:
> utils::sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.3.2    dplyr_0.8.0.1  sparklyr_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       pillar_1.3.1     compiler_3.4.1   later_0.8.0      dbplyr_1.4.0    
 [6] r2d3_0.2.3       base64enc_0.1-3  tools_3.4.1      digest_0.6.18    jsonlite_1.6    
[11] tibble_2.1.1     pkgconfig_2.0.2  rlang_0.3.4      DBI_1.0.0        rstudioapi_0.10 
[16] curl_3.3         yaml_2.2.0       parallel_3.4.1   withr_2.1.2      httr_1.4.0      
[21] askpass_1.1      generics_0.0.2   htmlwidgets_1.3  rappdirs_0.3.1   rprojroot_1.3-2 
[26] tidyselect_0.2.5 glue_1.3.1       forge_0.2.0      R6_2.4.0         purrr_0.3.2     
[31] magrittr_1.5     backports_1.1.4  promises_1.0.1   htmltools_0.3.6  ellipsis_0.1.0  
[36] assertthat_0.2.1 mime_0.6         xtable_1.8-4     httpuv_1.5.1     config_0.3      
[41] openssl_1.3      crayon_1.3.4

**Comment by dotRData** [comment]
same here

**Comment by saianger** [comment]
Hi,

Is there any update on this issue?

**Comment by gaganverma1** [comment]
I had the same problem. I think `sparklyr` does not have support for `scala 2.12` yet. 
I tried `sparklyr` with `spark 2.4.3` which is build with `scala 2.11.12` and the issue was resoved. 
See this as well:
https://github.com/rstudio/sparklyr/issues/1902
