### ISSUE TITLE
Setting `sparklyr.defaultPackages` not working in `minikube`

### ISSUE THREAD

**Issue by bmkor** [rstudio/sparklyr#2074]
Setting `sparklyr.defaultPackages` in `spark_config` works as expected in local `spark_connect` but found not working in `minikube`

For instance,

```
k8s_config<-spark_config_kubernetes(master = "k8s://https://192.168.99.101:8443",
                        image="spark-r:sparklyr", driver = "spark-pi-driver")

k8s_config$sparklyr.defaultPackages[[1]]<-"com.databricks:spark-xml_2.11:0.5.0"

sc<-spark_connect(master="k8s://https://192.168.99.101:8443",
                  config=k8s_config)
```

Error log appears:

```
Error: java.lang.ClassNotFoundException: Failed to find data source: xml. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:139)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: xml.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:634)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:634)
	at scala.util.Try.orElse(Try.scala:84)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:634)
	... 36 more
```

If using `spark_connect(master = "local", ...)`, works fine.

My `utils::sessionInfo()` shows:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.0.1  sparklyr_1.0.2 sp_1.3-1      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       pillar_1.3.1     compiler_3.5.3   later_0.8.0      dbplyr_1.4.0     r2d3_0.2.3       base64enc_0.1-3 
 [8] tools_3.5.3      digest_0.6.18    lattice_0.20-38  jsonlite_1.6     tibble_2.1.1     pkgconfig_2.0.2  rlang_0.3.1     
[15] shiny_1.2.0      DBI_1.0.0        rstudioapi_0.10  crosstalk_1.0.0  parallel_3.5.3   yaml_2.2.0       withr_2.1.2     
[22] httr_1.4.0       askpass_1.1      rappdirs_0.3.1   generics_0.0.2   htmlwidgets_1.3  rprojroot_1.3-2  leaflet_2.0.2   
[29] grid_3.5.3       tidyselect_0.2.5 glue_1.3.1       forge_0.2.0      R6_2.4.0         purrr_0.3.2      SparkR_2.4.1    
[36] magrittr_1.5     backports_1.1.3  promises_1.0.1   htmltools_0.3.6  ellipsis_0.1.0   assertthat_0.2.0 mime_0.6        
[43] xtable_1.8-3     httpuv_1.5.0     config_0.3       openssl_1.2.2    crayon_1.3.4    
```

Any help would be appreciated. Thanks.

**Comment by javierluraschi** [comment]
I would reconnect with the sparklyr.log.console spark setting set to TRUE which should log the spark-submit command sparklyr is using which we can then check that contains the spark packages and that they match Sparks documentation.

**Comment by javierluraschi** [comment]
It could also be the case that the com.databricks:spark-xml_2.11:0.5.0 package is not compatible with your version of Spark, so worth double checking that as well.

**Comment by bmkor** [comment]
Thanks @javierluraschi 

Turned on the `sparklyr.log.console` and found below

Please note `/Users/bmkor/` (not within cluster) here.

```
Ivy Default Cache set to: /Users/bmkor/.ivy2/cache
The jars for the packages stored in: /Users/bmkor/.ivy2/jars
:: loading settings :: url = jar:file:/Users/bmkor/spark/spark-2.4.0-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-xml_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-a2874bb2-34a0-461b-9359-bdefd5e6cf98;1.0
	confs: [default]
	found com.databricks#spark-xml_2.11;0.5.0 in central
:: resolution report :: resolve 165ms :: artifacts dl 3ms
	:: modules in use:
	com.databricks#spark-xml_2.11;0.5.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-a2874bb2-34a0-461b-9359-bdefd5e6cf98
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/4ms)
19/07/07 00:22:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/07/07 00:22:25 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-d30c2e0a99d04e7eb3501bfb2f7fbbc5, spark-role -> driver
	 pod uid: 3de81f4c-a00a-11e9-a2f5-080027bee637
	 creation time: 2019-07-06T16:22:26Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-pn2vl
	 node name: N/A
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
19/07/07 00:22:25 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-d30c2e0a99d04e7eb3501bfb2f7fbbc5, spark-role -> driver
	 pod uid: 3de81f4c-a00a-11e9-a2f5-080027bee637
	 creation time: 2019-07-06T16:22:26Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-pn2vl
	 node name: minikube
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
19/07/07 00:22:25 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-d30c2e0a99d04e7eb3501bfb2f7fbbc5, spark-role -> driver
	 pod uid: 3de81f4c-a00a-11e9-a2f5-080027bee637
	 creation time: 2019-07-06T16:22:26Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-pn2vl
	 node name: minikube
	 start time: 2019-07-06T16:22:26Z
	 container images: spark-r:sparklyr
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=spark-r:sparklyr, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={}), additionalProperties={}), additionalProperties={})]
19/07/07 00:22:25 INFO Client: Waiting for application sparklyr to finish...
19/07/07 00:22:26 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-d30c2e0a99d04e7eb3501bfb2f7fbbc5, spark-role -> driver
	 pod uid: 3de81f4c-a00a-11e9-a2f5-080027bee637
	 creation time: 2019-07-06T16:22:26Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-pn2vl
	 node name: minikube
	 start time: 2019-07-06T16:22:26Z
	 container images: spark-r:sparklyr
	 phase: Running
	 status: [ContainerStatus(containerID=docker://8b718d02ba693ca6ecd2d839dd66c326783cbf1500dc63d60557d0c1ca0abe58, image=spark-r:sparklyr, imageID=docker://sha256:e65f024e912963173fc13179f099607162ae7065460b3f12a6c118c1f2b8af77, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=true, restartCount=0, state=ContainerState(running=ContainerStateRunning(startedAt=Time(time=2019-07-06T16:22:26Z, additionalProperties={}), additionalProperties={}), terminated=null, waiting=null, additionalProperties={}), additionalProperties={})]
```

`kubectl logs -f spark-pi-driver` gives 

```
...
2019-07-06 16:22:29 WARN  DependencyUtils:66 - Local jar /Users/bmkor/.ivy2/jars/com.databricks_spark-xml_2.11-0.5.0.jar does not exist, skipping.
...
```

Think the Local jar path incorrect here?

**Comment by bmkor** [comment]
Found can overrride the default path for `ivy.default.user.dir` in https://spark.apache.org/docs/latest/configuration.html but wondering how to pass this in `sparklyr::spark_connect`, simply `spark_config()$spark.jars.ivy`? Look like I'm wrong. Hmmm..

**Comment by bmkor** [comment]
Stupid me! 

The following `spark_config` solved this issue:

```
spark_config_kubernetes(master = "k8s://https://192.168.99.102:8443",
                        image="spark-r:sparklyr", driver = "spark-pi-driver",
                        conf = list(
                          "spark.jars.packages"="com.databricks:spark-xml_2.11:0.5.0"              
                        ))
```
