### ISSUE TITLE
SSLHandshakeException when `spark_connect` k8s cluster

### ISSUE THREAD

**Issue by bmkor** [rstudio/sparklyr#2076]
Have a bare-metal `k8s` cluster in a remote server. Tried to use `spark_connect` connecting to the cluster but in vain.

The `spark-r:sparklyr` image was successfully built and pushed to a private repository which can also be accessed by the cluster and my local mac. 

Run the following `config` and try `spark_connect`

```
k8s_config<-spark_config_kubernetes(master = "k8s://https://10.53.64.19:6443",
                                    image="(private repo)/spark-r:sparklyr", 
                                    driver = "spark-pi-driver",
                                    conf = list(
                                      "spark.executor.memory" = "2g",
                                      "spark.executor.cores" = "2",
                                      "spark.jars.packages"="com.databricks:spark-xml_2.11:0.5.0"
                                    ))
k8s_config$sparklyr.log.console = TRUE
sc<-spark_connect(master=k8s_config$spark.master,
                  config=k8s_config)
```

The following error log appeared. Perhaps due to authenticating issue? As I am trying to use my local mac connecting to a remote `k8s` cluster which is a different machine sitting in the same intranet subnet.

```
Ivy Default Cache set to: ~/.ivy2/cache
The jars for the packages stored in: ~.ivy2/jars
:: loading settings :: url = jar:file:/$SPARK_HOME/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-xml_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-a7b56d66-43ba-436c-98c2-79b94f85b87e;1.0
	confs: [default]
	found com.databricks#spark-xml_2.11;0.5.0 in central
:: resolution report :: resolve 189ms :: artifacts dl 3ms
	:: modules in use:
	com.databricks#spark-xml_2.11;0.5.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-a7b56d66-43ba-436c-98c2-79b94f85b87e
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/4ms)
19/07/08 18:36:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failed to start websocket
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:207)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
	at okhttp3.internal.ws.RealWebSocket$2.onFailure(RealWebSocket.java:208)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:148)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 39 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 45 more
19/07/08 18:36:14 INFO ShutdownHookManager: Shutdown hook called
19/07/08 18:36:14 INFO ShutdownHookManager: Deleting directory /private/var/folders/_1/95ph4cgn6y91fkw_r6xkjt1m0000gn/T/spark-be598197-7672-436b-9ada-2d77cf8e8433
Error from server (NotFound): pods "spark-pi-driver" not found
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (95074): Gateway in localhost:8880 did not respond.
    Path: $SPARK_HOME/bin/spark-submit
    Parameters: --master, k8s://https://10.53.64.19:6443, --deploy-mode, cluster, --name, sparklyr, --class, sparklyr.Shell, --conf, spark.kubernetes.container.image=(private repo)/spark-r:sparklyr, --conf, spark.kubernetes.driver.pod.name=spark-pi-driver, --conf, spark.kubernetes.authenticate.driver.serviceAccountName=spark, --conf, sparklyr.gateway.remote=TRUE, --conf, spark.executor.memory=2g, --conf, spark.executor.cores=2, --conf, spark.jars.packages=com.databricks:spark-xml_2.11:0.5.0, local:///opt/sparklyr/sparklyr-2.3-2.11.jar, 8880, 95074, --remote
    Log: /var/folders/_1/95ph4cgn6y91fkw_r6xkjt1m0000gn/T//RtmpfS64tz/file116481e953853_spark.log
```

Any help is greatly appreciated. Many thanks in advance.

**Comment by javierluraschi** [comment]
Maybe missing to specify `spark.kubernetes.authenticate.driver.serviceAccountName` parameter? See https://serverfault.com/questions/929806/spark-pi-sample-throws-sockettimeoutexception-in-cluster-k8s-mode 

Also, I would double check that you can run the `spark-pi` example in that K8s cluster from the same machine where R is running.

**Comment by bmkor** [comment]
Thanks @javierluraschi 
Tried to include the `spark.kubernetes.authenticate.driver.serviceAccountName` but still in vain.

However, I managed to get rid of the `SSLHandShakeException` by including `spark.kubernetes.authenticate.submission.caCertFile = (your crt location in local machine)`, the `caCertFile` can be found in the `/etc/kubernetes/pki/apiserver.crt` of the `k8s`, in the `config`.

Further, I need to include `spark.kubernetes.authenticate.submission.oauthToken` in the `config`. For how to get the `token` of the `serviceaccount spark`. One may visit https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/ (just have to aware I am finding the `token` of `spark` not `default`.

Despite having connected to the `k8s` and made it creating the `pod`  `spark-pi-driver`, I still encounter the following error:

```
Ivy Default Cache set to: ~/.ivy2/cache
The jars for the packages stored in: ~/.ivy2/jars
:: loading settings :: url = jar:file:$SPARK_HOME/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-xml_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-4b2104e2-c1bd-4947-b9bd-0bb614e7d823;1.0
	confs: [default]
	found com.databricks#spark-xml_2.11;0.5.0 in central
:: resolution report :: resolve 167ms :: artifacts dl 3ms
	:: modules in use:
	com.databricks#spark-xml_2.11;0.5.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-4b2104e2-c1bd-4947-b9bd-0bb614e7d823
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/4ms)
19/07/09 11:42:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/07/09 11:42:46 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-9af749201bf5468281c7cc42d2808c7e, spark-role -> driver
	 pod uid: 9de23e70-a1fb-11e9-b1c5-941882750a40
	 creation time: 2019-07-09T03:42:46Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-5v77l
	 node name: N/A
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
19/07/09 11:42:46 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-9af749201bf5468281c7cc42d2808c7e, spark-role -> driver
	 pod uid: 9de23e70-a1fb-11e9-b1c5-941882750a40
	 creation time: 2019-07-09T03:42:46Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-5v77l
	 node name: (node name, not master)
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
19/07/09 11:42:46 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-9af749201bf5468281c7cc42d2808c7e, spark-role -> driver
	 pod uid: 9de23e70-a1fb-11e9-b1c5-941882750a40
	 creation time: 2019-07-09T03:42:46Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-5v77l
	 node name: (node name, not master)
	 start time: 2019-07-09T03:42:46Z
	 container images: (private repo)/spark-r:sparklyr
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=(private repo)/spark-r:sparklyr, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={}), additionalProperties={}), additionalProperties={})]
19/07/09 11:42:47 INFO Client: Waiting for application sparklyr to finish...
19/07/09 11:42:49 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-9af749201bf5468281c7cc42d2808c7e, spark-role -> driver
	 pod uid: 9de23e70-a1fb-11e9-b1c5-941882750a40
	 creation time: 2019-07-09T03:42:46Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-5v77l
	 node name: (node name, not master)
	 start time: 2019-07-09T03:42:46Z
	 container images: (private repo)/spark-r:sparklyr
	 phase: Running
	 status: [ContainerStatus(containerID=docker://0e2af5165a2158387792f70f3402c02761001b4f1e0f8329ab0e2af6524dd857, image=(private repo)/spark-r:sparklyr, imageID=docker-pullable://(private repo)/spark-r@sha256:72ef692ae820a2115212fce52bc370ef0cdf9c938e0eb0003f546c2b8b1af7a5, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=true, restartCount=0, state=ContainerState(running=ContainerStateRunning(startedAt=2019-07-09T03:42:49Z, additionalProperties={}), terminated=null, waiting=null, additionalProperties={}), additionalProperties={})]
Error from server (NotFound): pods "spark-pi-driver" not found
19/07/09 11:43:57 INFO LoggingPodStatusWatcherImpl: State changed, new state: 
	 pod name: spark-pi-driver
	 namespace: default
	 labels: spark-app-selector -> spark-9af749201bf5468281c7cc42d2808c7e, spark-role -> driver
	 pod uid: 9de23e70-a1fb-11e9-b1c5-941882750a40
	 creation time: 2019-07-09T03:42:46Z
	 service account name: spark
	 volumes: spark-local-dir-1, spark-conf-volume, spark-token-5v77l
	 node name: (node name, not master)
	 start time: 2019-07-09T03:42:46Z
	 container images: (private repo)/spark-r:sparklyr
	 phase: Failed
	 status: [ContainerStatus(containerID=docker://0e2af5165a2158387792f70f3402c02761001b4f1e0f8329ab0e2af6524dd857, image=(private repo)/spark-r:sparklyr, imageID=docker-pullable://(private repo)/spark-r@sha256:72ef692ae820a2115212fce52bc370ef0cdf9c938e0eb0003f546c2b8b1af7a5, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://0e2af5165a2158387792f70f3402c02761001b4f1e0f8329ab0e2af6524dd857, exitCode=1, finishedAt=2019-07-09T03:43:57Z, message=null, reason=Error, signal=null, startedAt=2019-07-09T03:42:49Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})]
19/07/09 11:43:57 INFO LoggingPodStatusWatcherImpl: Container final statuses:


	 Container name: spark-kubernetes-driver
	 Container image: (private repo)/spark-r:sparklyr
	 Container state: Terminated
	 Exit code: 1
19/07/09 11:43:57 INFO Client: Application sparklyr finished.
19/07/09 11:43:57 INFO ShutdownHookManager: Shutdown hook called
19/07/09 11:43:57 INFO ShutdownHookManager: Deleting directory /private/var/folders/_1/95ph4cgn6y91fkw_r6xkjt1m0000gn/T/spark-76958da6-1034-408d-839c-8f8e871b0cad
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (65451): Sparklyr gateway did not respond while retrieving ports information after 60 seconds
    Path: $SPARK_HOME/bin/spark-submit
    Parameters: --master, k8s://https://(api-server):(api-port), --deploy-mode, cluster, --name, sparklyr, --class, sparklyr.Shell, --conf, spark.kubernetes.container.image=(private repo)/spark-r:sparklyr, --conf, spark.kubernetes.driver.pod.name=spark-pi-driver, --conf, spark.kubernetes.authenticate.driver.serviceAccountName=spark, --conf, spark.executor.memory=2g, --conf, spark.executor.cores=2, --conf, spark.kubernetes.authenticate.driver.serviceAccountName=spark, --conf, spark.kubernetes.authenticate.submission.caCertFile=(crt file location), --conf, spark.kubernetes.authenticate.submission.oauthToken=(token), --conf, spark.jars.packages=com.databricks:spark-xml_2.11:0.5.0, local:///opt/sparklyr/sparklyr-2.3-2.11.jar, 8880, 65451, --remote
    Log: /var/folders/_1/95ph4cgn6y91fkw_r6xkjt1m0000gn/T//Rtmp8FPOvq/file11f0930d1049f_spark.log


---- Output Log ----


---- Error Log ----
```

Interestingly, I found `Error from server (NotFound): pods "spark-pi-driver" not found` but this pod exists in the `k8s` as `kubectl get pods` showed.

Any help/comment would be greatly appreciated.
