### ISSUE TITLE
Compute fails on Spark 1.6.3

### ISSUE THREAD

**Issue by konradzdeb** [rstudio/sparklyr#2099]
# Background
On prod, I've Spark cluster 1.6.3 everytime I try to execute compute I get the following error. I was able to repriduce on desktop machine as shown.

# Reprex

```r
library("sparklyr")
library("tidyverse")
# spark_install(version = "1.6.3")
sc <- withr::with_envvar(
    new = c(
        JAVA_HOME = file.path(
            "/Library",
            "Java",
            "JavaVirtualMachines",
            "adoptopenjdk-8.jdk",
            "Contents",
            "Home"
        )
    ),
    code = spark_connect(master = "local", version = "1.6.3")
)

tbl_mtcars <- copy_to(dest = sc, df = mtcars, name = "mtcars")
tbl_mtcars_new <- tbl_mtcars %>% 
    transmute(am = am + 100) %>% 
    compute()
```

## Error
```
Error: java.lang.RuntimeException: [1.13] failure: ``in'' expected but identifier LIKE found

SHOW TABLES LIKE"dbplyr_001"
            ^
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
	at org.apache.spark.sql.SQLContext$$anonfun$1.apply(SQLContext.scala:208)
	at org.apache.spark.sql.SQLContext$$anonfun$1.apply(SQLContext.scala:208)
	at org.apache.spark.sql.execution.datasources.DDLParser.parse(DDLParser.scala:43)
	at org.apache.spark.sql.SQLContext.parseSql(SQLContext.scala:231)
	at org.apache.spark.sql.hive.HiveContext.parseSql(HiveContext.scala:331)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke.invoke(invoke.scala:147)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
```

# Session Info

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.4.0   stringr_1.4.0   dplyr_0.8.3     purrr_0.3.2     readr_1.3.1    
 [6] tidyr_0.8.3     tibble_2.1.3    ggplot2_3.2.0   tidyverse_1.2.1 shiny_1.3.2    
[11] sparklyr_1.0.2 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1               lubridate_1.7.4          here_0.1                
 [4] lattice_0.20-38          forge_0.2.0              assertthat_0.2.1        
 [7] zeallot_0.1.0            rprojroot_1.3-2          digest_0.6.20           
[10] packrat_0.5.0            mime_0.7                 R6_2.4.0                
[13] cellranger_1.1.0         backports_1.1.4          httr_1.4.0              
[16] pillar_1.4.2             rlang_0.4.0              lazyeval_0.2.2          
[19] curl_3.3                 readxl_1.3.1             rstudioapi_0.10         
[22] miniUI_0.1.1.1           config_0.3               r2d3_0.2.3              
[25] htmlwidgets_1.3          munsell_0.5.0            broom_0.5.2             
[28] compiler_3.5.3           httpuv_1.5.1             modelr_0.1.4            
[31] pkgconfig_2.0.2          askpass_1.1              base64enc_0.1-3         
[34] htmltools_0.3.6          openssl_1.4              reformatFilePath_0.0.0.1
[37] tidyselect_0.2.5         crayon_1.3.4             dbplyr_1.4.2            
[40] withr_2.1.2              later_0.8.0              rappdirs_0.3.1          
[43] grid_3.5.3               nlme_3.1-140             jsonlite_1.6            
[46] xtable_1.8-4             gtable_0.3.0             DBI_1.0.0               
[49] magrittr_1.5             formatR_1.7              scales_1.0.0            
[52] cli_1.1.0                stringi_1.4.3            promises_1.0.1          
[55] xml2_1.2.0               ellipsis_0.2.0.1         fortunes_1.5-4          
[58] generics_0.0.2           vctrs_0.2.0              tools_3.5.3             
[61] glue_1.3.1               hms_0.5.0                parallel_3.5.3          
[64] yaml_2.2.0               colorspace_1.4-1         rvest_0.3.4             
[67] haven_2.1.1             
```
---
# Side notes
* Table is generated:
    <img width="731" alt="image" src="https://user-images.githubusercontent.com/7386756/61901316-5f549c80-af17-11e9-8f89-abe1dac37c85.png">

**Comment by javierluraschi** [comment]
@konradzdeb thanks, this is a bug in `sparklyr` when using Spark 1.6, a workaround is to turn off `analyze`:

```
tbl_mtcars %>% 
    transmute(am = am + 100) %>% 
    compute(analyze = FALSE)
```

Fix to be available in `remotes::install_github("rstudio/sparklyr")` once https://github.com/rstudio/sparklyr/pull/2100 gets merged.

**Comment by konradzdeb** [comment]
Excellent, thanks very much for that answer!
