### ISSUE TITLE
*_join(..., copy = T) doesn't work

### ISSUE THREAD

**Issue by kjedrzejewski** [rstudio/sparklyr#215]
I'm working on Spark 2.0.0 with local master. When i run following code:

``` R

n = 1000000
x = data.table(id = 1:n, val = rnorm(n), t = 1:10)
x_spark = sc %>% copy_to(x, overwrite = T)
ts = data.table(t = 1:10, name = letters[1:10])

x_spark %>%
  group_by(t) %>%
  summarize(m = mean(val)) %>%
  arrange(t) %>%
  inner_join(ts, by = c('t'), copy = T)

```

and i receive following error:

```
ERROR: org.apache.spark.sql.catalyst.parser.ParseException: 
CREATE TEMPORARY TABLE is not supported yet. Please use CREATE TEMPORARY VIEW as an alternative.(line 1, pos 0)

== SQL ==
CREATE TEMPORARY TABLE `rnprrlqxwk` (`t` INTEGER, `name` STRING)
^^^

    at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateTable$1.apply(SparkSqlParser.scala:905)
    at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateTable$1.apply(SparkSqlParser.scala:901)
    at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:96)
    at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateTable(SparkSqlParser.scala:901)
    at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateTable(SparkSqlParser.scala:53)
    at org.apache.spark.sql.catalyst.parser.SqlBaseParser$CreateTableContext.accept(SqlBaseParser.java:474)
    at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:42)
    at org.apache.spark.sql.catalyst.pa
```

which as I understand comes from `Spark` directly not `sparklyr`.

**Comment by javierluraschi** [comment]
Thanks, sent a PR to implement joins against local tables, thanks for pointing this out: https://github.com/rstudio/sparklyr/pull/216

**Comment by javierluraschi** [comment]
Forgot to close, we are good with this one:

```
> x_spark %>%
+   group_by(t) %>%
+   summarize(m = mean(val)) %>%
+   arrange(t) %>%
+   inner_join(ts, by = c('t'), copy = T)
# Source:     lazy query [?? x 3]
# Database:   spark_connection
# Ordered by: t
       t             m  name
   <int>         <dbl> <chr>
 1     1 -0.0004385101     a
 2     2 -0.0006503791     b
 3     3 -0.0017928206     c
 4     4  0.0023800648     d
 5     5  0.0037335291     e
 6     6  0.0021714008     f
 7     7 -0.0009366300     g
 8     8  0.0032418166     h
 9     9 -0.0006577226     i
10    10  0.0003838563     j
# ... with more rows
```
