### ISSUE TITLE
Normalizer

### ISSUE THREAD

**Issue by csgillespie** [rstudio/sparklyr#225]
Is it possible to use the Spark [normalizer](https://spark.apache.org/docs/latest/ml-features.html#normalizer)?

**Comment by kevinushey** [comment]
Good idea! Not sure why this one was missed.

**Comment by kevinushey** [comment]
Ah, I recall why now -- the feature transformer accepts rows of _vectors_, not rows of _doubles_, so attempting to run it naively will give you an error like:

```
 Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12.0 failed 1 times, most recent failure: Lost task 0.0 in stage 12.0 (TID 12, localhost): java.lang.ClassCastException: java.lang.Double cannot be cast to org.apache.spark.ml.linalg.Vector
	at org.apache.spark.ml.feature.Normalizer$$anonfun$createTransformFunc$1.apply(Normalizer.scala:59)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
       ...
```

**Comment by csgillespie** [comment]
Is there a way to not run the function naively?

**Comment by kevinushey** [comment]
No, not performantly anyway. I would suggest just doing the normalization by hand.

**Comment by csgillespie** [comment]
Is this something you plan to add to sparklyr in the future?

**Comment by kevinykuo** [comment]
tracking in https://github.com/rstudio/sparklyr/issues/1092
