### ISSUE TITLE
Spark DF column limit? 

### ISSUE THREAD

**Issue by cam333** [rstudio/sparklyr#244]
Hi all, 
I've been playing around with sparklyr and seem to be running into a column limit of some sort?  I have a data set that has around 4500 columns and couldn't get it into a spark DF, but subsets of the df work.  
Here is an example:

Works:
``` 
library(sparklyr)
library(dplyr)
sc <- spark_connect(master =  "local")
df <- matrix(0, ncol = 200, nrow = 2) %>% as_data_frame()
sdf <- copy_to(sc, df, "df", overwrite = TRUE)

```

When I up the columns to 5000 I get an error:

``` 
library(sparklyr)
library(dplyr)
sc <- spark_connect(master =  "local")
df <- matrix(0, ncol = 5000, nrow = 2) %>% as_data_frame()
sdf <- copy_to(sc, df, "df", overwrite = TRUE)

```

The following error is thrown:

```
Error in if (ncol(df) > 0) df else invisible(df) : 
  argument is of length zero
In addition: Warning message:
In value[[3L]](cond) : java.lang.StackOverflowError
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.generic.GenericCompanion.apply(GenericCompanion.scala:48)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.children(Expression.scala:358)
	at org.apache.spark.sql.catalyst.trees.TreeNode.containsChild$lzycompute(TreeNode.scala:86)
	at org.apache.spark.sql.catalyst.trees.TreeNode.containsChild(TreeNode.scala:86)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:280)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala. [... truncated]
```

Any idea what's going on? 

Thanks

**Comment by kevinushey** [comment]
For reference, the error seems to occur after we attempt to cache the table -- the stack trace I see running your code (with `options(warn = 2, error = recover)`):

```R
> sdf <- copy_to(sc, df, overwrite = TRUE)
Error in value[[3L]](cond) : 
  (converted from warning) java.lang.StackOverflowError
	at org.apache.spark.sql.catalyst.trees.TreeNode.containsChild(TreeNode.scala:86)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:280)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(Traversa

Enter a frame number, or 0 to exit   

 1: copy_to(sc, df, overwrite = TRUE)
 2: copy_to.spark_connection(sc, df, overwrite = TRUE)
 3: dplyr_spark.R#90: tbl_cache(sc, name)
 4: dplyr_spark.R#116: dbGetQuery(sc, paste("SELECT count(*) FROM", dplyr::escape(ident(name), con = sc)))
 5: dbGetQuery(sc, paste("SELECT count(*) FROM", dplyr::escape(ident(name), con = sc)))
 6: dbi_spark_result.R#61: tryCatch(dbFetch(rs, n = -1, ...), error = function(e) {
    warning(conditionMessage
 7: tryCatchList(expr, classes, parentenv, handlers)
 8: tryCatchOne(expr, names, parentenv, handlers[[1]])
 9: value[[3]](cond)
10: dbi_spark_result.R#64: warning(conditionMessage(e), call. = conditionCall(e))
11: .signalSimpleWarning("java.lang.StackOverflowError\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.contai
12: withRestarts({
    .Internal(.signalCondition(simpleWarning(msg, call), msg, call))
    .Internal(.dfltWarn(
13: withOneRestart(expr, restarts[[1]])
14: doWithOneRestart(return(expr), restart)
```

You can disable caching with:

```R
sdf <- copy_to(sc, df, overwrite = TRUE, memory = FALSE)
```

which seems to work fine. We might need to report this upstream to the Spark team.

**Comment by cam333** [comment]
@kevinushey  'memory = FALSE' did the trick. I Was able to load a 22242x4755 df with no problem. 
Thanks and keep up the great work!

**Comment by kevinushey** [comment]
Great, thanks!

**Comment by HashRocketSyntax** [comment]
wow, didn't know sparklyr had been around this long. why are ppl still talking about sparkr?
