### ISSUE TITLE
SparkContext was shut down on long running as_h2o_frame

### ISSUE THREAD

**Issue by jmuhlenkamp** [rstudio/sparklyr#256]
Any idea what might be causing this or where I might turn for help here?  Thanks!

```
> cat(max(system.time(
+   df <- as_h2o_frame(sc, tbl2)
+ ),na.rm=T), file = parlist$out_txt, fill = T, labels = 'convert spark df to h2o df: ', append = T)
Error: org.apache.spark.SparkException: Job 34 cancelled because SparkContext was shut down
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:806)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:804)
    at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
    at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:804)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1658)
    at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
    at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1581)
    at org.apache.spark.SparkContext$$anonfun$stop$9.apply$mcV$sp(SparkContext.scala:1740)
    at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1219)
    at org.apache.spark.SparkContext.stop(SparkContext.scala:1739)
    at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend$MonitorThrea
Timing stopped at: 12.68 2.464 5883.92 

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2016.03

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsparkling_0.1.0 h2o_3.10.0.6     statmod_1.4.26   sparklyr_0.4.12  dplyr_0.5.0     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    R6_2.2.0        assertthat_0.1  rprojroot_1.0-2 DBI_0.5-1       tools_3.2.2     RCurl_1.95-4.8 
 [8] tibble_1.2      Rcpp_0.12.7     jsonlite_1.1    digest_0.6.10   bitops_1.0-6   
Warning messages:
1: replacing previous import by ‘magrittr::%>%’ when loading ‘sparklyr’ 
2: replacing previous import by ‘tibble::data_frame’ when loading ‘sparklyr’
```

**Comment by jmuhlenkamp** [comment]
It runs fine on smaller test data, but has given me this error multiple times on larger data after running for a few hours.

**Comment by javierluraschi** [comment]
@jmuhlenkamp this exception is probably covering up some other issue. Most likely, running out out memory or some other resource constraint. Looking into the Spark worker logs could help here.

**Comment by jmuhlenkamp** [comment]
Thanks, Javier!

**Comment by ledell** [comment]
@jmuhlenkamp Can you say a bit more about your H2O cluster size and the size of `tbl2`?

**Comment by jmuhlenkamp** [comment]
@ledell tbl2 has 1,880,100 rows and 750 columns.

The error I am getting is not specific to as_h2o_frame, but also occurs when I try other functions such as collect() or write.csv() using tbl2.

I have no trouble with the same code in spark 2.0.0, but get this error in 1.6.2.  Here is one of the many cluster configs I have tried.

    sc_config <- spark_config()
    sc_config$spark.driver.extraJavaOptions <- 'append -XX:MaxPermSize=30G'
    sc_config$spark.driver.maxResultSize <- 0
    sc_config$spark.driver.memory <- '30G'
    sc_config$spark.yarn.driver.memoryOverhead <- 4096
    sc_config$spark.yarn.executor.memoryOverhead <- 4096
    sc_config$spark.executor.memory <- '4G'
    sc_config$spark.executor.cores <- 2
    sc_config$spark.dynamicAllocation.maxExecutors <- 15  
    sc_config['yarn.nodemanager.resource.memory-mb'] <- 64512
    sc_config['yarn.nodemanager.resource.cpu-vcores'] <- 15
    sc_config$spark.dynamicAllocation.enabled <- 'false'

    sc <- spark_connect(master = 'yarn-client', config = sc_config, version = '1.6.2')

**Comment by javierluraschi** [comment]
Seems we believe this is a memory limitation from the cluster, so closing with current suggestion of increasing memory.
