### ISSUE TITLE
dplyr::sample_n fails with wrong SQL when non Hive context is available

### ISSUE THREAD

**Issue by rvm-xx** [rstudio/sparklyr#271]
During Spark connection (spark_connect), there was a failure to create Hive context.
The following code, tested with Spark 1.6.2 & sparklyr 0.4,

```
user <- c(1,    1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4)
item <- c(1,    2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4)
rating <- c(5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0)
df = data.frame(user, item, rating)
ddf <- copy_to(sc, df, "test")
ddf %>% sample_n(10)
```

generates a SQL error.

```
Source:   query [?? x 3]
Database: spark connection master=local[4] app=sparklyr local=TRUE

Error: java.lang.RuntimeException: [3.35] failure: ``)'' expected but `(' found

FROM (SELECT *, row_number() OVER (ORDER BY `user`) as rownumber

                                  ^
    at scala.sys.package$.error(package.scala:27)
    at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
    at org.apache.spark.sql.catalyst.DefaultParserDialect.parse(ParserDialect.scala:67)
    at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
    at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
    at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:114)
    at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:113)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
```

Should these functions (sample_frac) be protected with a HIVE context check?

**Comment by kevinushey** [comment]
For what it's worth, you can use `sdf_sample()` to directly access the Spark DataFrame API for the equivalent of `sample_frac()`, and that should work without Hive.

**Comment by kykuo** [comment]
@rvm-xx seems to run fine in the latest version of sparklyr

```
user <- c(1,    1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4)
item <- c(1,    2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4)
rating <- c(5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0,    1.0,    5.0)
df = data.frame(user, item, rating)
ddf <- copy_to(sc, df, "test")
ddf %>% sample_n(10)

# user  item rating rownumber
# <dbl> <dbl>  <dbl>     <int>
#   1      1     1      5         1
# 2      1     2      1         2
# 3      1     3      5         3
# 4      1     4      1         4
# 5      2     1      5         5
# 6      2     2      1         6
# 7      2     3      5         7
# 8      2     4      1         8
# 9      3     1      1         9
# 10     3     2      5        10
# # ... with more rows
```

**Comment by javierluraschi** [comment]
We used to have a custom implementation for `sample_n` but we moved towards the built-in function which is probably the change that fixed this.
