### ISSUE TITLE
copy_to error on Debian

### ISSUE THREAD

**Issue by caprice-j** [rstudio/sparklyr#278]
My issue is similar to #277.
When I execute copy_to(sc, iris), it returns:

```
iris_tbl <- copy_to(sc, iris)
Error: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
    at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
    at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
    at org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
    at org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
    at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycompute(HiveSharedState.scala:46)
    at org.apache.spark.sql.hive.HiveSharedState.externalC
```

I tried all proposed changes in #277, but had no success. 

**The supplemental info**

```
spark_log(sc)
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
    confs: [default]
    found com.databricks#spark-csv_2.11;1.3.0 in central
    found org.apache.commons#commons-csv;1.1 in central
    found com.univocity#univocity-parsers;1.5.1 in central
:: resolution report :: resolve 266ms :: artifacts dl 6ms
    :: modules in use:
    com.databricks#spark-csv_2.11;1.3.0 from central in [default]
    com.univocity#univocity-parsers;1.5.1 from central in [default]
    org.apache.commons#commons-csv;1.1 from central in [default]
    ---------------------------------------------------------------------
    |                  |            modules            ||   artifacts   |
    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    ---------------------------------------------------------------------
    |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
    ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
    confs: [default]
    0 artifacts copied, 3 already retrieved (0kB/10ms)
16/10/22 05:15:14 INFO sparklyr session (7001) starting
16/10/22 05:15:16 INFO sparklyr gateway received command identifier (0)
16/10/22 05:15:16 INFO sparklyr gateway found current session (7001)
16/10/22 05:15:16 INFO sparklyr gateway created backend for session (7001)
16/10/22 05:15:16 INFO sparklyr gateway waiting for r process to end in session (7001)
16/10/22 05:15:17 INFO SparkContext: Running Spark version 2.0.1
16/10/22 05:15:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/22 05:15:17 INFO SecurityManager: Changing view acls to: PCUser
16/10/22 05:15:17 INFO SecurityManager: Changing modify acls to: PCUser
16/10/22 05:15:17 INFO SecurityManager: Changing view acls groups to: 
16/10/22 05:15:17 INFO SecurityManager: Changing modify acls groups to: 
16/10/22 05:15:17 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(PCUser); groups with view permissions: Set(); users  with modify permissions: Set(PCUser); groups with modify permissions: Set()
16/10/22 05:15:17 INFO Utils: Successfully started service 'sparkDriver' on port 34646.
16/10/22 05:15:17 INFO SparkEnv: Registering MapOutputTracker
16/10/22 05:15:17 INFO SparkEnv: Registering BlockManagerMaster
16/10/22 05:15:17 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-91ec0401-478c-4dea-aba1-339954faec7b
16/10/22 05:15:17 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
16/10/22 05:15:17 INFO SparkEnv: Registering OutputCommitCoordinator
16/10/22 05:15:17 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/10/22 05:15:17 INFO SparkUI: Bound SparkUI to 127.0.0.1, and started at http://127.0.0.1:4040
16/10/22 05:15:17 INFO SparkContext: Added JAR file:/home/PCUser/.ivy2/jars/com.databricks_spark-csv_2.11-1.3.0.jar at spark://127.0.0.1:34646/jars/com.databricks_spark-csv_2.11-1.3.0.jar with timestamp 1477113317909
16/10/22 05:15:17 INFO SparkContext: Added JAR file:/home/PCUser/.ivy2/jars/org.apache.commons_commons-csv-1.1.jar at spark://127.0.0.1:34646/jars/org.apache.commons_commons-csv-1.1.jar with timestamp 1477113317910
16/10/22 05:15:17 INFO SparkContext: Added JAR file:/home/PCUser/.ivy2/jars/com.univocity_univocity-parsers-1.5.1.jar at spark://127.0.0.1:34646/jars/com.univocity_univocity-parsers-1.5.1.jar with timestamp 1477113317910
16/10/22 05:15:17 INFO SparkContext: Added JAR file:/home/PCUser/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar at spark://127.0.0.1:34646/jars/sparklyr-2.0-2.11.jar with timestamp 1477113317910
16/10/22 05:15:17 INFO Executor: Starting executor ID driver on host localhost
16/10/22 05:15:17 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43421.
16/10/22 05:15:17 INFO NettyBlockTransferService: Server created on 127.0.0.1:43421
16/10/22 05:15:17 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 127.0.0.1, 43421)
16/10/22 05:15:17 INFO BlockManagerMasterEndpoint: Registering block manager 127.0.0.1:43421 with 366.3 MB RAM, BlockManagerId(driver, 127.0.0.1, 43421)
16/10/22 05:15:17 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 127.0.0.1, 43421)
16/10/22 05:15:18 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
16/10/22 05:15:18 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
16/10/22 05:15:18 INFO HiveSharedState: Warehouse path is '/home/PCUser/spark-warehouse'.
16/10/22 05:15:18 INFO SparkSqlParser: Parsing command: SHOW TABLES
16/10/22 05:15:18 INFO HiveUtils: Initializing HiveMetastoreConnection version 1.2.1 using Spark classes.
16/10/22 05:15:19 INFO HiveMetaStore: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
16/10/22 05:15:19 INFO ObjectStore: ObjectStore, initialize called
16/10/22 05:15:19 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/10/22 05:15:19 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
16/10/22 05:15:20 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
16/10/22 05:15:21 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:15:21 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:15:22 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:15:22 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:15:22 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
16/10/22 05:15:22 INFO ObjectStore: Initialized ObjectStore
16/10/22 05:15:22 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/10/22 05:15:23 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/10/22 05:15:23 INFO HiveMetaStore: Added admin role in metastore
16/10/22 05:15:23 INFO HiveMetaStore: Added public role in metastore
16/10/22 05:15:23 INFO HiveMetaStore: No user is added in admin role, since config is empty
16/10/22 05:15:23 INFO HiveMetaStore: 0: get_all_databases
16/10/22 05:15:23 INFO audit: ugi=PCUser    ip=unknown-ip-addr  cmd=get_all_databases   
16/10/22 05:15:23 INFO HiveMetaStore: 0: get_functions: db=default pat=*
16/10/22 05:15:23 INFO audit: ugi=PCUser    ip=unknown-ip-addr  cmd=get_functions: db=default pat=* 
16/10/22 05:15:23 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:15:23 ERROR sql on 9 failed
16/10/22 05:21:39 INFO SparkSqlParser: Parsing command: SHOW TABLES
16/10/22 05:21:39 INFO HiveUtils: Initializing HiveMetastoreConnection version 1.2.1 using Spark classes.
16/10/22 05:21:39 INFO HiveMetaStore: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
16/10/22 05:21:39 INFO ObjectStore: ObjectStore, initialize called
16/10/22 05:21:40 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
16/10/22 05:21:40 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
16/10/22 05:21:41 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
16/10/22 05:21:41 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:21:41 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:21:42 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:21:42 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:21:42 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
16/10/22 05:21:42 INFO ObjectStore: Initialized ObjectStore
16/10/22 05:21:42 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/10/22 05:21:42 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/10/22 05:21:42 INFO HiveMetaStore: Added admin role in metastore
16/10/22 05:21:42 INFO HiveMetaStore: Added public role in metastore
16/10/22 05:21:42 INFO HiveMetaStore: No user is added in admin role, since config is empty
16/10/22 05:21:42 INFO HiveMetaStore: 0: get_all_databases
16/10/22 05:21:42 INFO audit: ugi=PCUser    ip=unknown-ip-addr  cmd=get_all_databases   
16/10/22 05:21:42 INFO HiveMetaStore: 0: get_functions: db=default pat=*
16/10/22 05:21:42 INFO audit: ugi=PCUser    ip=unknown-ip-addr  cmd=get_functions: db=default pat=* 
16/10/22 05:21:42 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.
16/10/22 05:21:42 ERROR sql on 9 failed
```

My session info (on Google Cloud Compute)

```

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0          sparklyr_0.4.19      RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      digest_0.6.9     withr_1.0.2      rprojroot_1.0-2  assertthat_0.1   rappdirs_0.3.1   R6_2.1.2        
 [8] DBI_0.4-1        magrittr_1.5     config_0.1.0     RevoUtils_10.0.1 tools_3.3.1      yaml_2.1.13      parallel_3.3.1  
[15] tibble_1.0      

```

**Comment by alexwwang** [comment]
I met the same situation with you and no method works in #277 .

**Comment by alexwwang** [comment]
I've solved this. You may refer to #277 where I posed the details.

**Comment by javierluraschi** [comment]
@caprice-j  since the `ERROR sql on 9 failed` has beed resolved now, let's close this issue and finish troubleshooting your issue on #277.

For reference, to solve the `ERROR sql on 9 failed`, from @alexwwang:

"Remember to export some system var in your $spark_home/conf/spark-env.sh as follows:"

```
hadoop_home=/usr/local/hadoop
hadoop_user_name=hadoop # if you use this account launch the hadoop and spark
hadoop_conf_dir=$hadoop_home/etc/hadoop # where hadoop configuration locates
ld_library_path=$hadoop_home/lib/native # solve the warn poped when starting spark # saying can't find native jars library, not sure if necessary.
```

"Before connecting to spark in R, I made config items like below:"

```{r}
config <- spark_config() config[["spark.sql.hive.thriftServer.singleSession"]] <- "true"
```
