### ISSUE TITLE
spark_connect error

### ISSUE THREAD

**Issue by zheguzai100** [rstudio/sparklyr#295]
`sc=spark_connect(master='spark://192.168.1.103:7077')`

`# localhost:192.168.1.102 with Windows OS; spark_master:192.168.1.103 with Ubuntu OS`

`Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\ddd\AppData\Local\Temp\Rtmpua5g1v\file197816677353_spark.log': Permission denied`

**Comment by javierluraschi** [comment]
@zheguzai100 could you try connecting again and provide the full output log?

**Comment by raphael-psr** [comment]
Hi @javierluraschi, I'm having the same issue. Which log do you need?

**Comment by dsblr** [comment]
@javierluraschi  I am also facing the same issue; that is unable to open the logfile. By the time I close R studio, the folder path get deleted automatically.

sc <- spark_connect(master = "spark://##.##.###.##:7077",app_name = "sparklyr_test")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'D:\Users\user1\R\R-3.3.1\Local\Temp\6\RtmpSyVvTW\file3fa056e21a48_spark.log': Permission denied

> spark_log(sc)
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file 'log4j.spark.log': No such file or directory
Please help us to resolve the issue.

**Comment by edgararuiz** [comment]
@zheguzai100 Hi, when you navigate to the master's web UI, port 8080, what's the URL address, it normally is: "ip-##-##-##:7077".  Granted, I've done this in AWS, but I know that when the master URL in sparklyr matches to the URL in the Web UI it connects.  Here's a screenshot: 

![xk8bizabngakyactabjsaezgsbfsznbtn3wgsyabngakyactabjncxemdbflfeor43e2actiajmaemwasywhkh8p8bqutrt5mochaaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7875923/21395840/9c4e7956-c763-11e6-937d-bea1e4c8fd59.png)

**Comment by prbhadra** [comment]
Hi,
I have installed Spark 2.1.0 and configured the Winutils, HADOOP_HOME, SPARK_HOME as advised.

I am facing problem connecting the spark instance. Please find the log below and suggest:
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch       
> library(sparklyr)
> spark_install(version = "2.1.0")
Spark 2.1.0 for Hadoop 2.7 or later already installed.
> sc <- spark_connect(master = "local")
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In prepare_windows_environment(spark_home) :
  HADOOP_HOME was already but does not match current Spark installation
2: In file(con, "r") :
  cannot open file 'C:\Users\prbha\AppData\Local\Temp\Rtmpe6M86n\file2ac810972c5d_spark.log': Permission denied
> sc <- spark_connect(master = "spark://192.168.199.1:7077")
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In prepare_windows_environment(spark_home) :
  HADOOP_HOME was already but does not match current Spark installation
2: In file(con, "r") :
  cannot open file 'C:\Users\prbha\AppData\Local\Temp\Rtmpe6M86n\file2ac8689b538c_spark.log': Permission denied
>

**Comment by javierluraschi** [comment]
The `*.log` file permissions issues should be resolved now, the issue form @prbhadra looks like `SPARK_HOME` is mismatched between connection/installation, feel free to open a new issue if this issue is still reproducible.

**Comment by BruceZhaoR** [comment]
@javierluraschi  I encountered the issue before. 

I used `devtools` to install the latest sparklyr, it showed the following error and warnings : 

```java
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file 'log4j.spark.log': No such file or directory
Error: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionState':
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:981)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:110)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:109)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:878)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:878)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:978)
	... 44 more
Caused by: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveExternalCatalog':
	at org.apache.spark.sql.internal.SharedState$.org$apache$spark$sql$internal$SharedState$$reflect(SharedState.scala:169)
	at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:86)
	at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
	at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:101)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:101)
	at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:100)
	at org.apache.spark.sql.internal.SessionState.<init>(SessionState.scala:157)
	at org.apache.spark.sql.hive.HiveSessionState.<init>(HiveSessionState.scala:32)
	... 49 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.internal.SharedState$.org$apache$spark$sql$internal$SharedState$$reflect(SharedState.scala:166)
	... 57 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:264)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:366)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:270)
	at org.apache.spark.sql.hive.HiveExternalCatalog.<init>(HiveExternalCatalog.scala:65)
	... 62 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The root scratch dir: /tmp/hive on HDFS should be writable. Current permissions are: ---------
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:192)
	... 70 more
Caused by: java.lang.RuntimeException: The root scratch dir: /tmp/hive on HDFS should be writable. Current permissions are: ---------
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:612)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:508)
	... 71 more
```

```r
> sc
$master
[1] "local"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$sparklyr.cores.local
[1] 4

$config$spark.sql.shuffle.partitions.local
[1] 4

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

attr(,"config")
[1] "default"
attr(,"file")
[1] "D:\\R\\R-3.4.0\\library\\sparklyr\\conf\\config-template.yml"

$spark_home
[1] "C:\\Users\\Bruce\\AppData\\Local\\rstudio\\spark\\Cache\\spark-2.1.0-bin-hadoop2.7"

$backend
A connection with                               
description "->localhost:61046"
class       "sockconn"         
mode        "wb"               
text        "binary"           
opened      "opened"           
can read    "yes"              
can write   "yes"              

$monitor
A connection with                              
description "->localhost:8880"
class       "sockconn"        
mode        "rb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$output_file
[1] "C:\\Users\\Bruce\\AppData\\Local\\Temp\\RtmpWooSMo\\file274c63237fb_spark.log"

$spark_context
<jobj[5]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@36098ded

$java_context
<jobj[6]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@23dae85d

attr(,"class")
[1] "spark_connection"       "spark_shell_connection"
[3] "DBIConnection"  


Session info ------------------------------------------------------------
 setting  value                         
 version  R version 3.4.0 (2017-04-21)  
 system   x86_64, mingw32               
 ui       RStudio (1.0.143)             
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 tz       Asia/Shanghai                 
 date     2017-05-15                    

Packages ----------------------------------------------------------------
 package    * version    date       source                           
 assertthat   0.2.0      2017-04-11 CRAN (R 3.3.3)                   
 backports    1.0.5      2017-01-18 CRAN (R 3.3.2)                   
 base       * 3.4.0      2017-04-21 local                            
 base64enc    0.1-3      2015-07-28 CRAN (R 3.3.0)                   
 compiler     3.4.0      2017-04-21 local                            
 config       0.2        2016-08-02 CRAN (R 3.3.2)                   
 curl         2.6        2017-04-27 CRAN (R 3.4.0)                   
 data.table   1.10.4     2017-02-01 CRAN (R 3.3.2)                   
 datasets   * 3.4.0      2017-04-21 local                            
 DBI          0.6-1      2017-04-01 CRAN (R 3.3.3)                   
 dbplyr       0.0.0.9001 2017-05-15 Github (tidyverse/dbplyr@cf6e0a6)
 devtools     1.13.1     2017-05-13 CRAN (R 3.4.0)                   
 digest       0.6.12     2017-01-27 CRAN (R 3.3.2)                   
 dplyr      * 0.5.0.9004 2017-05-15 Github (tidyverse/dplyr@f12d245)               
 git2r        0.18.0     2017-01-01 CRAN (R 3.3.2)                   
 glue         1.0.0      2017-04-17 CRAN (R 3.4.0)                   
 graphics   * 3.4.0      2017-04-21 local                            
 grDevices  * 3.4.0      2017-04-21 local                            
 grid         3.4.0      2017-04-21 local                            
 hms          0.3        2016-11-22 CRAN (R 3.3.2)                   
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                   
 httpuv       1.3.3      2015-08-04 CRAN (R 3.3.1)                   
 httr         1.2.1      2016-07-03 CRAN (R 3.3.1)                   
 jsonlite     1.4        2017-04-08 CRAN (R 3.3.3)                   
 knitr        1.15.1     2016-11-22 CRAN (R 3.3.2)                   
 lattice      0.20-35    2017-03-25 CRAN (R 3.4.0)                   
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.3.0)                   
 magrittr     1.5        2014-11-22 CRAN (R 3.3.0)                   
 Matrix       1.2-10     2017-04-28 CRAN (R 3.4.0)                   
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                   
 methods    * 3.4.0      2017-04-21 local                            
 mime         0.5        2016-07-07 CRAN (R 3.3.1)                   
 parallel     3.4.0      2017-04-21 local                            
 R6           2.2.1      2017-05-10 CRAN (R 3.4.0)                   
 rappdirs     0.3.1      2016-03-28 CRAN (R 3.3.1)                   
 Rcpp         0.12.10    2017-03-19 CRAN (R 3.3.3)                   
 readr        1.1.0      2017-03-22 CRAN (R 3.3.3)                   
 rlang        0.1.9000   2017-05-15 Github (tidyverse/rlang@c17568e) 
 rprojroot    1.2        2017-01-16 CRAN (R 3.3.2)                   
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.1)                   
 sparklyr   * 0.5.4-9002 2017-05-15 Github (rstudio/sparklyr@9f34eb5)
 stats      * 3.4.0      2017-04-21 local                            
 stringi      1.1.5      2017-04-07 CRAN (R 3.3.3)                   
 tibble       1.3.0.9006 2017-05-15 Github (tidyverse/tibble@e311218)
 tools        3.4.0      2017-04-21 local                            
 utils      * 3.4.0      2017-04-21 local                            
 withr        1.0.2      2016-06-20 CRAN (R 3.3.1)                                          
 yaml         2.1.14     2016-11-12 CRAN (R 3.3.2)   
```
If you need further information, please at me at anytime, thank you in advanced, regards!

**Comment by kevinushey** [comment]
@BruceZhaoR can you please open a separate issue? Your error seems to imply that you're trying to open a Spark connection in a directory in which you don't have write permissions (for some reason, Spark is not able to create the `log4j` log file).

**Comment by BruceZhaoR** [comment]
@kevinushey  Thank you very much! The sparklyr(0.5.4) &spark(2.1.0)  worked fine on my Ubuntu OS.

On Windows , when I use RStudio open a new R Session ,it automatically creates a temp file in `C:\Users\Bruce\AppData\Local\Temp\Rtmp*****\` , and the log file is created in it.  

But I successed before on Windows with spaklyr(0.5.3) & spark(2.0.1). It's ok , I will wait for the latest dplyr 0.6 and sparklyr(0.5.5)  ☺️

**Comment by javierluraschi** [comment]
Fix commited, please retry with `sparklyr 0.5.6-9002` or newer. You can install using `devtools::install_github("rstudio/sparklyr")`.

**Comment by huanfachen** [comment]
Hi, I am using sparkly 0.7.0-9035, and encountered the problem of _cannot open file 'log4j.spark.log': No such file or directory_, when I called `spark_web(sc)`.

I am using R 3.3.3, RStudio 1.0.136, on 64-bit Windows 7.

Below is the details of sc. Please let me know if other information is needed. Thanks!

$master
[1] "local[8]"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$sparklyr.cores.local
[1] 8

$config$spark.sql.shuffle.partitions.local
[1] 8

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

attr(,"config")
[1] "default"
attr(,"file")
[1] "C:\\Users\\HuanfaChen\\Documents\\R\\win-library\\3.3\\sparklyr\\conf\\config-template.yml"

$spark_home
[1] "C:\\Users\\HuanfaChen\\AppData\\Local\\spark\\spark-2.1.0-bin-hadoop2.7"

$backend
        description               class                mode                text              opened 
"->localhost:51760"          "sockconn"                "wb"            "binary"            "opened" 
           can read           can write 
              "yes"               "yes" 

$monitor
       description              class               mode               text             opened 
"->localhost:8880"         "sockconn"               "rb"           "binary"           "opened" 
          can read          can write 
             "yes"              "yes" 

$output_file
[1] "C:\\Users\\HUANFA~1\\AppData\\Local\\Temp\\RtmpkNUsjB\\file36942408347e_spark.log"

$spark_context
<jobj[7]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@26a9d3e5

$java_context
<jobj[8]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@70cb63d2

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"

**Comment by AkanimohOD19A** [comment]
Newbie to Spark and trying to call data from Spark using sparklyr in r.

sc <- spark_connect(master = "local", version = "2.3")

car <- copy_to(sc, mtcars, overwrite = TRUE)

However when car is called, it throws the following error:

Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8, localhost, executor driver): java.io.IOException: Failed to connect to AfroLogicInsect/10.118.20.81:64289 at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245) at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187) at org.apache.spark.rpc.netty.NettyRpcEnv.org$apache$spark$rpc$netty$NettyRpcEnv$$downloadClient(NettyRpcEnv.scala:368) at org.apache.spark.rpc.netty.NettyRpcEnv$$anonfun$openChannel$1.apply$mcV$sp(NettyRpcEnv.scala:336) at org.apache.spark.rpc.netty.NettyRpcEnv$$anonfun$openChannel$1.apply(NettyRpcEnv.scala:335) at org.apache.spark.rpc.netty.NettyRpcEnv$$anonfun$openChannel$1.apply(NettyRpcEnv.scala:335) at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1415) at org.apache.spark.rpc.netty.NettyRpcEnv.openChannel(NettyRpcEnv.scala:339) at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:665) at org.apache.spark.util.Utils$.fetchFile(Utils.scala:489) at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:755) at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:747) at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733) at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732) at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:747) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:312) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Suppressed: java.lang.NullPointerException at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1423) ... 17 more Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: AfroLogicInsect/10.118.20.81:64289 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323) at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) ... 1 more Caused by: java.net.ConnectException: Connection refused: no further information ... 11 more Driver stacktrace: at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1661) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1649) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1648) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1648) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831) at scala.Option.foreach(Option.scala:257) at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1882) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1831) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1820) at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48) at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074) at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:363) at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38) at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3278) at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2727) at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2727) at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3259) at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77) at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3258) at org.apache.spark.sql.Dataset.collect(Dataset.scala:2727) at sparklyr.Utils$.collect(utils.scala:24) at sparklyr.Utils.collect(utils.scala) at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at sparklyr.Invoke.invoke(invoke.scala:161) at sparklyr.StreamHandler.handleMethodCall(stream.scala:141) at sparklyr.StreamHandler.read(stream.scala:62) at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:60) at scala.util.control.Breaks.breakable(Breaks.scala:38) at sparklyr.BackendHandler.channelRead0(handler.scala:40) at sparklyr.BackendHandler.channelRead0(handler.scala:14) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.

also spark_web(sc) throws a web page that is inaccessible.

packageVersion("sparklyr") [1] ‘1.7.3’

spark_home_dir() [1] "C:\Users\PC\AppData\Local/spark/spark-2.3.3-bin-hadoop2.7"

system("java -version") java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode) [1] 0

spark_installed_versions() spark hadoop 1 2.3.3 2.7 dir 1 C:\Users\PC\AppData\Local/spark/spark-2.3.3-bin-hadoop2.7

Kindly assist, Thanks.
