### ISSUE TITLE
Error when copying dataframe to spark context

### ISSUE THREAD

**Issue by aissaelouafi** [rstudio/sparklyr#304]
I tried to copy a dataframe to `sparkcontext`  using : 
`copy_to(sc,df,overwrite = TRUE)`
The `df` contains textual row data. I get the following error message : 

```
Erreur : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 3, localhost): java.lang.NumberFormatException: For input string: "<p>It seems like a lot of the cruises don't run in this month due to Hurricane season so I'm looking for other good options.</p>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at com.databricks.spark.csv.util.TypeCast$.castTo(TypeCast.scala:53)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:118)
	at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$2.apply(CsvRelation.scala:104)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:
```

**Comment by kevinushey** [comment]
Can you provide a reproducible example?

The error message seems to suggest that a cell that is actually a string is being parsed as integer:

> Erreur : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 3, localhost): java.lang.NumberFormatException: For input string: "<p>It seems like a lot of the cruises don't run in this month due to Hurricane season so I'm looking for other good options.</p>

**Comment by aissaelouafi** [comment]
@kevinushey yes my dataframe contains 3 variables; id (integer), title(string) and description (string)

**Comment by kevinushey** [comment]
Can you provide a reproducible example?

**Comment by aissaelouafi** [comment]
This is the content of my session info : 
```

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wordcloud_2.5      RColorBrewer_1.1-2 tm_0.6-2           NLP_0.1-9          stringr_1.1.0     
[6] plotly_3.6.0       ggplot2_2.1.0      dplyr_0.5.0        sparklyr_0.4      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      knitr_1.14       magrittr_1.5     munsell_0.4.3    colorspace_1.2-6 R6_2.1.2        
 [7] httr_1.1.0       plyr_1.8.3       tools_3.2.3      parallel_3.2.3   grid_3.2.3       gtable_0.2.0    
[13] DBI_0.5-1        htmltools_0.3.5  yaml_2.1.13      assertthat_0.1   digest_0.6.9     rprojroot_1.0-2 
[19] tibble_1.2       gridExtra_2.2.1  tidyr_0.6.0      viridis_0.3.4    htmlwidgets_0.6  base64enc_0.1-3 
[25] evaluate_0.9     slam_0.1-35      rmarkdown_1.1    stringi_1.1.2    scales_0.4.0     jsonlite_1.0  
```

As I said my `dataframe` contains 3 columns, `id` : integer, `title` : string and `description` : string.

**Comment by kevinushey** [comment]
You might try updating to the development version of `sparklyr` and trying once more:

```
devtools::install_github("rstudio/sparklyr")
```

Make sure to restart the R session after updating `sparklyr`.

**Comment by aissaelouafi** [comment]
@kevinushey I get already the same error after updating `sparklyr`, I can copy numerical matrix but not textual matrix to `sc`

**Comment by kevinushey** [comment]
Can you please provide a reproducible example? By that, I mean a segment of standalone code that shows the problem you're seeing. Perhaps with some artificial / generated data that you attempt to copy to Spark?

**Comment by aissaelouafi** [comment]
@kevinushey the code that shows the problem is : 

```
sc <- spark_connect(master="local")
robotic = read.csv("../robotics.csv")
copy_to(sc,robotic,overwrite = TRUE)
```
`robotic` contains 4 columns : <b>id, title, content and tags</b> : 

```
-----------------------------------------------------------------------------------
id | title                           |  content                     | tags        |
-----------------------------------------------------------------------------------
1 | example of title 1               | example of content           | tag         |
2 | example of title 2               | example of content           | tag         |
3 | example of title 3               | example of content           | tag         |
4 | example of title 4               | example of content           | tag         |
-----------------------------------------------------------------------------------
```

**Comment by javierluraschi** [comment]
@aissaelouafi any chance you could share a subset of this file to reproduce this problem? You can reach me out at javier at rstudio.com - Thanks!

**Comment by aissaelouafi** [comment]
@javierluraschi can you provide me your email and I will send you a part of the `data.frame`

**Comment by javierluraschi** [comment]
@aissaelouafi javier at rstudio.com

**Comment by javierluraschi** [comment]
Improvements to `copy_to` now tracked in https://github.com/rstudio/sparklyr/issues/941
