### ISSUE TITLE
Titanic data loaded OK in local mode, fail to load in yarn-client mode

### ISSUE THREAD

**Issue by desertnaut** [rstudio/sparklyr#307]
I am trying to replicate [this ML example](https://beta.rstudioconnect.com/content/1518/notebook-classification.html) with the Titanic data but in `yarn-client` mode instead of `local`. The `titanic` data fail to load, while data from other packages (namely `iris`, `flights`, and `batting`) are loaded without an issue. In `local` mode the `titanic` data are loaded successfully.

Here is a reproducible script:

```
library(sparklyr)
library(dplyr)

library(titanic)
library(nycflights13)
library(Lahman)

Sys.setenv(SPARK_HOME = "/home/ctsats/spark-1.6.1-bin-hadoop2.6")
Sys.setenv(HADOOP_CONF_DIR = '/etc/hadoop/conf.cloudera.hdfs')
Sys.setenv(YARN_CONF_DIR = '/etc/hadoop/conf.cloudera.yarn')

config <- spark_config()
config$spark.executor.instances <- 4
config$spark.executor.cores <- 4
config$spark.executor.memory <- "4G"

sc <- spark_connect(master="yarn-client", config=config, version = '1.6.1')

# iris, flights, and batting data work OK:
iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)  
flights_tbl <- copy_to(sc, nycflights13::flights, "flights")
batting_tbl <- copy_to(sc, Lahman::Batting, "batting")

# titanic data fail:
titanic_tbl <- copy_to(sc, titanic::titanic_train, "titanic", overwrite = TRUE)
```
```
> iris_tbl
Source:   query [?? x 5]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
          <dbl>       <dbl>        <dbl>       <dbl>   <chr>
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa
6           5.4         3.9          1.7         0.4  setosa
7           4.6         3.4          1.4         0.3  setosa
8           5.0         3.4          1.5         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa
# ... with more rows
```

Additional info:

- In `local` mode the data are loaded successfully
- With Spark 2.0.0, the behavior is the same (not shown)
- YARN provided by CDH 5.7 
- Using `sparklyr` 0.4 (currently in CRAN)

Error log:

```
16/11/04 12:06:43 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 26.0 (TID 28, host-hd-03.corp.nodalpoint.com): java.lang.ArrayIndexOutOfBoundsException: 11
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.genericGet(rows.scala:227)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.getAs(rows.scala:35)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow$class.isNullAt(rows.scala:36)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.isNullAt(rows.scala:221)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:140)
	at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:130)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:285)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[...]
16/11/04 12:06:43 WARN scheduler.TaskSetManager: Lost task 0.3 in stage 26.0 (TID 31, host-hd-04.corp.nodalpoint.com): java.lang.ArrayIndexOutOfBoundsException

16/11/04 12:06:43 ERROR scheduler.TaskSetManager: Task 0 in stage 26.0 failed 4 times; aborting job
[...]
16/11/04 12:06:43 ERROR sql on 9 failed
```
System info:

```
> sessionInfo()
Oracle Distribution of R version 3.2.0  (--)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Oracle Linux Server 7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Lahman_5.0-0       nycflights13_0.2.0 titanic_0.1.0      dplyr_0.5.0        sparklyr_0.4      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3     digest_0.6.9    withr_1.0.2     rprojroot_1.1   assertthat_0.1  R6_2.2.0        DBI_0.5-1      
 [8] backports_1.0.4 magrittr_1.5    config_0.2      tools_3.2.0     readr_1.0.0     yaml_2.1.13     parallel_3.2.0 
[15] tibble_1.2     
```

**Comment by desertnaut** [comment]
Interestingly enough, saving the `titanic_train` dataset to a CSV file and loading it does not reproduce the error above and allows the data to be read in Spark:

```
> write.csv(titanic_train, file="/home/ctsats/R/titanic.csv")
> library(readr)
> titanic <- read_csv("~/R/titanic.csv")
Parsed with column specification:
cols(
  X1 = col_integer(),
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)
Warning message:
Missing column names filled in: 'X1' [1] 
> titanic_tbl <- copy_to(sc, titanic, "titanic", overwrite = TRUE)
> titanic_tbl
Source:   query [?? x 13]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      X1 PassengerId Survived Pclass                                                Name    Sex   Age SibSp Parch
   <int>       <int>    <int>  <int>                                               <chr>  <chr> <dbl> <int> <int>
1      1           1        0      3                             Braund, Mr. Owen Harris   male    22     1     0
2      2           2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female    38     1     0
3      3           3        1      3                              Heikkinen, Miss. Laina female    26     0     0
4      4           4        1      1        Futrelle, Mrs. Jacques Heath (Lily May Peel) female    35     1     0
5      5           5        0      3                            Allen, Mr. William Henry   male    35     0     0
6      6           6        0      3                                    Moran, Mr. James   male   NaN     0     0
7      7           7        0      1                             McCarthy, Mr. Timothy J   male    54     0     0
8      8           8        0      3                      Palsson, Master. Gosta Leonard   male     2     3     1
9      9           9        1      3   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) female    27     0     2
10    10          10        1      2                 Nasser, Mrs. Nicholas (Adele Achem) female    14     1     0
# ... with more rows, and 4 more variables: Ticket <chr>, Fare <dbl>, Cabin <chr>, Embarked <chr>
```

**Comment by desertnaut** [comment]
Interestingly enough, saving the `titanic_train` dataset to a CSV file and loading it does not reproduce the error above and allows the data to be read in Spark:

```
> write.csv(titanic_train, file="/home/ctsats/R/titanic.csv")
> library(readr)
> titanic <- read_csv("~/R/titanic.csv")
Parsed with column specification:
cols(
  X1 = col_integer(),
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)
Warning message:
Missing column names filled in: 'X1' [1] 
> titanic_tbl <- copy_to(sc, titanic, "titanic", overwrite = TRUE)
> titanic_tbl
Source:   query [?? x 13]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      X1 PassengerId Survived Pclass                                                Name    Sex   Age SibSp Parch
   <int>       <int>    <int>  <int>                                               <chr>  <chr> <dbl> <int> <int>
1      1           1        0      3                             Braund, Mr. Owen Harris   male    22     1     0
2      2           2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female    38     1     0
3      3           3        1      3                              Heikkinen, Miss. Laina female    26     0     0
4      4           4        1      1        Futrelle, Mrs. Jacques Heath (Lily May Peel) female    35     1     0
5      5           5        0      3                            Allen, Mr. William Henry   male    35     0     0
6      6           6        0      3                                    Moran, Mr. James   male   NaN     0     0
7      7           7        0      1                             McCarthy, Mr. Timothy J   male    54     0     0
8      8           8        0      3                      Palsson, Master. Gosta Leonard   male     2     3     1
9      9           9        1      3   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) female    27     0     2
10    10          10        1      2                 Nasser, Mrs. Nicholas (Adele Achem) female    14     1     0
# ... with more rows, and 4 more variables: Ticket <chr>, Fare <dbl>, Cabin <chr>, Embarked <chr>
```

**Comment by desertnaut** [comment]
Interestingly enough, saving the `titanic_train` dataset to a CSV file and loading it does not reproduce the error above and allows the data to be read in Spark:

```
> write.csv(titanic_train, file="/home/ctsats/R/titanic.csv")
> library(readr)
> titanic <- read_csv("~/R/titanic.csv")
Parsed with column specification:
cols(
  X1 = col_integer(),
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)
Warning message:
Missing column names filled in: 'X1' [1] 
> titanic_tbl <- copy_to(sc, titanic, "titanic", overwrite = TRUE)
> titanic_tbl
Source:   query [?? x 13]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      X1 PassengerId Survived Pclass                                                Name    Sex   Age SibSp Parch
   <int>       <int>    <int>  <int>                                               <chr>  <chr> <dbl> <int> <int>
1      1           1        0      3                             Braund, Mr. Owen Harris   male    22     1     0
2      2           2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female    38     1     0
3      3           3        1      3                              Heikkinen, Miss. Laina female    26     0     0
4      4           4        1      1        Futrelle, Mrs. Jacques Heath (Lily May Peel) female    35     1     0
5      5           5        0      3                            Allen, Mr. William Henry   male    35     0     0
6      6           6        0      3                                    Moran, Mr. James   male   NaN     0     0
7      7           7        0      1                             McCarthy, Mr. Timothy J   male    54     0     0
8      8           8        0      3                      Palsson, Master. Gosta Leonard   male     2     3     1
9      9           9        1      3   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) female    27     0     2
10    10          10        1      2                 Nasser, Mrs. Nicholas (Adele Achem) female    14     1     0
# ... with more rows, and 4 more variables: Ticket <chr>, Fare <dbl>, Cabin <chr>, Embarked <chr>
```

**Comment by desertnaut** [comment]
Interestingly enough, saving the `titanic_train` dataset to a CSV file and loading it does not reproduce the error above and allows the data to be read in Spark:

```
> write.csv(titanic_train, file="/home/ctsats/R/titanic.csv")
> library(readr)
> titanic <- read_csv("~/R/titanic.csv")
Parsed with column specification:
cols(
  X1 = col_integer(),
  PassengerId = col_integer(),
  Survived = col_integer(),
  Pclass = col_integer(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_double(),
  SibSp = col_integer(),
  Parch = col_integer(),
  Ticket = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Embarked = col_character()
)
Warning message:
Missing column names filled in: 'X1' [1] 
> titanic_tbl <- copy_to(sc, titanic, "titanic", overwrite = TRUE)
> titanic_tbl
Source:   query [?? x 13]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      X1 PassengerId Survived Pclass                                                Name    Sex   Age SibSp Parch
   <int>       <int>    <int>  <int>                                               <chr>  <chr> <dbl> <int> <int>
1      1           1        0      3                             Braund, Mr. Owen Harris   male    22     1     0
2      2           2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female    38     1     0
3      3           3        1      3                              Heikkinen, Miss. Laina female    26     0     0
4      4           4        1      1        Futrelle, Mrs. Jacques Heath (Lily May Peel) female    35     1     0
5      5           5        0      3                            Allen, Mr. William Henry   male    35     0     0
6      6           6        0      3                                    Moran, Mr. James   male   NaN     0     0
7      7           7        0      1                             McCarthy, Mr. Timothy J   male    54     0     0
8      8           8        0      3                      Palsson, Master. Gosta Leonard   male     2     3     1
9      9           9        1      3   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) female    27     0     2
10    10          10        1      2                 Nasser, Mrs. Nicholas (Adele Achem) female    14     1     0
# ... with more rows, and 4 more variables: Ticket <chr>, Fare <dbl>, Cabin <chr>, Embarked <chr>
```

**Comment by kevinushey** [comment]
I believe this issue is resolved in the development version of `sparklyr` -- if I recall correctly, this can be caused when the last column in a `data.frame` is `character` and has missing values.

**Comment by javierluraschi** [comment]
`copy_to()` improvements now tracked under https://github.com/rstudio/sparklyr/issues/941
