### ISSUE TITLE
Failing with OOM when reading Hive table of few GiB

### ISSUE THREAD

**Issue by czxm** [rstudio/sparklyr#3195]
Sparklyr with Arrow failed to collect a Hive table sized in few GiB (e.g csv files 1.8GiB in total):

sc <- spark_connect(master="yarn-client",)
di <- tbl(sc, glue::glue("wide_test.wide")) %>%
  collect()

The sparklyr Driver throws OOM as below and fail out:

java.lang.OutOfMemoryError
        at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
        at org.apache.arrow.vector.ipc.WriteChannel.write(WriteChannel.java:75)
        at org.apache.arrow.vector.ipc.WriteChannel.write(WriteChannel.java:58)
        at sparklyr.ArrowBatchStreamWriter$$anonfun$writeBatches$1.apply(arrowbatchstreamwriter.scala:28)
        at sparklyr.ArrowBatchStreamWriter$$anonfun$writeBatches$1.apply(arrowbatchstreamwriter.scala:28)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at sparklyr.ArrowBatchStreamWriter.writeBatches(arrowbatchstreamwriter.scala:28)
        at sparklyr.ArrowConverters$.toArrowBatchRdd(arrowconverters.scala:273)
        at sparklyr.ArrowConverters.toArrowBatchRdd(arrowconverters.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sparklyr.Invoke.invoke(invoke.scala:161)
        at sparklyr.StreamHandler.handleMethodCall(stream.scala:138)
        at sparklyr.StreamHandler.read(stream.scala:62)
        at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:59)
        at scala.util.control.Breaks.breakable(Breaks.scala:38)
        at sparklyr.BackendHandler.channelRead0(handler.scala:39)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

other attached packages:
[1] sparklyr_1.7.2  dplyr_1.0.7     devtools_2.3.1  usethis_1.6.1  
[5] Rook_1.1-1      RJSONIO_1.3-1.4 Cairo_1.5-6    

A Hive table with few GiB data is not that huge and should fit in R in most cases.  However, Sparklyr uses a ByteArrayOutputStream to serialize the RDD in arrow format before sending back to R runtime. But ByteArrayOutputStream has a capacity limit of Integer.MAX_VALUE - 8. (2147483639 Bytes) hence this failing:

https://github.com/sparklyr/sparklyr/blob/main/java/spark-2.3.0/arrowconverters.scala#L271-L273

Can we handle this in a more graceful way that only the process memory is the limit ?

**Comment by harryprince** [comment]
pretty weird problem, what is your spark connection configuration?

**Comment by edgararuiz** [comment]
Hi, does the issue also occur when Arrow is not in the mix?
