### ISSUE TITLE
Random forest unable to handle catagorical independent varaible which contains "."

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#348]
Hi Team,
I am testing ml_random_forest, and I am getting the following error.

model <- test_data %>%  ml_random_forest(response = "y",features = c("age", "job","balance"),type = "classification")
Error: java.lang.RuntimeException: [1.11] failure: end of input
job_admin.
          ^
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.catalyst.SqlParser$.parseExpression(SqlParser.scala:49)
	at org.apache.spark.sql.DataFrame$$anonfun$selectExpr$1.apply(DataFrame.scala:741)
	at org.apache.spark.sql.DataFrame$$anonfun$selectExpr$1.apply(DataFrame.scala:740)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.apache.spark.sql.DataFrame.selectExpr(DataFrame.scala:740)
	at org.apache.spark.sql.DataFrame.selectExpr(DataFrame.scala:739)

Here variable "job" is categorical. 
When I removed the categorical input and build the model  I was not getting any error.
Please help me how to include categorical input to build the model using ml_random_forest.

**Comment by dsblr** [comment]
Hi sparklyr team, after tweaking around with the data, I have realized that there is some bug in core sparklyr ml_random_forest() program. Due to which it is unable to handle such categorical independent variable which is having "." character in its field. In this case variable "job" contains a category "admin." instead of "admin" and after removing "." character from the data, I am able to execute random forest algorithm.

But there is no issue with the R randomForest package due to "." in the dataset, which is working perfectly fine.
I am expecting this bug will be fix for ml_random_forest() function.

> x <- read.csv("E:/Users/user1/data/bk_test1.csv")
> randomForest(y ~ age + balance + job, data = x, ntree = 500)   ##this works

Call:
 randomForest(formula = y ~ age + balance + job, data = x, ntree = 500) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 1

        OOB estimate of  error rate: 11.67%
Confusion matrix:
       no yes class.error
no  39864  58 0.001452833
yes  5218  71 0.986575912

> system.time(test_data %>%  ml_random_forest(response = "y",features = c("job","age","balance"),num.trees = 500))
Error: java.lang.RuntimeException: [1.11] failure: end of input

job_admin.
          ^
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.catalyst.SqlParser$.parseExpression(SqlParser.scala:49)
	at org.apache.spark.sql.DataFrame$$anonfun$selectExpr$1.apply(DataFrame.scala:741)
	at org.apache.spark.sql.DataFrame$$anonfun$selectExpr$1.apply(DataFrame.scala:740)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.apache.spark.sql.DataFrame.selectExpr(DataFrame.scala:740)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
Timing stopped at: 0.11 0 0.51 

test3 is the dataset  <- After removing "." from job variable
> test_data <- spark_read_csv(sc = sc, name = "test1",path ="E:/Users/user1/data/bk_test3.csv",repartition = 8)
> system.time(test_data %>%  ml_random_forest(response = "y",features = c("job","age","balance"),num.trees = 500))
* No rows dropped by 'na.omit' call
   user  system elapsed 
   0.61    0.09   13.25

**Comment by kevinykuo** [comment]
@dsblr if this is still happening, could you provide a reprex?
