### ISSUE TITLE
Cannot connect to livy on EMR cluster using spark 2.0.1/livy3.0/scala 2.10 

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#367]
- On the EMR clusters the version of `Spark` is 2.0.1 and it uses `scala` 2.11
- When we install `livy` 3.0, it installs a version that uses `scala` 2.10
- This seems to be causing an issue with the connection from `sparklyr` to `livy`. I was getting error on some classes not found. (full stack below).
- The only useful reference to the error that I found is this one:

`https://groups.google.com/a/cloudera.org/forum/#!searchin/livy-user/AbstractPartialFunction$24mcVL$24sp%7Csort:relevance/livy-user/jCE07EGnhrU/0VDc50YmBAAJ`

which point to `scala` version.
- I built `livy` from source with `scala` 2.11, and that got me past the error. 

May be other variables were involved here that I am not aware of.

Stack trace:

```
16/12/06 17:07:53 INFO ContextLauncher: 16/12/06 17:07:53 INFO RSCDriver: SparkContext not yet up, queueing job request.
16/12/06 17:07:53 INFO ContextLauncher: Exception in thread "main" java.lang.NoClassDefFoundError: scala/runtime/AbstractPartialFunction$mcVL$sp
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.defineClass1(Native Method)
16/12/06 17:07:53 WARN RSCClient: Client RPC channel closed unexpectedly.
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
16/12/06 17:07:53 INFO RSCClient: Failing pending job 0819b78a-d993-4582-a934-9a46fc513261 due to shutdown.
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.security.AccessController.doPrivileged(Native Method)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
16/12/06 17:07:53 INFO ContextLauncher: 	at com.cloudera.livy.repl.Session.start(Session.scala:63)
16/12/06 17:07:53 INFO ContextLauncher: 	at com.cloudera.livy.repl.ReplDriver.initializeContext(ReplDriver.scala:55)
16/12/06 17:07:53 INFO ContextLauncher: 	at com.cloudera.livy.rsc.driver.RSCDriver.run(RSCDriver.java:300)
16/12/06 17:07:53 INFO ContextLauncher: 	at com.cloudera.livy.rsc.driver.RSCDriverBootstrapper.main(RSCDriverBootstrapper.java:85)
16/12/06 17:07:53 INFO ContextLauncher: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16/12/06 17:07:53 INFO ContextLauncher: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16/12/06 17:07:53 INFO ContextLauncher: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.reflect.Method.invoke(Method.java:498)
16/12/06 17:07:53 INFO ContextLauncher: 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
16/12/06 17:07:53 INFO ContextLauncher: 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
16/12/06 17:07:53 INFO ContextLauncher: 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
16/12/06 17:07:53 INFO ContextLauncher: 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
16/12/06 17:07:53 INFO ContextLauncher: 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/12/06 17:07:53 INFO ContextLauncher: Caused by: java.lang.ClassNotFoundException: scala.runtime.AbstractPartialFunction$mcVL$sp
16/12/06 17:07:53 INFO ContextLauncher: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
16/12/06 17:07:53 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
16/12/06 17:07:53 INFO ContextLauncher: 	... 24 more
16/12/06 17:07:54 INFO ContextLauncher: Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org/apache/spark/repl/SparkIMain
16/12/06 17:07:54 INFO ContextLauncher: 	at com.cloudera.livy.repl.SparkInterpreter.start(SparkInterpreter.scala:60)
16/12/06 17:07:54 INFO ContextLauncher: 	at com.cloudera.livy.repl.Session$$anonfun$1.apply(Session.scala:59)
16/12/06 17:07:54 INFO ContextLauncher: 	at com.cloudera.livy.repl.Session$$anonfun$1.apply(Session.scala:57)
16/12/06 17:07:54 INFO ContextLauncher: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
16/12/06 17:07:54 INFO ContextLauncher: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
16/12/06 17:07:54 INFO ContextLauncher: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
16/12/06 17:07:54 INFO ContextLauncher: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
16/12/06 17:07:54 INFO ContextLauncher: 	at java.lang.Thread.run(Thread.java:745)
16/12/06 17:07:54 INFO ContextLauncher: Caused by: java.lang.ClassNotFoundException: org.apache.spark.repl.SparkIMain
16/12/06 17:07:54 INFO ContextLauncher: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
16/12/06 17:07:54 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
16/12/06 17:07:54 INFO ContextLauncher: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
16/12/06 17:07:54 INFO ContextLauncher: 	... 8 more
16/12/06 17:07:54 WARN ContextLauncher: Child process exited with code 1.
```

**Comment by javierluraschi** [comment]
@fereshtehRS I believe this one is the one we discussed in chat, correct? Closing as fixed in Fixed in `0.4.38`, otherwise, please reopen, thanks!

**Comment by fereshtehRS** [comment]
@javierluraschi I mentioned this in the chat, but I don't think it is fixed. This was related to version of Scala being used by Livy which seemed to be in conflict with the version on the EMR cluster.

**Comment by fereshtehRS** [comment]
@javierluraschi I tried again with sparklyr 0.4.39 and the same issue when we use Livy that comes with the package. But using the version of Livy that I build works fine. Not sure what other people have experienced (@edgararuiz).

**Comment by javierluraschi** [comment]
Looks like this needs to be re-investigated...

**Comment by javierluraschi** [comment]
Pushed a fix for Spark 2.1.0 and Livy 0.3.0, this is working now on EMR:

From EMR (lateset version as of this writting):

```
devtools::install_github("rstudio/sparklyr")

livy_install(version = "0.3.0", spark_home = "/usr/lib/spark", spark_version = "2.1.0")

Sys.setenv(SPARK_HOME = "/usr/lib/spark")
livy_service_start()
```

From client:

```
devtools::install_github("rstudio/sparklyr")

sc <- spark_connect(master = "http://ec2-54-162-220-84.compute-1.amazonaws.com:8998/", method = "livy")
copy_to(sc, iris)
spark_disconnect_all()
```

**Comment by javierluraschi** [comment]
From Emr emr-4.8.2:

```
devtools::install_github("rstudio/sparklyr")
library(sparklyr)

livy_install(version = "0.3.0", spark_home = "/usr/lib/spark", spark_version = "1.6.2")

Sys.setenv(SPARK_HOME = "/usr/lib/spark")
livy_service_start()
```

```
devtools::install_github("rstudio/sparklyr")
library(sparklyr)

sc <- spark_connect(master = "ec2-54-166-178-107.compute-1.amazonaws.com:8998/", method = "livy")
copy_to(sc, iris)
spark_disconnect_all()
```

**Comment by javierluraschi** [comment]
Closing for now until more info becomes available of missing version combinations.
