### ISSUE TITLE
Unable to launch master locally

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#375]
Hello Sparklyr team,
I am unable to launch spark master locally, while adding local system ip as master = "ip:port"
sc <- spark_connect(master = "local")     ## works fine

But the following code gives error.
Test1: 
sc <- spark_connect(master = "spark://##.##.##.###:7077")
##.##.##.### is the local machine IP. I am testing this on windows server 2012
Test2:
sc <- spark_connect(master = "spark://##.##.##.###:7077", config = list(spark.sql.warehouse.dir = "C:/Users/user1/AppData/Local/rstudio/spark/Cache/spark-1.6.2-bin-hadoop2.6/tmp/hadoop/bin"))
##.##.##.### is the local machine IP. I am testing this on windows server 2012
Error: 
INFO AppClient$ClientEndpoint: Connecting to master spark://#.##.##.###:7077...
WARN AppClient$ClientEndpoint: Failed to connect to master #.##.##.###:7077
java.io.IOException: Failed to connect to /#.##.##.###:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:216)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:167)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:200)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:187)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:183)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: no further information: /#.##.##.###:7077
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more

Please help me to resolve the issue.

**Comment by javierluraschi** [comment]
@dsblr This seems to be the problem: `Caused by: java.net.ConnectException: Connection refused` could you make sure that port `7077` is open externally in the Windows firewall?

**Comment by dsblr** [comment]
@javierluraschi the firewall is off. The port 7077 is open.

**Comment by edgararuiz** [comment]
Hi @dsblr, I don't believe that this will work on a Windows box.  The reason why 7077 is the port to connect to is because there's a Master service started using: ```sudo spark-2.0.0/sbin/start-master.sh```, which is  a Linux command.  After it's started, then it uses several ports, including 7077, to listen for the slave nodes, drivers and even the Web UI (port 8080).  If you go to your web browser and type "###.##.###:8080", if you have a master service running, then the Spark UI should show up.  My understanding is that when running on "local" mode, sparklyr is using the Spark shell directly to run the jobs, so there's no need to setup a full gateway, which is pretty cool because it allows it to run on Windows.  My suggestion would be to install a VM, like maybe Virtual Box, on your 2012 machine and install and start Spark there.

**Comment by javierluraschi** [comment]
Yes, I believe something is off in the Spark configuration/deployment, not sparklyr, let us know if that's not the case to reopen.

**Comment by dsblr** [comment]
I found the solution and here is how it should work.
Check if your spark is up and running in standalone mode. If not then run that using the following commands.
go to SPARK_HOME/bin 
spark-class.cmd org.apache.spark.deploy.master.Master
go to the path go to SPARK_HOME/bin again from another window and run the worker where spark master is running. spark://**.**.**.**:7077
spark-class2.cmd org.apache.spark.deploy.worker.Worker spark://**.**.**.**:7077
library(sparklyr)
sc <- spark_connect(master = "spark://**.**.**.**:7077",app_name = "test_spark")
dat <- copy_to(sc, iris, overwrite = TRUE)
