### ISSUE TITLE
ft_one_hot_encoder columns name exception

### ISSUE THREAD

**Issue by aissaelouafi** [rstudio/sparklyr#384]
Hi, 

I use `sparklyr 0.4.41`, I try to use the `ft_one_hot_encoder` transformer on `servername` column : 

```{r}
data_spark_table = copy_to(sc,df)
ft_one_hot_encoder(data_spark_table,input.col = "servername",output.col = "servernmae")
```

I get the following error message :  
```{r}
Error: java.lang.IllegalArgumentException: requirement failed: Column servername must be of type DoubleType but was actually StringType.
	at scala.Predef$.require(Predef.scala:233)
	at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)
	at org.apache.spark.ml.feature.OneHotEncoder.transformSchema(OneHotEncoder.scala:72)
	at org.apache.spark.ml.feature.OneHotEncoder.transform(OneHotEncoder.scala:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javierluraschi** [comment]
@aissaelouafi what you want to use first is `ft_string_indexer`, see http://spark.apache.org/docs/latest/ml-features.html#onehotencoder, as in:

```
iris1 <- sdf_copy_to(sc, iris)
ft_string_indexer(iris1 ,input.col = "Species", output.col = "hot")

# Source:   table<sparklyr_tmp_e8b01309dbcf> [?? x 6]
# Database: spark_connection
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species   hot
          <dbl>       <dbl>        <dbl>       <dbl>   <chr> <dbl>
 1          5.1         3.5          1.4         0.2  setosa     2
 2          4.9         3.0          1.4         0.2  setosa     2
 3          4.7         3.2          1.3         0.2  setosa     2
 4          4.6         3.1          1.5         0.2  setosa     2
 5          5.0         3.6          1.4         0.2  setosa     2
 6          5.4         3.9          1.7         0.4  setosa     2
 7          4.6         3.4          1.4         0.3  setosa     2
 8          5.0         3.4          1.5         0.2  setosa     2
 9          4.4         2.9          1.4         0.2  setosa     2
10          4.9         3.1          1.5         0.1  setosa     2
# ... with more rows
```
