### ISSUE TITLE
Error when establishing Connection to spark

### ISSUE THREAD

**Issue by gbortz27** [rstudio/sparklyr#397]
sc <- spark_connect(master = "local")

returns with:

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\grbortz\AppData\Local\Temp\RtmpgTTQcx\file1f1076fd17cd_spark.log': Permission denied

**Comment by raphael-psr** [comment]
Same error happening with me. 

library(sparklyr)
sc <- spark_connect(master = "localhost", version = "2.0.1", spark_home="C:/Spark/psrcore-spark-2.0.1/spark-2.0.1-bin-hadoop2.7")

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\rsampaio\AppData\Local\Temp\Rtmp6diKLf\file126424b2715_spark.log': Permission denied

**Comment by gbortz27** [comment]
Hi raphael

Battling to solve all these errors.

Either its a java problem..memory problem or environmental variable
problem. Tried it on 2 different machines..windows 7 and 8 with diffetent
java versions etc..get tge same problem..if i run it once i get the problem
you have. If i run the sc command again i get another probblem a bout a
timeout on port 8880? I have a 64 bit java version v8.1 jre or jdk makes no
difference ..also checked the paths via sys.getinv() and all correct. Other
users said the 64bit java fixed their connect problem..not mine..so i can
only wait for assistance..hoping someone can help. Also set memory to 1gig
then 4 gig..no luck

Let me know if you come right ..thx

Graham

**Comment by gbortz27** [comment]
Hi All

I managed to connect and run part of the tutorial 

however the session abruptly terminated.

Now when I run the dplyr command Ie get the following

iris_tbl <- copy_to(sc, iris)
Error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycompute(HiveSharedState.scala:46)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog(HiveSharedState.scala:45)
	at org.apache.spark.sql.hive.HiveSessionState.catalog$lzycompute(HiveSessionState.scala:50)
	at org.apache.spark.sql.hive.HiveSessionState.catalog(HiveSessionState.scala:48)
	at org.apache.spark.sql.hive.HiveSessionState$$anon$1.<init>(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer$lzycompute(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer(HiveSessionState.scala:62)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The root scratch dir: C:/Users/grbortz/AppData/Local/rstudio/spark/Cache/spark-2.0.2-bin-hadoop2.7/tmp/hive on HDFS should be writable. Current permissions are: rw-rw-rw-
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:189)
	... 46 more
Caused by: java.lang.RuntimeException: The root scratch dir: C:/Users/grbortz/AppData/Local/rstudio/spark/Cache/spark-2.0.2-bin-hadoop2.7/tmp/hive on HDFS should be writable. Current permissions are: rw-rw-rw-
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:612)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:508)
	... 47 more

See the permissions...who must have the permissions , my user or any user and how do I create these?

How do I set "writable"

My username   has all the permissions

Thanks

**Comment by edgararuiz** [comment]
Morning @gbortz27, last night I found this article that may be of help.  The author talks about setting the security permission for each individual cmd file: http://yokekeong.com/running-apache-spark-with-sparklyr-and-r-in-windows/

**Comment by gbortz27** [comment]
Hi @Edgar,

Yes i saw this article before but hadnt checked the permissions..just did
so and all were set to full permissions / control including read and
execute.

*I did mange to force a connection by not going onto my companies wireless
lan / network , but now when running an instruction ie the iris_tbl =
copy_to(sc,..)  in the tutorial I get a differenrt Error *

...

Caused by: java.lang.RuntimeException: The root scratch dir:
C:/Users/grbortz/AppData/Local/rstudio/spark/Cache/spark-2.0.2-bin-hadoop2.7/tmp/hive
on HDFS *should be writable.* Current permissions are: rw-rw-rw-
at
org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:612)
at
org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
at
org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:508)
... 47 more

*See the permissions...who must have the permissions , my user or any user
and how do I create these?*

*How do I set "writable"..is this ? There is no such permission as Writable*

*My username has all the permissions. Does this mean the Attributes must
not be read only ..when I try change the attributes for that
directory (tmp)..It changes back when I look at it again*

**Comment by javierluraschi** [comment]
Fix commited, please retry with `sparklyr 0.5.6-9002` or newer. You can install using `devtools::install_github("rstudio/sparklyr")`.
