### ISSUE TITLE
sparklyr in YARN with high availability

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#401]
Found this in linkedin. I can't think of anything that would prevent sparklyr to function appropriately in HA, but given the comment, would make sense to explore this further:

> I am trying to use sparklyr (0.4 and 0.5.2) with Cloudera 5.9 but unfortunately it seems that it is not compatible with YARN in high availability. 
> 
> In practice, when I request the spark context from RStudio sparklyr try to make a connection on the YARN standby on port 8032 instead of the active YARN 8032.

CC: @edgararuiz

**Comment by learndm** [comment]
Starting from Rstudio Server on my CDH edge node after the sparklyr package installation I type:

>  sc <- spark_connect(master = "yarn-client", spark_home = "/opt/cloudera/parcels/CDH/lib/spark", config = list(default = list(spark.yarn.keytab = "/home/AD/user1/.config/user1.keytab", spark.yarn.principal = "user1@MYHOST.COM")))

and I receive the message (after a long time):

Error in force(code) : 
  Failed during initialize_connection: java.net.ConnectException: Call From mynode.myhost.com/11.45.4.215 to yarnstandby.myhost.con:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused

spark-shell is able to make regularly the connection to spark from the edge node and I see the process regularly running on Cloudera Hue of my cluster

yarnstandby.myhost.con:8032 is our YARN standby and as expected no service is running on 8032.
It is not clear why the requets of Spark context is directed on the stand by instead of our active YARN

thanks

**Comment by edgararuiz** [comment]
Hi all,

@learndm -  Can we confirm if your stand-by host is listed first in the yarn-site.xml file, either in the yarn.resourcemanager.hostname or yarn.resourcemanager.address ? 

@javierluraschi - Here's some background on how Cloudera's HA works, http://blog.cloudera.com/blog/2014/05/how-apache-hadoop-yarn-ha-works/, the "Deploying an HA Cluster Manually" section explains how clients select the Resource Manager they need to talk to

**Comment by edgararuiz** [comment]
@learndm - One more thing, can you try submitting a job via spark-submit instead of spark-shell please?

Thanks

**Comment by learndm** [comment]
Hi @edgararuiz:

- I confirm our stand by is listed before in yarn-site.xml  and the file is produced automatically form CM (I think that the order must be irrelevant for sparklyr to be resilient in case of failover but a reverse oreder could be a temporary work around ?)

- spark-submit runs regularly and I see the spark job in status "succeeded" in Hue web. From the shell I see the expected output for a simple spark application:

https://github.com/sryza/simplesparkapp

spark-submit --class com.cloudera.sparkwordcount.SparkWordCount ./target/sparkwordcount-0.0.1-SNAPSHOT.jar ./data/inputfile.txt 2

Thanks

**Comment by edgararuiz** [comment]
Thanks @learndm , @javierluraschi let me know that sparklyr does not read the yarn-site.xml file directly, but if this is a dev cluster it may be worth testing a reverse order, this may very helpful to diagnose and maybe even as a temp workaround like you mentioned.

**Comment by learndm** [comment]
@edgararuiz:

- we are in staging environnement and the order changed in yarn.site.xml shows that: 

sc <- spark_connect(master = "yarn-client",version = "1.6.0", config = list(default = list(spark.yarn.keytab = "/home/AD/user1/.config/user1.keytab", spark.yarn.principal = "user1@MYHOST.COM")))

is now trying to establish a connection on the active YARN node but remains waiting:

netstat -nt| grep 8032 (on the edge node)
tcp6       0      0 XX.XX.X.XXX:MMMM       YY.YY.Y.YYY:8032        TIME_WAIT  

- on the active YARN we don't see the connection request from the edge node

It takes really a long time to receive a message back from Rstudio and currently is not available

- spark-shell makes regulary a connection to the cluster from the edge node independently from the change in yarn-site.xml 

- spark submit runs regularly

**Comment by javierluraschi** [comment]
@learndm can you try reconnecting with `sparklyr.gateway.start.timeout` set to `10` seconds and share the output of `spark_connect`? Otherwise, you can also wait `60` seconds which is the connection timeout default.

Here is your connection with 10s timeout:

```{r}
sc <- spark_connect(
  master = "yarn-client",
  version = "1.6.0",
  config = list(
    default = list(
      spark.yarn.keytab = "/home/AD/user1/.config/user1.keytab",
      spark.yarn.principal = "user1@MYHOST.COM",
      sparklyr.gateway.start.timeout = "10"
    )
  )
)

**Comment by learndm** [comment]
@javierluraschi:
- after waiting a long time I receive this message:
Error in force(code) : 
  Failed during initialize_connection: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "myedgenode.MYDOMAIN.COM/xx.xx.x.xxx"; destination host is: "myyarnactive.MYDOMAIN.COM":8032; 
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:772)
        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1408)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at com.sun.proxy.$Proxy10.getClusterMetrics(Unknown Source)
        at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterMetrics(ApplicationClientProtocolPBClientImpl.java:202)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
        at com.sun.proxy.$Proxy11.getClusterMetrics(Unknown Source)
        at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getYarnClusterMetrics(YarnClientImpl.java:483)
        at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:130)
        at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:130)
        at org.apache.spark.Logging$class.logInfo(Logging.scala:58)
        at org.apache.spark.deploy.yarn.Client.logInfo(Client.scala:63)
        at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:129)
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:57)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:157)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:542)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2293)
        at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sparklyr.Invoke$.invoke(invoke.scala:94)
        at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
        at sparklyr.StreamHandler$.read(stream.scala:55)
        at sparklyr.BackendHandler.channelRead0(handler.scala:49)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:687)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1524)
        at org.apache.hadoop.ipc.Client.call(Client.java:1447)
        ... 48 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:413)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        ... 51 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
        ... 60 more



---- Output Log ----
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
        ... 60 more
17/01/05 18:30:26 INFO ui.SparkUI: Stopped Spark web UI at http://.......:4043
17/01/05 18:30:26 INFO cluster.YarnClientSchedulerBackend: Stopped
17/01/05 18:30:26 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/01/05 18:30:26 ERROR util.Utils: Uncaught exception in thread nioEventLoopGroup-2-2
java.lang.NullPointerException
        at org.apache.spark.network.shuffle.ExternalShuffleClient.close(ExternalShuffleClient.java:152)
        at org.apac
In addition: Warning messages:
1: In if (nchar(config[[e]]) == 0) found <- FALSE :
  the condition has length > 1 and only the first element will be used
2: In if (nchar(config[[e]]) == 0) found <- FALSE :
  the condition has length > 1 and only the first element will be used
3: In if (nchar(config[[e]]) == 0) found <- FALSE :
  the condition has length > 1 and only the first element will be used

- I tried to add the parameter named sparklyr.gateway.start.timeout = "10" but even after many minutes I am waiting for a response.

Is there any other parameter that can help us to speed up the response ?

**Comment by learndm** [comment]
@javierluraschi, @edgararuiz - Hi all I tried to launch the request of my spark context using R (/usr/bin/R) from the linux shell of my edge node and I have been able to get the spark context:

![image](https://cloud.githubusercontent.com/assets/10106978/21799692/98bce4be-d71a-11e6-8f7b-a6e6d55bf64e.png)

and here the sc request:

![image](https://cloud.githubusercontent.com/assets/10106978/21799870/5e542e44-d71b-11e6-9128-469f487cc5ce.png)

Currently it seems that:

- Rstudio web not unaable to make a connection to the cluster (maybe this tell something on how to overcome the problem in order to make the web app speaking with the cluster, http server conf or what else ?)
- sparklyr need to recognize who is the active YARN node in case of YARN in High Availability otherwise you need to change manually YARN conf file (or I should try with the original configuration command line provided that the problem seems relate to Rstudio web ?)

Please give feedback

**Comment by vishalvpv** [comment]
We are facing the exact same problem. Would be great if there is a workaround.

**Comment by kevinykuo** [comment]
@learndm @vishalvpv try getting the kerberos ticket via `kinit` issued through the shell inside RStudio (Tools -> Shell...)

**Comment by learndm** [comment]
Thanks @kevinykuo, after typing the statements below within the shell called inside Rstudio I have been able to start the spark context:

$ cd ${HOME}/.config
$ ktutil
ktutil: addent -password -p userxxxxx@YOURHOST.COM -k 1 -e rc4-hmac
ktutil: addent -password -p userxxxxx@YOURHOST.COM -k 1 -e aes256-cts-hmac-sha1-96
ktutil: addent -password -p userxxxxx@YOURHOST.COM -k 1 -e arcfour-hmac
ktutil: wkt cg08410.keytab
ktutil: q
$ kinit userxxxxx@YOURHOST.COM -k -t userxxxxx.keytab

Probably is still open the question about the capability of sparkyr to recognize the ACTIVE YARN node but currently we managed manually the conf file

In my case it takes a few seconds to start

Thanks also to @javierluraschi and @edgararuiz for the answers provided in this issue

**Comment by learngit12** [comment]
Hi,

 try getting the kerberos ticket via kinit issued through the shell inside RStudio (Tools -> Shell...) ----- this need to accessed from Rstudio UI?
Tried search in UI but coludnt find shell option in UI
![imace](https://user-images.githubusercontent.com/69804078/90408522-eb32ec80-e075-11ea-82f5-adaf99f22740.PNG)
