### ISSUE TITLE
Unable to create DTM document term matrix java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#416]
Hello sparklyr team I am getting java.lang.OutOfMemoryError: Java heap space outof memory error while collecting transformed object to create a DTM out of corpus. Please help me with the solution.

library(dplyr)
library(sparklyr)
library(janeaustenr)

**sessioninfo**
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] janeaustenr_0.1.4 dplyr_0.5.0       sparklyr_0.4.41  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     withr_1.0.2     digest_0.6.10   rprojroot_1.1   assertthat_0.1  R6_2.2.0        jsonlite_1.1    DBI_0.5-1       backports_1.0.4 magrittr_1.5    httr_1.2.1     
[12] config_0.2      tools_3.3.1     parallel_3.3.1  yaml_2.1.13     base64enc_0.1-3 tibble_1.2 

**Code**
sc <- spark_connect(master = "local")
austen     <- austen_books()
austen_tbl <- copy_to(sc, austen, overwrite = TRUE)

sdf <- spark_dataframe(austen_tbl)
tokenized <-  sdf %>% 
  na.omit() %>%
  ft_tokenizer(input.col = "text", output.col = "tokens")

transformed <- invoke_new(sc, "org.apache.spark.ml.feature.HashingTF") %>%
  invoke("setInputCol", "tokens") %>%
  invoke("setOutputCol", "hashed") %>%
  invoke("transform", spark_dataframe(tokenized)) %>%
  sdf_register()
hashed <- collect(transformed)

While collecting the transformes object I am getting the following error.
error: Caused by: java.lang.OutOfMemoryError: Java heap space

**Complete error**
Error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Utils$$anonfun$collectImplVector$1.apply(utils.scala:157)
	at sparklyr.Utils$$anonfun$collectImplVector$1.apply(utils.scala:153)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at sparklyr.Utils$.collectImplVector(utils.scala:153)
	at sparklyr.Utils$.collectImpl(utils.scala:188)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:197)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:197)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.Utils$.collect(utils.scala:197)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.ml.linalg.SparseVector.toArray(Vectors.scala:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Utils$$anonfun$collectImplVector$1.apply(utils.scala:157)
	at sparklyr.Utils$$anonfun$collectImplVector$1.apply(utils.scala:153)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at sparklyr.Utils$.collectImplVector(utils.scala:153)
	at sparklyr.Utils$.collectImpl(utils.scala:188)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:197)
	at sparklyr.Utils$$anonfun$collect$1.apply(utils.scala:197)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.Utils$.collect(utils.scala:197)
	at sparklyr.Utils.collect(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)

When I set the following parameters;
 config <- spark_config()
 config$ sparklyr.shell.driver-memory  <- "8G"
 config$ sparklyr.shell.executor-memory  <- "8G"
 config$ spark.yarn.executor.memoryOverhead  <- "4g"

sc <- spark_connect(master = "spark://server1:7077", config = config)

I got a different error:
Error in invoke_method.spark_shell_connection(sc, TRUE, class, method, :
 No status is returned. Spark R backend might have failed.

Please help me with the solution to resolve the issue.

**Comment by javierluraschi** [comment]
Right, the problem seems to be `hashed <- collect(transformed)` since the `transformed` data is too big to collect into R. You could try instead `hashed <- head(transformed)` and I would definitely use this time to upgrade to the latest version of `sparklyr`. Closing but please open a new issue if you are still hitting any issues.
