### ISSUE TITLE
Uanble to implement invoke_new

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#429]
Hello Sparklyr team,
I have created a JAR for a Scala program and would like to access the functions defined in that scala program from Rstudio using sparklyr::invoke_new

While doing the same, I am getting the following error. Please help me to resolve this issue.
**steps:::**
1) created a scala program 
`package pkg1

object obj1 {
  def main(args: Array[String]) {
  val pi = 3.14
  def area_of_circle(radius: Double): Double = pi * radius *radius;
  println(area_of_circle(5));
}
}
`
2) Export the same into a JAR and paste the JAR file called F1
3) Paste the JAR on the path :  SPARK_HOME/jars where other apache jars are present
4) Execute the following command to access the class object

 **Error**

> x <- invoke_new(sc, "pkg1.obj1")
Error: java.lang.ClassNotFoundException: pkg1.obj1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:77)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by javierluraschi** [comment]
There are a couple ways to achieve this, the one I find myself using the most is by setting the `sparklyr.jars.default` parameter in the `sparklyr` config, example follows:

```{r}
# load sparkly
library(sparklyr)

# create new sparklyr config
config <- spark_config()

# add a new default jar to load on connection, path or relative path to custom jar
config[["sparklyr.jars.default"]] <- c("/Users/javierluraschi/RStudio/spark.hello/inst/java/sparkhello-1.6-2.10.jar")

# connect with config parameter
sc <- spark_connect(master = "local", version = "2.0.1")

# invoke function inside jar using fully qualified name defined in the custom jar
sparklyr::invoke_static(sc, "SparkHello.HelloWorld", "hello")
```

Alternatively, you should be able to specify the `--driver-class-path` and `--spark.executor.extraClassPath` parameter and copy this jar manually to the driver and executors. I wouldn't recommend this approach unless the `jar` is of significant size, etc. I'm saying this since it's harder to get it working since some of the paths are relative to the running directory. More info here: http://stackoverflow.com/questions/31707722/how-to-add-configuration-file-to-classpath-of-all-spark-executors-in-spark-1-2-0

**Comment by javierluraschi** [comment]
I believe this question has been answered, let us know if it's not the case.
