### ISSUE TITLE
ml_lda error

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#436]
Hi Team,
I was trying to implement topic modeling using ml_lda and I while doing the same I found the following error,
Error: java.lang.IllegalArgumentException: Data type StringType is not supported.

While trying to resolve the ml_lda error,
I tried to implement the ml_lda.R code step by step replicating the function body, and I found the error at **line number** 63 in the ml_lda.R code

> sc1 <- spark_connect(master = "local")
> austen     <- austen_books()
> austen_tbl <- copy_to(sc1, austen, overwrite = TRUE)

> df <- spark_dataframe(austen_tbl)
> sc <- spark_connection(df)
> alpha      <- ensure_scalar_double(6)
> beta       <- ensure_scalar_double(1.1)
> k          <- ensure_scalar_integer(10)
> ml.options = ml_options()
> only.model <- ensure_scalar_boolean(ml.options$only.model)
> envir <- new.env(parent = emptyenv())
> envir$id <- ml.options$id.column
> df <- df %>% sdf_with_unique_id(envir$id) %>%  spark_dataframe()
> tdf <- ml_prepare_dataframe(df, features, ml.options = ml.options, envir = envir)
Error: java.lang.IllegalArgumentException: Data type StringType is not supported.
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:121)
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:117)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.ml.feature.VectorAssembler.transformSchema(VectorAssembler.scala:117)
	at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:70)
	at org.apache.spark.ml.feature.VectorAssembler.transform(VectorAssembler.scala:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

It seems like ml_prepare_dataframe designed to handle only numeric data. Could you please help to understand what parameter value I should pass to ml_prepare_dataframe to get a tdf from a data frame.

Can you please help me, how to proceed further to resolve the issue.

**Comment by javierluraschi** [comment]
Try running `ml_lda` as follows:

```{r}
devtools::install_github("rstudio/sparklyr", ref = "feature/ft_count_vectorizer")
```

```{r}
library(janeaustenr)
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

austen_books <- austen_books()
books_tbl <- sdf_copy_to(sc, austen_books, overwrite = TRUE)
first_tbl <- books_tbl %>% filter(nchar(text) > 0) %>% head(2)

first_tbl %>%
  ft_tokenizer("text", "tokens") %>%
  ft_count_vectorizer("tokens", "features") %>%
  ml_lda("features", k = 4)
```

If for some reason you can't install the latest version of `sparklyr` source the following function from `sparklyr 0.5` in CRAN:

```{r}
ft_count_vectorizer <- function(x,
                                input.col = NULL,
                                output.col = NULL,
                                min_df = NULL,
                                min_tf = NULL,
                                vocab_size = NULL,
                                ...)
{
  ml_backwards_compatibility_api()
  class <- "org.apache.spark.ml.feature.CountVectorizer"
  invoke_simple_transformer(x, class, list(
    setInputCol   = ensure_scalar_character(input.col),
    setOutputCol  = ensure_scalar_character(output.col),
    setMinDF      = min_df,
    setMinTF      = min_tf,
    setVocabSize  = vocab_size,
    fit           = spark_dataframe(x)
  ))
}
```

**Comment by javierluraschi** [comment]
Provided `ml_lda` sample, let us know if this was not enough.
