### ISSUE TITLE
Error when trying to save a 'ml_model' - Error: Invalid method save for object 2109

### ISSUE THREAD

**Issue by schristel** [rstudio/sparklyr#449]
Hello, 

I'm trying to save two models I produced using ml_random_forest and ml_gradient_boosted_trees. I saw this post <https://github.com/rstudio/sparklyr/issues/134> and tried implementing the solution using ml_save. I also hard  coded the solution. From hard coding the solution I found that the error is after the `invoke(model$.model,"save",file)` step.

 Specifically, I'm getting this error:

`Error: java.lang.IllegalArgumentException: invalid method save for object 2109
        at sparklyr.Invoke$.invoke(invoke.scala:113)
        at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
        at sparklyr.StreamHandler$.read(stream.scala:55)
        at sparklyr.BackendHandler.channelRead0(handler.scala:49)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
`

Any thoughts on what's going on?

**Comment by kevinushey** [comment]
What version of Spark are you using? It looks like `save` / `load` methods should be provided with all versions of Spark >= 1.6.

Can you by any chance provide a reproducible example?

**Comment by schristel** [comment]
We have Spark 1.6.0 . Sure thing, re: reproducible example

**Comment by schristel** [comment]
Here is a reproducible example:

`# create fake data and put it on the hdfs
a <- rnorm(100000,mean=2,sd=3)
b <- rnorm(100000,mean=0,sd=1)
c <- rnorm(100000,mean=5,sd=1)
d <- rnorm(100000,mean=1,sd=.5)
e <- rnorm(100000,mean=0,sd=1)
f <- rnorm(100000,mean=6,sd=2)
g <- rnorm(100000,mean=0,sd=1)
resp <- rnorm(100000,mean=2,sd=3)*pi
fake.dat <- data.frame(a,b,c,d,e,f,g,resp)

#set config options
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "2G"
config$`sparklyr.shell.executor-memory` <- "2G"
config$`spark.yarn.executor.memoryOverhead` <- "1g"

sc = spark_connect(master='local', spark_home='/usr/hdp/2.4.2.0-258/spark')
sc

#read in fake dat
df <- spark_read_csv(sc,name='fake_dat',path='hdfs://pnhadoop/user/stc004/fake_dat_sparklyr.csv')
tdat <- tbl(sc,'fake_dat')

#build model - create train,test, formula and create RF model
partition <- tdat %>%
  sdf_partition(train=0.75,test=0.25,seed=8080)

train_tbl <- partition$train
test_tbl <- partition$test

predVars <- colnames(fake.dat)[which(colnames(fake.dat)!='resp')]
ml_formula <- formula(paste('resp',"~",paste(predVars,collapse="+")))

#create random forest
ml_rf <- ml_random_forest(train_tbl, ml_formula)
ml_save(ml_rf,file = '/rhome/stc004')`

After ml_save() I get the error posted above - obviously with a different object number.

**Comment by kevinushey** [comment]
Ah, looking at the API documentation it looks like the random forest models didn't implement the `MLWritable` interface until Spark 2.0.0. Compare:

http://spark.apache.org/docs/2.0.0/api/scala/index.html#org.apache.spark.ml.regression.RandomForestRegressionModel

http://spark.apache.org/docs/1.6.2/api/scala/index.html#org.apache.spark.ml.regression.RandomForestRegressionModel

So unfortunately the only way to enable saving / loading of these model fits is to upgrade Spark.

**Comment by schristel** [comment]
Ok than you
