### ISSUE TITLE
Error on spark_connect() after installing msvc redistributable without restarting RStudio

### ISSUE THREAD

**Issue by dfalty** [rstudio/sparklyr#45]
Windows 10
v0.99.1243
sparklyr 0.2.7

Error on spark_connect() after installing Microsoft Visual C++ redistributable without restarting RStudio.

Steps:
1. Install sparklyr
2. Try connecting to spark
`sc <- spark_connect(master = "local")`
3. Observe message to install msvc
4. Install msvc redistributable
5. Go back to RStudio and try to run the same spark_connect() command
6. Observe error

```
Error on spark_connect() if you install Microsoft Visual C++ Redistributable Package
Created default hadoop bin directory under: C:\tmp\hadoop
Error: java.lang.RuntimeException: java.lang.NullPointerException at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522) 
at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:204) 
at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238) 
at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:218) 
at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:208) 
at org.apache.spark.sql.hive.HiveContext.functionRegistry$lzycompute(HiveContext.scala:462) 
at org.apache.spark.sql.hive.HiveContext.functionRegistry(HiveContext.scala:461) 
at org.apache.spark.sql.UDFRegistration.<init>(UDFRegistration.scala:40) 
at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:330) 
at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:90) 
at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101) 
at sun.reflect.NativeConstru
```

**Comment by javierluraschi** [comment]
Mentioning the restart in the VS redist installation instructions.
