### ISSUE TITLE
No FileSystem for scheme: s3n

### ISSUE THREAD

**Issue by bboychencan** [rstudio/sparklyr#482]
When I tried to use sparklyr to read parquet file from s3 bucket, the following error is reported. 
I tried spark_install(version = "2.0.0") and spark_install(version = "2.1.0"), neither of them works.

Error: java.io.IOException: No FileSystem for scheme: s3n
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2644)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:352)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:350)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:427)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by javierluraschi** [comment]
@bboychencan You need to include the Amazon S3 package, with something similar to:

```
config <- spark_config()
config[["sparklyr.defaultPackages"]] <- "com.amazonaws:aws-java-sdk-pom:1.10.34"

sc <- spark_connect(master = "<master>", config = config)
spark_read_parquet("s3n://<path-to-data>")
```

**Comment by ElianoMarques** [comment]
In the above example where do you specific the key and secret for aws?

**Comment by edgararuiz** [comment]
Hi @ElianoMarques , you can  add them as environment vars:
```
Sys.setenv(AWS_ACCESS_KEY_ID="[your key]")
Sys.setenv(AWS_SECRET_ACCESS_KEY="[your key]")

**Comment by niklasvm** [comment]
I am receiving a similar error. I have managed to get it to work with spark version 2.0.0 and hadoop version 2.3 after adding the key and secret as environment variables.

Is there a reason why it only works for the above versions?

**Comment by edgararuiz** [comment]
Hi try adding the following package:

org.apache.hadoop:hadoop-aws:2.7.3

This is main package needed to read S3 data

Also, I'd recommend using s3a instead of s3n for your file path

**Comment by niklasvm** [comment]
@edgararuiz thank you that does work. What is the difference between s3n and s3a? Also, how do I go about adding more than one package. i.e. org.apache.hadoop:hadoop-aws:2.7.3 and com.amazonaws:aws-java-sdk-pom:1.10.34 ?

**Comment by edgararuiz** [comment]
Great!

s3a is to access the 'acceleretaded' version of s3 which should be faster

To add more than 1 package use list() to enumerate them, although from
testing Ive done the hadoop-aws package is all you'll need, unless you have
additional  goals

**Comment by edgararuiz** [comment]
Hi @niklasvm, recently posted an article about S3 to the official site, here is the link: http://spark.rstudio.com/example-s3.html

**Comment by niklasvm** [comment]
Thank you very much for this. Very helpful!

**Comment by javierluraschi** [comment]
Looks like we suggested the right configuration settings, closing.
