### ISSUE TITLE
Installation and copy_to errors

### ISSUE THREAD

**Issue by FinScience** [rstudio/sparklyr#491]
Hi,
I plan to use sparklyr. However, I am getting errors which I am unable to resolve. I have followed the steps mentioned in http://spark.rstudio.com/

On trying to create the spark context the following messages are being shown

> sc <- spark_connect(master = "local")
Warning messages:
1: In value[[3L]](cond) :
  java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:204)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:218)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:208)
	at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:440)
	at org.apache.spark.sql.SQLContext$$anonfun$4.apply(SQLContext.scala:272)
	at org.apache.spark.sql.SQLContext$$anonfun$4.apply(SQLContext.scala:271)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at [... truncated]
2: In create_hive_context_v1(sc) :
  Failed to create Hive context, falling back to SQL. Some operations, like window-functions, will not work

While trying to use copy_to , the following errors are being shown
> iris_tbl <- copy_to(sc, iris)
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.io.IOException: No FileSystem for scheme: C
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1686)
	at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:598)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:395)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:430)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:422)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:422)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:206)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:926)
	at sparklyr.Utils$.collectColumnString(utils.scala:59)
	at sparklyr.Utils$.collectColumn(utils.scala:73)
	at sparklyr.Utils.collectColumn(utils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: No FileSystem for scheme: C
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
	at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1686)
	at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:598)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:395)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:430)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:422)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at org.apache.spark.executor.Executor.org$apache$s

**Comment by javierluraschi** [comment]
@FinScience could you retry using the following code?

```
devtools::install_github("rstudio/sparklyr)
options("sparklyr.verbose" = TRUE)
sc <- spark_connect(master = "local")
```

**Comment by FinScience** [comment]
@javierluraschi . Thanks for the reply. But the issue still persists. Is there any problem with the JAVA in my machine? Or something similar?

**Comment by javierluraschi** [comment]
@FinScience Could you try removing the `sparklyr` package first? I doesn't seem that is picking up the change, so run something like:

```
remove.packages("sparklyr")
```

Followed by:

```
devtools::install_github("rstudio/sparklyr)
options("sparklyr.verbose" = TRUE)
sc <- spark_connect(master = "local")
```

You should see a log like this one:

<img width="487" alt="screen shot 2017-02-15 at 1 02 09 pm" src="https://cloud.githubusercontent.com/assets/3478847/22995249/ff64d480-f37e-11e6-9a1f-58f8f216396e.png">

To give you some context, the challenge here is that Spark does not really support a nice installation on Windows; therefore, `sparklyr` is doing a good amount of operations on your behalf to configure Spark in Windows appropriately, we need to first diagnose what is wrong before I can perform a fix or recommend a workaround.

Thanks for putting the time to help us get this resolved.

**Comment by FinScience** [comment]
@javierluraschi . Tried this as well. Sharing the screen shot here. Just to bring a bit of perspective to the discussion, before going ahead with sparklyr, I had tried installing spark on my system through CMD. I just hope that there is no contention between the two.
![image](https://cloud.githubusercontent.com/assets/11004504/22995556/58905e86-f3f1-11e6-8cfe-01f2c85b8bc2.png)

**Comment by javierluraschi** [comment]
@FinScience Great! From the logs, the culprit is this:

`The trust relationship between this workstation and the primary domain failed.`

Some other community user already hit this problem, see: https://github.com/rstudio/sparklyr/issues/277

The fix for them was to leave and rejoin the domain.

**Comment by FinScience** [comment]
@javierluraschi , Thanks for going through the logs. I went through the entire discussion in #277,and deleted the file derby.txt and folder metastore_db from my working directory. Could you please be a bit more specific regarding leaving and rejoining the domain. I mean what exactly do I need to do in order to execute this.

**Comment by javierluraschi** [comment]
@FinScience couple question to help with the domain: Which version of windows you are using? Is this a personal computer or a work computer?

**Comment by javierluraschi** [comment]
@FinScience See this step-by-step approach from the Microsoft support article: https://support.microsoft.com/en-us/help/2771040/-the-trust-relationship-between-this-workstation-and-the-primary-domain-failed-error-when-you-log-on-to-a-computer-that-is-running-windows-7

**Comment by FinScience** [comment]
@javierluraschi . Thanks for the reply. However, I will not be able to do this since there are restrictions regarding this set by my employer. Still, thanks a lot for taking time to respond to my queries. Keep up the great work!!

**Comment by javierluraschi** [comment]
@FinScience thanks! I would mention your IT administrators that one of the applications you are using is hitting this error windows error: `FindFileOwnerAndPermissions error(1789): The trust relationship between this workstation and the primary domain failed.`, they would be better equipped to help you resolve this. Good luck!

**Comment by FinScience** [comment]
@javierluraschi - Thanks for the help. The issue has been resolved and I am able to create spark context. Hope to put this to good use :)

**Comment by javierluraschi** [comment]
@FinScience This is to great to hear! Would you mind sharing the resolution for this error `FindFileOwnerAndPermissions error(1789): The trust relationship between this workstation and the primary domain failed.`? What did you have to do to get past this problem?

I'm asking to help the rest of the community from your investigation.

**Comment by FinScience** [comment]
HI,

The trick was leaving and joining the domian again.

Thanks

**Comment by javierluraschi** [comment]
For reference to the `sparklyr` community, to upgrade to this fix is enough to:

```
remove.packages("sparklyr")
install.packages("sparklyr")
```
