### ISSUE TITLE
ClassNotFoundException when running spark_connect

### ISSUE THREAD

**Issue by admoseremic** [rstudio/sparklyr#508]
Hi, just trying to follow the steps as per spark.rstudio.com, and I keep getting the following:

> sc = spark_connect(master="local")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (9497): Gateway in port (8880) did not respond.
    Path: /Users/tpaulsen/Library/Caches/spark/spark-1.6.2-bin-hadoop2.6/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --jars, '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/spark-csv_2.11-1.3.0.jar','/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/commons-csv-1.1.jar','/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/univocity-parsers-1.5.1.jar', '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 9497

---- Output Log ----
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/launcher/Main
Caused by: java.lang.ClassNotFoundException: org.apache.spark.launcher.Main
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

---- Error Log ----

I've tried installing multiple versions of spark, etc. but have not been able to get it to work.  Here's my version info:

> version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch

**Comment by edgararuiz** [comment]
Hi @admoseremic , did you set up you JAVA_HOME environment variable?

**Comment by admoseremic** [comment]
@edgararuiz : I think so.  Doing an echo $JAVA_HOME gives me /Library/Java/Home

**Comment by edgararuiz** [comment]
Can you try this?

```
spark_install(version = "2.1.0")
sc <- spark_connect(master = "local", version = "2.1.0")
```
Definitely pass the version you wish to use

**Comment by admoseremic** [comment]
Here's what I get:

`Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (4045): Gateway in port (8880) did not respond.
    Path: /Users/tpaulsen/Library/Caches/spark/spark-2.1.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.1-2.11.jar', 8880, 4045


---- Output Log ----
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

---- Error Log ----`

**Comment by javierluraschi** [comment]
@admoseremic See comment and resolution from https://github.com/rstudio/sparklyr/issues/306

> The error seems related to the Java version. Spark supports version 1.7+ and so does sparklyr. However, it's possible than some module is being loaded in your system compiled with Java 8 since version 51.0 is Java 7. Therefore, try installing Java 8 to try to solve this issue.
>
> See. http://stackoverflow.com/questions/28070863/spark-unsupported-class-version-error

**Comment by admoseremic** [comment]
@javierluraschi & @edgararuiz : Updating Java seems to have corrected my problem, thank you very much!  Perhaps the documentation on spark.rstudio.com could be updated to mention a Java update is recommended?

**Comment by edgararuiz** [comment]
That's a good point, we'll make the proper updates to the site.  Thanks
