### ISSUE TITLE
Sparklyr copy_to fails

### ISSUE THREAD

**Issue by OlivierDeruyver** [rstudio/sparklyr#525]
I am using the Sparklyr library to read and write data from R to HDFS. Reading data works as expected but writing gives issues.

To be able to use the spark_write_csv function, I need to convert my R data.frames into Spark objects. I use the sparklyr sdf_copy_to function for this (also tried with copy_to). However, I always get errors

Code:
```
table1 <- sdf_copy_to(sc,dataframe,OVERWRITE=TRUE)
spark_write_csv(table1, "path")
```
Error:

> `    Error: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://iacchadoopdev01.dap:8020/tmp/Rtmp2gpelH/spark_serialize_62547a7b0f9ad206fd384af04e585deb3a2636ca7b1f026943d4cc1d11c7759a.csv`

Did somebody encountered the same problem and knows how to solve this?

A possible reason might be that the sdf_copy_to function stores the data onto my linux /tmp folder while the write function is looking for data on the HDFS /tmp folder.

Thanks in Advance!

**Comment by Jordi-** [comment]
Same problem here! In my case I tried
  tb <- sdf_copy_to(sc, irirs)
and raises
  Error: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://localhost:9000/tmp/Rtmp5IsJmd/spark_serialize_9fd0bf1861994b0d294634211269ec9e591b014b83a5683f179dd18e7e70ef0b.csv;

**Comment by ths2o** [comment]
I also encountered same problem.
In my case, copy_to(sc, df) works on r studio but same code with 'Rscript' execution(like, Rscript bb.R) doesn't works and throw the error as you mentioned.
Error: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://localhost:9000/tmp/Rtmp7GOqHB/spark_serialize_aa3f31fce072ee17db5bb6fefeeb9332a5e33762470025c09b0325e15fbaf4e5.csv;

**Comment by jan-sterba** [comment]
same here

**Comment by jtbirdsell** [comment]
same

**Comment by jakubglinka** [comment]
same here :/

**Comment by kevinykuo** [comment]
Maybe we need to prefix `file:///` when we're in a Hadoop environment around here: https://github.com/rstudio/sparklyr/blob/041ebdfda9f1ab84a4c7a59a03d39bed64348e1b/R/data_copy.R#L20?

**Comment by kevinykuo** [comment]
Not able to reproduce. Could you guys share a little more about your setups?

**Comment by javierluraschi** [comment]
Will investigate before `sparklyr 0.6` release, please provide as much additional info as needed to help us troubleshoot/resolve this one, thanks!

**Comment by ths2o** [comment]
I've got some clues with this issues.

In case the environment variables related to the hadoop config(like HADOOP_CONF_DIR, HADOOP_HOME, HADOOP_PREFIX, YARN_CONF_DIR) is set, the hadoop host is attached to the tempdir address.

If I remove the configuration, then it works well

here's sample code.

If you set some hadoop config, then you will see the same message as i mentioned above.

###############################################
library(plyr)
library(dplyr)
library(sparklyr)

#HADOOP_CONF_DIR         /data01/hadoop/hadoop-2.7.1/etc/hadoop

Sys.setenv(HADOOP_CONF_DIR = "")
Sys.setenv(HADOOP_HOME = "")
Sys.setenv(HADOOP_PREFIX = "")
Sys.setenv(YARN_CONF_DIR = "")
Sys.getenv()

config <- spark_config()
config$spark.executor.cores = 2
config$spark.executor.memory = "4G"
config$spark.default.parallelism = 200
config$spark.dynamicAllocation.minExecutors=50
config$spark.dynamicAllocation.maxExecutors=100 
config$park.shuffle.memoryFraction=0.6 
config$spark.driver.memory="4G"
config$sparklyr.gateway.port = 8881

sc = spark_connect(master = "local", spark_home = "/data01/spark/spark-2.0.2-bin-hadoop2.7", config = config)

a = as.data.frame(cbind(c(1, 2,3), c(3,4,5)))

wrt3 = copy_to(sc, a, overwrite = TRUE)
wrt3%>%spark_write_parquet(path = "hdfs://[host]/user/R_COPY_TO_FAIL",
                           mode='overwrite')
###############################################

**Comment by jvicentem** [comment]
Same here

**Comment by jvicentem** [comment]
Now it works for me. I didn't configured correctly the driver's memory. I increased it and now everything works perfectly.

**Comment by javierluraschi** [comment]
@OlivierDeruyver @jakubglinka @jtbirdsell @jan-sterba @ths2o @Jordi- Taking a look at this one, could one of you share your `spark_connect` call? My guess is that this is triggering under `yarn-client`, is this the case? Which version of `sparklyr`? CRAN or devel? Could one of you share `sessionInfo()`? Thanks.

**Comment by Wfore0990** [comment]
Hello,

I've recently inherited a docker project which is running into this error.  I've pared down as much excess as I can while maintaining the error and pushed the project to a repository.

[https://github.com/Wfore0990/sparklyrerror](https://github.com/Wfore0990/sparklyrerror)

I'm building and running the docker project using the Docker client on macOS Sierra 10.12.5.

I will also post my sessionInfo() report in the event that it is at all helpful to @javierluraschi :

```R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0    sparklyr_0.5.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     withr_1.0.2     digest_0.6.12   rprojroot_1.2   assertthat_0.1  R6_2.2.0        jsonlite_1.3   
 [8] DBI_0.5-1       backports_1.0.5 magrittr_1.5    httr_1.2.1      config_0.2      tools_3.3.2     yaml_2.1.14    
[15] parallel_3.3.2  base64enc_0.1-3 tibble_1.2 ```

This is relatively new territory for me, but if there is any more info I can provide or elaborate upon to be of any further help in solving this issue, please let me know.  Thanks!

**Comment by kevinykuo** [comment]
@Wfore0990 could you test this: `devtools::install_github("kevinykuo/sparklyr@5a4d24fd95bc95796fbca116e18f9490e238a78f")`

**Comment by Wfore0990** [comment]
@kevinykuo the issue appears to persist with the same error. 
Here is the error response I get to the command ``` faithful_tbl <- copy_to(sc, faithful, "faithful") ```

```
Error: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://hadoop:9000/tmp/RtmpqkobXg/spark_serialize_b59ca47eb7d16528008bad86385e41905874aebd94086c16c5479a29fd2f9588.csv;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:390)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:379)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:379)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:413)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
```
