### ISSUE TITLE
* No rows dropped by 'na.omit' call

### ISSUE THREAD

**Issue by NachoGar** [rstudio/sparklyr#563]
I'm following the manual and I do not know what's wrong

library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local",version = "2.1.0")
iris_tbl <- copy_to(sc, iris,"iris", overwrite = T)
iris_tbl
kmeans_model <- iris_tbl %>% 
  select(Petal_Width,Petal_Length) %>%
  ml_kmeans(centers = 3)

* No rows dropped by 'na.omit' call
Error: java.lang.IllegalArgumentException: invalid method computeCost for object 207
	at sparklyr.Invoke$.invoke(invoke.scala:113)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)

**Comment by kevinushey** [comment]
Try invoking `ml_kmeans()` with `compute.cost = FALSE`. I do not know why it fails on your machine; are you sure that you're using Spark 2.1.0?

**Comment by duttashi** [comment]
@NachoGar, The following code works for me 

```
> sc <- spark_connect(master = "local", version="2.1.0")
> iris_tbl <- copy_to(sc, iris,"iris", overwrite = T)
> kmeans_model <- iris_tbl %>%
+   select(Petal_Width,Petal_Length) %>%
+   ml_kmeans(centers = 3)
* No rows dropped by 'na.omit' call
> kmeans_model
K-means clustering with 3 clusters

Cluster centers:
  Petal_Width Petal_Length
1    1.359259     4.292593
2    0.246000     1.462000
3    2.047826     5.626087

Within Set Sum of Squared Errors =  31.41289
```

My session info is;
```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
other attached packages:
[1] sparklyr_0.5.6-9011 dplyr_0.7.1   
```

**Comment by javierluraschi** [comment]
As Kevin points out, verify that `spark_version(sc)` returns `2.1.0` and troubleshoot this otherwise. The problem could be that an Spark version already exists and `SPARK_HOME` is somehow overriding the version specified during `spark_connect()`
