### ISSUE TITLE
investigate test warnings / failures

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#589]
```
$ ./run-tests
==> Running tests with Spark 2.1.0 ...
Loading sparklyr
Loading required package: testthat
Testing sparklyr
dplyr do: .........................................................
dplyr: .......
feature transformers: .................S
install: ................................................................
invoke: .............
glm: ..
clustering: .
lm: ....................................
saveload: .WW1
naive bayes: .
pivot: ...
read-write: .
serialization: .....S2SS

Skipped ------------------------------------------------------------------------
1. ft_quantile_discretizer() works with basic input (@test-feature-transformers.R#100) - Empty test

2. data.frames with many columns don't cause Java StackOverflows (@test-serialization.R#85) - Skipping slow serialization test

3. copy_to() succeeds when last column contains missing / empty values (@test-serialization.R#118) - Empty test

4. newlines are properly serialized / deserialized (@test-serialization.R#131) - NYI

Warnings -----------------------------------------------------------------------
1. we can save + load tables using the various save/load APIs (@test-ml-saveload.R#42) - 'writer' is deprecated.
Use 'spark_write_table' instead.
See help("Deprecated")

2. we can save + load tables using the various save/load APIs (@test-ml-saveload.R#43) - 'reader' is deprecated.
Use 'spark_read_table' instead.
See help("Deprecated")

Failed -------------------------------------------------------------------------
1. Error: we can save + load tables using the various save/load APIs (@test-ml-saveload.R#43)
org.apache.spark.sql.catalyst.analysis.NoSuchTableException: Table or view '17b05504fb219' not found in database 'default';
        at org.apache.spark.sql.hive.client.HiveClient$$anonfun$getTable$1.apply(HiveClient.scala:76)
        at org.apache.spark.sql.hive.client.HiveClient$$anonfun$getTable$1.apply(HiveClient.scala:76)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.hive.client.HiveClient$class.getTable(HiveClient.scala:76)
        at org.apache.spark.sql.hive.client.HiveClientImpl.getTable(HiveClientImpl.scala:78)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable$1.apply(HiveExternalCatalog.scala:110)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable$1.apply(HiveExternalCatalog.scala:110)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
        at org.apache.spark.sql.hive.HiveExternalCatalog.org$apache$spark$sql$hive$HiveExternalCatalog$$getRawTable(HiveExternalCatalog.scala:109)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:601)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:601)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:95)
        at org.apache.spark.sql.hive.HiveExternalCatalog.getTable(HiveExternalCatalog.scala:600)
        at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:106)
        at org.apache.spark.sql.hive.HiveSessionCatalog.lookupRelation(HiveSessionCatalog.scala:69)
        at org.apache.spark.sql.DataFrameReader.table(DataFrameReader.scala:473)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sparklyr.Invoke$.invoke(invoke.scala:96)
        at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
        at sparklyr.StreamHandler$.read(stream.scala:55)
        at sparklyr.BackendHandler.channelRead0(handler.scala:49)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
1: reader(sc, nameCopy, path) at /Users/kevin/r/pkg/sparklyr/tests/testthat/test-ml-saveload.R:43
2: spark_read_table(sc, name, options, repartition, memory, overwrite) at /Users/kevin/r/pkg/sparklyr/R/data_interface.R:392
3: spark_data_read_generic(sc, name, "table", options) at /Users/kevin/r/pkg/sparklyr/R/data_interface.R:370
4: invoke(options, fileMethod, path) at /Users/kevin/r/pkg/sparklyr/R/data_interface.R:317
5: invoke.shell_jobj(options, fileMethod, path) at /Users/kevin/r/pkg/sparklyr/R/spark_invoke.R:33
6: invoke_method(spark_connection(jobj), FALSE, jobj, method, ...) at /Users/kevin/r/pkg/sparklyr/R/spark_shell.R:556
7: invoke_method.spark_shell_connection(spark_connection(jobj), FALSE, jobj, method,
       ...) at /Users/kevin/r/pkg/sparklyr/R/spark_invoke.R:62
8: withr::with_options(list(warning.length = 8000), {
       if (nzchar(msg))
           stop(msg, call. = FALSE)
       else {
           msg <- read_spark_log_error(sc)
           stop(msg, call. = FALSE)
       }
   }) at /Users/kevin/r/pkg/sparklyr/R/spark_shell.R:446
9: force(code)
10: stop(msg, call. = FALSE) at /Users/kevin/r/pkg/sparklyr/R/spark_shell.R:449

2. Error: 'sdf_predict()', 'predict()' return same results (@test-serialization.R#104)
unable to find an inherited method for function ‘dbQuoteString’ for signature ‘"spark_connection", "character"’
1: predict(model) at /Users/kevin/r/pkg/sparklyr/tests/testthat/test-serialization.R:104
2: predict.ml_model(model)
3: sdf_read_column(arranged, "prediction") at /Users/kevin/r/pkg/sparklyr/R/ml_utils.R:119
4: spark_dataframe(x) at /Users/kevin/r/pkg/sparklyr/R/sdf_wrapper.R:71
5: spark_dataframe.tbl_spark(x) at /Users/kevin/r/pkg/sparklyr/R/spark_dataframe.R:13
6: sql_render(sql_build(x, con = sc), con = sc) at /Users/kevin/r/pkg/sparklyr/R/sdf_wrapper.R:9
7: sql_build(x, con = sc) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-render.R:4
8: sql_build.tbl_lazy(x, con = sc) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-build.R:26
9: sql_build(op$ops, con = con, ...) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-build.R:32
10: sql_build.op_arrange(op$ops, con = con, ...) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-build.R:26
...
13: lapply(.x, .f, ...) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/compat-purrr.R:10
14: FUN(X[[i]], ...)
15: escape(get_expr(x), con = con) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/translate-sql.r:134
16: escape.character(get_expr(x), con = con) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-escape.r:95
17: sql_vector(sql_escape_string(con, x), parens, collapse, con = con) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-escape.r:131
18: sql_escape_string(con, x) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-escape.r:173
19: sql_escape_string.DBIConnection(con, x) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e55a678f8e/hadley-dplyr-67bf4b9/R/dbplyr.R:180
20: dbQuoteString(con, x) at /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0OrtJY/devtools172e5766ffce1/hadley-dbplyr-44772f1/R/sql-generic.R:177
21: (function (classes, fdef, mtable)
   {
       methods <- .findInheritedMethods(classes, fdef, mtable)
       if (length(methods) == 1L)
           return(methods[[1L]])
       else if (length(methods) == 0L) {
           cnames <- paste0("\"", vapply(classes, as.character, ""), "\"", collapse = ", ")
           stop(gettextf("unable to find an inherited method for function %s for signature %s",
               sQuote(fdef@generic), sQuote(cnames)), domain = NA)
       }
       else stop("Internal error in finding inherited methods; didn't return a unique method",
           domain = NA)
   })(list("spark_connection", "character"), structure(function (conn, x, ...)
   standardGeneric("dbQuoteString"), generic = structure("dbQuoteString", package = "DBI"), package = "DBI", group = list(), valueClass = character(0), signature = c("conn",
   "x"), default = `\001NULL\001`, skeleton = (function (conn, x, ...)
   stop("invalid call in method dispatch to 'dbQuoteString' (no default method)", domain = NA))(conn,
       x, ...), class = structure("standardGeneric", package = "methods")), <environment>)
22: stop(gettextf("unable to find an inherited method for function %s for signature %s",
       sQuote(fdef@generic), sQuote(cnames)), domain = NA)

DONE ===========================================================================
```

**Comment by albit3** [comment]
Hey Kevin,

Everything seems to work fine following the tutorial at the spark.studio.com

However, I get this error message every time I create a spark object. This is while following the tutorial from the website step by step. The first time it appears is when I run the following code:

library(dplyr)
iris_tbl <- copy_to(sc, iris)


![unexpected_data_type](https://cloud.githubusercontent.com/assets/26827080/24583856/b5b29158-1726-11e7-9376-9fec5e01d159.jpeg)

Thanks,

Albit
