### ISSUE TITLE
Google Dataproc: Certain error conditions cause a hang in the command

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#59]
Using sparklyr 0.2.9 (but not new to this version)
- Bring up Google Dataproc Spark/Hadoop cluster
  I am using n1-standard-2, 7.5G RAM, 1 master and 2 worker nodes
  Not any change to the setup, expect for installing R,RSP, and packages
- Do the initial setup and connect to spark
  Note: I use `sc <- spark_connect(master = "yarn-client")` to connect. Connect using the hostname as master didn't work in this environment.
  Note: May be the configuration is not correct for our purposes, and leading to this issue. (I don't see this issue on the AWS cluster)
- As an example, running the following command to read a valid s3 path works fine after initial environment setup:

```
dpd <- spark_read_csv(sc, "dpd", "s3n://dallas-police/current.csv")
```

but if I change that to use an invalid bucket:

```
dpd1 <- spark_read_csv(sc, "dpd", "s3n://dallas-police1/current.csv")
```

then the command just hangs. I have waited for 10 minutes, nothing happened. At this point if you cancel the command then nothing else, even spark_disconnect wouldn't work.

I have seen this issue with some valid commands that for some reason didn't work in this environment. But here I am used an invalid command that should return an error pretty quickly.

There is no info in the log when I run spark_log(sc).

**Comment by javierluraschi** [comment]
To reproduce this locally:

```
Sys.setenv(AWS_ACCESS_KEY_ID="...")
Sys.setenv(AWS_SECRET_ACCESS_KEY="...")

config <- spark_config()
config$sparklyr.defaultPackages[[3]] <- "org.apache.hadoop:hadoop-aws:2.6.0"
sc <- spark_connect(master = "local", config = config)
dpd1 <- spark_read_csv(sc, "dpd", "s3n://dallas-police1/current.csv”)
```

**Comment by javierluraschi** [comment]
@fereshtehRS are we still hitting this issue with the latest versions of sparklyr and sparkapi?

I've ran this locally and hit the following error with the sample above:

```
dpd1 <- spark_read_csv(sc, "dpd", "s3n://dallas-police1/current.csv")
Error: org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.ServiceException: Service Error Message. -- ResponseCode: 404, ResponseStatus: Not Found, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>dallas-police1</BucketName><RequestId>7A2AE94C98CACBE7</RequestId><HostId>J96fYnW0gXxB48oZ56zfxerA1pLIifv4YXoh7ubHyC5gvlu7UZe4SOHxccnWRvpur6VF4z/k2bs=</HostId></Error>
```

which is what I would expect. If this is still an issue, could you please share by mail credentials and url to connect and debug this further? Thanks!

**Comment by fereshtehRS** [comment]
@javierluraschi This still happens with version 0.2.29.

The error you are seeing is correct, as this is not a valid path. But the issue on the Google cluster is that the error is never returned to user, command just hangs.

**Comment by fereshtehRS** [comment]
I tried it again on AWS cluster; it is returned immediately with error. Problem only on GCP.

**Comment by javierluraschi** [comment]
@fereshtehRS are other errors returning appropiately in GCP? For instance:

```
tbl(sc, "missing-table") %>% collect()
```

If this is specific to GCP and `spark_read_*` with custom storage providers, it is likely an issue in GCP that we might be better off waiting for a fix than providing a workaround, specially since this is an error case and does not block usage.

**Comment by fereshtehRS** [comment]
That one returns quickly. I tried few other ones. Everything except `s3` interactions returns quickly. You are probably correct that this might be an issue with GCP. We can definitely wait for a fix; not a top priority.

**Comment by javierluraschi** [comment]
K. I'll mark this as feature request to improve integration with GCP, if needed, later on.

**Comment by ElianoMarques** [comment]
Hi @javierluraschi i'm also trying to connect to S3 and i'm facing some issues. 

```
Sys.setenv(AWS_ACCESS_KEY_ID = mykey)
Sys.setenv(AWS_SECRET_ACCESS_KEY = mysecret)
data <- spark_read_csv(sc, "data","s3n://path/path/input_data.csv")
```
I got the following error:

```
Error: java.io.IOException: No FileSystem for scheme: s3n
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2644)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:352)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:350)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:401)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

After researching quite a bit i cant found the potential error. Is this something you or somebody else have faced? 

Thank you, Eliano

**Comment by ElianoMarques** [comment]
I solve this in python with this: 
```
#Read the dataset
hadoopConf = sc._jsc.hadoopConfiguration()
hadoopConf.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
```

**Comment by javierluraschi** [comment]
Thanks for the comments Eliano, closing this one since we haven't heard of any issues in Google Dataproc for a while.
