### ISSUE TITLE
How to create Array of `PipelineStage`?

### ISSUE THREAD

**Issue by chezou** [rstudio/sparklyr#593]
I'm trying to write [Spark.ml pipeline code](https://spark.apache.org/docs/latest/ml-tuning.html#cross-validation) with sparklyr, but it returns an error. How can I instantiate Array like `new PipelineStage[]`?

Code:

```r
lazy_tokenizer <- invoke_new(sc, "org.apache.spark.ml.feature.Tokenizer") %>%
  invoke("setInputCol", ensure_scalar_character("text")) %>%
  invoke("setOutputCol", ensure_scalar_character("tokens"))

output_col <- lazy_tokenizer %>% invoke("getOutputCol")

lazy_hasher <- invoke_new(sc, "org.apache.spark.ml.feature.HashingTF") %>%
  invoke("setInputCol", output_col) %>%
  invoke("setOutputCol", "features")

lr <- invoke_new(sc, "org.apache.spark.ml.classification.LogisticRegression") %>%
  invoke("setMaxIter", ensure_scalar_integer(10))

pipeline <- invoke_new(sc, "org.apache.spark.ml.Pipeline") %>%
  invoke("setStages", list(lazy_tokenizer, lazy_hasher, lr))
```

Error:

```java
Error: java.lang.Exception: No matched method found for class org.apache.spark.ml.Pipeline.setStages
	at sparklyr.Invoke$.invoke(invoke.scala:93)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745) 
```

**Comment by kevinushey** [comment]
Good question -- I'm not sure if we expose a method for easily creating arrays from an R list of Spark objects. I think it might be worth implementing something for this, e.g. a `spark_array(...)` function that creates an array given one or more objects.

**Comment by chezou** [comment]
I understand we should write some grew code between R and Spark to handling Array including inherited class.

**Comment by kevinykuo** [comment]
Tracking in https://github.com/rstudio/sparklyr/issues/944

**Comment by kevinykuo** [comment]
@chezou this has been implemented in devel:

```
pipeline <- ml_pipeline(sc) %>%
  ft_tokenizer("text", "tokens") %>%
  ft_hashing_tf("tokens", "features") %>%
  ml_logistic_regression(max_iter = 10)
> pipeline
Pipeline (Estimator) with 3 stages
<pipeline_58c17d385f3f>
  Stages
|--1 Tokenizer (Transformer)
|    <tokenizer_58c146c8901f>
|     (Parameters -- Column Names)
|      input_col: text
|      output_col: tokens
|--2 HashingTF (Transformer)
|    <hashing_tf_58c16b03d1c>
  |     (Parameters -- Column Names)
|      input_col: tokens
|      output_col: features
|--3 LogisticRegression (Estimator)
|    <logistic_regression_58c1100b18ba>
|     (Parameters -- Column Names)
|      features_col: features
|      label_col: label
|      prediction_col: prediction
|      probability_col: probability
|      raw_prediction_col: rawPrediction
|     (Parameters)
|      aggregation_depth: 2
|      elastic_net_param: 0
|      family: auto
|      fit_intercept: TRUE
|      max_iter: 10
|      reg_param: 0
|      standardization: TRUE
|      threshold: 0.5
|      tol: 1e-06
```

**Comment by chezou** [comment]
@kevinykuo Great job! Thanks for your efforts. Will try it 😄
