### ISSUE TITLE
Could not locate executable winutils.exe in the Hadoop binaries

### ISSUE THREAD

**Issue by AlexYoung757** [rstudio/sparklyr#600]
Hello,

After I install sparklyr packages, I got an error message below. Does anyone know how to resolve this problem? Thanks a lot.

17/04/05 12:46:26 INFO SparkContext: Running Spark version 2.0.1
17/04/05 12:46:26 ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
	at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:379)
	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:394)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:387)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.security.SecurityUtil.getAuthenticationMethod(SecurityUtil.java:611)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:273)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:261)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:791)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2265)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2265)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2265)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:294)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2275)
	at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
17/04/05 12:46:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/04/05 12:46:26 INFO SecurityManager: Changing view acls to: AlexYung
17/04/05 12:46:26 INFO SecurityManager: Changing modify acls to: AlexYung
17/04/05 12:46:26 INFO SecurityManager: Changing view acls groups to: 
17/04/05 12:46:26 INFO SecurityManager: Changing modify acls groups to: 
17/04/05 12:46:26 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(AlexYung); groups with view permissions: Set(); users  with modify permissions: Set(AlexYung); groups with modify permissions: Set()
17/04/05 12:46:26 INFO Utils: Successfully started service 'sparkDriver' on port 50708.
17/04/05 12:46:26 INFO SparkEnv: Registering MapOutputTracker
17/04/05 12:46:26 INFO SparkEnv: Registering BlockManagerMaster
17/04/05 12:46:26 INFO DiskBlockManager: Created local directory at C:\Users\AlexYung\AppData\Local\Temp\blockmgr-318ecf58-0ac6-4bee-9644-993cbcbab99d
17/04/05 12:46:26 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
17/04/05 12:46:26 INFO SparkEnv: Registering OutputCommitCoordinator
17/04/05 12:46:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/04/05 12:46:26 INFO SparkUI: Bound SparkUI to 127.0.0.1, and started at http://127.0.0.1:4040
17/04/05 12:46:27 INFO SparkContext: Added JAR file:/D:/R-3.3.3/library/sparklyr/java/sparklyr-2.0-2.11.jar at spark://127.0.0.1:50708/jars/sparklyr-2.0-2.11.jar with timestamp 1491367587001
17/04/05 12:46:27 INFO Executor: Starting executor ID driver on host localhost
17/04/05 12:46:27 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 50730.
17/04/05 12:46:27 INFO NettyBlockTransferService: Server created on 127.0.0.1:50730
17/04/05 12:46:27 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 127.0.0.1, 50730)
17/04/05 12:46:27 INFO BlockManagerMasterEndpoint: Registering block manager 127.0.0.1:50730 with 366.3 MB RAM, BlockManagerId(driver, 127.0.0.1, 50730)
17/04/05 12:46:27 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 127.0.0.1, 50730)
17/04/05 12:46:27 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
17/04/05 12:46:27 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
17/04/05 12:46:27 INFO HiveSharedState: Warehouse path is 'C:UsersAlexYungAppDataLocal
studiosparkCachespark-2.0.1-bin-hadoop2.7	mphive'.
17/04/05 12:46:27 INFO SparkSqlParser: Parsing command: SHOW TABLES
17/04/05 12:46:27 INFO HiveUtils: Initializing HiveMetastoreConnection version 1.2.1 using Spark classes.
17/04/05 12:46:28 INFO HiveMetaStore: 0: Opening raw store with implemenation class:org.apache.hadoop.hive.metastore.ObjectStore
17/04/05 12:46:28 INFO ObjectStore: ObjectStore, initialize called
17/04/05 12:46:28 INFO Persistence: Property hive.metastore.integral.jdo.pushdown unknown - will be ignored
17/04/05 12:46:28 INFO Persistence: Property datanucleus.cache.level2 unknown - will be ignored
17/04/05 12:46:29 INFO ObjectStore: Setting MetaStore object pin classes with hive.metastore.cache.pinobjtypes="Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order"
17/04/05 12:46:30 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
17/04/05 12:46:30 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
17/04/05 12:46:30 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MFieldSchema" is tagged as "embedded-only" so does not have its own datastore table.
17/04/05 12:46:30 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MOrder" is tagged as "embedded-only" so does not have its own datastore table.
17/04/05 12:46:31 INFO MetaStoreDirectSql: Using direct SQL, underlying DB is DERBY
17/04/05 12:46:31 INFO ObjectStore: Initialized ObjectStore
17/04/05 12:46:31 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
17/04/05 12:46:31 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
17/04/05 12:46:31 INFO HiveMetaStore: Added admin role in metastore
17/04/05 12:46:31 INFO HiveMetaStore: Added public role in metastore
17/04/05 12:46:31 INFO HiveMetaStore: No user is added in admin role, since config is empty
17/04/05 12:46:31 INFO HiveMetaStore: 0: get_all_databases
17/04/05 12:46:31 INFO audit: ugi=AlexYung	ip=unknown-ip-addr	cmd=get_all_databases	
17/04/05 12:46:31 INFO HiveMetaStore: 0: get_functions: db=default pat=*
17/04/05 12:46:31 INFO audit: ugi=AlexYung	ip=unknown-ip-addr	cmd=get_functions: db=default pat=*	
17/04/05 12:46:31 INFO Datastore: The class "org.apache.hadoop.hive.metastore.model.MResourceUri" is tagged as "embedded-only" so does not have its own datastore table.

**Comment by javierluraschi** [comment]
@AlexYoung757 Probably missing permissions to run this in your particular system? Have you tried running as admin? I would also try with latest version of `sparklyr` using:

```
devtools::install_github("rstudio/sparklyr")
```

Does the `winutils.exe` file exist under the following list of files?

```r
dir(file.path(spark_home_dir(), "tmp", "hadoop"))
```

Please feel free to open a new github issue to help troubleshoot, alternatively, you might want to find me in https://gitter.im/rstudio/sparklyr to help troubleshoot this realtime.

**Comment by AlexYoung757** [comment]
@javierluraschi thank you for your help , i have solved this problem.

**Comment by AlexYoung757** [comment]
@javierluraschi thanks for your help , i have solved this problem. i find that if we download the hadoop from rstudio , the "winutils.exe" file will miss. so  you should add the "winutils" that fit for same version of hadoop
