### ISSUE TITLE
Unable to convert data.frame to SparkR format using as.DataFrame

### ISSUE THREAD

**Issue by dianegal** [rstudio/sparklyr#691]
I have not been able to convert an R data.frame to a SparkR format using as.DataFrame and get the following error:
 df <- as.DataFrame(documents)
Error in handleErrors(returnStatus, conn) : 
  java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionState':
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$reflect(SparkSession.scala:981)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:110)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:109)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:62)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:552)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:307)
	at org.apache.spark.sql.api.r.SQLUtils$.createDF(SQLUtils.scala:139)
	at org.apache.spark.sql.api.r.SQLUtils.createDF(SQLUtils.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.ref

Any suggestions on how to fix this issue would be appreciated.  Thanks.

**Comment by kevinykuo** [comment]
Welcome to sparklyr! Here's a resource to get you started: https://github.com/rstudio/sparklyr/blob/master/README.md

**Comment by javierluraschi** [comment]
Closing since this is a `sparkR` question. In `sparklyr` you want to use `copy_to(sc, documents)`.
