### ISSUE TITLE
spark_apply not working with sdf_repartition

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#737]
From @kevinykuo:

```
iris_tbl <- copy_to(sc, iris) %>%
  sdf_repartition(2L)

spark_apply(iris_tbl, function(data) {
  data[1:4] + rgamma(1,2)
})

 Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 8.0 failed 1 times, most recent failure: Lost task 1.0 in stage 8.0 (TID 8, localhost, executor driver): java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:51)
	at sparklyr.WorkerRDD$$anon$2.run(rdd.scala:79)
```

**Comment by kevinykuo** [comment]
This is now working for some reason (also works with `memory = FALSE`). Let's leave open until we have a test?

**Comment by javierluraschi** [comment]
Looks fixed by https://github.com/rstudio/sparklyr/pull/883, can't repro this anymore.
