### ISSUE TITLE
logistic multinomial model training errors-out

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#748]
Attempting to build a `ml_logistic_regression` errors-out with `sparklyr`.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.5.6'
sc <- spark_connect(master= 'local',
                    version = '2.1.0')
d <- data.frame(x=1:9,
                y=rep(c('a','b','c'),3))
d <- copy_to(sc, d, 'd')
model <- ml_logistic_regression(d, y~x)
#> * No rows dropped by 'na.omit' call
#> Error: org.apache.spark.SparkException: Multinomial models contain a matrix of coefficients, use coefficientMatrix instead.
#>  at org.apache.spark.ml.classification.LogisticRegressionModel.coefficients(LogisticRegression.scala:707)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:94)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
#>  at sparklyr.StreamHandler$.read(stream.scala:55)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:49)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:745)
```

Seems to work okay for binary classification:

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.5.6'
sc <- spark_connect(master= 'local',
                    version = '2.1.0')
d <- data.frame(x=1:8,
                y=rep(c('a','b'),4))
d <- copy_to(sc, d, 'd')
model <- ml_logistic_regression(d, y~x)
#> * No rows dropped by 'na.omit' call
model
#> Call: y ~ x
#> 
#> Coefficients:
#> (Intercept)           x 
#>  -0.8822487   0.1960550
```

Also fails for `sparklyr` `0.5.4` with `dplyr` `0.5.0`.

```r
# install.packages("~/Downloads/dplyr_0.5.0.tar.gz", repos = NULL)
# install.packages("~/Downloads/sparklyr_0.5.4.tar.gz", repos = NULL)
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.5.0'
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.5.4'
sc <- spark_connect(master= 'local',
                    version = '2.1.0')
d <- data.frame(x=1:9,
                y=rep(c('a','b','c'),3))
d <- copy_to(sc, d, 'd')
model <- ml_logistic_regression(d, y~x)
#> * No rows dropped by 'na.omit' call
#> Error: org.apache.spark.SparkException: Multinomial models contain a matrix of coefficients, use coefficientMatrix instead.
#>  at org.apache.spark.ml.classification.LogisticRegressionModel.coefficients(LogisticRegression.scala:707)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:94)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
#>  at sparklyr.StreamHandler$.read(stream.scala:55)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:49)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:745)
model
#> Error in eval(expr, envir, enclos): object 'model' not found
```

**Comment by kevinushey** [comment]
Thanks for the bug report! I'll take a look and see if this is something we can enable without too much fuss.

**Comment by kevinushey** [comment]
This should be implemented now (available in the development version). If you have time to play around with it, please let us know if you encounter any issues!
