### ISSUE TITLE
Some Scala exceptions cause backend to not return a status and crash r session

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#780]
Create the following scala object and compile with `sparklyr`

```scala
object WorkerContext2 {
  def setResultArraySeq3(resultParam: Array[Any]) : String = {
    resultParam.map(x => x.asInstanceOf[Array[Any]])

    ""
  }
}
```

Run:

```r
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.1.0")

testlist <- list(structure(list(Hit = "True", Project = "Blue", Year = "2011", Rating = "4", Launch = "26 Jan 2012", ID = "19", Dept = "1, 2, 4"),
                           .Names = c("Hit","Project", "Year", "Rating", "Launch", "ID", "Dept")),
                 structure(list(Hit = "False", Error = "Record not found"), .Names = c("Hit","Error")),
                 structure(list(Hit = "True", Project = "Green", Year = "2004",  Rating = "8", Launch = "29 Feb 2004", ID = "183", Dept = "6, 8"), .Names = c("Hit", "Project", "Year", "Rating", "Launch", "ID", "Dept")))

testdf <- bind_rows(testlist)

r2 <- testdf[2]
d2 <- lapply(1:nrow(r2), function(i) as.list(r2[i,]))

invoke_static(sc, "sparklyr.WorkerContext2", "setResultArraySeq3", d2)
```

Notice:

```
Error in core_invoke_method(sc, static, object, method, ...) : 
  No status is returned. The sparklyr backend might have failed.
```

From logs:

```
17/06/23 09:10:54 ERROR sparklyr: Backend (6023) failed calling exceptionString on sparklyr.Utils
java.lang.OutOfMemoryError: Java heap space
	at sparklyr.Serializer$.readStringBytes(serializer.scala:90)
	at sparklyr.Serializer$.readString(serializer.scala:99)
	at sparklyr.Serializer$$anonfun$readStringArr$1.apply(serializer.scala:141)
	at sparklyr.Serializer$$anonfun$readStringArr$1.apply(serializer.scala:141)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.Serializer$.readStringArr(serializer.scala:141)
	at sparklyr.Serializer$.readArray(serializer.scala:149)
	at sparklyr.Serializer$$anonfun$readArray$2.apply(serializer.scala:156)
	at sparklyr.Serializer$$anonfun$readArray$2.apply(serializer.scala:156)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.Serializer$.readArray(serializer.scala:156)
	at sparklyr.Serializer$.readTypedObject(serializer.scala:55)
	at sparklyr.Serializer$.readObject(serializer.scala:41)
	at sparklyr.StreamHandler$$anonfun$readArgs$1.apply(stream.scala:114)
	at sparklyr.StreamHandler$$anonfun$readArgs$1.apply(stream.scala:113)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.StreamHandler$.readArgs(stream.scala:113)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:96)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
```

Run a few more times, usually once or twice is enough:

```r
invoke_static(sc, "sparklyr.WorkerContext2", "setResultArraySeq3", list("A", NA, "B"))
```

**R Session Aborted**

Crash under [R_SockWrite](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/modules/internet/Rsock.c#L547-L570):

<img width="1188" alt="screen shot 2017-06-22 at 5 42 02 pm" src="https://user-images.githubusercontent.com/3478847/27490946-21443656-57f5-11e7-9aac-a304136aaf24.png">

**Comment by javierluraschi** [comment]
Easier repro:

```
naChar <- NA
class(naChar) <- "character")
d2 <- list(list("A"), list(naChar), list("b"))

invoke_static(sc, "sparklyr.WorkerContext2", "setResultArraySeq3", d2)
```

**Comment by javierluraschi** [comment]
Fixed with https://github.com/rstudio/sparklyr/pull/781; however, my guess is that the r session issue is still reproducible with something like:

```scala
object TerminateHelper {
  def throwCritical() : String = {
    throw classOf[OutOfMemoryError]
  }
}
```

```r
invoke_static(sc, "sparklyr.TerminateHelper", "throwCritical")
```

worth investigating this at some point...
