### ISSUE TITLE
Crash on r-session after serializing bad strings or critical Spark exceptions

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#785]
Follow up from https://github.com/rstudio/sparklyr/issues/780.

There are a few instances where something bad happens in Spark (see https://github.com/rstudio/sparklyr/issues/783 and https://github.com/rstudio/sparklyr/issues/780) which follows a termination of the backend and the r-session crashing while reading from the socket.

With this helper function...

```
spark_serialize_bad_string <- function(sc) {
  rc <- rawConnection(raw(), "r+")
  sparklyr:::writeString(rc, "sparklyr.SQLUtils")
  sparklyr:::writeBoolean(rc, TRUE)
  sparklyr:::writeString(rc, "getSQLDataType")

  # write args
  sparklyr:::writeInt(rc, 1)
  sparklyr:::writeType(rc, "character")
  utfVal <- enc2utf8("test")
  sparklyr:::writeInt(rc, as.integer(4)) # giant string should cause OOM
  writeBin(utfVal, rc, endian = "big", useBytes = TRUE)

  bytes <- rawConnectionValue(rc)
  close(rc)

  rc <- rawConnection(raw(0), "r+")
  sparklyr:::writeInt(rc, length(bytes))
  writeBin(bytes, rc)
  con <- rawConnectionValue(rc)
  close(rc)

  backend <- sc$backend
  writeBin(con, backend)

  returnStatus <- sparklyr:::readInt(backend)

  if (length(returnStatus) == 0)
    stop("No status is returned. The sparklyr backend might have failed.")
  if (returnStatus != 0) {
    # get error message from backend and report to R
    msg <- sparklyr:::readString(backend)
    withr::with_options(list(
      warning.length = 8000
    ), {
      stop(msg, call. = FALSE)
    })
  }
}
```

connect,

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.1.0")
```

and then running the following a few times will crash the r-session...

```
spark_serialize_bad_string(sc)
```

logs...

```
17/06/26 12:22:39 INFO audit: ugi=javierluraschi	ip=unknown-ip-addr	cmd=get_tables: db=default pat=*	
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at sparklyr.Serializer$.readStringBytes(serializer.scala:92)
	at sparklyr.Serializer$.readString(serializer.scala:99)
	at sparklyr.Serializer$.readTypedObject(serializer.scala:52)
	at sparklyr.Serializer$.readObject(serializer.scala:41)
	at sparklyr.StreamHandler$$anonfun$readArgs$1.apply(stream.scala:114)
	at sparklyr.StreamHandler$$anonfun$readArgs$1.apply(stream.scala:113)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sparklyr.StreamHandler$.readArgs(stream.scala:113)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:96)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
17/06/26 12:23:25 INFO sparklyr: Gateway (3056) is terminating
17/06/26 12:23:25 INFO SparkContext: Invoking stop() from shutdown hook
17/06/26 12:23:25 INFO SparkUI: Stopped Spark web UI at http://127.0.0.1:4040
17/06/26 12:23:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/06/26 12:23:25 INFO MemoryStore: MemoryStore cleared
17/06/26 12:23:25 INFO BlockManager: BlockManager stopped
17/06/26 12:23:25 INFO BlockManagerMaster: BlockManagerMaster stopped
17/06/26 12:23:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/06/26 12:23:25 INFO SparkContext: Successfully stopped SparkContext
17/06/26 12:23:25 INFO ShutdownHookManager: Shutdown hook called
17/06/26 12:23:25 INFO ShutdownHookManager: Deleting directory /private/var/folders/fz/v6wfsg2x1fb1rw4f6r0x4jwm0000gn/T/spark-726843e5-077e-4550-b785-60945010ab80
```

**Comment by javierluraschi** [comment]
<img width="1139" alt="screen shot 2017-06-26 at 12 20 27 pm" src="https://user-images.githubusercontent.com/3478847/27556311-ebaee62c-5a69-11e7-8d6c-a2fd53fe55bf.png">
