### ISSUE TITLE
Consider applying settings to shell and Spark Config automatically

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#808]
User reports that in `yarn` and using `sparkR` one can specify `spark.driver.memory`:

```r
sparkR.session(
  master="yarn",
  appName="BP-Dash :: user=%s",
  sparkHome="/usr/lib/spark",
  sparkConfig =list(
    spark.driver.memory="10g",
    spark.sql.shuffle.partitions="5000",
    spark.driver.maxResultSize="5000",
    spark.dynamicAllocation.enabled="true"
  )
)
```

`pyspark` does seem to require a special case of this parameter by passing it outside the `--conf` argument.

```python
pyspark --master yarn --driver-memory 10g --conf spark.sql.shuffle.partitions=5000 --conf spark.dynamicAllocation.enabled=true --conf spark.driver.maxResultSize=10000
```

However, in `sparklyr`, this is not very discoverable since users expect this to work:

```r
sc <- spark_connect(master = "yarn", app_name = "test", spark_home="/usr/lib/spark", config = list(
  spark.driver.memory="10g",
  spark.sql.shuffle.partitions="5000",
  spark.driver.maxResultSize="5000",
  spark.dynamicAllocation.enabled="true"
))
```

while this is needed instead:

```
r
sc <- spark_connect(master = "yarn", app_name = "test", spark_home="/usr/lib/spark", config = list(
`sparklyr.shell.spark.driver-memory`="10g",
spark.sql.shuffle.partitions="5000",
spark.driver.maxResultSize="5000",
spark.dynamicAllocation.enabled="true"
))
```

**Comment by statmatt** [comment]
FWIW I'm the "user" :-) 

The spark configurations need to be used as consistently as possible across all APIs to keep barriers to entry low.

**Comment by statmatt** [comment]
In fact, not sure the bottom level is working either:
`> sc <- spark_connect(master = "yarn", app_name = "test", spark_home="/usr/lib/spark", config = list(
+     `sparklyr.shell.spark.driver-memory`="10g",
+     spark.sql.shuffle.partitions="5000",
+     spark.driver.maxResultSize="5000",
+     spark.dynamicAllocation.enabled="true"
+ ))
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (8705): Gateway in port (8880) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --spark.driver-memory, 10g, --class, sparklyr.Shell, '/home/matt.anthony/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 8705
    Log: /tmp/RtmpBjm4sk/file1858958b31237_spark.log


---- Output Log ----
                              specified, this will look for conf/spark-defaults.conf.

  --driver-memory MEM         Memory for driver (e.g. 1000M, 2G) (Default: 1024M).
  --driver-java-options       Extra Java options to pass to the driver.
  --driver-library-path       Extra library path entries to pass to the driver.
  --driver-class-path         Extra class path entries to pass to the driver. Note that
                              jars added with --jars are automatically included in the
                              classpath.

  --executor-memory MEM       Memory per executor (e.g. 1000M, 2G) (Default: 1G).

  --proxy-user NAME           User to impersonate when submitting the application.
                              This argument does not work with --principal / --keytab.

  --help, -h                  Show this help message and exit.
  --verbose, -v               Print additional debug output.
  --version,                  Print the version of current Spark.

 Spark standalone with cluster deploy mode only:
  --driver-cores NUM          Cores for driver (Default: 1).

 Spark standalone or Mesos with cluster deploy mode only:
  --supervise                 If given, restarts the driver on failure.
  --kill SUBMISSION_ID        If given, kills the driver specified.
  --status SUBMISSION_ID      If given, requests the status of the driver specified.

 Spark standalone and Mesos only:
  --total-executor-cores NUM  Total cores for all executors.

 Spark standalone and YARN only:
  --executor-cores NUM        Number of cores per executor. (Default: 1 in YARN mode,
                              or all available cores on the worker in standalone mode)

 YARN-only:
  --driver-cores NUM          Number of cores used by the driver, only in cluster mode
                              (Default: 1).
  --queue QUEUE_NAME          The YARN queue to submit to (Default: "default").
  --num-executors NUM         Number of executors to launch (Default: 2).
                              If dynamic allocation is enabled, the initial number of
                              executors will be at least NUM.
  --archives ARCHIVES         Comma separated list of archives to be extracted into the
                              working directory of each executor.
  --principal PRINCIPAL       Principal to be used to login to KDC, while running on
                              secure HDFS.
  --keytab KEYTAB             The full path to the file that contains the keytab for the
                              principal specified above. This keytab will be copied to
                              the node running the Application Master via the Secure
                              Distributed Cache, for renewing the login tickets and the
                              delegation tokens periodically.
      

---- Error Log ----`

**Comment by javierluraschi** [comment]
@statmatt by bad, I think `g` is case sensitive (yet another thing to consider streamlining in `sparklyr` config).

```r
sc <- spark_connect(master = "yarn", app_name = "test", spark_home="/usr/lib/spark", config = list(
  `sparklyr.shell.spark.driver-memory`="10G",
  spark.sql.shuffle.partitions="5000",
  spark.driver.maxResultSize="5000",
  spark.dynamicAllocation.enabled="true"
))
```

**Comment by msolano00** [comment]
Hello @javierluraschi, I have been trying to use the proxy-user property:

```
# Import dependencies
library(DBI)
library(sparklyr)

options("sparklyr.verbose" = TRUE)

config <- spark_config()
config$`spark.yarn.queue` <- "adhoc-eoc"
config$`spark.yarn.am.cores` <- 1
config$`spark.executor.cores` <- 3
config$`sparklyr.shell.num-executors` <- 50
config$`sparklyr.shell.driver-cores` <- 1
config$`sparklyr.shell.driver-memory` <- "2G"
config$`spark.executor.memory` <- "9G"
config$`sparklyr.shell.proxy-user` <- "username"

sc <- spark_connect(
    master = "yarn-client",
    app_name = "sparklyr_impersonation_test",
    spark_home="/usr/hdp/current/spark-client",
    version = "1.6.2",
    config = config
)

hive_context(sc)
result <- dbGetQuery(sc, "show databases")
print(result)
```

But every time we run it we get the following hiveContext issue:

```
 Loading required package: methods
<jobj[14]>
  class org.apache.spark.sql.SQLContext
  org.apache.spark.sql.SQLContext@1fc2e0db
Warning messages:
1: In value[[3L]](cond) : java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:249)
        at org.apache.spark.sql.hive.HiveContext.metadataHive$lzycompute(HiveContext.scala:345)
        at org.apache.spark.sql.hive.HiveContext.metadataHive(HiveContext.scala:255)
        at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:459)
        at org.apache.spark.sql.hive.HiveContext.defaultOverrides(HiveContext.scala:233)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:236)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
        at sparklyr.Backend.getOrCreateHiveContext [... truncated]
2: In shell_create_hive_context_v1(sc) :
  Failed to create Hive context, falling back to SQL. Some operations, like window-functions, will not work
Error: java.lang.RuntimeException: [1.1] failure: ``with'' expected but identifier show found

show databases
^
        at scala.sys.package$.error(package.scala:27)
        at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
        at org.apache.spark.sql.catalyst.DefaultParserDialect.parse(ParserDialect.scala:67)
        at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
        at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:211)
        at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:114)
        at org.apache.spark.sql.execution.SparkSQLParser$$anonfun$org$apache$spark$sql$execution$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:113)
        at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
        at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
        at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
        at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
        at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
        at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
        at scala.util.parsing.combinator.PackratParsers$$anon$1.apply(PackratParsers.scala:110)
        at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:34)
        at org.apache.spark.sql.SQLContext$$anonfun$1.apply(SQLContext.scala:208)
        at org.apache.spark.sql.SQLContext$$anonfun$1.apply(SQLContext.scala:208)
        at org.apache.spark.sql.execution.datasources.DDLParser.parse(DDLParser.scala:43)
        at org.apache.spark.sql.SQLContext.parseSql(SQLContext.scala:231)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sparklyr.Invoke$.invoke(invoke.scala:102)
        at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
        at sparklyr.StreamHandler$.read(stream.scala:62)
        at sparklyr.BackendHandler.channelRead0(handler.scala:52)
        at sparklyr.BackendHandler.channelRead0(handler.scala:14)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
In addition: Warning messages:
1: In value[[3L]](cond) : java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:249)
        at org.apache.spark.sql.hive.HiveContext.metadataHive$lzycompute(HiveContext.scala:345)
        at org.apache.spark.sql.hive.HiveContext.metadataHive(HiveContext.scala:255)
        at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:459)
        at org.apache.spark.sql.hive.HiveContext.defaultOverrides(HiveContext.scala:233)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:236)
        at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
        at sparklyr.Backend.getOrCreateHiveContext [... truncated]
2: In shell_create_hive_context_v1(sc) :
  Failed to create Hive context, falling back to SQL. Some operations, like window-functions, will not work
Execution halted
```

From yarn I am able to see that a application was created. Do you have any idea what might be going on?

@archanbhatt
