### ISSUE TITLE
sparklyr parse error

### ISSUE THREAD

**Issue by YunMai-SPS** [rstudio/sparklyr#832]
Hello, 

The codes:
install.packages("sparklyr",repos="http://cran.rstudio.com/")
library(sparklyr)
library(dplyr)
# spark_available_versions()
spark_install(version = "2.0.2",hadoop_version = "2.7")
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)

I can connect to spark but had a problem in copying data and got the following errors:

Error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycompute(HiveSharedState.scala:46)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog(HiveSharedState.scala:45)
	at org.apache.spark.sql.hive.HiveSessionState.catalog$lzycompute(HiveSessionState.scala:50)
	at org.apache.spark.sql.hive.HiveSessionState.catalog(HiveSessionState.scala:48)
	at org.apache.spark.sql.hive.HiveSessionState$$anon$1.<init>(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer$lzycompute(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer(HiveSessionState.scala:62)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error while running command to get file permissions : java.io.IOException: (null) entry in command string: null ls -F C:\Users\john\AppData\Local\rstudio\spark\Cache\spark-2.0.2-bin-hadoop2.7\tmp\hive
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:770)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:866)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:849)
	at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1097)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.loadPermissionInfo(RawLocalFileSystem.java:659)
	at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.getPermission(RawLocalFileSystem.java:634)
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:599)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:554)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:508)
	at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:189)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycompute(HiveSharedState.scala:46)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog(HiveSharedState.scala:45)
	at org.apache.spark.sql.hive.HiveSessionState.catalog$lzycompute(HiveSessionState.scala:50)
	at org.apache.spark.sql.hive.HiveSessionState.catalog(HiveSessionState.scala:48)
	at org.apache.spark.sql.hive.HiveSessionState$$anon$1.<init>(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer$lzycompute(HiveSessionState.scala:63)
	at org.apache.spark.sql.hive.HiveSessionState.analyzer(HiveSessionState.scala:62)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io
> 

Then I uninstalled sparklyr and install it from github as suggested from"Error Trying to create tables on spark using copy_to #456" and some other latest discussions.

devtools::install_github("rstudio/sparklyr")
library(sparklyr)
library(dplyr)
spark_available_versions() 
spark_install(version = "2.0.2",hadoop_version = "2.7")
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)

Then I got this error:
Error: parse error: premature EOF (right here) ------^
15. parse_string(txt, bigint_as_char)
14. parseJSON(txt, bigint_as_char)
13. fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, flatten = flatten, ...)
12. fromJSON(system.file("extdata/config.json", package = "sparkinstall"))
11. spark_install_dir()
10. dir(c(spark_install_old_dir(), spark_install_dir()), full.names = TRUE)
9. lapply(dir(c(spark_install_old_dir(), spark_install_dir()), full.names = TRUE), function(maybeDir) { if (dir.exists(maybeDir)) { fileName <- basename(maybeDir) ...
8. lapply(x, f)
7. unlist(lapply(x, f))
6. Filter(function(e) !is.null(e), lapply(dir(c(spark_install_old_dir(), spark_install_dir()), full.names = TRUE), function(maybeDir) { if (dir.exists(maybeDir)) { fileName <- basename(maybeDir) ...
5. lapply(Filter(function(e) !is.null(e), lapply(dir(c(spark_install_old_dir(), spark_install_dir()), full.names = TRUE), function(maybeDir) { if (dir.exists(maybeDir)) { fileName <- basename(maybeDir) ...
4. spark_versions(latest = latest)
3. spark_install_find(version, hadoop_version, latest = FALSE, hint = TRUE)
2. shell_connection(master = master, spark_home = spark_home, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = FALSE, extensions = extensions)
1. spark_connect(master = "local")

> utils::sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.1    sparklyr_0.5.6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     rstudioapi_0.6   knitr_1.15.1     bindr_0.1        magrittr_1.5    
 [6] hms_0.3          rappdirs_0.3.1   xtable_1.8-2     R6_2.2.0         rlang_0.1.1     
[11] httr_1.2.1       tools_3.4.1      parallel_3.4.1   config_0.2       DBI_0.7         
[16] withr_1.0.2      dbplyr_1.1.0     htmltools_0.3.5  yaml_2.1.14      assertthat_0.2.0
[21] digest_0.6.12    rprojroot_1.2    tibble_1.3.3     bindrcpp_0.2     shiny_1.0.3     
[26] readr_1.1.1      base64enc_0.1-3  glue_1.1.1       mime_0.5         compiler_3.4.1  
[31] backports_1.0.5  jsonlite_1.5     httpuv_1.3.5     pkgconfig_2.0.1 

> devtools::session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-07-11                  

Packages ------------------------------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.2.0   2017-04-11 CRAN (R 3.4.1)
 backports    1.0.5   2017-01-18 CRAN (R 3.3.2)
 base       * 3.4.1   2017-06-30 local         
 base64enc    0.1-3   2015-07-28 CRAN (R 3.3.2)
 bindr        0.1     2016-11-13 CRAN (R 3.4.1)
 bindrcpp     0.2     2017-06-17 CRAN (R 3.4.1)
 compiler     3.4.1   2017-06-30 local         
 config       0.2     2016-08-02 CRAN (R 3.4.1)
 datasets   * 3.4.1   2017-06-30 local         
 DBI          0.7     2017-06-18 CRAN (R 3.4.1)
 dbplyr       1.1.0   2017-06-27 CRAN (R 3.4.1)
 devtools     1.13.2  2017-06-02 CRAN (R 3.4.1)
 digest       0.6.12  2017-01-27 CRAN (R 3.3.3)
 dplyr      * 0.7.1   2017-06-22 CRAN (R 3.4.1)
 glue         1.1.1   2017-06-21 CRAN (R 3.4.1)
 graphics   * 3.4.1   2017-06-30 local         
 grDevices  * 3.4.1   2017-06-30 local         
 hms          0.3     2016-11-22 CRAN (R 3.4.1)
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.3)
 httpuv       1.3.5   2017-07-04 CRAN (R 3.4.1)
 httr         1.2.1   2016-07-03 CRAN (R 3.3.3)
 jsonlite     1.5     2017-06-01 CRAN (R 3.4.1)
 knitr        1.15.1  2016-11-22 CRAN (R 3.3.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.3.3)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.1)
 methods    * 3.4.1   2017-06-30 local         
 mime         0.5     2016-07-07 CRAN (R 3.3.2)
 parallel     3.4.1   2017-06-30 local         
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.4.1)
 R6           2.2.0   2016-10-05 CRAN (R 3.3.3)
 rappdirs     0.3.1   2016-03-28 CRAN (R 3.4.1)
 Rcpp         0.12.10 2017-03-19 CRAN (R 3.3.3)
 readr        1.1.1   2017-05-16 CRAN (R 3.4.1)
 rlang        0.1.1   2017-05-18 CRAN (R 3.4.1)
 rprojroot    1.2     2017-01-16 CRAN (R 3.3.3)
 rstudioapi   0.6     2016-06-27 CRAN (R 3.4.1)
 shiny        1.0.3   2017-04-26 CRAN (R 3.4.1)
 sparklyr   * 0.5.6   2017-06-10 CRAN (R 3.4.1)
 stats      * 3.4.1   2017-06-30 local         
 tibble       1.3.3   2017-05-28 CRAN (R 3.4.1)
 tools        3.4.1   2017-06-30 local         
 utils      * 3.4.1   2017-06-30 local         
 withr        1.0.2   2016-06-20 CRAN (R 3.4.1)
 xtable       1.8-2   2016-02-05 CRAN (R 3.4.1)
 yaml         2.1.14  2016-11-12 CRAN (R 3.3.3)
 

 Please Help!

Thank you in advance.

**Comment by YunMai-SPS** [comment]
Problem solved.

First, need to install sparklyr then upgrade to the Github version. If I remove sparklyr followed by devtools::install_github("rstudio/sparklyr"), parse error will occur when command sparklyr install and connect functions.

install.packages("sparklyr", repos="http://cran.rstudio.com/")
library(sparklyr)
spark_install(version = "2.0.2")
library(dplyr)
devtools::install_github("rstudio/sparklyr")
library(sparklyr)
# Change SPARK_HOME and JAVA_HOME
Sys.setenv(JAVA_HOME = "C:/Java/jre1.8.0_131")
Sys.setenv(SPARK_HOME = "C:/Users/###/AppData/Local/rstudio/spark/Cache/spark-2.0.2-bin-hadoop2.7")

sc <- spark_connect(master = "local")

Good to go.

**Comment by AkhilNairAmey** [comment]
I'm seeing this error simply by using `sparklyr::spark_install("2.0.2")`

```
> library(sparklyr)
> spark_install("2.0.2")
Error: parse error: premature EOF
                                       
                     (right here) ------^
```

The error seems to come from https://github.com/rstudio/sparklyr/blob/master/R/install_spark.R#L283, where on my linux platform, `fromJSON` is passed an empty string (which produces the same error).

**Comment by javierluraschi** [comment]
@AkhilNairAmey parse error fixed with https://github.com/rstudio/sparklyr/commit/e88632e06aa2ff65cc85f7cb2b175bcf88018282.

@YunMai-SPS glad you were able to figure this out, thanks for sharing your fix.
