### ISSUE TITLE
Error in creating Local Spark Connection, Error in instances[[scon$sconRef]] <- NULL

### ISSUE THREAD

**Issue by ChangxingDou** [rstudio/sparklyr#85]
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

After running "spark_install", I got error message: -----------------
sc <- spark_connect(master = 'local')
Error: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:204)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:218)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:208)
	at org.apache.spark.sql.hive.HiveContext.functionRegistry$lzycompute(HiveContext.scala:462)
	at org.apache.spark.sql.hive.HiveContext.functionRegistry(HiveContext.scala:461)
	at org.apache.spark.sql.UDFRegistration.<init>(UDFRegistration.scala:40)
	at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:330)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:90)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
	at sun.reflect.NativeConstru
 ----------------- ----------------- ----------------- ----------------- ----------------- -----------------
Then I manually install java for 64 bit, and reset the java sys.env:
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre7')
 ----------------- ----------------- ----------------- ----------------- ----------------- -----------------
Rerun spark_connect:
sc <- spark_connect(master = 'local')
Error in instances[[scon$sconRef]] <- NULL : 
  attempt to select less than one element
 ----------------- ----------------- ----------------- ----------------- ----------------- -----------------
Any idea on how to fix this?

**Comment by javierluraschi** [comment]
@ChangxingDou Could you uninstall/reinstall `sparklyr` and retry on the latest version? Could you also run `packageVersion("sparklyr")` and share the version with us please?

**Comment by javierluraschi** [comment]
@ChangxingDou sparklyr `0.2.22` contains several fixes for windows that no longer make use for this code path. The following steps should get you past this issue:

1. Upgrade to the latest version of sparklyr, instructions here: https://github.com/rstudio/sparklyr#installation
2. Rerun 1spark_install()1, optionally, specify the version parameter.
3. Optional, but recommended, delete the `c:\Users\<user-name>\AppData\local\Temp` directory, not only the contents but the actual `Temp` directory as well.
4. Connect again as `sc <- spark_connect(master = "local")`.
5. If something fails, please run `spark_log(sc)` and post the log in here.

I'm closing this issue since the code referenced in the exception has been removed. Feel free to open a new issue if you still hit issues during connection.
