### ISSUE TITLE
spark_apply() fails when running an operation over a partitioned SDF

### ISSUE THREAD

**Issue by edgararuiz** [rstudio/sparklyr#904]
spark_apply() fails when running an operation over a partitioned SDF.  Reprex uses `spark_repartition()` because the dataset is small.  The error "naturally" occurs when caching large datasets which Spark partitions by default.

```
 sc <- spark_connect(master = "local", version = "2.1.0")
 
 iris_tbl <- sdf_copy_to(sc, iris, memory = FALSE) %>%
   sdf_repartition(partitions = 3) 
 
 iris_tbl <- sdf_register(iris_tbl, "iris_cached")
 
 tbl_cache(sc, "iris_cached")
 
 iris_tbl %>%
   spark_apply(nrow, group_by = "Species")

```

```
Error in force(code) : 
  sparklyr worker rscript failure, check worker logs for details
    Log: /var/folders/vd/krh_y3qd0c5bw8k77lmdtw7r0000gn/T//Rtmp87NHt7/file6ba03b60be3e_spark.log


---- Output Log ----
17/08/06 10:36:04 WARN TaskSetManager: Lost task 0.0 in stage 16.0 (TID 18, localhost, executor driver): java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:55)
	at sparklyr.WorkerRDD$$anon$2.run(rdd.scala:86)

...

```

Session Info

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2   DBI_0.7        ggplot2_2.2.1  dplyr_0.7.2    sparklyr_0.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     dbplyr_1.1.0     compiler_3.4.1   plyr_1.8.4       bindr_0.1        base64enc_0.1-3 
 [7] tools_3.4.1      digest_0.6.12    evaluate_0.10.1  gtable_0.2.0     jsonlite_1.5     tibble_1.3.3    
[13] nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.1.9000 psych_1.7.5      shiny_1.0.3     
[19] rstudioapi_0.6   curl_2.8.1       yaml_2.1.14      parallel_3.4.1   withr_2.0.0      httr_1.2.1      
[25] stringr_1.2.0    knitr_1.16       rappdirs_0.3.1   rprojroot_1.2    grid_3.4.1       glue_1.1.1      
[31] R6_2.2.2         rmarkdown_1.6    foreign_0.8-69   reshape2_1.4.2   tidyr_0.6.3      magrittr_1.5    
[37] scales_0.4.1     backports_1.1.0  htmltools_0.3.6  rsconnect_0.8    assertthat_0.2.0 mnormt_1.5-5    
[43] colorspace_1.3-2 mime_0.5         xtable_1.8-2     httpuv_1.3.5     config_0.2       stringi_1.1.5   
[49] munsell_0.4.3    lazyeval_0.2.0   broom_0.4.2   
```

**Comment by edgararuiz** [comment]
Better reprex

```
library(sparklyr)
library(dplyr)

if(!file.exists("2003.csv.bz2"))
{download.file("http://stat-computing.org/dataexpo/2009/2003.csv.bz2", "2003.csv.bz2")}

conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "16G"
sc <- spark_connect(master = "local", config = conf, version = "2.1.0")

flights_tbl <- spark_read_csv(sc, "flights", "2003.csv.bz2", memory = FALSE)

flights_tbl <- flights_tbl %>%
  select(Year, Month) %>%
  sdf_register("flights_cached")

tbl_cache(sc, "flights_cached")

flights_tbl %>%
  spark_apply(nrow, group_by = "Month")
```

```
Error in force(code) : 
  sparklyr worker rscript failure, check worker logs for details
    Log: /var/folders/vd/krh_y3qd0c5bw8k77lmdtw7r0000gn/T//RtmpEM24Ce/file706b2114a691_spark.log


---- Output Log ----
17/08/06 11:15:24 INFO sparklyr: Worker (9184) is waiting for sparklyr client to connect to port 56581
17/08/06 11:15:24 INFO sparklyr: Worker (4826) finished registration in gateway with status 0
17/08/06 11:15:24 INFO sparklyr: Worker (4826) is waiting for sparklyr client to connect to port 56578
17/08/06 11:15:24 INFO sparklyr: Worker (7858) completed R process
17/08/06 11:15:24 INFO sparklyr: Gateway (7858) is terminating backend
(17/08/06 11:15:24 ERROR sparklyr: Gateway (7858) is shutting down with exception ,java.net.SocketException: Socket closed)
...
```

**Comment by edgararuiz** [comment]
Works in DEV version

**Comment by javierluraschi** [comment]
@edgararuiz ah, yes. I hit a few race conditions last week and had to push a patch to CRAN. CRAN binaries are still building, but this will be fixed on CRAN as well. Thanks for passing this along!

**Comment by harryprince** [comment]
@javierluraschi , I got the same issue, due to the NA problem.

However the Rscript remote log need be improved..

Indeed, I can find the error on `stdout` instead of `stderr` log by Spark UI
