### ISSUE TITLE
copy_to() function returns error

### ISSUE THREAD

**Issue by raghavprasad** [rstudio/sparklyr#920]
# Reporting an Issue with sparklyr

I am trying to use spark through rstudio and am facing issues with the copy_to function

The following is the code snippet, I am running on rstudio
---------------------------------------------------
devtools::install_github("rstudio/sparklyr")
sparklyr::spark_install(version = "2.2.0", hadoop_version = "2.7")
library("sparklyr")
sparkContext <- spark_connect(master = "local", version = "2.2.0")
library("dplyr")
local_tbl_cars <- copy_to(sparkContext, mtcars, overwrite = TRUE)
--------------------------------------------------
My connect function is successful but the copy_to() function returns the following error
--------------------------------------
Error: java.lang.IllegalArgumentException: invalid method sql for object 9
	at sparklyr.Invoke$.invoke(invoke.scala:122)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)
--------------------------------------------------------------------------

I am a C programmer and hence not used to Java programming. Any help on this error will do a world of good to me.

Kindly HELP!!!!!

**Comment by javierluraschi** [comment]
@raghavprasad could you share the output of `spark_log(sparkContext)`?

**Comment by raghavprasad** [comment]
@javierluraschi : Thanks a lot for responding.

Please find the output of spark_log(sparkContext)
--------------------------------------------------
at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
17/08/12 06:31:46 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
17/08/12 06:31:56 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
17/08/12 06:32:06 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:726)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:755)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:755)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 14 more
17/08/12 06:32:06 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(false)
17/08/12 06:32:06 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(false)
17/08/12 06:32:06 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(false)
17/08/12 06:32:06 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(false)
--------------------------------------------------------------------------------------

Please let me know if you require any further information.

**Comment by raghavprasad** [comment]
@javierluraschi : Thanks a lot for responding.

Please find below the output of spark_log(sparkContext)

---------------------------------------------------------------------------------
 spark_log(sparkContext)
17/08/12 06:38:34 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4194304 bytes, open cost is considered as scanning 4194304 bytes.
17/08/12 06:38:35 INFO CodeGenerator: Code generated in 33.205793 ms
17/08/12 06:38:35 INFO CodeGenerator: Code generated in 22.415396 ms
17/08/12 06:38:35 INFO SparkContext: Starting job: sql at <unknown>:0
17/08/12 06:38:35 INFO DAGScheduler: Registering RDD 10 (sql at <unknown>:0)
17/08/12 06:38:35 INFO DAGScheduler: Got job 1 (sql at <unknown>:0) with 1 output partitions
17/08/12 06:38:35 INFO DAGScheduler: Final stage: ResultStage 2 (sql at <unknown>:0)
17/08/12 06:38:35 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 1)
17/08/12 06:38:35 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 1)
17/08/12 06:38:35 INFO DAGScheduler: Submitting ShuffleMapStage 1 (MapPartitionsRDD[10] at sql at <unknown>:0), which has no missing parents
17/08/12 06:38:35 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 21.8 KB, free 366.0 MB)
17/08/12 06:38:35 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 9.6 KB, free 366.0 MB)
17/08/12 06:38:35 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 127.0.0.1:64476 (size: 9.6 KB, free: 366.3 MB)
17/08/12 06:38:35 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
17/08/12 06:38:35 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 1 (MapPartitionsRDD[10] at sql at <unknown>:0) (first 15 tasks are for partitions Vector(0))
17/08/12 06:38:35 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
17/08/12 06:38:35 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, executor driver, partition 0, PROCESS_LOCAL, 5366 bytes)
17/08/12 06:38:35 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
17/08/12 06:38:35 INFO ContextCleaner: Cleaned accumulator 55
17/08/12 06:38:35 INFO ContextCleaner: Cleaned accumulator 0
17/08/12 06:38:35 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 127.0.0.1:64476 in memory (size: 3.4 KB, free: 366.3 MB)
17/08/12 06:38:35 INFO FileScanRDD: Reading File path: file:///C:/Users/RAGHAV~1/AppData/Local/Temp/RtmpsV6t1u/spark_serialize_600df8759318fe0d3e7cd227dfb889264b9395236a2336b9c1d32f83ed509279.csv, range: 0-1336, partition values: [empty row]
17/08/12 06:38:35 INFO CodeGenerator: Code generated in 40.167288 ms
17/08/12 06:38:36 INFO MemoryStore: Block rdd_7_0 stored as values in memory (estimated size 4.2 KB, free 366.0 MB)
17/08/12 06:38:36 INFO BlockManagerInfo: Added rdd_7_0 in memory on 127.0.0.1:64476 (size: 4.2 KB, free: 366.3 MB)
17/08/12 06:38:36 INFO CodeGenerator: Code generated in 12.036627 ms
17/08/12 06:38:36 INFO CodeGenerator: Code generated in 44.561775 ms
17/08/12 06:38:36 INFO Executor: Finished task 0.0 in stage 1.0 (TID 1). 2547 bytes result sent to driver
17/08/12 06:38:36 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 834 ms on localhost (executor driver) (1/1)
17/08/12 06:38:36 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
17/08/12 06:38:36 INFO DAGScheduler: ShuffleMapStage 1 (sql at <unknown>:0) finished in 0.839 s
17/08/12 06:38:36 INFO DAGScheduler: looking for newly runnable stages
17/08/12 06:38:36 INFO DAGScheduler: running: Set()
17/08/12 06:38:36 INFO DAGScheduler: waiting: Set(ResultStage 2)
17/08/12 06:38:36 INFO DAGScheduler: failed: Set()
17/08/12 06:38:36 INFO DAGScheduler: Submitting ResultStage 2 (MapPartitionsRDD[13] at sql at <unknown>:0), which has no missing parents
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 7.0 KB, free 366.0 MB)
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 3.7 KB, free 366.0 MB)
17/08/12 06:38:36 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on 127.0.0.1:64476 (size: 3.7 KB, free: 366.3 MB)
17/08/12 06:38:36 INFO SparkContext: Created broadcast 3 from broadcast at DAGScheduler.scala:1006
17/08/12 06:38:36 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 2 (MapPartitionsRDD[13] at sql at <unknown>:0) (first 15 tasks are for partitions Vector(0))
17/08/12 06:38:36 INFO TaskSchedulerImpl: Adding task set 2.0 with 1 tasks
17/08/12 06:38:36 INFO TaskSetManager: Starting task 0.0 in stage 2.0 (TID 2, localhost, executor driver, partition 0, ANY, 4726 bytes)
17/08/12 06:38:36 INFO Executor: Running task 0.0 in stage 2.0 (TID 2)
17/08/12 06:38:36 INFO ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 1 blocks
17/08/12 06:38:36 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 15 ms
17/08/12 06:38:36 INFO Executor: Finished task 0.0 in stage 2.0 (TID 2). 1538 bytes result sent to driver
17/08/12 06:38:36 INFO TaskSetManager: Finished task 0.0 in stage 2.0 (TID 2) in 82 ms on localhost (executor driver) (1/1)
17/08/12 06:38:36 INFO DAGScheduler: ResultStage 2 (sql at <unknown>:0) finished in 0.084 s
17/08/12 06:38:36 INFO DAGScheduler: Job 1 finished: sql at <unknown>:0, took 1.084616 s
17/08/12 06:38:36 INFO TaskSchedulerImpl: Removed TaskSet 2.0, whose tasks have all completed, from pool 
17/08/12 06:38:36 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
17/08/12 06:38:36 INFO SparkSqlParser: Parsing command: SELECT count(*) FROM  `mtcars`
17/08/12 06:38:36 INFO HiveMetaStore: 0: get_database: default
17/08/12 06:38:36 INFO audit: ugi=Raghavendra	ip=unknown-ip-addr	cmd=get_database: default	
17/08/12 06:38:36 INFO SparkContext: Starting job: collect at utils.scala:196
17/08/12 06:38:36 INFO DAGScheduler: Registering RDD 16 (collect at utils.scala:196)
17/08/12 06:38:36 INFO DAGScheduler: Got job 2 (collect at utils.scala:196) with 1 output partitions
17/08/12 06:38:36 INFO DAGScheduler: Final stage: ResultStage 4 (collect at utils.scala:196)
17/08/12 06:38:36 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 3)
17/08/12 06:38:36 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 3)
17/08/12 06:38:36 INFO DAGScheduler: Submitting ShuffleMapStage 3 (MapPartitionsRDD[16] at collect at utils.scala:196), which has no missing parents
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_4 stored as values in memory (estimated size 21.8 KB, free 365.9 MB)
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_4_piece0 stored as bytes in memory (estimated size 9.6 KB, free 365.9 MB)
17/08/12 06:38:36 INFO BlockManagerInfo: Added broadcast_4_piece0 in memory on 127.0.0.1:64476 (size: 9.6 KB, free: 366.3 MB)
17/08/12 06:38:36 INFO SparkContext: Created broadcast 4 from broadcast at DAGScheduler.scala:1006
17/08/12 06:38:36 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 3 (MapPartitionsRDD[16] at collect at utils.scala:196) (first 15 tasks are for partitions Vector(0))
17/08/12 06:38:36 INFO TaskSchedulerImpl: Adding task set 3.0 with 1 tasks
17/08/12 06:38:36 INFO TaskSetManager: Starting task 0.0 in stage 3.0 (TID 3, localhost, executor driver, partition 0, PROCESS_LOCAL, 5366 bytes)
17/08/12 06:38:36 INFO Executor: Running task 0.0 in stage 3.0 (TID 3)
17/08/12 06:38:36 INFO BlockManager: Found block rdd_7_0 locally
17/08/12 06:38:36 INFO Executor: Finished task 0.0 in stage 3.0 (TID 3). 1737 bytes result sent to driver
17/08/12 06:38:36 INFO TaskSetManager: Finished task 0.0 in stage 3.0 (TID 3) in 43 ms on localhost (executor driver) (1/1)
17/08/12 06:38:36 INFO DAGScheduler: ShuffleMapStage 3 (collect at utils.scala:196) finished in 0.045 s
17/08/12 06:38:36 INFO DAGScheduler: looking for newly runnable stages
17/08/12 06:38:36 INFO DAGScheduler: running: Set()
17/08/12 06:38:36 INFO DAGScheduler: waiting: Set(ResultStage 4)
17/08/12 06:38:36 INFO DAGScheduler: failed: Set()
17/08/12 06:38:36 INFO DAGScheduler: Submitting ResultStage 4 (MapPartitionsRDD[19] at collect at utils.scala:196), which has no missing parents
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_5 stored as values in memory (estimated size 7.0 KB, free 365.9 MB)
17/08/12 06:38:36 INFO MemoryStore: Block broadcast_5_piece0 stored as bytes in memory (estimated size 3.7 KB, free 365.9 MB)
17/08/12 06:38:36 INFO TaskSchedulerImpl: Removed TaskSet 3.0, whose tasks have all completed, from pool 
17/08/12 06:38:36 INFO BlockManagerInfo: Added broadcast_5_piece0 in memory on 127.0.0.1:64476 (size: 3.7 KB, free: 366.2 MB)
17/08/12 06:38:36 INFO SparkContext: Created broadcast 5 from broadcast at DAGScheduler.scala:1006
17/08/12 06:38:36 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 4 (MapPartitionsRDD[19] at collect at utils.scala:196) (first 15 tasks are for partitions Vector(0))
17/08/12 06:38:36 INFO TaskSchedulerImpl: Adding task set 4.0 with 1 tasks
17/08/12 06:38:36 INFO TaskSetManager: Starting task 0.0 in stage 4.0 (TID 4, localhost, executor driver, partition 0, ANY, 4726 bytes)
17/08/12 06:38:36 INFO Executor: Running task 0.0 in stage 4.0 (TID 4)
17/08/12 06:38:36 INFO ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 1 blocks
17/08/12 06:38:36 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
17/08/12 06:38:36 INFO Executor: Finished task 0.0 in stage 4.0 (TID 4). 1538 bytes result sent to driver
17/08/12 06:38:36 INFO TaskSetManager: Finished task 0.0 in stage 4.0 (TID 4) in 13 ms on localhost (executor driver) (1/1)
17/08/12 06:38:36 INFO DAGScheduler: ResultStage 4 (collect at utils.scala:196) finished in 0.016 s
17/08/12 06:38:36 INFO DAGScheduler: Job 2 finished: collect at utils.scala:196, took 0.106296 s
17/08/12 06:38:36 INFO TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool 
17/08/12 06:38:36 INFO CodeGenerator: Code generated in 17.904226 ms
17/08/12 06:38:36 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
17/08/12 06:38:36 INFO SparkSqlParser: Parsing command: SELECT *
FROM `mtcars` AS `zzz1`
WHERE (0 = 1)
-----------------------------------------------------------------------------------------------------------

**Comment by javierluraschi** [comment]
@raghavprasad does the following code work?

```r
src_tbls(sc)
```

```r
sparklyr:::create_hive_context_v2(sc)
```

```r
spark_session(sc)
```

```r
spark_session(sc) %>% invoke("sql", "SELECT 1")
```
