### ISSUE TITLE
SparkContext was shut down when collcet data after spark_apply

### ISSUE THREAD

**Issue by ZJUguquan** [rstudio/sparklyr#938]
Hi,
I'm running spark on yarn and I have found a problem that when I compute a spark dataframe using spark_apply and  `dplyr::collcet` the spark dataframe, it goes wrong and shut down, although it seems goes right that when call/print the dataframe alone...

The cluster is under Ubuntu 14.04.5 LTS . Here is my environment information,
```r
> R.version                    
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness  

> packageVersion("sparklyr")
[1] ‘0.6.1’

> library(sparklyr)
> library(dplyr)
> config <- spark_config()
> Sys.setenv(JAVA_HOME = "/usr/java/jdk1.8.0_77")
> sc <- spark_connect(master = "yarn-client", version = "1.6.0",
                     app_name = "guquan1234",
                     spark_home = "/opt/cloudera/parcels/CDH-5.10.0-1.cdh5.10.0.p0.41/lib/spark",
                     config = config)

```

The origin spark dataframe is named `compare` with 234021 rows and 6 columns which is about the China's stock market data, like below,
```r
> compare
# Source:     lazy query [?? x 6]
# Database:   spark_connection
# Ordered by: stock_no, init_date, stock_no, init_date
   stock_no stock_name init_date price_change_rate   close change_rate
      <chr>      <chr>     <chr>             <dbl>   <dbl>       <dbl>
 1   000006   深振业Ａ  20150105              0.43 3350.52        3.58
 2   000006   深振业Ａ  20150106             -3.25 3351.45        0.03
 3   000006   深振业Ａ  20150107              0.15 3373.95        0.67
 4   000006   深振业Ａ  20150108             -1.17 3293.46       -2.39
 5   000006   深振业Ａ  20150109             -1.18 3285.41       -0.24
 6   000006   深振业Ａ  20150112             -3.88 3229.32       -1.71
 7   000006   深振业Ａ  20150113              0.00 3235.30        0.19
 8   000006   深振业Ａ  20150114             -0.93 3222.44       -0.40
 9   000006   深振业Ａ  20150115              2.35 3336.46        3.54
10   000006   深振业Ａ  20150116             -0.46 3376.50        1.20
# ... with more rows

> sdf_dim(compare)
[1] 234021      6

```

And my `spark_apply` code is below. I want to do a linear-regression between the two columns  `price_change_rate`(for each stock) and `change_rate`(for Shanghai Composite Index) on each group of `stock_no`. And the result spark dataframe is named `beta`.

```r
> beta <- compare %>%
+   spark_apply(group_by = "stock_no", f = function(g){
+     g2 = g[order(g$init_date), ]
+     coefs = coef(lm(price_change_rate ~ change_rate, data = g2))
+     if(length(coefs)==2){
+       return(data.frame('stock_name' = g2$stock_name[1],
+                         'intercept' = coefs[1], 'beta' = coefs[2]))
+     } else {
+       return(data.frame('stock_name' = g2$stock_name[1],
+                         'intercept' = 0, 'beta' = 1))
+     }
+     data.frame('stock_name' = g2$stock_name[1],
+                'intercept' = coefs[1], 'beta' = coefs[2])
+   },
+   columns = c('stock_name', 'intercept', 'beta'))

> beta
# Source:   table<sparklyr_tmp_353a3677da2d> [?? x 4]
# Database: spark_connection
   stock_no stock_name   intercept      beta
      <chr>      <chr>       <dbl>     <dbl>
 1   300135   宝利国际 0.069472654 1.2252459
 2   600006   东风汽车 0.104978713 1.3109445
 3   600790     轻纺城 0.028354280 1.3284182
 4   600619   海立股份 0.125463226 1.4173904
 5   002703   浙江世宝 0.078672518 0.9348847
 6   600502   安徽水利 0.132295450 1.4128546
 7   000923   河北宣工 0.335848425 1.3732432
 8   000761   本钢板材 0.007514814 0.9401329
 9   300020   银江股份 0.161656853 1.3162445
10   601233   桐昆股份 0.129247174 1.4038329
# ... with more rows
```

When I call `beta` alone, it returns some data rightly, but when I collect it, several minutes later, it **goes wrong** and the **SparkContext was shut down**...... >_<!

```r
> beta_df <- collect(beta)
Error: org.apache.spark.SparkException: Job 20 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:806)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:804)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:804)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
	at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1581)
	at org.apache.spark.SparkContext$$anonfun$stop$7.apply$mcV$sp(SparkContext.scala:1731)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1229)
...
...

```

I looked into the logs from the spark job UI but I could not find where the problem was and why it went wrong. Here is some information(screenshots or logs) that may help you...

---

![](http://o8e1oty0e.bkt.clouddn.com/collect%E6%8A%A5%E9%94%992.png) 
![](http://o8e1oty0e.bkt.clouddn.com/collect%E6%8A%A5%E9%94%993.png) 
![](http://o8e1oty0e.bkt.clouddn.com/collect4.png)

>
15 | 3905 | 1 | FAILED | NODE_LOCAL | 3 / bigdata6.liangzhi.com | 2017/08/16 00:26:45 |   |   | / | ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 133225 ms
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

---

Besides, when I `collect` some test data, there is no problems.
```r
> test <- tbl(sc, "guquan.test")
> test_df <- collect(test)
> test_df
# A tibble: 15 x 5
   sepallength sepalwidth petallength petalwidth    species
         <dbl>      <dbl>       <dbl>      <dbl>      <chr>
 1         5.1        3.5         1.4        0.2     setosa
 2         4.9        3.0         1.4        0.2     setosa
 3         4.7        3.2         1.3        0.2     setosa
 4         4.6        3.1         1.5        0.2     setosa
 5         5.0        3.6         1.4        0.2     setosa
 6         7.0        3.2         4.7        1.4 versicolor
 7         6.4        3.2         4.5        1.5 versicolor
 8         6.9        3.1         4.9        1.5 versicolor
 9         5.5        2.3         4.0        1.3 versicolor
10         6.5        2.8         4.6        1.5 versicolor
11         6.3        3.3         6.0        2.5  virginica
12         5.8        2.7         5.1        1.9  virginica
13         7.1        3.0         5.9        2.1  virginica
14         6.3        2.9         5.6        1.8  virginica
15         6.5        3.0         5.8        2.2  virginica
```

<br/>

**Hope to receive your reply. Thanks.**

<br/>

**Comment by ZJUguquan** [comment]
sorry, the reason seems to be that I have added two lines of useless codes after the `return` expression...

```r
...
+     if(length(coefs)==2){
+       return(data.frame('stock_name' = g2$stock_name[1],
+                         'intercept' = coefs[1], 'beta' = coefs[2]))
+     } else {
+       return(data.frame('stock_name' = g2$stock_name[1],
+                         'intercept' = 0, 'beta' = 1))
+     }
+     data.frame('stock_name' = g2$stock_name[1],   #useless
+                'intercept' = coefs[1], 'beta' = coefs[2])   #useless
...
```

I remove these codes and it seems running OK!

**Comment by kevinykuo** [comment]
@ZJUguquan thanks for the update!
