### ISSUE TITLE
sdf_partition doesnt work with livy

### ISSUE THREAD

**Issue by xhudik** [rstudio/sparklyr#957]
library(sparklyr)
     library(dplyr)
     livy_service_start()
     sc <- spark_connect(master = "http://example.com:8998", method = "livy")
     ir <- copy_to(sc,iris, overwrite = TRUE)
     sdf_partition(ir, training = 0.7, testing = 0.3)

Gave error
    `Error: org.apache.spark.sql.AnalysisException: Table not found: sparklyr_tmp_22656995fe7c; line 2 pos 36
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.getTable(Analyzer.scala:305)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:314)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:309)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:57)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:57)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:56)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:54)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:54)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:281)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)`

The same works fine if  `sc` is not **livy** 
```

sdf_partition(it, training = 0.7, testing = 0.3)
$training
# Source:   table<sparklyr_tmp_168e6778651d> [?? x 5]
# Database: spark_connection
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
          <dbl>       <dbl>        <dbl>       <dbl>   <chr>
 1          4.3         3.0          1.1         0.1  setosa
 2          4.4         2.9          1.4         0.2  setosa
...
```

**Comment by xhudik** [comment]
it seems problem is in:
(https://github.com/rstudio/sparklyr/blob/master/R/sdf_interface.R#L138) where ` invoke(x, "registerTempTable", name) ` returns `NULL` and  `tbl(sc, name)` (https://github.com/rstudio/sparklyr/blob/master/R/sdf_interface.R#L141) gives the `Table not found` error.

**Comment by javierluraschi** [comment]
@xhudik I wasn't able to reproduce this issue in the latest version of `sparklyr` and Livy `0.3.0`. Which version of sparklyr/Livy are you running?

```r
sc <- spark_connect(master = "http://localhost:8998", method = "livy")
ir <- copy_to(sc,iris, overwrite = TRUE)
sdf_partition(ir, training = 0.7, testing = 0.3)
```

```
# Source:   table<sparklyr_tmp_26f133b993f5> [?? x 5]
# Database: spark_connection
   Sepal_Length Sepal_Width Petal_Length Petal_Width    Species
          <dbl>       <dbl>        <dbl>       <dbl>      <chr>
 1          4.3         3.0          1.1         0.1     setosa
 2          4.4         2.9          1.4         0.2     setosa
 3          4.4         3.0          1.3         0.2     setosa
 4          4.5         2.3          1.3         0.3     setosa
 5          4.6         3.2          1.4         0.2     setosa
 6          4.8         3.0          1.4         0.1     setosa
 7          4.9         3.1          1.5         0.1     setosa
 8          5.0         2.0          3.5         1.0 versicolor
 9          5.0         2.3          3.3         1.0 versicolor
10          5.0         3.2          1.2         0.2     setosa
# ... with more rows
```

**Comment by xhudik** [comment]
strange - i tried once more and the problem is still here...

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.2         sparklyr_0.7.0-9012

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     dbplyr_1.1.0     compiler_3.4.1   plyr_1.8.4       bindr_0.1        base64enc_0.1-3  tools_3.4.1      digest_0.6.12   
 [9] packrat_0.4.8-1  jsonlite_1.5     tibble_1.3.3     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.5     
[17] shiny_1.0.4      DBI_0.7          rstudioapi_0.6   curl_2.8.1       yaml_2.1.14      parallel_3.4.1   bindrcpp_0.2     withr_2.0.0     
[25] httr_1.3.1       stringr_1.2.0    hms_0.3          rappdirs_0.3.1   rprojroot_1.2    grid_3.4.1       glue_1.1.1       R6_2.2.2        
[33] foreign_0.8-69   readr_1.1.1      SparkR_2.1.1     reshape2_1.4.2   tidyr_0.6.3      magrittr_1.5     backports_1.1.0  htmltools_0.3.6 
[41] assertthat_0.2.0 mnormt_1.5-5     mime_0.5         xtable_1.8-2     httpuv_1.3.5     config_0.2       stringi_1.1.5    lazyeval_0.2.0  
[49] broom_0.4.2     
```

```

livy_installed_versions()
   livy                     livyVersionDir
1 0.3.0 /home/tomas/.cache/livy/livy-0.3.0
```


What came to my mind, I;m using an older spark (version 2.0) - might this be a problem?

**Comment by xhudik** [comment]
i tried it on newer Spark 2.1

```
> sdf_partition(a, training = 0.7, testing = 0.3)
Error: org.apache.spark.sql.AnalysisException: Table not found: sparklyr_tmp_2a3620bfdf93; line 2 pos 36
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.getTable(Analyzer.scala:305)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:314)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:309)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:57)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:57)

```

@javierluraschi  did you try it over real network(really remotely)?

**Comment by xhudik** [comment]
hmm, strange with a new HDP 2.6 and Spark 2.2 - it is working well.

What might had been problem: I had set `SPARK_MAJOR_VERSION=2` which is fine, however I accidentally might run `livy-server` instead of `livy2-server`

thanks!
