### ISSUE TITLE
import spark.implicits._

### ISSUE THREAD

**Issue by schlichtanders** [rstudio/sparklyr#958]
when I try to convert a spark dataframe to rdd and back, by following the tutorial https://spark.apache.org/docs/latest/sql-programming-guide.html#inferring-the-schema-using-reflection

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)
sparklyr_df <- copy_to(sc, data.frame(x = 1:4, y = 4:7), "df")
java_df <- spark_dataframe(sparklyr_df)
java_rdd <- sparklyr::invoke(java_df,"rdd")
java_df2 <- sparklyr::invoke(java_rdd, "toDF", colnames(sparklyr_df))
```
I get the following error
```
Error: java.lang.IllegalArgumentException: invalid method toDF for object 51
	at sparklyr.Invoke$.invoke(invoke.scala:122)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
In addition: Warning message:
In if (is.na(object)) { :
  the condition has length > 1 and only the first element will be used
```

My best guess is that `import spark.implicits._` is missing in the jar files which are used to create the spark_connection.

**Comment by kevinykuo** [comment]
This works:

```
java_df2 <- spark_session(sc) %>%
  invoke("createDataFrame", java_rdd, invoke(java_df, "schema"))
java_df2
# <jobj[406]>
#   class org.apache.spark.sql.Dataset
# [x: int, y: int]
```

`toDF` only works on specific types of RDDs, see e.g. https://stackoverflow.com/questions/37011267/how-to-convert-an-rddrow-back-to-dataframe

**Comment by schlichtanders** [comment]
So in fact the implicits are all there?

--- 

I actually already found this very reference, however was not careful enough in reading / interpreting.

Intuitively I thought that if I form a RDD[Row] out of a Dataframe than all but the row-names should be preserved, namely also the types. Unfortunately this is false as you pointed out. A pity, but ok, now I know.

Thank you so much for answering my question that rapid! I spend a few hours trying to get this running. Actually I still don't know how I would execute the ``import spark_session.implicits._`` into the right scope... but that is probably not needed.

**Comment by kevinykuo** [comment]
Yeah all of Spark core should be available.

Out of curiosity – do you have a use case that deals with manipulating RDDs?

**Comment by schlichtanders** [comment]
yes =), namely Spark MLlib Statistics:
https://spark.apache.org/docs/latest/mllib-statistics.html

they work on RDDs

**Comment by javierluraschi** [comment]
Currently, we can't add imports as `import spark_session.implicits._` with the `invoke()` functions; however, it is usually the case that there is a way around that. Say, to get the implicits we could run `invoke(hive_context(sc), "implicits")`; that said, I'll close this one since Kevin already pass a workaround, but feel free to open a new one if you find yourself stuck with other `invoke()` related constraints.

**Comment by kevinykuo** [comment]
I'll also take a look at the RDD API to see if we should implement some of the features missing from spark.ml
