### ISSUE TITLE
Connecting to Spark on IBM Bluemix

### ISSUE THREAD

**Issue by campanell** [rstudio/sparklyr#98]
I have been trying to connect to a Spark cluster on the IBM Bluemix service.   I am using R Studio on Windows 10.   

`library(sparklyr)`
`library(dplyr)`

`# Spark Home Bluemix cluster`
`#Sys.setenv(SPARK_HOME = "/usr/local/src/spark160master/spark-1.6.0-bin-2.6.0")`
`# Spark Home on my local machine`
`Sys.setenv(SPARK_HOME = "C:\\\\Users\\Campanell\\AppData\\Local\\rstudio\\spark\\Cache\\spark-1.6.1-bin-hadoop2.6")`

`spark_config()`
`sc <- spark_connect(master="spark://169.54.219.20:8443")`
`spark_connection_is_open(sc)`

I have edited the config.yml to include my Bluemix credentials.   When I get to spark_connect, R Studio aborts.

Should I have to edit the spark_submit.cmd file?   IBM has a huge spark_submit.sh script for Unix and Mac OS X.   I don't know how to configure it for R Studio on Windows.

[https://console.ng.bluemix.net/docs/services/AnalyticsforApacheSpark/index-gentopic3.html#using_spark-submit](url)

**Comment by campanell** [comment]
Installed Spark 1.6.2.   No R session abort this time, but am getting a bunch of Java error messages:

> **sc <- spark_connect(master="spark://169.54.219.20:8443")**
Created default hadoop bin directory under: C:\Users\Campanell\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\tmp\hadoop
Error: java.lang.NullPointerException
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:583)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.spark.api.r.RBackendHandler.handleMethodCall(RBackendHandler.scala:162)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:86)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:38)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.Mes
> **spark_connection_is_open(sc)**
Error in sparkapi::connection_is_open(sc) : object 'sc' not found

**Comment by javierluraschi** [comment]
@campanell could you retry with `sparklyr` version `0.2.29` or newer? We've isolated our backend and this should improve connection to multiple systems, including IBM Bluemix. To upgrade run

`devtools::install_github("rstudio/sparklyr")` and restart the r session

**Comment by campanell** [comment]
Javier,

I updated sparklyr to version 0.2.32, but I am still getting a very similar message

` Sys.setenv(SPARK_HOME = "C:\\\\Users\\Campanell\\AppData\\Local\\rstudio\\spark\\Cache\\spark-1.6.2-bin-hadoop2.6")`

`spark_config(file="C:\\\\Users\\Campanell\\Documents\\R\\win-library\\3.2\\sparklyr\\conf\\config-template.yml", use_default = FALSE)`

$sparklyr.cores.local
[1] 8

$spark.sql.shuffle.partitions.local
[1] 8

$sparklyr.defaultPackages
[1] "com.databricks:spark-csv_2.11:1.3.0"    "com.amazonaws:aws-java-sdk-pom:1.10.34"

attr(,"config")
[1] "default"
attr(,"file")
[1] "C:\\Users\\Campanell\\Documents\\R\\win-library\\3.2\\sparklyr\\conf\\config-template.yml"

`sc <- spark_connect(master="spark://169.54.219.20:8443")`

Error: java.lang.NullPointerException
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:583)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sparkapi.Handler.handleMethodCall(handler.scala:139)
	at sparkapi.Handler.channelRead0(handler.scala:63)
	at sparkapi.Handler.channelRead0(handler.scala:15)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.A

Is spark_config set properly?   I am not seeing the credentials variables show up in the console output.   I set those in the config-template.yml file.   Is it still pointing to a default file?

**Comment by javierluraschi** [comment]
@campanell we are working through out backlog and have time to take a look a this. Could you retry with `0.4.13` or newer and provide a description of your IBM Bluemix environment? What do I have to get a repro in my environment (I do have an Bluemix account)? Where are you running R from? The gateway node?

**Comment by javierluraschi** [comment]
Fix commited, please retry with `sparklyr 0.5.6-9002` or newer. You can install using `devtools::install_github("rstudio/sparklyr")`.
