### ISSUE TITLE
spark_apply runs forever and nothing appears in the gui

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#980]
Hello the sparklyr team!

I am using the promising spark_apply function but even a simple call seems to break.
I have a pretty large dataset, broken down in about 50 parquet files (they contain a column called myurl).

The code I run is essentially

```
library(httr)
# for parse_url() in the spark_apply call

df<- read_parquet(sc, //mypath/myfiles* , memory = FALSE, overwrite = TRUE, name = 'df')
df_agg  <- df %>% head()  %>% spark_apply(
    function(e) data.frame(parse_url$my_url, e),
    names = c("mypath", colnames(df)))
```

note the `head(.)` that should make this computation straighforward. Yet, Rstudio seems stuck in computation mode forever, and nothing happens on the `stages` tab of the spark GUI. Is that a bug? Is that expected? Other stuff like `df %>% group_by(myurl) %>% summarise(count = n()) %>% collect()` work just fine

Thanks again for your help. This `spark_apply` would be a life saver for me.

**Comment by randomgambit** [comment]
@kevinykuo  @javierluraschi 
actually doing something as simple as 

```
df %>%
  spark_apply(function(e) head(e, 1))
```

creates the same problem (crash of the R session, nothing happens in the GUI). Cant spark apply work with parquet files? Do you see a probleme here?

Thanks!!

**Comment by kevinykuo** [comment]
does `head(df)` work?

**Comment by randomgambit** [comment]
@kevinykuo yes, even some more involved group_by + summarise + collect. what do you think?😱

**Comment by kevinykuo** [comment]
Would help to see the logs when you run the `spark_apply()` code

**Comment by randomgambit** [comment]
where can I find them? I can have a look and see if I can share them (or at least tell you what is the main error). thanks!!

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi the problem is that there is not output in the console at all. Essentially the command starts a computation and then breaks. I tried all the tabs in the Spark GUI: no activity at all as well. Where can I find the log you are talking about? Happy to help solve this important issue

Thanks!!

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi sorry but I need to BUMP this!! :D please let me know how I can help here. Thanks again!

**Comment by kevinykuo** [comment]
@randomgambit let's start with the `log4j.spark.log*` files in your working directory. You might also want to check out the logs on the worker nodes. IIRC you're running standalone? This might help: https://spark.apache.org/docs/latest/spark-standalone.html#monitoring-and-logging

**Comment by javierluraschi** [comment]
@randomgambit could you share `sessionInfo()`, I would recommend installing the latest version of `sparklyr` for `spark_apply()`, as in `devtools::install_github("rstudio/sparklyr")`, getting the logs as KevinKuo suggested would be necessary as well.

**Comment by randomgambit** [comment]
```

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-ubuntu14-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS/LAPACK: /opt/intel/2015.3.187/composer/mkl/lib/intel64/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.3.1          lubridate_1.6.0     dplyr_0.7.2         listviewer_1.4.0    sparklyr_0.7.0-9017 MKLthreads_0.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     compiler_3.4.1   dbplyr_1.1.0     plyr_1.8.4       bindr_0.1        base64enc_0.1-3  tools_3.4.1     
 [8] digest_0.6.12    jsonlite_1.5     tibble_1.3.3     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.1     
[15] psych_1.7.5      shiny_1.0.3      DBI_0.7          rstudioapi_0.6   yaml_2.1.14      parallel_3.4.1   bindrcpp_0.2    
[22] withr_1.0.2      stringr_1.2.0    htmlwidgets_0.8  rprojroot_1.2    grid_3.4.1       glue_1.1.1       R6_2.2.2        
[29] foreign_0.8-69   reshape2_1.4.2   tidyr_0.6.3      magrittr_1.5     backports_1.1.0  htmltools_0.3.6  assertthat_0.2.0
[36] mnormt_1.5-5     mime_0.5         xtable_1.8-2     httpuv_1.3.5     config_0.2       stringi_1.1.5    lazyeval_0.2.0  
[43] broom_0.4.2     
```

**Comment by randomgambit** [comment]
I see this in the stderr 
```

17/09/05 20:32:04 WARN ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
17/09/05 20:32:04 WARN ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
17/09/05 20:41:39 ERROR sparklyr: Worker (1111) failed to complete R process
(17/09/05 20:41:39 ERROR sparklyr: Worker (1111) failed to run rscript: ,java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.)
17/09/05 20:41:39 WARN BlockManager: Putting block rdd_21_0 failed due to an exception
17/09/05 20:41:39 WARN BlockManager: Block rdd_21_0 could not be removed as it was not found on disk or in memory
17/09/05 20:41:39 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 92)
java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:67)
	at sparklyr.WorkerRDD$$anon$2.run(rdd.scala:90)
17/09/05 20:41:39 WARN ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
17/09/05 20:41:39 WARN ParquetRecordReader: Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
```

**Comment by randomgambit** [comment]
this is what happens after the simple `spark_apply` and `head` mentioned above. I see a `take at NativeMethodAccessorImpl.java:0` that takes about 30 min to fail and show the errors shown. What do you think? Thanks!!

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi do you get the updates without the @ stuff? I wonder if this is useful at all ;-)

**Comment by kevinykuo** [comment]
Can you try to obtain the worker log, as per
`17/09/05 20:41:39 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 92)
java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.`, so we can see what's throwing the error?

The Spark docs linked above might give you hints as to where they sit on your cluster.

**Comment by javierluraschi** [comment]
@randomgambit currently, I'm catching up on older github issues, so the @javierluraschi notification doesn't help much, finding me in [gitter](https://gitter.im/rstudio/sparklyr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or email is your best bet.

As KevinKuo mentioned, we really need to get the worker logs since this error: `java.lang.Exception: sparklyr worker rscript failure, check worker logs for details.` is just mentioning that something failed in the worker node, once you share that log, we should be able to point you in the right direction.

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi thanks, I am trying to find out where I can find these logs. Most of the stuff I found only contain this generic error

**Comment by randomgambit** [comment]
in any case, my understanding is that `spark_apply` is expected to be much much slower (in particular when using a generic R package in the computation) than the other native `sparklyr` functions. Is that correct?

**Comment by javierluraschi** [comment]
@randomgambit yes, this is correct. There is currently a performance cost between transferring data between Scala and R during `spark_apply()`, it could actually save time in some instances (say, high computation in R for packages using C libraries), but most of the time it will come with an overhead.  I would always start by using `dplyr`, `ml_`, `sdf_`, etc. and only when the functionality is not available, consider using `spark_apply()`.

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo some updates. I appears every time one uses `spark_apply` there is some bottleneck due to `Sparklyr` copying over the entire R distribution over each node. 

This can take quite a while and will not show up on the Spark gui. Also, calling a package from withing spark_apply only works with the syntax `mypackage::myfunction`.

You may want to specify the IO thing on the doc at some point? Anyways, Thanks for your help again!

**Comment by javierluraschi** [comment]
Thanks, suggestion added to https://github.com/rstudio/sparklyr/issues/1021

**Comment by benoitrolland** [comment]
15 minutes overhead for a single master and worker node is a real problem, the use of Apache arrow seems not to overcome. Is there any way to initialize the nodes at start time, independently from the later launched spark_apply commands ?
