### ISSUE TITLE
sparklyr::spark_write_table ( , , mode = 'append') fails for ORC and Parquet

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#992]
sparklyr::spark_write_table(valuesToWrite, tableName, mode = 'append') fails writing to an empty table, but  spark_write_table(valuesToWrite, tableName, mode = 'overwrite') works (tried both in `ORC` and `parquet` `SerDe`s.

```r
packageVersion("dplyr")
# [1] ‘0.7.2’
packageVersion("sparklyr")
# [1] ‘0.6.2’
```

The error msg is:

```
Error: org.apache.spark.sql.AnalysisException: Saving data in the Hive serde table GST_ANALYTICS.MODEL_INSTANCE_EXECUTION is not supported yet. Please use the insertInto() API as an alternative.;
	at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:162)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:404)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:358)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javierluraschi** [comment]
@JohnMount do you have a local repro? This is what I tried:

```
library(sparklyr)
sc <- spark_connect(master = "local")
* Using Spark: 2.1.0
iris_tbl <- copy_to(sc, iris)
spark_write_table(iris_tbl, "x", mode = "append")
> tbl(sc, "x")
# Source:   table<x> [?? x 5]
# Database: spark_connection
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
          <dbl>       <dbl>        <dbl>       <dbl>   <chr>
 1          5.1         3.5          1.4         0.2  setosa
 2          4.9         3.0          1.4         0.2  setosa
 3          4.7         3.2          1.3         0.2  setosa
 4          4.6         3.1          1.5         0.2  setosa
 5          5.0         3.6          1.4         0.2  setosa
 6          5.4         3.9          1.7         0.4  setosa
 7          4.6         3.4          1.4         0.3  setosa
 8          5.0         3.4          1.5         0.2  setosa
 9          4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa
# ... with more rows
```

**Comment by javierluraschi** [comment]
Also,

```r
spark_write_parquet(iris_tbl, "i1")
spark_write_parquet(iris_tbl, "i1", mode = "append")
spark_read_parquet(sc, "i1_back", "i1") %>% sdf_nrow()
```
```
[1] 300
```

Anyways, a full local repro would be very helpful here.

**Comment by russellpierce** [comment]
Thanks for looking in on this @javierluraschi .  I'm glad to know it doesn't appear to be a widespread issue.  I tried on my set-up just now and couldn't reproduce either, even with the s3a backend.

```
library(sparklyr)
library(glue)
bucket <- "your_bucket"
config <- sparklyr::spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "1G"
config[["sparklyr.defaultPackages"]] <- "org.apache.hadoop:hadoop-aws:2.7.3"
sc <- spark_connect(master = "local", config = config)
sc <- sparklyr::spark_connect(master = "local", config = config)
iris_tbl <- copy_to(sc, iris)
spark_write_parquet(iris_tbl, glue("s3a://{your_bucket}/temp/iris"), mode = "append")
spark_write_parquet(iris_tbl, glue("s3a://{your_bucket}/temp/iris"), mode = "append")
```

The error message @JohnMount reported looks related to this https://forums.databricks.com/questions/11027/spark-210-append-to-hive-table.html .  Maybe the part we're missing is that somehow HIVE is in the loop for this operation?  Hopefully @JohnMount can tell us more.

**Comment by MZLABS** [comment]
@JohnMount here.

I don't have a simple reprex.  Right now it works stand-alone.  I'll try the newest `sparklyr` in production in a bit.

``` r
base::date()
#> [1] "Wed Sep 20 15:02:18 2017"
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("dplyr")
#> [1] '0.7.3'
packageVersion("sparklyr")
#> [1] '0.7.0.9031'
sc <- spark_connect(master = 'local', 
                   version = '2.1.0')
d <- copy_to(sc, data.frame(x=1:3, y=6:8), 
              'exampleData')
d0 <- d %>% 
  filter(x > 70)

# create empty table
# this works in append or overwrite mode
spark_write_table(d0, "x", mode = "overwrite")
x <- tbl(sc, 'x')
print(x)
#> # Source:   table<x> [?? x 2]
#> # Database: spark_connection
#> # ... with 2 variables: x <int>, y <int>

# try to apped to it (this is where I am failing in 
# production, appears to work here.  and in production 
# and mode="overwrite" works here).
# In production table was created from Hive, not R.
spark_write_table(d, "x", mode = "append")
print(x)
#> # Source:   table<x> [?? x 2]
#> # Database: spark_connection
#>       x     y
#>   <int> <int>
#> 1     1     6
#> 2     2     7
#> 3     3     8

spark_disconnect(sc)
```

**Comment by JohnMount** [comment]
I now have a `reprex`:

``` r

suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("sparklyr"))
#> Warning: package 'sparklyr' was built under R version 3.4.2
packageVersion("dplyr")
#> [1] '0.7.4'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'
packageVersion("sparklyr")
#> [1] '0.6.3'

sc <- spark_connect(master = 'local', 
                    version = '2.1.0')

createQ <- 
"
CREATE EXTERNAL TABLE `ex` (
  `id` bigint )
ROW FORMAT SERDE
'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
'/tmp/zzz'
"

DBI::dbGetQuery(sc, createQ)

DBI::dbGetQuery(sc, "SELECT * FROM ex")
#> [1] id
#> <0 rows> (or 0-length row.names)

d <- copy_to(sc, data.frame(id= 1L), 'd')

# fails
tryCatch(
  spark_write_table(d, "ex", mode = 'append'),
  error = function(e) { print(e); NULL }
)
#> <simpleError: org.apache.spark.sql.AnalysisException: Saving data in the Hive serde table `default`.`ex` is not supported yet. Please use the insertInto() API as an alternative..;
#>  at org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand.run(createDataSourceTables.scala:187)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
#>  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
#>  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
#>  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
#>  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
#>  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
#>  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:87)
#>  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:87)
#>  at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:404)
#>  at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:358)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:102)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
#>  at sparklyr.StreamHandler$.read(stream.scala:62)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:52)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
#>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
#>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
#>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
#>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
#>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
#>  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
#>  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
#>  at java.lang.Thread.run(Thread.java:745)
#> >
#> NULL

# works
spark_write_table(d, "ex", mode = 'overwrite')

DBI::dbGetQuery(sc, "SELECT * FROM ex")
#>   id
#> 1  1

spark_disconnect(sc)
```
